marimo-team/marimo

Makefile
frontend/package.json
frontend/src/editor/output/HtmlOutput.tsx
frontend/src/plugins/core/RenderHTML.tsx
frontend/src/plugins/core/componentFactory.tsx
frontend/src/plugins/impl/ButtonPlugin.tsx
frontend/src/plugins/impl/CheckboxPlugin.tsx
frontend/src/plugins/impl/SwitchPlugin.tsx
frontend/src/plugins/layout/AccordionPlugin.tsx
frontend/src/plugins/layout/TabsPlugin.tsx
frontend/src/plugins/layout/TexPlugin.tsx

* This improves the TexPlugin to grab the already rendered HTML from the mounted element instead of re-rendering inside the shadow dom.
* this also changes RenderHTML from a react component to function, which simplifies the WebComponent created in `registerReactComponent`

Improve renderHTML and TexPlugin

---

Makefile
README.md
docs/guides/index.md
docs/guides/scripts.md

Document running programs as scripts

Docs: running programs as scripts

---

examples/ai/data_labeler.py

Template for a basic data labeling tool:
- Cycle through a set of examples to label
- Assign labels to each example
- Labels persisted to disk on write, loaded from disk when cycling through examples

Data labeling example

---

docs/api/inputs/index.md
docs/api/inputs/refresh.md
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/ui/native-select.tsx
frontend/src/plugins/impl/RefreshPlugin.tsx
frontend/src/plugins/plugins.ts
marimo/_plugins/ui/__init__.py
marimo/_plugins/ui/_impl/refresh.py
marimo/_smoke_tests/refresh.py

- the value in `setValue` is somewhat arbitrary and likely not useful (it includes the number of times it occurred)
- the refresh icon spin when it refreshes
https://www.loom.com/share/b9b4dd03d2de4056a0a18ac921fbeb0f?sid=ff47436b-9993-420e-9a93-2707686573da

Refresh plugin

---

frontend/src/components/ui/button.tsx
frontend/src/plugins/impl/ButtonPlugin.tsx
frontend/src/plugins/impl/common/intent.ts
frontend/src/stories/button.stories.mdx
marimo/_plugins/ui/_impl/input.py
marimo/_smoke_tests/buttons.py

note: ideally we make consistent with Callout, but Callout's `alert` is not really `danger`. And the warning, looks closer to `danger`

Update button to support "kind" and "disabeld"

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/App.tsx
frontend/src/components/find-replace/find-replace.tsx
frontend/src/components/ui/button.tsx
frontend/src/components/ui/toggle.tsx
frontend/src/core/codemirror/cm.ts
frontend/src/core/codemirror/find-replace/extension.ts
frontend/src/core/codemirror/find-replace/navigate.ts
frontend/src/core/codemirror/find-replace/state.ts
frontend/src/core/hotkeys/hotkeys.ts
frontend/src/core/state/cells.ts
frontend/src/core/state/jotai.ts
frontend/src/editor/Controls.tsx
frontend/src/hooks/useHotkey.ts
frontend/src/main.tsx

feat: global find replace

---

docs/api/media/audio.md
docs/api/media/image.md
docs/api/media/index.md
docs/api/media/pdf.md
marimo/__init__.py
marimo/_output/builder.py
marimo/_output/test_builder.py
marimo/_plugins/stateless/pdf.py
marimo/_smoke_tests/pdf.py

https://github.com/marimo-team/marimo/issues/64

feat: add PDF with initial page number

---

docs/api/control_flow.md
docs/api/debugging.md
docs/api/index.md

- stop
- refresh (also listed in inputs)

docs: control flow API page

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/App.tsx
frontend/src/MarimoApp.tsx
frontend/src/components/export/export-output-button.tsx
frontend/src/components/export/menu-dropdown.tsx
frontend/src/components/icons/multi-icon.tsx
frontend/src/components/shortcuts/renderShortcut.tsx
frontend/src/components/sort/SortableCellsProvider.tsx
frontend/src/components/ui/command.tsx
frontend/src/components/ui/dropdown-menu.tsx
frontend/src/core/mode.ts
frontend/src/core/state/cells.ts
frontend/src/css/common.css
frontend/src/css/globals.css
frontend/src/editor/Cell.tsx
frontend/src/editor/CommandPallette.tsx
frontend/src/editor/Controls.styles.ts
frontend/src/editor/Controls.tsx
frontend/src/editor/Output.tsx
frontend/src/editor/SortableCell.tsx
frontend/src/editor/cell/cell-actions.tsx
frontend/src/editor/inputs/Inputs.styles.ts
frontend/src/main.tsx
frontend/src/utils/download.ts

* download full page as PNG
* download output as PNG
* create a Cell Action Menu where the drag handle is
* change the accent background and foreground colors

feat: Download PNG 

---

frontend/.storybook/sb.css
frontend/src/css/md.css
frontend/src/stories/cell.stories.tsx
frontend/src/stories/colors.stories.tsx
frontend/tailwind.config.js

Add variables to storybook

---

docs/api/inputs/microphone.md
docs/api/inputs/refresh.md
docs/api/media/audio.md
docs/api/media/image.md
docs/api/media/pdf.md

Can merge once we deploy new components app

uncomment some component iframes (0.1.5 released)

---

examples/model_comparison/model_comparison.py

Add an example for comparing two NLP models that both predict spans (substrings), given a string. The example lets the user pick which model they prefer for each example in a dataset.

example: model comparison 

---

README.md

So media renders correctly on pypi.org

Use full URLs for README media

---

marimo/_config/test_config.py

test: user config

---

marimo/_ast/app.py
marimo/_ast/codegen.py
marimo/_ast/test_codegen.py
marimo/_cli/ipynb_to_marimo.py
marimo/_cli/test_cli.py
marimo/_server/api/save.py
marimo/_server/api/save_app_config.py

- generate_filecontents takes a list of CellConfigs
- update all callers to provide configs
- update api/kernel/save to require list of configs

Add cell config to save logic

---

marimo/_runtime/runtime.py
marimo/_runtime/test_runtime.py

store config in cell metadata
also, don't clear queue on interrupt

fix: set config before registering cell

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/ui/command.tsx
frontend/src/components/ui/context-menu.tsx
frontend/src/components/ui/dropdown-menu.tsx
frontend/src/components/ui/menu-items.tsx
frontend/src/core/vscode/vscode-bindings.ts
frontend/src/editor/Cell.tsx
frontend/src/editor/actions/types.ts
frontend/src/editor/actions/useCellActionButton.tsx
frontend/src/editor/actions/useNotebookActions.tsx
frontend/src/editor/cell/cell-actions.tsx
frontend/src/editor/cell/cell-context-menu.tsx
frontend/src/stories/context-menu.stories.mdx

- get rid of "Focus above"/"Focus below" in the cell action dropdown
- add "Open documentation" in the notebook dropdown and command palette
- show right-click context menu on cells

feat: context menu

---

frontend/e2e-tests/cells.spec.ts
marimo/_messaging/message_types.py
marimo/_messaging/messages.py
marimo/_runtime/runtime.py

Send information on variables to the frontend
Makes progress on #96

Variable messages

---

frontend/src/App.tsx
frontend/src/components/app-config/app-config-form.tsx
frontend/src/components/app-config/common.tsx
frontend/src/components/app-config/theme-toggle.tsx
frontend/src/components/app-config/user-config-form.tsx
frontend/src/core/config/config.ts
frontend/src/core/websocket/useMarimoWebSocket.tsx
frontend/src/css/common.css
frontend/src/stories/cell.stories.tsx
frontend/vite.config.ts
marimo/_config/config.py

Config named `auto_instantiate`, nested in a new **Runtime config**. Note:
- this differs from `autosave` which is one word
- this differs from what we tell the user, which is "Auto-run on startup
happy to change for consistency

feat: add disable auto-run config

---

frontend/src/components/app-config/app-config-form.tsx
frontend/src/components/app-config/common.tsx
frontend/src/components/app-config/user-config-form.tsx

make distinction bewteen user/app config clear
clean up spacing

minor styling of config menu

---

Makefile
frontend/src/components/variables/variables-table.tsx
frontend/src/editor/chrome/wrapper/app-chrome.css
frontend/src/editor/chrome/wrapper/app-chrome.tsx
frontend/tailwind.config.js

style them to better fit in with the marimo editor

style variables table and chrome

---

marimo/_messaging/ops.py

Print the module name instead of the default string.

Pretty print module value in variables table

---

frontend/src/editor/chrome/wrapper/app-chrome.tsx

didn't actually do anything, conflicted with gradient on disconnection

remove unnecessary background color 

---

marimo/_plugins/stateless/mpl/_mpl.py
marimo/_runtime/cell_lifecycle_item.py
marimo/_runtime/cell_lifecycle_registry.py
marimo/_runtime/conftest.py
marimo/_runtime/context.py
marimo/_runtime/runtime.py
marimo/_runtime/virtual_file.py

- Adds a registry for cell lifecycle items
- Ports interactive matplotlib plugin to use registry
- Prototype (incomplete) of virtual file lifecycle item

Cell lifecycle

---

frontend/src/components/data-table/columns.tsx
frontend/src/components/data-table/pagination.tsx

improvement: show table selection count, support select all

---

marimo/_plugins/ui/_impl/altair_chart.py
marimo/_plugins/ui/_impl/charts/altair_transformer.py

- replace NaN with null
- cast selection values to dataframe column type

Fixes to altair_chart related to csv transformer

---

README.md
examples/reactive_plots.py

@mscolnick maybe an improvement over what we have today?

New intro gif

---

marimo/_ast/cell.py
marimo/_output/formatting.py
marimo/_plugins/stateless/mpl/_mpl.py
marimo/_plugins/ui/_core/ui_element.py
marimo/_runtime/conftest.py
marimo/_runtime/context.py
marimo/_runtime/runtime.py
marimo/_runtime/state.py
marimo/_runtime/test_state.py

refactor runtime context's initialization, which was getting unwieldy

refactor runtime context

---

marimo/_runtime/context.py

- make global context thread-local, with an entry for runtime context
- because global context is thread-local, and has an entry for the runtime context, the runtime context no longer needs to be a thread-local object

Fix regression re: thread-local context

---

examples/dashboards/movies.py
frontend/src/components/data-table/columns.tsx
frontend/src/components/data-table/data-table.tsx
frontend/src/plugins/core/BadPlugin.tsx
frontend/src/plugins/core/registerReactComponent.tsx
frontend/src/plugins/impl/DataTablePlugin.tsx
frontend/src/stories/data-table.stories.mdx
marimo/_plugins/ui/_impl/table.py
marimo/_plugins/ui/_impl/test_table.py

improvement: add row headers

---

marimo/_runtime/functions.py
marimo/_utils/test_parse_dataclass.py

Adds a utility class to for RPCs that take 0 args.

Utility class for fn that take 0 args

---

frontend/src/core/functions/FunctionRegistry.ts

- backend sends a completed-run once RPC is done

Register run start for rpc call

---

docs/index.md

- add installation command to top
- simplify features/highlights
future PR:
- setting up a virtualenv
- FAQ on autorelaoding
- Simplify/better videos on docs homepage
- Why marimo? page

Simplify docs homepage

---

docs/conf.py
docs/getting_started/index.md
pyproject.toml

- adds sphinx-design as a dev dependency for the dropdown/accordion

virtualenv instructions in getting started installation

---

frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
frontend/src/core/codemirror/cm.ts
frontend/src/core/codemirror/keymaps/keymaps.ts

- it was previously getting overriden by deleteCharBackward

Fix priority of closeBracketsKeymap

---

frontend/src/plugins/impl/DataTablePlugin.tsx
frontend/src/plugins/impl/vega/VegaPlugin.tsx
frontend/src/plugins/impl/vega/loader.ts
frontend/src/plugins/impl/vega/types.ts
frontend/vite.config.ts

fixes https://github.com/marimo-team/marimo/issues/251

fix: preload vega data to avoid flicker in vegaembed

---

marimo/_runtime/runtime.py
marimo/_runtime/virtual_file.py
marimo/_server/sessions.py

This change fixes a bug in which server shutdown sometimes hung, leading to orphaned processes/ports.
- Previously we were shutting the kernel down with sys.exit(). Exiting with sys.exit() when the process was created after a fork may trigger undefined behavior, since cleanup functions run twice, once for the parent process and once for the child process.
- This change uses os._exit() instead to kill the child process, as recommended by Python docs.
- This change also makes the SIGTERM handler re-entrant, to fix a bug in which the virtual file registry shutdown method was being interrupted upon receipt of a second SIGTERM. We terminate the process once manually, and because the process is a daemon process it gets another SIGTERM.

Fix undefined behavior in kernel shutdown

---

frontend/src/core/hotkeys/hotkeys.ts

swap focus, move up/down shortcuts

---

frontend/src/components/app-config/app-config-button.tsx
frontend/src/css/App.css
frontend/src/css/Cell.css
frontend/src/css/globals.css
frontend/src/editor/cell/TinyCode.tsx
frontend/src/editor/links/cell-link.tsx
frontend/src/editor/output/JsonOutput.tsx
frontend/src/editor/renderers/grid-layout/grid-layout.tsx
frontend/src/editor/renderers/grid-layout/styles.css
frontend/src/editor/renderers/layout-select.tsx
frontend/src/plugins/core/registerReactComponent.tsx
frontend/src/plugins/impl/vega/VegaPlugin.tsx
frontend/src/plugins/impl/vega/vega.css
frontend/src/plugins/layout/StatPlugin.tsx
frontend/src/stories/checkbox.stories.mdx
frontend/src/stories/input.stories.mdx
frontend/src/stories/popover.stories.mdx
frontend/src/stories/tabs.stories.mdx
frontend/src/stories/textarea.stories.mdx
frontend/src/theme/useTheme.ts

in the next PR, ill move `theme: "light" | "dark"` to UserConfig

improve dark mode

---

frontend/src/core/state/__tests__/__snapshots__/cells.test.ts.snap
frontend/src/core/state/__tests__/cells.test.ts
frontend/src/core/state/cell.ts
frontend/src/editor/cell/CellStatus.tsx

fix: Update cell state to track elapsed run time when interrupted or stale

---

frontend/src/editor/Controls.tsx
frontend/src/editor/cell/RunButton.tsx
frontend/src/editor/cell/useShouldShowInterrupt.ts

Make the interrupt button easier to find

fix: Show interrupt button in the Cell's run button

---

frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
frontend/src/plugins/impl/data-frames/python/code-panel.tsx

add floating copy button to mo.ui.dataframe

---

frontend/src/editor/Cell.tsx
frontend/src/editor/actions/useCellActionButton.tsx
frontend/src/editor/cell/cell-actions.tsx
frontend/src/editor/cell/useRunCells.ts

Add 'Run cell' action to cellActionButtons and update cell status in CellComponent

---

frontend/src/css/table.css
marimo/_output/md.py
marimo/_smoke_tests/md_table.py

Enable python-markdown tables extension

---

frontend/src/components/app-config/app-config-form.tsx
frontend/src/css/index.css
frontend/src/editor/chrome/wrapper/app-chrome.tsx

this makes charts/plots update their size

Dispatch resize event when config width changes 

---

frontend/src/components/data-table/column-header.tsx
frontend/src/plugins/impl/data-frames/panel.tsx

before the overlay would cover the full screen

fix: popover overlay on a dropdowns

---

marimo/_plugins/stateless/status/_progress.py

Add destructor/constructor calls to Progress

---

marimo/_plugins/ui/_impl/array.py
marimo/_plugins/ui/_impl/batch.py
marimo/_plugins/ui/_impl/dictionary.py

@mscolnick FYI, responding to a user request to make this more explicit in our docs

docs: improve docs for higher order elements

---

frontend/src/components/editor/renderers/grid-layout/grid-layout.tsx
frontend/src/components/editor/renderers/grid-layout/plugin.tsx
frontend/src/components/editor/renderers/grid-layout/styles.css
frontend/src/components/editor/renderers/grid-layout/types.ts
frontend/src/components/editor/renderers/vertical-layout/vertical-layout-wrapper.tsx
frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
frontend/src/core/App.tsx

* improves images in grid to resize correctly
* adds a "bordered" flag that puts the Grid in a container - this makes using max-width a bit cleaner

Add bordered grid and image styling

---

frontend/src/plugins/impl/vega/__tests__/encodings.test.ts
frontend/src/plugins/impl/vega/encodings.ts
frontend/src/plugins/impl/vega/make-selectable.ts
frontend/src/plugins/impl/vega/marks.ts
marimo/_smoke_tests/altair_charts.py

fixes https://github.com/marimo-team/marimo/issues/287

fix: Update opacity for interactive selection to be a ratio of user defined opacity

---

frontend/src/components/editor/chrome/panels/logs-panel.tsx
frontend/src/components/editor/chrome/types.ts
frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
frontend/src/components/editor/chrome/wrapper/footer.tsx
frontend/src/core/cells/cells.ts
frontend/src/core/cells/logs.ts
frontend/src/core/kernel/messages.ts
frontend/src/stories/cell.stories.tsx
frontend/src/stories/log-viewer.stories.tsx
frontend/src/utils/strings.ts
frontend/vite.config.ts

Add support for notebook logs and additional panel type in editor

---

marimo/_cli/cli.py
marimo/_cli/file_path.py
marimo/_cli/test_file_path.py

Update cli.py run/edit from github or external files
can do things like:
```
marimo edit https://github.com/marimo-team/marimo/issues/339
marimo edit https://raw.githubusercontent.com/marimo-team/marimo/main/examples/optimization/regularization_and_sparsity.py
marimo edit https://github.com/marimo-team/marimo/blob/main/examples/optimization/regularization_and_sparsity.py
```

feat: Update cli.py run/edit from github or external files

---

examples/third_party/mapbox.py

So user can select and drill down into individual cities!

Use reactive plotly in mapbox example

---

marimo/_runtime/test_cell_runner.py

Adds a unit test for testing that the last expression of a cell is its output.

Add a unit test for cell runner's output

---

marimo/_cli/cli.py
marimo/_cli/print.py
marimo/_cli/test_upgrade.py
marimo/_cli/upgrade.py

feat: Add version update check and print in 'marimo edit'

---

docs/faq.md
docs/index.md
docs/recipes.md
marimo/_runtime/control_flow.py

Add recipes for a variety of common tasks.

docs: recipes

---

docs/recipes.md

A recipe for making a batch of UI elements with custom formatting

Batch recipe

---

docs/_static/css/custom.css
docs/conf.py
docs/guides/best_practices.md
docs/guides/state.md
docs/index.md

- Add example for how to avoid mutation
- Enable `colon_fence` myst extension so we can use code in admonitions, dropdowns, and other directives

improve best practices

---

examples/embeddings/us_counties.py

add us counties embedding example

---

docs/faq.md

FAQ on annotations, and how they affect the DAG.
Improve FAQ on the distinction between notebooks and apps.
Closes #385

docs: annoations, notebook/app

---

marimo/_cli/cli.py

As part of our effort to clarify our terminology around marimo notebooks vs marimo apps. The user creates/edits marimo notebooks, and runs notebooks as apps.

CLI help message: terminology of notebook vs app

---

.github/workflows/playwright.yml
frontend/.gitignore
frontend/e2e-tests/cells.spec.ts
frontend/e2e-tests/helper.ts
frontend/e2e-tests/kitchen-sink.spec.ts
frontend/e2e-tests/py/kitchen_sink.py
frontend/index.html
frontend/playwright.config.ts
frontend/src/components/editor/notebook-menu-dropdown.tsx
frontend/src/components/editor/renderers/grid-layout/styles.css
frontend/src/core/cells/cells.ts
frontend/src/core/static/__tests__/__snapshots__/download-html.test.ts.snap
frontend/src/core/static/__tests__/download-html.test.ts
frontend/src/core/static/__tests__/files.test.ts
frontend/src/core/static/download-html.ts
frontend/src/core/static/types.ts
frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
frontend/src/utils/blob.ts
frontend/src/utils/json/__tests__/base64.test.ts
frontend/src/utils/json/base64.ts

* fix special characters or html tags in output by encoding/decoding static dumps as base64
* improve Base64 types with branded strings
* add e2e test for kitchen sink - will export as html and take a photo of the export 
* fix height expansion on some elements when set to 100% 
* include `__resizeIframe` in the html dump

experimental: export as html improvements and bug fixes

---

examples/third_party/plotly_image_selection.py

example: Add plotly image selection examples

---

docs/faq.md

FAQ on how to avoid accidental execution of expensive cells

docs: faq on expensive cells

---

frontend/src/components/ui/combobox.tsx

fixes https://github.com/marimo-team/marimo/issues/447

fix: stale filtering when using a multi-select

---

frontend/src/components/editor/Cell.tsx
frontend/src/components/editor/cell/useRunCells.ts
frontend/src/components/editor/renderers/CellArray.tsx
frontend/src/core/functions/FunctionRegistry.ts
frontend/src/core/websocket/useMarimoWebSocket.tsx
frontend/src/stories/cell.stories.tsx

If we fail to register a run (or function call), we should remove the running counter increment

fix runtime state registration in error handling

---

frontend/index.html
frontend/src/core/static/__tests__/__snapshots__/download-html.test.ts.snap
frontend/src/core/static/__tests__/download-html.test.ts
frontend/src/core/static/download-html.ts

This roundtrip is not noticeable locally, but when apps are deployed, it is much more noticeable

improvement: preload main fonts

---

README.md

Update the readme for clarity.

Editing pass over README

---

docs/index.md

Update the docs landing page for clarity

Editing pass over docs index.md

---

examples/embeddings/debugging_embeddings.py
examples/embeddings/google_scholar.py

This PR adds a new example notebook.

Add example notebook on embedding google scholar

---

README.md
docs/getting_started/index.md
docs/index.md

Document installation via conda forge.

Docs: document conda installation

---

frontend/src/components/dependency-graph/custom-node.tsx
frontend/src/components/editor/Cell.tsx
frontend/src/components/editor/actions/name-cell-input.tsx
frontend/src/components/editor/actions/types.ts
frontend/src/components/editor/actions/useCellActionButton.tsx
frontend/src/components/editor/cell/cell-actions.tsx
frontend/src/components/editor/cell/cell-context-menu.tsx
frontend/src/components/editor/links/cell-link.tsx
frontend/src/components/editor/notebook-menu-dropdown.tsx
frontend/src/components/editor/output/ConsoleOutput.tsx
frontend/src/components/editor/renderers/CellArray.tsx
frontend/src/core/App.tsx
frontend/src/core/cells/__tests__/names.test.ts
frontend/src/core/cells/cells.ts
frontend/src/core/cells/names.ts
frontend/src/core/cells/outputs.ts
frontend/src/core/cells/types.ts
frontend/src/core/saving/useAutoSave.ts
frontend/src/core/websocket/useMarimoWebSocket.tsx
frontend/src/css/Cell.css
frontend/src/hooks/useLifecycle.ts
frontend/src/stories/cell.stories.tsx

- add a way to rename cells in the cell content menu
- if a cell is named, it is show below
- drive-by: fix a small bug where we allowed downloading a png of a cell's empty output

feat: allow renaming cells

---

examples/refresh.py
marimo/_tutorials/refresh.py

An example showing the usage of refresh widget to fetch new data and update plots of the International Space Station location above Earth.
There's probably a few things to clean up but wanted to get this going in 2023. :)

refresh with ISS API

---

marimo/_tutorials/intro.py
scripts/pycopyright.sh

Update tutorial notebook for clarity.

Update tutorial notebook

---

frontend/src/components/editor/actions/name-cell-input.tsx
frontend/src/components/editor/cell/cell-actions.tsx
frontend/src/components/editor/output/ConsoleOutput.tsx
frontend/src/components/editor/output/MarimoErrorOutput.tsx
frontend/src/core/cells/__tests__/names.test.ts
frontend/src/core/cells/names.ts

- Handle banned names when renaming a cell
- Fix console warnings that are shown during development

fix: Handle banned names when renaming a cell

---

pyproject.toml

Don't include tutorials in test coverage, since these are examples

Omit tutorials from coverage

---

marimo/_smoke_tests/third_party/seaborn.py
marimo/_tutorials/dataflow.py
marimo/_tutorials/fileformat.py
marimo/_tutorials/intro.py
marimo/_tutorials/layout.py
marimo/_tutorials/markdown.py
marimo/_tutorials/plots.py
marimo/_tutorials/ui.py

This makes the notebooks much more readable.

Hide some code in tutorials!

---

frontend/src/components/editor/chrome/footer/feedback-button.tsx
frontend/src/components/editor/chrome/wrapper/footer.tsx

This adds a feedback dialog for users to send anonymous feedback

misc: feedback dialog

---

frontend/src/components/editor/Controls.tsx

close window on shutdown

---

marimo/_cli/file_path.py

Can test with `marimo edit https://marimo.io/static/embedding-mnist-wze6`. This URL does not end in py or html, so it was a case we had not handled yet.

improvement: support running from https://marimo.io/static/

---

frontend/src/components/app-config/user-config-form.tsx
frontend/src/core/codemirror/format.ts
frontend/src/core/config/config-schema.ts
frontend/src/core/network/requests.ts
frontend/src/core/network/types.ts
frontend/src/stories/cell.stories.tsx
marimo/_config/config.py
marimo/_server/api/format.py

This change makes the black line length configurable via user config.

feat: configurable line length in format

---

README.md

Link out to our FAQs. In the future we can update the README to with a 1-2 sentence TL;DR.

Update README.md: link to what problems does marimo solve

---

marimo/_tutorials/dataflow.py
marimo/_tutorials/markdown.py

Fix formatting in dataflow example

---

frontend/src/components/app-config/user-config-form.tsx
frontend/src/core/config/config-schema.ts
frontend/src/plugins/impl/CodeEditorPlugin.tsx
frontend/src/theme/useTheme.ts
marimo/_config/config.py
marimo/_plugins/ui/_impl/input.py
marimo/_smoke_tests/code_editor.py

This adds system theme option which chooses the them based on the user's OS preferences. 
Closes https://github.com/marimo-team/marimo/issues/547

improvement: add 'system' theme option

---

marimo/_tutorials/intro.py

Updates the description of moving a cell. There are no arrow buttons, but a drag handle.

Update description of cell movement in intro.py

---

pyproject.toml

Add typos as dev dependency, for local usage

---

docs/_static/css/custom.css
frontend/src/css/globals.css
frontend/src/css/index.css
marimo/_smoke_tests/inputs.py

Fixes https://github.com/marimo-team/marimo/issues/562
Use color-scheme for the native browser dark mode. This also makes scrollbars dark

fix: fix native select background color on Linux, improve other dark more support

---

docs/api/media/pdf.md

The PDF was auto-downloading in some browsers.

docs: Remove mo.pdf iframe to prevent autodownloads

---

docs/api/layouts/index.md
docs/api/layouts/mermaid.md
examples/third_party/mermaid.py
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/editor/output/HtmlOutput.tsx
frontend/src/plugins/impl/CodeEditorPlugin.tsx
frontend/src/plugins/layout/mermaid/MermaidPlugin.tsx
frontend/src/plugins/layout/mermaid/mermaid.tsx
frontend/src/plugins/plugins.ts
marimo/__init__.py
marimo/_plugins/stateless/mermaid.py

This add `mo.mermaid`. 
* I tried initially making this a recipe by using `mo.Html` and esm imports, but was not working properly with reloads with the current way to render scripts.

feat: mo.mermaid

---

frontend/src/plugins/impl/RadioPlugin.tsx
marimo/_plugins/ui/_impl/input.py
marimo/_smoke_tests/inputs.py

Fixes https://github.com/marimo-team/marimo/issues/583

improvement: add 'inline=bool' to mo.ui.radio

---

codecov.yml
marimo/_server/api/code_complete.py
marimo/_server/api/delete.py
marimo/_server/api/directory_autocomplete.py
marimo/_server/api/format.py
marimo/_server/api/function_call.py
marimo/_server/api/instantiate.py
marimo/_server/api/interrupt.py
marimo/_server/api/read_code.py
marimo/_server/api/rename.py
marimo/_server/api/run.py
marimo/_server/api/save.py
marimo/_server/api/save_app_config.py
marimo/_server/api/save_user_config.py
marimo/_server/api/set_cell_config.py
marimo/_server/api/set_ui_element_value.py
marimo/_server/api/stdin.py
marimo/_server/api/validated_handler.py
marimo/_server/model.py
marimo/_server/print.py
marimo/_server/server.py
marimo/_server/server_handler.py
marimo/_server/server_utils.py
marimo/_server/sessions.py
marimo/_server/utils.py
marimo/_smoke_tests/stdin.py

Decoupling sessions.py from any tornado logic. This is so we can switch to another webframework much more easily

chore: decouple sessions from tornado

---

marimo/_output/formatters/leafmap_formatters.py
marimo/_output/formatters/pandas_formatters.py

Fixes https://github.com/marimo-team/marimo/issues/598

fix: fix nullable max_rows, max_columns

---

frontend/src/components/ui/native-select.tsx

fix: dropdown visibility in dark mode

---

marimo/_ast/app.py
marimo/_runtime/dataflow.py
marimo/_server/api/endpoints/execution.py
marimo/_server/api/endpoints/files.py
marimo/_server/api/endpoints/ws.py
marimo/_server/sessions.py
tests/_ast/test_app.py
tests/_ast/test_app_cell.py
tests/_ast/test_codegen.py
tests/_cli/test_ipynb_to_marimo.py

- split up `class App` into smaller chunks
- initialize empty apps, this clean up the code checking for `None`
- use `yield` in iterators

chore: Cleanup app.py file, initialize empty App()

---

frontend/src/components/editor/notebook-banner.tsx
frontend/src/components/editor/renderers/CellArray.tsx
frontend/src/core/errors/state.ts
frontend/src/core/kernel/messages.ts
frontend/src/core/websocket/useMarimoWebSocket.tsx

This does nothing on its own. Ideally this is paired with the BE notifying the user when there are missing dependencies

misc: allow the FE to recieve banner messages from the kernel

---

frontend/src/components/editor/notebook-banner.tsx
frontend/src/core/errors/state.ts

chore: lint frontend

---

frontend/src/components/find-replace/find-replace.tsx
frontend/src/core/codemirror/find-replace/extension.ts
frontend/src/core/codemirror/find-replace/navigate.ts
frontend/src/core/codemirror/find-replace/query.ts
frontend/src/core/codemirror/find-replace/search-highlight.ts

Previously we only highlighted the focused cell. This highlights all the cells that match the given search. 
Fixes #679 #685

improvement: highlight matches across all cells (instead of 1 cell)

---

docs/faq.md

docs: add --host

---

docs/getting_started/index.md
docs/guides/overview.md
marimo/_tutorials/intro.py

Addresses some of the issues raised in #656

docs: minor improvements for creating notebooks

---

docs/guides/interactivity.md
docs/recipes.md

Simplify the recipes for embedding a dynamic number of UI elements in another output

docs: use new array/dict features in recipes

---

marimo/_server/api/endpoints/health.py
marimo/_server/api/router.py
marimo/_server/model.py
marimo/_server/sessions.py
tests/_server/api/endpoints/test_health.py
tests/_server/mocks.py

Fixes: https://github.com/marimo-team/marimo/issues/706

feat: health and status endpoints

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/editor/output/ConsoleOutput.tsx
frontend/src/components/editor/output/TextOutput.tsx
marimo/_smoke_tests/ansi.py
marimo/_smoke_tests/third_party/rich.py

Fixes https://github.com/marimo-team/marimo/issues/707

feat: support ansi in console output

---

marimo/_output/md.py
marimo/_smoke_tests/md.py

improvement: support footnotes in markdown

---

frontend/src/css/Cell.css

Fixes https://github.com/marimo-team/marimo/issues/740

fix: hover tooltip z-index

---

marimo/_runtime/state.py

Related to #746 and other issues that have come up in the past

warn against putting ui elements in state

---

docs/faq.md

Update FAQs for #745. Also update FAQ for restarting kernel.

FAQ: dotenv, restart kernel

---

docs/api/plotting.md
marimo/_output/formatters/bokeh_formatters.py
marimo/_output/formatters/formatters.py
marimo/_output/formatters/holoviews_formatters.py
marimo/_output/formatters/plotly_formatters.py
marimo/_smoke_tests/third_party/holoviews.py

Closes https://github.com/marimo-team/marimo/issues/743
Adds support for Bokeh and Holoviews formatters. 
You can test with ` marimo edit marimo/_smoke_tests/third_party/holoviews.py`

feat: add support for holoviews

---

tests/_cli/test_cli.py

Add CLI tests that start the server, shut it down, and check that it was actually shut down.

test: test quitting the server

---

marimo/_config/config.py
marimo/_config/manager.py
marimo/_config/utils.py
marimo/_output/rich_help.py
marimo/_plugins/stateless/json_output.py
marimo/_runtime/requests.py
marimo/_runtime/runtime.py
marimo/_server/api/deps.py
marimo/_server/api/endpoints/assets.py
marimo/_server/api/endpoints/config.py
marimo/_server/api/lifespans.py
marimo/_server/start.py
marimo/_smoke_tests/arrays_and_dicts.py
tests/_config/test_config.py
tests/_server/api/test_middleware.py
tests/_server/conftest.py

* Move some logic out of the endpoints
* Don't make the config global (in case we have different users with different configs)

internal: make config non-global, ensapsulate more logic

---

marimo/_server/sessions.py

fix: filewatcher uses absolute paths

---

marimo/_pyodide/pyodide_session.py
marimo/_runtime/cell_lifecycle_registry.py
marimo/_runtime/context.py
marimo/_runtime/virtual_file.py

This replaces vfiles with data urls, making sure not to hit multiprocessing code/shared memory.
EDIT: Working now.

Replace virtual files with data urls in pyodide session

---

examples/probability/bayes_theorem.py

[Example link](https://marimo.app/?code=JYWwDg9gTgLgBCAhlUEBQaD6mDmBTAOzykRjwBNMB3YGACzgF44AiABgDoAmDgVhbSIwYJgmSoOAQWEAKGuXqMWAMwCuAG3UsAlBjQABIWA4BjPJrTk8yuNhkgI2gFxo4bhBA4hyM1%2B-9QLEF%2B-m4AxHAAQogAnngAzgDkcAAqdHjQeCAYoe6YacDxcMAEZCQmMMAAbnhwBBBkAEYQEADWcFSIRUhWHbQMANpIKA4AujJ0MDBg8U4A9HM4-aqNphAgc8OoALRkiBtbDtoANHCIBOTFRQONXRRwEARnT3gAHmDq56TAjw820XEkql0pkQHBGjE4ABxEilOAAZXOVig8Ue40m01mCyoOI4MQgqhgKzwaw2nRgJjoAH4qowABIALShAGEIAA1ABiAGYAJpVACyADJ1IUYIwAAoAGQAXgBHADsEHIIBgygA0gBFKhcNUASUaGtlbCg0oA6lBZUtlHS1a1xVCAIyCkpWV6MJ1irnxbSYDg5XJRWIJOD0DJQLJwMBQCBVYBWIqIOAmR41AjAQjwTqQmAQJOIdQmDSkWqhyPR26NYAimAxEKhCA2RN0GKQUPxQpwPCp%2BAAEjpPbgS1TndjVgIZjgPYAoj2XHX-AAdAbz9zimR0uALkBxuBT7SiBfKcoAbzXdP3a6nm%2B3l3PAF9TzI93e-QHN6M9G%2BAFRftK1AiqCAxCkNAHA-sC-6AcBOZQFcIbpGWEAVlWtCQg2I4ZkU04Dkik79nAdBGIQJ …

Add an example for Bayes Theorem

---

frontend/src/components/app-config/user-config-form.tsx
frontend/src/core/config/__tests__/config-schema.test.ts
frontend/src/core/config/config-schema.ts
frontend/src/core/pyodide/bridge.ts
frontend/src/core/pyodide/store.ts
frontend/src/hooks/useLocalStorage.ts
frontend/src/utils/localStorage.ts

improvement: support user-settings in wasm-mode

---

marimo/_output/formatters/altair_formatters.py
marimo/_plugins/ui/_impl/charts/altair_transformer.py
tests/_plugins/ui/_impl/test_altair_chart.py

Previously if a user set an altair setting. Our custom transformer would be lossy and lose this information

fix: preserve altair settings

---

marimo/_plugins/ui/_impl/refresh.py

Closes https://github.com/marimo-team/marimo/issues/831

fix: refresh docs

---

frontend/src/plugins/impl/RefreshPlugin.tsx
marimo/_plugins/ui/_impl/refresh.py
marimo/_smoke_tests/refresh.py

update: refresh plugin to allow 100ms

---

docs/guides/wasm.md
frontend/src/core/pyodide/worker/bootstrap.ts

Closes https://github.com/marimo-team/marimo/issues/788
This makes a small tweak to fix loading pyodide in wasm notebooks

fix: wasm notebooks on ff

---

frontend/src/components/app-config/user-config-form.tsx
frontend/src/core/pyodide/worker/bootstrap.ts
marimo/_pyodide/pyodide_session.py
marimo/_runtime/complete.py
marimo/_runtime/runtime.py

Adds code completion to the wasm runtime. This is done on the same thread, but with another async task.
- we add a flag for `docstrings` limit to prevent searching for docstrings past 5 for performance reasons

improvement: support completions in wasm

---

docs/guides/wasm.md

docs: we now have code completion in wasm

---

frontend/src/components/editor/file-tree/requesting-tree.tsx

chore: fix typo ci

---

frontend/src/components/ui/slider.tsx
frontend/src/plugins/impl/SliderPlugin.tsx
frontend/src/utils/__tests__/numbers.test.ts
frontend/src/utils/numbers.ts

Adds commas and clipping to numbers in the slider.

improvement: format numbers in slider

---

frontend/src/components/data-table/data-table.tsx
frontend/src/components/editor/chrome/panels/file-explorer-panel.tsx
frontend/src/components/editor/file-tree/file-explorer.tsx
frontend/src/components/editor/file-tree/file-viewer.tsx
frontend/src/components/editor/file-tree/state.tsx
frontend/src/components/editor/file-tree/upload.tsx
frontend/src/core/network/types.ts
frontend/src/plugins/impl/vega/loader.ts
frontend/src/utils/objects.ts
marimo/_pyodide/pyodide_session.py
marimo/_server/api/endpoints/file_explorer.py
marimo/_server/files/file_system.py
marimo/_server/files/os_file_system.py
marimo/_server/models/files.py
tests/_server/api/endpoints/test_file_explorer.py
tests/_server/files/test_os_file_system.py

1. Add uploading a file (up to 50mb) via drag-n-drop or a button
2. Add a csv viewer that renders in our data-table.

improvement: add upload file (dnd and button), render csv in a table

---

frontend/src/core/config/config-schema.ts

Provide better fallbacks if the app fails to parse
Closes https://github.com/marimo-team/marimo/issues/860

fix: fallback when parsing config

---

frontend/src/components/editor/controls/notebook-menu-dropdown.tsx

Helpful for debugging and useful for marimo.app

add version to UI dropdown

---

frontend/src/components/app-config/app-config-form.tsx
frontend/src/components/editor/renderers/vertical-layout/vertical-layout-wrapper.tsx
frontend/src/core/config/config-schema.ts
frontend/src/css/App.css
frontend/tailwind.config.js
marimo/_ast/app.py

Adds a third width option, approximately 120 characters as requested in #872 
Closes #872

Add a third width option, "medium", in between normal and full

---

docs/api/plotting.md
docs/guides/plotting.md

fix example

---

marimo/_runtime/cell_runner.py

Fixes a bug in which traceback formatting raised an error when used with cell composition.
Bug is fixed by removing traceback formatting code that is no longer needed, since our compiler now gives each cell a filename (and can lookup its code)

fix: traceback formatting with cell composition

---

docs/guides/plotting.md

We support plotly in addition to altair for reactive plots

docs: add plotly to reactive plots guide

---

marimo/_cli/cli.py
marimo/_server/api/lifespans.py
marimo/_smoke_tests/bugs/852.py
marimo/_smoke_tests/bugs/877.py
marimo/_smoke_tests/bugs/881.py
marimo/_utils/debounce.py

Users can opt-in to listening on all interfaces

Make 127.0.0.1 the default host

---

docs/api/inputs/anywidget.md
docs/api/inputs/index.md
frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
frontend/src/plugins/plugins.ts
marimo/_dependencies/dependencies.py
marimo/_output/data/data.py
marimo/_output/formatters/anywidget_formatters.py
marimo/_output/formatters/formatters.py
marimo/_plugins/ui/__init__.py
marimo/_plugins/ui/_impl/from_anywidget.py
marimo/_smoke_tests/anywidget_compat.py
marimo/_smoke_tests/bugs/852.py
marimo/_smoke_tests/bugs/877.py
marimo/_smoke_tests/bugs/881.py
marimo/_utils/debounce.py
tests/_plugins/ui/_impl/test_anywidget.py

This adds an anywidget formatter to render anywidgets. But also if you do `mo.ui.anywidget`, itll bring the widget into our reactivity system. 
https://github.com/marimo-team/marimo/assets/2753772/2e66b6e2-b7dd-4c21-b3e4-737e61866068

Add anywidget formatter

---

docs/api/inputs/anywidget.md
marimo/_plugins/ui/__init__.py
marimo/_plugins/ui/_impl/from_anywidget.py
marimo/_server/models/completion.py
marimo/_smoke_tests/carousel.py
tests/_plugins/ui/_impl/test_anywidget.py

fixes docs to not show internal/private APIs

chore: _anywidget -> anywidget

---

frontend/src/plugins/core/registerReactComponent.tsx
frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
frontend/src/plugins/layout/CarouselPlugin.tsx
frontend/src/plugins/layout/carousel.css
frontend/src/plugins/types.ts
frontend/vite.config.mts

Fixes #913 
Carousel styling imports mess up the global styling, so this moves to to scoped on the carousel.

fix: carousel global styles which fixes latex rendering

---

frontend/src/core/pyodide/worker/types.ts
marimo/_pyodide/pyodide_session.py

address review comments from previous pr

---

.github/workflows/dev-release.yml

- PEP 440 local identifiers not allowed by PYPI -- remove git sha
- add fetch-depth: 0 to get history of tags

dev release fixes

---

.github/workflows/dev-release.yml

To make it easier to install from test pypi with dependencies ...

bump patch version for dev release

---

.github/workflows/dev-release.yml

Add a link to the URL in a post PR

chore: add PR comment with dev url 

---

.github/workflows/dev-release.yml
frontend/src/core/pyodide/bridge.ts
frontend/src/core/pyodide/worker/bootstrap.ts
frontend/vite.config.mts

This keeps the versions in sync to prevent breaking changes from breaking the app

chore: pass marimo version to worker

---

.github/workflows/dev-release.yml
frontend/index.html
marimo/_smoke_tests/bugs/924.py

Add some padding to `_resizeIframe` since it won't account for a scrollbar added.
Fixes #924

fix: add additional padding for scrollbar on resize

---

frontend/src/plugins/core/registerReactComponent.tsx

This broke when moving off jsdeliver

fix: copy styles

---

frontend/src/core/config/__tests__/config-schema.test.ts
frontend/src/core/config/config-schema.ts
frontend/src/utils/localStorage.ts

We were falling back to the default config instead of what came from index.html

fix: update user config in wasm to fallback to config from html

---

docs/faq.md

faq: document how to make marimo accessible on all network interfaces

---

frontend/src/components/editor/package-alert.tsx

For discoverability of the config

improvement: configure package manager in the missing package alert

---

marimo/_cli/envinfo.py
marimo/_server/api/endpoints/health.py
marimo/_utils/health.py
tests/_cli/test_envinfo.py

fixes expectation of pip being installed reported in #992
Exposed this data over the API, because I thought it would be nice to see from the notebook - but UI decisions are beyond anything I want to contribute

bug fix: support env / status without pip (#992)

---

frontend/src/core/pyodide/__tests__/router.test.ts
frontend/src/core/pyodide/__tests__/share.test.ts
frontend/src/core/pyodide/bridge.ts
frontend/src/core/pyodide/router.ts
frontend/src/core/pyodide/share.ts
frontend/src/core/pyodide/store.ts

This is part of the fix to allow for larger URL sizes

improvement: use url hash instead of query param

---

frontend/src/core/pyodide/router.ts
frontend/src/core/pyodide/store.ts
marimo/_smoke_tests/third_party/holoviews.py

This is a nice QOL when copying the url again

improvement: update hash in url when running in wasm

---

frontend/src/components/editor/package-alert.tsx
marimo/_runtime/packages/package_manager.py
marimo/_runtime/packages/pypi_package_manager.py
marimo/_runtime/runtime.py

Fixes a task mentioned in #992

fix: don't crash kernel when package managers are missing

---

frontend/src/components/app-config/user-config-form.tsx
frontend/src/components/editor/package-alert.tsx
frontend/src/core/config/config-schema.ts
frontend/src/core/network/types.ts
marimo/_runtime/packages/package_manager.py
marimo/_runtime/packages/package_managers.py
marimo/_runtime/packages/pypi_package_manager.py

make it possible to install packages with poetry.

improvement: add poetry as a package manager

---

.github/workflows/cla.yml

Locking the PR was interfering with other actions

dont lock gh prs after merge

---

frontend/src/components/editor/actions/useRestartKernel.tsx
frontend/src/core/pyodide/bridge.ts
frontend/src/core/pyodide/worker/worker.ts

Fix #1013 
A bit more defensive restart in wasm.

fix: more defensive restart in wasm

---

marimo/_plugins/core/media.py

fix local file reading for mo.audio

---

frontend/src/components/editor/Cell.tsx
frontend/src/components/editor/cell/cell-actions.tsx
frontend/src/core/hotkeys/hotkeys.ts

This is a pretty nice QOL improvement. You can run any cell action without leaving your keyboard, and we restore focus back

improvement: Cmd+p to open cell actions , restore focus back to cell

---

frontend/src/components/editor/cell/code/cell-editor.tsx
frontend/src/components/editor/cell/code/language-toggle.tsx
frontend/src/core/codemirror/language/markdown.ts

Should help unblock: https://github.com/marimo-team/marimo/pull/1021
cc @riyavsinha

fix: one source of truth for language adapter state

---

frontend/src/components/app-config/user-config-form.tsx
frontend/src/components/editor/package-alert.tsx
frontend/src/core/config/config-schema.ts
frontend/src/core/network/types.ts
marimo/_config/config.py
marimo/_runtime/packages/package_managers.py
marimo/_runtime/packages/pypi_package_manager.py

Make it possible to install packages using pixi via the frontend
Also cleanup types on frontend

feat: add pixi package manager

---

frontend/src/components/editor/renderers/cells-renderer.tsx
frontend/src/components/editor/renderers/layout-select.tsx
frontend/src/core/App.tsx
frontend/src/core/cells/cells.ts
frontend/src/core/layout/layout.ts
frontend/src/core/websocket/useMarimoWebSocket.tsx
marimo/_server/file_manager.py

This correctly updates the `AppConfig` when a user goes back to Vertical layout from Grid Layout
Closes #1031

fix: allow removing Grid layout

---

frontend/src/components/editor/actions/useCellActionButton.tsx
frontend/src/components/editor/cell/code/cell-editor.tsx
frontend/src/core/codemirror/__tests__/setup.test.ts
frontend/src/core/codemirror/cm.ts
frontend/src/core/codemirror/extensions.ts
frontend/src/core/codemirror/placeholder/extensions.ts
frontend/src/core/config/config.ts

Clickable placeholder to open the "generate with AI". This only shows if you have AI enabled.

feat: editor placeholder for AI prompt

---

marimo/_server/api/endpoints/ai.py

improvement: update ai system prompt to be mpl aware

---

frontend/src/core/pyodide/worker/bootstrap.ts
marimo/_pyodide/pyodide_session.py
marimo/_runtime/patches.py
marimo/_runtime/runtime.py

Patch the recursion limit back to the Python default
Also move the pyodide networking patch into the kernel

fix: jedi stack overflow bug

---

docs/guides/ai_completion.md

since openai is an optional dependency.

pip install openai in docs

---

frontend/src/plugins/impl/FileUploadPlugin.tsx
marimo/_plugins/ui/_impl/input.py
marimo/_smoke_tests/bugs/1064.py

- communicate when a file has been uploaded, show files in tooltip
- add option to remove uploaded files
- truncate file contents in Python repr -- very long contents rendered in a list was making the FE very slow
Closes #1075 
Closes #1053

improvement: mo.ui.file upload confirmation, removal

---

marimo/_output/formatters/matplotlib_formatters.py
marimo/_output/mpl.py
marimo/_plugins/stateless/mpl/_mpl.py
marimo/_smoke_tests/bugs/1064.py
marimo/_utils/file_watcher.py

silence type errors for matplotlib/watchdog, which were cluttering the output of make py-check ...

chore: silence some type errors

---

marimo/_output/formatters/matplotlib_formatters.py
marimo/_runtime/context.py
marimo/_smoke_tests/bugs/1086.py

fix: dont use mpl backend when running as a script

---

frontend/e2e-tests/cells.spec.ts
frontend/e2e-tests/components.spec.ts
frontend/e2e-tests/disabled.spec.ts
frontend/e2e-tests/helper.ts
frontend/e2e-tests/mode.spec.ts

chore: e2e - count() -> toHaveCount()

---

frontend/src/components/editor/chrome/panels/documentation-panel.tsx
frontend/src/components/editor/chrome/types.ts
frontend/src/components/editor/chrome/wrapper/footer.tsx

A few folks have been confused about what the docs panel does

UX hint for live docs

---

.github/workflows/dev-release.yml
.github/workflows/playwright.yml
.github/workflows/release.yml
.github/workflows/test.yaml
.github/workflows/test_cli.yaml

chore: use uv in CI

---

frontend/src/plugins/impl/SliderPlugin.tsx
marimo/_plugins/ui/_impl/input.py

improvement: add full_width option to slider

---

frontend/src/plugins/impl/SliderPlugin.tsx

fix slider styling

---

marimo/_cli/upgrade.py
marimo/_plugins/ui/_impl/dataframes/dataframe.py
marimo/_plugins/ui/_impl/dataframes/handlers.py
marimo/_runtime/packages/conda_package_manager.py
marimo/_runtime/packages/package_manager.py
marimo/_runtime/packages/pypi_package_manager.py
marimo/_server/api/endpoints/assets.py
marimo/_server/exceptions.py
marimo/_server/sessions.py
pyproject.toml
tests/_ast/test_app.py
tests/_plugins/stateless/status/test_progress.py
tests/_plugins/stateless/test_image.py
tests/_plugins/ui/_impl/test_table.py
tests/_server/api/endpoints/test_files.py
tests/_server/api/endpoints/test_ws.py
tests/_server/test_file_manager.py
tests/_server/test_utils.py
tests/_utils/test_file_watcher.py
tests/_utils/test_parse_dataclass.py

Manually fix some ruff rules to keep the codebase healthy

chore: enable more ruff rules

---

README.md
docs/faq.md
docs/getting_started/index.md
marimo/_server/api/lifespans.py
marimo/_server/print.py
marimo/_tutorials/intro.py

Update docs to reflect new behavior of `marimo edit`

docs: marimo edit - homepage

---

marimo/_utils/parse_dataclass.py
tests/_utils/test_parse_dataclass.py

This PR proposes a small refactoring to avoid the need for an unconditional `except` clause to catch all exceptions. Instead, additional checks are introduced and only `TypeError` is ignored. (If there are additional expected exceptions that can safely be ignored, these would need to be added.)

refactor parse_dataclass.py

---

docs/api/index.md
docs/api/miscellaneous.md
marimo/__init__.py
marimo/_runtime/runtime.py
tests/_runtime/test_runtime.py

Returns True if running in a (marimo) notebook, otherwise False
Closes #1138

feat: mo.running_in_notebook()

---

marimo/_ast/codegen.py
tests/_ast/codegen_data/test_generate_filecontents_async_long_signature.py
tests/_ast/test_codegen.py

fix: dont drop async prefix when re-formatting cell signature

---

docs/api/inputs/anywidget.md
docs/api/miscellaneous.md
docs/guides/editor_features.md
docs/guides/index.md
docs/guides/integrating_with_marimo/custom_ui_plugins.md
docs/guides/integrating_with_marimo/displaying_objects.md
docs/guides/integrating_with_marimo/index.md

Add documentation on displaying objects and implementing plugins (AnyWidget). Also document hot-reloading.

docs: integrations guide

---

frontend/src/css/katex.min.css

Slightly bigger latex

---

docs/api/media/index.md
docs/guides/outputs.md
docs/guides/overview.md

add a bit more info about outputs to docs

---

docs/_static/css/custom.css
docs/conf.py
docs/index.md

docs: add search and icons to the header

---

marimo/_runtime/cell_runner.py
tests/_cli/test_cli_export.py
tests/conftest.py

fix: don't install interrupt signal handler in run mode

---

docs/guides/overview.md
docs/guides/reactivity.md
docs/index.md

doc improvements

---

tests/_runtime/reload/test_module_watcher.py

nondeterminism in the module reloader test ...

Bump timeout

---

marimo/_server/file_router.py

Don't fail if searching on a marimo app fails

fix: don't fail if searching for marimo apps fail on a file

---

docs/faq.md

faq about late binding closures in Python

---

frontend/islands/__demo__/output.html
frontend/src/components/editor/actions/useCellActionButton.tsx
frontend/src/components/editor/actions/useNotebookActions.tsx
frontend/src/components/editor/cell/useDeleteCell.tsx
frontend/src/components/editor/renderers/CellArray.tsx
frontend/src/core/App.tsx
frontend/src/core/cells/cells.ts

Fixes #1192
* add cell deletion toast to undo
* add to command pallete
* add to notebook actions

improvement: add cell deletion toast to undo, and add to command pallete and notebook actions

---

marimo/_server/api/utils.py

fix: graalpy

---

frontend/src/core/codemirror/cm.ts
frontend/src/css/codehilite.css

requested in notion feedback; hit it myself a few times too.

improvement: tab to start completion

---

marimo/_utils/flatten.py
tests/_ast/test_app.py
tests/_smoke_tests/test_run_as_script.py
tests/_utils/test_flatten.py

Fixes a bug when trying to format subclasses of list/tuple.
Fixes #1219

fix: flatten subtype

---

frontend/src/css/globals.css

This was regressed when adding styles for islands

fix: dark theme selectors

---

.github/workflows/dev-release.yml
.github/workflows/release.yml

Publish islands in the release.yml workflow

chore: publish islands

---

frontend/src/components/editor/actions/useCellActionButton.tsx
frontend/src/components/editor/cell/useDeleteCell.tsx
frontend/src/core/cells/cells.ts

* hide cell action items
* don't toast when using the hotkey

fix: edge-case for not deleting the last cell

---

frontend/islands/__demo__/index.html
frontend/src/components/data-table/mime-cell.tsx
frontend/src/components/editor/Output.tsx
frontend/src/components/editor/output/ConsoleOutput.tsx
frontend/src/core/islands/bridge.ts
frontend/src/core/islands/components/output-wrapper.tsx
frontend/src/core/islands/parse.ts

- properly render json output
- skip reactive/wasm when there is no code

fix: marimo islands output rendering edge-cases

---

marimo/_plugins/ui/_impl/input.py

`steps` needs to be at the end of the args

fix: revert breaking change in mo.ui.slider

---

marimo/_server/file_router.py
tests/_server/test_file_router.py

fix: avoid failing marimo edit on broken symlinks

---

marimo/_plugins/ui/_impl/tables/pandas_table.py
marimo/_smoke_tests/bugs/1140.py
tests/_plugins/ui/_impl/tables/test_pandas_table.py

fix: include datatime and timedelta index in output

---

CONTRIBUTING.md
frontend/src/plugins/core/RenderHTML.tsx
marimo/_output/formatters/leafmap_formatters.py
marimo/_smoke_tests/bugs/1241.py

fix: leafmap.folium.Map formatting

---

marimo/_pyodide/pyodide_session.py
marimo/_runtime/packages/package_manager.py
marimo/_runtime/packages/pypi_package_manager.py
marimo/_runtime/runtime.py
tests/_runtime/reload/test_module_watcher.py
tests/_runtime/test_runtime.py
tests/conftest.py

this autoinstalls packages in micropip which will help reduce the errors when in run mode

feat: autoinstall packages in micropip

---

tests/_server/files/test_os_file_system.py

Follow-up PR to #1253 to stream-line my added unit test.

removed unittest from test_os_file_system.py

---

frontend/src/css/codehilite.css

improve traceback colors

---

frontend/src/components/ui/input.tsx
frontend/src/components/variables/variables-table.tsx

- add global text search to filters table
- sticky header
Part of #1261 for searching

improvement: add global text search to filters table, sticky header

---

marimo/_output/builder.py
marimo/_smoke_tests/bugs/1291.py
tests/_output/test_builder.py

Fixes #1291
React has my brain working wrong:
Allowed self-closing tags:
```
<area>
<base>
<br>
<col>
<embed>
<hr>
<img>
<input>
<link>
<meta>
<param>
<source>
<track>
<wbr>
```

fix: self-closing iframes is not a thing

---

frontend/e2e-tests/kitchen-sink.spec.ts
frontend/e2e-tests/layout-grid.spec.ts
frontend/e2e-tests/stdin.spec.ts
frontend/playwright.config.ts

Should reduce some startup time in CI

test: consolidate some 'edit' e2e tests to a single server

---

frontend/src/components/dependency-graph/panels.tsx
frontend/src/components/editor/cell/cell-actions.tsx
frontend/src/components/editor/chrome/wrapper/footer.tsx
frontend/src/components/editor/chrome/wrapper/machine-stats.tsx
frontend/src/components/editor/links/cell-link-list.tsx
frontend/src/components/ui/button.tsx
frontend/src/core/cells/focus.ts

* Add cell actions and input/output variables to DAG viewer panel
* Reduce hover delay on footer items

improvement: add cell actions and input/output variables to dag viewer panel

---

README.md
docs/_static/css/custom.css
docs/faq.md
docs/guides/coming_from_jupyter.md
docs/guides/editor_features.md
docs/guides/index.md
docs/guides/overview.md
docs/guides/reactivity.md
docs/guides/runtime_configuration.md

Document the lazy runtime. Fix a broken style in the docs, too.

docs: lazy runtime

---

docs/_static/css/custom.css
docs/guides/exporting.md
docs/guides/island_example.md
docs/guides/wasm.md
marimo/__init__.py
pyproject.toml

Docs and remove `experimental` prefix

feat: preview marimo-islands, add docs

---

docs/index.md

link to newsletter, twitter, blog

docs: add links

---

frontend/src/components/editor/cell/code/ai-completion-editor.tsx

Was a regression when i upgraded `ai` package

fix: ai completion streaming

---

marimo/_output/formatters/holoviews_formatters.py
pyproject.toml

Fixes #979, thanks to [Glide](https://glide.agenticlabs.com) 
https://glide.agenticlabs.com/sharing?userId=663a52d61b38e3aa664ef39d&taskId=MC4rIg1

fix: HoloMap formatter

---

marimo/_output/formatters/bokeh_formatters.py
marimo/_smoke_tests/bugs/1351.py

fix: use theme in bokeh formatter

---

README.md

fix: readme images when displayed off github

---

frontend/src/core/MarimoApp.tsx
frontend/src/core/edit-app.tsx
frontend/src/core/islands/main.ts
frontend/src/core/kernel/RuntimeState.ts
frontend/src/core/kernel/__tests__/RuntimeState.test.ts
frontend/src/core/run-app.tsx
frontend/src/utils/lazy.ts

There was a circular dependency between some of these files, causing wasm to fail

fix: circular dep in wasm controller

---

.github/workflows/playwright.yml
CONTRIBUTING.md
frontend/e2e-tests/kitchen-sink-wasm.spec.ts
frontend/playwright.config.ts
frontend/src/core/edit-app.tsx
frontend/src/core/pyodide/worker/bootstrap.ts
frontend/vite.config.mts
marimo/_server/api/endpoints/login.py

Previously we were always instantiating

fix: respect auto-instantiate while in wasm

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/plugins/impl/data-explorer/ConnectedDataExplorerComponent.tsx
frontend/src/plugins/impl/data-explorer/DataExplorerPlugin.tsx
frontend/src/plugins/impl/data-explorer/queries/types.ts
frontend/src/plugins/impl/vega/VegaPlugin.tsx
frontend/src/plugins/impl/vega/params.ts
frontend/src/plugins/impl/vega/vega-component.tsx
frontend/src/stories/data-explorer.stories.tsx
frontend/src/stories/vega.stories.tsx
frontend/src/utils/numbers.ts

Reduce some bundle size on the first index.js 
* lazy load vega
* remove mathjs

refactor: lazy-load vega plugins

---

marimo/_ast/app.py
tests/_smoke_tests/test_run_as_script.py

https://github.com/marimo-team/marimo/issues/1368
https://glide.agenticlabs.com/sharing?userId=65bae7547a39e05fc421bd8c&taskId=MuRvmdK

Skip disabled cells in script

---

frontend/src/components/editor/renderers/vertical-layout/sidebar/sidebar.tsx
marimo/_plugins/stateless/flex.py
marimo/_plugins/stateless/sidebar.py
tests/_plugins/stateless/test_flex.py

Fixes #1384
* add footer to sidebar 
* add `justify` to vstack
* raise errors on some fluid apis from the sidebar

improvement: add footer to sidebar and disbale some Html fluid apis (callout, batch)

---

marimo/_plugins/ui/_core/registry.py
marimo/_plugins/ui/_core/ui_element.py

`__del__` called each time refcount decremented, but we want to cleanup only when refcount reaches 0. Use weakref.finalize to do that.

fix: cleanup of UIElements

---

frontend/src/components/editor/renderers/CellArray.tsx

Footer buttons to easily add a new code or markdown cell

improvement: Add cell buttons at bottom

---

docs/guides/deploying/deploying_ploomber.md
docs/guides/deploying/index.md

documents ploomber cloud as an option for deployment
changed the guides/deploying indes and added a new subpage

adds ploomber cloud deployment

---

.gitignore
frontend/src/components/editor/ai/add-cell-with-ai.tsx
frontend/src/components/editor/cell/code/ai-completion-editor.tsx
frontend/src/components/editor/renderers/CellArray.tsx
marimo/_server/api/endpoints/ai.py

This adds a button to the button to add a new cell via AI, if enabled.

feat: ai completion button

---

frontend/src/css/admonition.css
frontend/src/css/globals.css
frontend/src/css/index.css
marimo/_output/md.py
marimo/_smoke_tests/admonitions.py

Adds admonition formatting with markdown and stylings
Fixes #1340

feat: admonition in markdown

---

docs/api/layouts/routes.md
marimo/_plugins/stateless/routes.py

Update routes docs

---

frontend/src/components/pages/edit-page.tsx
frontend/src/core/MarimoApp.tsx
frontend/src/core/edit-app.tsx
frontend/src/core/websocket/useMarimoWebSocket.tsx
frontend/src/core/websocket/useWebSocket.tsx
frontend/src/hooks/debug.ts

Apparent `useState` with a function could be called twice which would cause the websocket to connect multiple times

fix: websocket connection from connecting twice

---

frontend/src/core/codemirror/go-to-definition/underline.ts

This may fix https://github.com/marimo-team/marimo/issues/1462

fix: maybe fixes cmd+click, remove all underlines

---

frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
frontend/src/components/static-html/static-banner.tsx
marimo/_server/api/endpoints/export.py
marimo/_server/export/exporter.py
tests/_server/api/endpoints/test_export.py

Add download as html or png in Run mode. 
Note: this is always enabled and not configurable

feat: add download as html or png in Run mode

---

marimo/_cli/envinfo.py
marimo/_islands/island_generator.py
marimo/_server/export/__init__.py
marimo/_smoke_tests/bugs/key_with_period.py

PR #1410 accidentally reverted @gvarnavi's changes to islands ...

bring back island changes

---

frontend/src/core/codemirror/go-to-definition/underline.ts

Not sure if this is actually needed, but shouldn't hurt ...

more defensive underline clearing on keyup

---

frontend/src/components/editor/controls/Controls.tsx
frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx

download action button was showing up in app preview, clipping other buttons

dont show download action buttons in edit mode

---

frontend/src/core/pyodide/worker/getPyodideVersion.ts

bump pyodide to 0.26.0

---

marimo/_cli/cli.py
marimo/_server/api/lifespans.py
marimo/_server/start.py

@mscolnick Adds the proxy support I mentioned on ~github~ discord. Thanks to copilot for the nice ascii diagrams (although maybe a bit over the top)

Flag for reverse proxy support

---

marimo/_output/formatters/matplotlib_formatters.py
marimo/_output/mpl.py
marimo/_plugins/stateless/mpl/_mpl.py
marimo/_smoke_tests/bugs/1510.py

Fixes #1510
Previous legends outside the bounding box overflowed.

fix: matplotlib with legends outside of bbox

---

marimo/_plugins/ui/_impl/plotly.py

Fixes when `pio.renderers.default` is `""` or `None`

fix: mo.ui.plotly AttributeError

---

frontend/src/core/datasets/state.ts
marimo/_plugins/ui/_impl/tables/pandas_table.py
marimo/_smoke_tests/datasources.py
tests/_plugins/ui/_impl/tables/test_pandas_table.py

Fixes #1525 
- improvement: auto-refetch stale dataset column previews
- fix: dataset column summary for non-hashable columns

improvement: refetch stale dataset column previews, fix: dataset column summary for non-hashable columns

---

frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
frontend/src/css/app/App.css

Small cosmetic improvement to disconnected background.

tweak disconnected gradient positioning

---

docs/guides/dataframes.md

Update location of the `polars_example.py` file.
PR #1419 moved the location of the `polars_example.py` file. This PR adjusts sources to change.

fix: update polars example reference

---

marimo/_data/preview_column.py
marimo/_messaging/mimetypes.py
marimo/_plugins/ui/_impl/charts/altair_transformer.py
marimo/_plugins/ui/_impl/tables/default_table.py
marimo/_plugins/ui/_impl/tables/pandas_table.py
marimo/_plugins/ui/_impl/tables/polars_table.py
marimo/_plugins/ui/_impl/tables/pyarrow_table.py
marimo/_plugins/ui/_impl/tables/table_manager.py
marimo/_smoke_tests/bugs/1530.py
tests/_data/snapshots/column_preview_chart_code.txt
tests/_data/snapshots/column_preview_chart_spec.txt
tests/_data/snapshots/column_preview_date_chart_code.txt
tests/_data/snapshots/column_preview_date_chart_spec.txt
tests/_data/test_charts.py
tests/_data/test_preview_column.py
tests/_plugins/ui/_impl/tables/test_default_table.py
tests/_plugins/ui/_impl/tables/test_pandas_table.py
tests/_plugins/ui/_impl/tables/test_polars_table.py
tests/_plugins/ui/_impl/tables/test_pyarrow.py

- Select only the columns for the data being used
- Use csv on non-date columns
- Increase limit of data being sent to 20k

improvement: reduce data sent for each column preview

---

frontend/src/components/editor/boundary/ErrorBoundary.tsx
frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
frontend/src/utils/strings.ts

fix: escape newline in column name

---

frontend/src/components/variables/variables-table.tsx
marimo/_smoke_tests/bugs/643.py

Fixes https://github.com/marimo-team/marimo/issues/945

improvement: filter variable by cell name

---

frontend/src/components/data-table/column-header.tsx
frontend/src/components/data-table/data-table.tsx

fix: firefox table header

---

frontend/src/plugins/impl/FileBrowserPlugin.tsx
frontend/src/plugins/impl/FileUploadPlugin.tsx
frontend/src/utils/paths.ts
frontend/src/utils/pluralize.ts

improvement: mo.ui.file_browser UI polish

---

frontend/src/components/app-config/user-config-form.tsx
frontend/src/components/editor/controls/Controls.tsx
frontend/src/components/editor/renderers/vertical-layout/vertical-layout-wrapper.tsx
frontend/src/core/config/__tests__/config-schema.test.ts
frontend/src/core/config/config-schema.ts
frontend/src/stories/cell.stories.tsx
marimo/_ast/app.py
marimo/_config/config.py
marimo/_islands/island_generator.py
marimo/_pyodide/bootstrap.py
marimo/_server/file_manager.py
marimo/_server/file_router.py
marimo/_server/sessions.py
marimo/_server/templates/templates.py
tests/_ast/test_app.py
tests/_server/templates/snapshots/export1.txt
tests/_server/templates/snapshots/export2.txt
tests/_server/templates/snapshots/export3.txt

Adds a display.width configuration to the user config that controls the default app width for new notebooks, with a default value of "medium".

user config: display.width

---

frontend/src/plugins/impl/vega/loader.ts
frontend/src/utils/__tests__/url.test.ts
frontend/src/utils/url.ts

Fixes #1600 
- Fix altair rendering with `baseUrl` 
- Also fixes another bug found when passing a json url to altair, we were trying to modify it's headers

fix: altair rendering with baseUrl

---

marimo/_plugins/ui/_impl/tables/df_protocol_table.py
marimo/_plugins/ui/_impl/tables/types.py
marimo/_plugins/ui/_impl/tables/utils.py
marimo/_smoke_tests/bugs/1602.py
tests/_plugins/ui/_impl/tables/test_table_utils.py

Fixes #1602
This is a bit more robust checking if its "dataframe-like" and has the dataframe protocol

fix: false positive dataframe-like check

---

frontend/src/plugins/core/registerReactComponent.tsx

This broken static html export. We were accidentally copying over `.js` files

fix: more defensive stylesheet copy

---

marimo/_plugins/ui/_core/ui_element.py
marimo/_plugins/ui/_impl/altair_chart.py
marimo/_smoke_tests/no_mutating.py

We can educate when people try to mutate

improvement: better errors when mutated value or on_change

---

marimo/_runtime/runtime.py

This change fixes a bug in which the directory in which marimo home was started (when using marimo edit) was incorrectly added to sys.path even when working in a notebook in a subdirectory. This led to modules being importable that shouldn't have been importable.

fix:  marimo home directory shouldn't be in sys.path

---

frontend/src/core/cells/cell.ts

Fixes [regression](https://github.com/marimo-team/marimo/pull/1625#issuecomment-2172244502) introduced by #1625.

fix: Set stale status to false on cell transition to idle

---

frontend/src/core/edit-app.tsx
frontend/src/core/islands/main.ts
frontend/src/core/network/requests-network.ts
frontend/src/theme/useTheme.ts
marimo/_server/api/endpoints/files.py
marimo/_server/file_manager.py
marimo/_server/models/models.py
openapi/api.yaml
openapi/src/api.ts
tests/_server/api/endpoints/test_files.py

- theming selector for vscode
- return code on save and save_config

vscode: theming for vscode, return code on save

---

marimo/_output/formatters/plotly_formatters.py

Error from https://marimo.app/?slug=i2ila2

fix: plotly formatting error

---

CONTRIBUTING.md

This PR fixes a small typo in the command for printing the Python version.
Instead of `python -v` use `python -V` as explained in the `python -h` help menu:
```
-v     : verbose (trace import statements); also PYTHONVERBOSE=x
can be supplied multiple times to increase verbosity
-V     : print the Python version number and exit (also --version)
when given twice, print more information about the build
```

chore: fix typo

---

frontend/src/plugins/impl/DataTablePlugin.tsx
marimo/_plugins/ui/_impl/table.py
tests/_plugins/ui/_impl/test_table.py

- **fix: clear global search in the backend for dataframes**
- **fix: clear global search in the backend for dataframes**

fix: clear global search in the backend for dataframes

---

frontend/src/components/editor/ai/add-cell-with-ai.tsx
frontend/src/components/editor/cell/code/ai-completion-editor.tsx
frontend/src/components/pages/home-page.tsx
frontend/src/utils/__tests__/url.test.ts
marimo/_cli/cli.py

`--base-url` support for marimo edit/new
Fixes #1648

improvement: --base-url support for marimo edit/new

---

frontend/src/core/websocket/useWebSocket.tsx

decrease connection timeout for ws

---

frontend/src/components/editor/cell/useRunCells.ts

fix: cell run button in present

---

docs/recipes.md
frontend/src/components/editor/Output.tsx
frontend/src/core/dom/outline.ts
marimo/_smoke_tests/bugs/1710.py

Fixes #1710 
Don't error when the html is null (just return an empty object)

fix: don't error on null html

---

marimo/_messaging/ops.py
marimo/_output/formatting.py
marimo/_smoke_tests/bugs/1706.py
marimo/_smoke_tests/bugs/1711.py
tests/_messaging/test_ops.py
tests/_output/formatters/test_formatters.py

polars sometimes panics unexpectedly
fixes #1711

fix: make hooks robust to base exceptions

---

frontend/src/components/editor/Cell.tsx
frontend/src/components/editor/cell/CreateCellButton.tsx
frontend/src/css/app/Cell.css
frontend/src/css/common.css

improvement: right-click add button to add Markdown or SQL

---

frontend/src/components/editor/cell/CreateCellButton.tsx

tiny change, for completeness.

add python cell to create cell context menu

---

.github/PULL_REQUEST_TEMPLATE.md
docs/guides/ai_completion.md
docs/recipes.md
marimo/_plugins/ui/_impl/batch.py

Fix typos in the following documents:
- `docs/guides/ai_completion.md`
- `docs/recipes.md`
- `marimo/_plugins/ui/_impl/batch.py`
Fix a broken link `[contributor guidelines](../CONTRIBUTING.md)` in PR template

docs: fix typos and a broken link in PR template

---

frontend/src/core/cells/cells.ts
frontend/src/core/cells/scrollCellIntoView.ts

fix: focus top and focus bottom

---

frontend/src/components/home/state.ts
frontend/src/components/pages/home-page.tsx
frontend/src/core/network/types.ts
frontend/src/hooks/useAsyncData.ts
frontend/src/utils/dates.ts
marimo/_cli/development/commands.py
marimo/_server/api/endpoints/home.py
marimo/_server/file_router.py
marimo/_server/files/os_file_system.py
marimo/_server/models/files.py
marimo/_server/models/home.py
marimo/_server/recents.py
openapi/api.yaml
openapi/pnpm-lock.yaml
openapi/src/api.ts

improvement: improved homepage with search and file-explorer

---

docs/faq.md

Fixes the FAQ anchor for `Is marimo a notebook or a library?`
Simple anchor change in the FAQ md.

Fix FAQ anchor

---

frontend/src/components/pages/home-page.tsx
frontend/src/utils/__tests__/path.test.ts
frontend/src/utils/paths.ts

This lead to the incorrect file path being passed

fix: opening files when using 'marimo <dir>'

---

frontend/src/core/static/__tests__/files.test.ts
frontend/src/core/static/files.ts

fix: patching vegaloader again, supporting various pathnames

---

marimo/_plugins/ui/_impl/tables/types.py

this was breaking import of xdsl
Fixes #1699

fix: remove side-effectful isinstance check

---

pyproject.toml

add missing requirement

---

marimo/_server/file_router.py

Fixes an issue raised on Discord.

fix: handle os errors in listing files

---

marimo/_ast/app.py
marimo/_runtime/app/kernel_runner.py
marimo/_runtime/runtime.py

Implements function calling into nested apps.

fix: function calling with nested apps

---

marimo/_server/api/endpoints/xterm.py

I didn't want to spent too long on this, since I didn't think it was a priority.
Not super happy with the implementation- I think there's room for improvement- but it works!

Iterated on async implementation

---

frontend/src/components/data-table/data-table.tsx
frontend/src/components/editor/chrome/wrapper/sidebar.tsx
frontend/src/css/admonition.css

fix: column wrap styling, don't capitalize admonoition and better contrast

---

frontend/src/css/katex.min.css
marimo/_smoke_tests/bugs/1684.py

Fix: latex tag alignment

---

frontend/src/components/editor/chrome/panels/datasources-panel.tsx
frontend/src/core/datasets/state.ts
marimo/_ast/cell.py
marimo/_ast/visitor.py
marimo/_data/get_datasets.py
marimo/_data/models.py
marimo/_data/sql_visitor.py
marimo/_messaging/ops.py
marimo/_runtime/requests.py
marimo/_runtime/runner/hooks_post_execution.py
marimo/_runtime/runtime.py
marimo/_server/session/session_view.py
openapi/api.yaml
openapi/src/api.ts
tests/_ast/test_codegen.py
tests/_data/test_get_datasets.py
tests/_data/test_preview_column.py
tests/_data/test_sql_visitor.py
tests/_server/session/test_session_view.py

Whenever we come across a SQL statement with `CREATE, ATTACH, or DETACH`, we fetch tables from duckdb and update the UI

feat: sql datasources

---

marimo/_ast/cell.py
marimo/_smoke_tests/altair/altair_brush.py

Minor performance improvement. No need to re-parse sql statements on every access.

cache parsed SQL statements

---

marimo/_utils/distributor.py

Socket reads in the server sporadically fail. If a read fails with a BlockingIOError, retry it after a short wait (if the connection still polls() true).
This is an attempt to mitigate the issue discussed in #1568.

fix: make recv robust to EAGAIN, EDEADLK

---

frontend/src/core/cells/__tests__/__snapshots__/cells.test.ts.snap
frontend/src/core/cells/__tests__/cells.test.ts
frontend/src/core/cells/cell.ts

fix: move cell back to idle on error

---

frontend/src/components/editor/cell/code/cell-editor.tsx
frontend/src/components/scratchpad/scratchpad.tsx
frontend/src/core/codemirror/cells/extensions.ts
frontend/src/core/config/feature-flag.tsx
marimo/_runtime/runtime.py
tests/_runtime/test_runtime.py

This enables the scratchpad and cleans up some of the rough edges.

feat: scratchpad

---

frontend/src/components/scratchpad/scratchpad.tsx

style: scratchpad

---

frontend/src/components/editor/Cell.tsx
frontend/src/components/editor/Output.tsx
frontend/src/components/editor/actions/useCellActionButton.tsx
frontend/src/components/editor/cell/code/ai-completion-editor.tsx
frontend/src/components/editor/cell/code/cell-editor.tsx
frontend/src/components/editor/output/ConsoleOutput.tsx
frontend/src/components/editor/output/MarimoErrorOutput.tsx
frontend/src/components/editor/output/MarimoTracebackOutput.tsx
frontend/src/components/editor/output/traceback-output.css
frontend/src/components/ui/accordion.tsx
frontend/src/core/ai/state.ts
marimo/_messaging/mimetypes.py
marimo/_messaging/tracebacks.py
marimo/_output/mime.py
openapi/api.yaml
openapi/src/api.ts

Improve traceback readability on the FE. Also add help with Google or AI

feat: better traceback, help with google or AI

---

frontend/src/plugins/impl/DataTablePlugin.tsx

fix: stale dataframe summaries

---

frontend/src/components/editor/file-tree/file-explorer.tsx

improvement: add copy path / copy relative path to file explorer

---

frontend/src/components/editor/chrome/panels/outline-panel.tsx
frontend/src/components/editor/chrome/panels/outline/floating-outline.tsx
frontend/src/components/editor/chrome/panels/outline/useActiveOutline.tsx
frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
frontend/src/core/dom/outline.ts

feat: floating outline in run/present

---

marimo/_plugins/ui/_impl/tables/polars_table.py
tests/_plugins/ui/_impl/tables/test_polars_table.py

fix: polars Array type casting when converting to a csv

---

marimo/_plugins/stateless/mpl/_mpl.py

fix: dont close an already closed websocket with mo.mpl.interactive

---

docs/guides/editor_features.md
frontend/src/core/codemirror/keymaps/keymaps.ts
frontend/src/core/codemirror/keymaps/vim.ts

add vim go-to-definition (gd), and some docs

improvement: add vim go-to-definition (gd)

---

frontend/src/plugins/impl/RadioPlugin.tsx

Small PR based on user feedback. Lightens text weight for radio options.

style: radio button

---

frontend/src/components/slides/slides-component.tsx

fix: make carousel slides scrollable

---

frontend/src/core/cells/cells.ts

fix: show toc in static export

---

frontend/src/components/data-table/__test__/column_formatting.test.ts
frontend/src/components/data-table/column-formatting/feature.ts
frontend/src/components/data-table/column-formatting/types.ts
frontend/src/components/data-table/column-header.tsx

improvement: add examples to table formatting dropdown

---

marimo/_ast/visitor.py
marimo/_tutorials/sql.py
tests/_ast/test_visitor.py

fix sql references

---

frontend/src/components/editor/renderers/CellArray.tsx
frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
marimo/_plugins/core/web_component.py
marimo/_tutorials/sql.py

Small updates to SQL tutorial.
Also snuck in a couple of other changes:
- decrease label size for UI elements
- always show floating outline

touchup SQL tutorial

---

frontend/src/components/editor/file-tree/file-explorer.tsx
frontend/src/components/editor/file-tree/file-viewer.tsx

improvement: easy open marimo file

---

frontend/src/components/editor/Output.tsx

also adjusts z-index, previously expandicon was clipping tooltip

style fix for expand icon to prevent overlap with stale icon

---

frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx

no gap when in preview mode during edit session

fix: gap between cells for wasm

---

docs/api/inputs/anywidget.md

update anywidget docs

---

examples/sql/duckdb_connections.py
examples/sql/sqlite.py

Adds an example of how to work with sqlite databases.

example: sqlite

---

frontend/src/components/sort/SortableCellsProvider.tsx

fix: dont scroll horizontally when dragging cells

---

tests/_runtime/test_runtime.py

test: check that certain globals are populated in execution context

---

examples/ai/substrate-run.py

[Screencast from 08-09-2024 03:50:56 PM.webm](https://github.com/user-attachments/assets/85ce4c77-8a59-4ff1-a972-88848529d988)

add substrate example

---

frontend/src/components/editor/actions/useCellActionButton.tsx
marimo/_runtime/runner/cell_runner.py

Fixes a bug with disable status propagation.
Fixes the semantics of the disable toggle UI (fixes #1967).

Fix: disable transitively status

---

marimo/_cli/development/commands.py
marimo/_runtime/patches.py
marimo/_runtime/requests.py
marimo/_runtime/runtime.py
marimo/_server/api/endpoints/files.py
marimo/_server/models/models.py
tests/_server/api/endpoints/test_files.py
tests/_server/mocks.py

Followup to the tests, seemed like a quick change when reading over #1989 #1988
@akshayka

feat/fix: reactive filename/ fallback for __file__

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/editor/output/JsonOutput.tsx
frontend/src/components/editor/output/Outputs.css
frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
frontend/src/core/MarimoApp.tsx
frontend/src/css/app/reset.css
frontend/src/css/md.css
frontend/src/css/table.css
frontend/src/plugins/layout/AccordionPlugin.tsx
frontend/tailwind.config.js
marimo/_output/md.py
marimo/_plugins/core/web_component.py
tests/_islands/snapshots/island-no-code.txt
tests/_islands/snapshots/island.txt
tests/_output/test_md.py

- **Revert "Revert "improvement: cleanup markdown, use prose (#1892)" (#1950)"**
- **fix dark mode** (https://github.com/marimo-team/marimo/pull/2003/commits/0b3fb92331b91e9f4606123c6b1771fa00353d44)

improvement: cleanup markdown, use prose (try 2)

---

marimo/_ast/app.py

[doc] missing word

---

frontend/src/components/buttons/undo-button.tsx
frontend/src/components/editor/cell/useDeleteCell.tsx
frontend/src/components/find-replace/find-replace.tsx
frontend/src/components/shortcuts/renderShortcut.tsx

Add meta+z to trigger undo when its open/active.

improvement: bind meta-z to undo toast

---

marimo/_cli/upgrade.py

improvement: reduce payload of version check from pypi

---

README_Chinese.md

Provide Chinese annotations for the README.
I added a README_chinese.md file, which is the localized Chinese version of the README.md.
I localized the entire text of the README file, using highly localized phrasing and language habits. This opens the door for Chinese users to better understand our project. China has a large community of Python users and developers, and this localization helps empower more users and developers who struggle with the difficulties and error-prone nature of Jupyter. It will assist them in focusing their attention on making new discoveries in their respective fields.
Additionally, as someone working in a research institution and involved in education, I hope this is a good starting point for me to introduce this excellent project to my students and colleagues. …

Create README_Chinese.md. 

---

README.md
README_Chinese.md

some changes for the Chinese README
some 

some changes for the Chinese README

---

frontend/src/components/data-table/chart-spec-model.tsx

fix: bar chart x-scale for boolean column preview

---

frontend/src/components/editor/chrome/wrapper/sidebar.tsx
frontend/src/core/cells/cells.ts
frontend/src/core/cells/utils.ts

Adds a stack of green boxes to indicate the number of queued items

feature: queue stack on the left side-bar

---

.github/workflows/test_cli.yaml
examples/data_explorer.py
examples/requirements.txt
examples/third_party/duckdb_example.py
marimo/_smoke_tests/bugs/1351.py
marimo/_smoke_tests/bugs/1654-virtualize-multiselect.py
marimo/_smoke_tests/bugs/1711.py
marimo/_smoke_tests/dataframe.py
marimo/_smoke_tests/import_named_cells.py
marimo/_smoke_tests/third_party/altair_example.py
marimo/_smoke_tests/third_party/holoviews_example.py
tests/_smoke_tests/config.yml
tests/_smoke_tests/run_all.py

This runs more smokes tests and examples in CI, with expected errors. 
This may be something that causes more pain that catches errors over time, but we can remove it later if so.

tests: run more smoke tests in CI

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/core/codemirror/cm.ts
frontend/src/core/codemirror/theme/light.ts

improvement: color functions in theme, bold keywords

---

frontend/src/components/app-config/user-config-form.tsx

increase code editor max font size

---

development_docs/traces.md
marimo/_cli/cli.py
marimo/_config/settings.py
marimo/_runtime/runtime.py
marimo/_server/sessions.py

Adds a hidden command-line option to generate profiling statistics of the kernel.

chore: profile kernel execution 

---

examples/embeddings/embedding_numbers.py
examples/embeddings/interactive_cluster_analysis.py
marimo/_dependencies/dependencies.py
marimo/_plugins/ui/_impl/altair_chart.py
tests/_plugins/ui/_impl/test_altair_chart.py

Fixes a regression on `ui.altair_chart` when data has > 5k rows

fix: altair_chart() on dataframes with >5k rows

---

frontend/src/core/codemirror/language/panel.tsx
frontend/src/hooks/useAutoGrowInputProps.ts

The input box used to name the dataframe in the SQL cell will auto-grow

fix: auto-grow text input for dataframe sql name

---

marimo/_runtime/complete.py
marimo/_runtime/dataflow.py
marimo/_runtime/reload/module_watcher.py
marimo/_runtime/runner/cell_runner.py
marimo/_runtime/runner/hooks_post_execution.py
marimo/_runtime/runtime.py

Add additional logging to help with debugging.

chore: more debug logging in kernel

---

marimo/_plugins/ui/_impl/from_anywidget.py
tests/_plugins/ui/_impl/test_anywidget.py

We lost anywidget reactivity from https://github.com/marimo-team/marimo/pull/2055
This adds it back, with a test.

fix: anywidget reactivity

---

marimo/_plugins/ui/_impl/tables/default_table.py
marimo/_smoke_tests/tables/dictionary_table.py
tests/_plugins/ui/_impl/tables/test_default_table.py

Add support for dictionaries in the table - by converting to key/value columns

improvement: support dict in mo.ui.table

---

frontend/src/components/editor/output/JsonOutput.tsx
marimo/_output/formatters/structures.py
tests/_output/formatters/test_structures.py

improve: Python-like values in JSON outputs

---

.pre-commit-config.yaml
.vscode/settings.json
biome.json
frontend/e2e-tests/bugs.spec.ts
frontend/islands/vite.config.mts
frontend/package.json
frontend/playwright.config.ts
frontend/src/components/debugger/debugger-code.tsx
frontend/src/components/editor/ai/add-cell-with-ai.tsx
frontend/src/components/editor/links/cell-link.tsx
frontend/src/components/editor/output/CalloutOutput.styles.ts
frontend/src/components/editor/output/JsonOutput.tsx
frontend/src/components/editor/output/MarimoErrorOutput.tsx
frontend/src/core/cells/collapseConsoleOutputs.tsx
frontend/src/core/codemirror/__tests__/setup.test.ts
frontend/src/core/codemirror/find-replace/search-highlight.ts
frontend/src/core/codemirror/language/__tests__/sql.test.ts
frontend/src/core/codemirror/language/markdown.ts
frontend/src/core/codemirror/markdown/commands.ts
frontend/src/core/wasm/worker/getPyodideVersion.ts
frontend/src/plugins/core/__test__/RenderHTML.test.ts
frontend/src/plugins/impl/common/error-banner.tsx
frontend/src/plugins/impl/data-frames/forms/form-utils.ts
frontend/src/plugins/impl/data-frames/forms/form.tsx
frontend/src/plugins/impl/vega/__tests__/vega.test.ts
frontend/src/utils/__tests__/id-tree.test.ts
frontend/src/utils/staticImplements.ts
frontend/vite.config.mts
lsp/index.ts
openapi/src/index.ts

Enable a few more rules for consistency

chore: enable more biome rules

---

frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
marimo/_server/export/exporter.py
marimo/_server/templates/templates.py

fix: Show outputs below in HTML export if configured

---

marimo/_server/file_manager.py

When attempting to read CSS file.

fix: catch/log oserror

---

frontend/src/css/admonition.css
marimo/_smoke_tests/admonitions.py
marimo/_smoke_tests/bugs/2146-admonitions.py

Some styling fixes 
Fixes #2146

fix: admonition to display contents vertically

---

docs/guides/deploying/deploying_railway.md
docs/guides/deploying/index.md

Update deploying docs to distinguish between edit and run servers

improve: deploying docs 

---

marimo/_plugins/ui/_impl/table.py
tests/_cli/test_file_path.py
tests/_plugins/ui/_impl/test_table.py

Possible regression from moving to server-side

fix: fix column summaries to include filters

---

marimo/_cli/sandbox.py

Ensure that marimo is in the uv sandbox's dependencies; otherwise, the outer environment leaks into the inner environment, messing up package resolution.

fix: sandbox requires marimo

---

frontend/src/components/ui/accordion.tsx
marimo/_smoke_tests/bugs/2173-accordion.py

fix: accordion text alignment

---

tests/_config/test_manager.py

chore: dont overwrite user config in tests

---

docs/api/inputs/anywidget.md

docs: update anywidget examples link to include third_party directory

---

frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
marimo/_dependencies/dependencies.py
marimo/_plugins/ui/_impl/dataframes/dataframe.py
marimo/_plugins/ui/_impl/dataframes/transforms/apply.py
marimo/_plugins/ui/_impl/dataframes/transforms/handlers.py
marimo/_plugins/ui/_impl/tables/default_table.py
marimo/_plugins/ui/_impl/tables/df_protocol_table.py
marimo/_plugins/ui/_impl/tables/pyarrow_table.py
marimo/_server/api/endpoints/ai.py
marimo/_smoke_tests/ibis_example.py
pyproject.toml
tests/_plugins/ui/_impl/dataframes/test_handlers.py
tests/_sql/test_sql.py

improvement: ibis support in mo.ui.dataframe

---

tests/_server/test_file_manager.py

Fixes some assertions that were not being hit in test file manager.

fix: test_file_manager assertions

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/editor/cell/cell-actions.tsx
frontend/src/components/editor/header/filename-input.tsx
frontend/src/components/ui/command.tsx
frontend/src/components/ui/menu-items.tsx
frontend/src/components/ui/select.tsx

fix: upgrade cmd-k to fix html query selector bug crash

---

frontend/src/components/data-table/column-header.tsx
marimo/_cli/envinfo.py
marimo/_output/formatters/pandas_formatters.py
marimo/_smoke_tests/bugs/2211-pandas-formatting.py
marimo/_utils/health.py
tests/_cli/test_envinfo.py
tests/_output/formatters/test_pandas.py

Fixes #2211 
* Check for None in max_rows when formatting a series
* Add more env info for some common optional deps

fix: check for None max_rows from pandas series when formatting

---

marimo/_plugins/stateless/status/_progress.py
marimo/_smoke_tests/status.py

Fixes #2230
- add `disabled` param to mo.status.progress_bar
- update relevant smoke test 

fix: add disabled param to mo.status.progress_bar

---

frontend/src/components/editor/file-tree/upload.tsx

Change the sidebar upload limit from 50mb to 100mb

improvement: increase upload limit to 100mb

---

marimo/_runtime/runtime.py
tests/_runtime/test_runtime.py

Fix various edge cases in staleness that arise when cells transition to error. These edges cases were uncovered when porting a Jupyter notebook to marimo using the lazy runtime.

fix: edge cases with errors and staleness

---

frontend/src/core/codemirror/language/__tests__/markdown.test.ts
frontend/src/core/codemirror/language/markdown.ts

fix: fix detection of markdown language support

---

frontend/src/components/editor/chrome/panels/datasources-panel.tsx
marimo/_plugins/ui/_impl/dataframes/dataframe.py
tests/_plugins/ui/_impl/dataframes/test_dataframe.py

Fixes #2273
We were not using the original page_size being passed through

fix: dataframe initial page_size

---

marimo/_output/formatters/altair_formatters.py
marimo/_plugins/ui/_impl/altair_chart.py
marimo/_smoke_tests/altair/vegafusion_nb.py

Fixes #2282
This fixes #2282 for now. But I have other ideas/improvements for performance

fix: vegafusion rendering when used outside mo.ui.altair_chart

---

frontend/src/components/data-table/chart-spec-model.tsx

improvement: set maximum bar width with column summaries

---

frontend/src/components/app-config/app-config-form.tsx
frontend/src/components/editor/actions/useNotebookActions.tsx
frontend/src/core/config/__tests__/config-schema.test.ts
frontend/src/core/config/config-schema.ts
frontend/src/core/config/config.ts
frontend/src/core/export/hooks.ts
frontend/src/core/export/state.ts
frontend/src/core/kernel/handlers.ts
frontend/src/utils/arrays.ts
marimo/_ast/app.py
marimo/_ast/codegen.py
marimo/_cli/convert/markdown.py
marimo/_runtime/functions.py
marimo/_server/api/endpoints/config.py
marimo/_server/api/endpoints/export.py
marimo/_server/api/utils.py
marimo/_server/export/exporter.py
marimo/_server/templates/templates.py
marimo/_smoke_tests/quak-demo.py
marimo/_utils/config/config.py
marimo/_utils/parse_dataclass.py
pyproject.toml
tests/_ast/test_app.py
tests/_ast/test_app_config.py
tests/_ast/test_codegen.py
tests/_plugins/ui/_impl/utils/test_dataframe_utils.py
tests/_server/api/endpoints/test_export.py
tests/_utils/test_parse_dataclass.py

This moves the auto-download to app config to it persists across sessions, per notebook.

improvement: move auto-download to app config

---

.github/workflows/playwright.yml
.github/workflows/test_be.yaml
.github/workflows/test_cli.yaml
.github/workflows/test_fe.yaml

chore: use paths-filter github action

---

docs/integrations/google_cloud_bigquery.md
docs/integrations/google_cloud_storage.md
docs/integrations/google_sheets.md

PR #2162 moved the location of the GCP files. This PR adjusts sources to changes.

fix: update gcp references

---

marimo/_ast/cell.py
marimo/_ast/compiler.py
marimo/_runtime/runtime.py
tests/_runtime/test_runtime.py

fix: memory leak with temporary variables

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/data-table/__test__/useColumnPinning.test.ts
frontend/src/components/data-table/columns.tsx
frontend/src/components/data-table/hooks/useColumnPinning.ts
frontend/src/components/data-table/renderers.tsx
frontend/src/components/ui/table.tsx
marimo/_smoke_tests/tables/ibis_example.py

* Set max width on the checkbox in the table
* Use the same background for pinned columns when hovered or selected
* fix/test pinning logic

fix: table checkbox width and pinning styles

---

frontend/src/components/app-config/app-config-button.tsx
frontend/src/components/app-config/common.tsx
frontend/src/components/app-config/user-config-form.tsx
frontend/src/components/editor/actions/useNotebookActions.tsx
frontend/src/components/ui/form.tsx
frontend/src/core/codemirror/copilot/copilot-config.tsx
frontend/src/css/globals.css

Move the use settings from the small area it was given, into a larger modal

improvement: user settings modal

---

marimo/_plugins/stateless/status/__init__.py
marimo/_plugins/stateless/status/_progress.py
marimo/_smoke_tests/toast.py

Fixes #2364  
1. Implement marimo.status.toast
2. Add missing doc for disabled arg in marimo.status.progress_bar
3. Add smoke_test for marimo.status.toast

fix#2364: implement marimo.status.toast

---

docs/guides/configuration.md
docs/guides/editor_features/ai_completion.md
docs/guides/editor_features/hotkeys.md
frontend/src/components/app-config/user-config-form.tsx
marimo/_config/manager.py
marimo/_config/utils.py
tests/_config/test_config.py

This allows a user to use a config file that follows the [XDG](https://xdgbasedirectoryspecification.com/) convention (i.e. the config file is located at `~/.config/marimo/marimo.toml`).
This ended up a bit clunky so that I could make a clean test. Not my favorite to messy up the code for the sake of a test though, so if it seems too messy lmk and I can put a bit more time into cleaning that up.
Also, I looked to see if there was any discussion about not wanting to support something like this any didn't find anything, but apologies if I missed something.
Thanks for your work on marimo 🙂 
(I'm assuming this isn't big enough to warrant this, but lmk)
(I tested that `get_config_path` can find a config file at `~/.config/marimo/marimo.toml` now, but can do some more thorough testing later …

feat: xdg config file

---

docs/guides/troubleshooting.md

docs: symlink docs

---

frontend/src/components/editor/package-alert.tsx
frontend/src/utils/__tests__/versions.test.ts
frontend/src/utils/versions.ts
marimo/_runtime/packages/package_manager.py
marimo/_runtime/packages/utils.py
marimo/_runtime/requests.py
marimo/_runtime/runtime.py
openapi/api.yaml
openapi/src/api.ts
tests/_runtime/packages/test_package_utils.py
tests/_runtime/packages/test_pypi_package_manager.py
tests/_server/api/endpoints/test_editing.py

feat: support installing packages at particular versions in the UI

---

frontend/src/components/editor/chrome/panels/packages-panel.tsx
frontend/src/components/editor/chrome/types.ts
frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
frontend/src/components/ui/input.tsx
frontend/src/components/ui/tooltip.tsx
frontend/src/core/islands/bridge.ts
frontend/src/core/network/requests-network.ts
frontend/src/core/network/requests-static.ts
frontend/src/core/network/requests-toasting.ts
frontend/src/core/network/requests.ts
frontend/src/core/network/types.ts
frontend/src/core/wasm/bridge.ts
frontend/src/core/wasm/worker/worker.ts
marimo/_cli/development/commands.py
marimo/_runtime/packages/conda_package_manager.py
marimo/_runtime/packages/package_manager.py
marimo/_runtime/packages/pypi_package_manager.py
marimo/_server/api/endpoints/packages.py
marimo/_server/api/router.py
marimo/_server/main.py
marimo/_server/models/packages.py
openapi/api.yaml
openapi/src/api.ts
tests/_server/api/endpoints/test_packages.py

feat: panel for packagemanagement

---

marimo/_plugins/ui/_impl/input.py
marimo/_server/models/packages.py

- stdout not appropriate
- LOGGER.error() was not showing up for me (to debug later)

fix: emit some errors to stderr

---

frontend/tailwind.config.js

styles: increase slides default font-size to 80px

---

marimo/_output/formatters/matplotlib_formatters.py
tests/_output/formatters/matplotlibrc
tests/_output/formatters/test_matplotlib.py

Fixes #2404 
Thanks @YDX-2147483647 for reporting and finding a fix!

fix: restore users custom rcparams

---

marimo/_cli/file_path.py
marimo/_cli/sandbox.py
tests/_cli/test_file_path.py

Fixes #2415 and cleans up a lot of our logic for reading files

fix: install inline-metadata for remote deps

---

docs/api/index.md
docs/faq.md
docs/guides/best_practices/performance.md
marimo/_save/loaders/memory.py
marimo/_save/save.py
tests/_save/test_cache.py

- more docs (in progress)
- remove maxsize from cache()
- make lru_cache threadsafe

lru_cache thread-safety, remove maxsize from cache

---

examples/layouts/grid-dashboard.py
examples/layouts/layouts/grid-dashboard.grid.json
pyproject.toml

examples: grid dashboard

---

frontend/src/plugins/impl/NumberPlugin.tsx
frontend/src/stories/data-table.stories.tsx
marimo/_plugins/ui/_impl/input.py
marimo/_plugins/validators.py
marimo/_smoke_tests/inputs/numbers.py
tests/_plugins/test_validators.py
tests/_plugins/ui/_impl/test_input.py

improvement: remove bounds on number, add warnings and validation

---

frontend/src/components/editor/chrome/panels/packages-panel.tsx
marimo/_runtime/packages/conda_package_manager.py
marimo/_runtime/packages/pypi_package_manager.py
marimo/_runtime/packages/utils.py
tests/_runtime/packages/test_pypi_package_manager.py

improvement: add multiple dependencies and pressing ENTER for package manager

---

frontend/src/components/ui/combobox.tsx
frontend/src/plugins/impl/MultiselectPlugin.tsx
marimo/_smoke_tests/bugs/1654-virtualize-multiselect.py

improvement: add select all and deselect all to multi-select

---

marimo/_cli/convert/commands.py
tests/_cli/snapshots/ipynb_to_marimo.txt
tests/_cli/snapshots/ipynb_to_marimo_with_output.txt
tests/_cli/snapshots/markdown_to_marimo.txt
tests/_cli/test_cli_convert.py

Fixes #2460 
add -o to marimo convert CLI

improvement: add -o to marimo convert CLI

---

frontend/src/plugins/impl/DataTablePlugin.tsx
marimo/_plugins/ui/_impl/table.py

Fixes #2466
Regressed when adding some performance improvements to the table rendering

fix: honor show_column_summaries

---

frontend/src/components/editor/Cell.tsx
frontend/src/components/editor/Output.tsx
frontend/src/components/editor/cell/DeleteButton.tsx
frontend/src/components/editor/cell/RunButton.tsx
frontend/src/components/editor/cell/StopButton.tsx
frontend/src/components/editor/cell/cell-actions.tsx
frontend/src/components/editor/cell/code/cell-editor.tsx
frontend/src/components/editor/cell/code/language-toggle.tsx
frontend/src/components/editor/cell/toolbar.tsx
frontend/src/components/editor/renderers/CellArray.tsx
frontend/src/components/editor/renderers/vertical-layout/vertical-layout-wrapper.tsx
frontend/src/core/codemirror/language/panel.tsx
frontend/src/css/app/Cell.css
frontend/src/css/app/codemirror.css
frontend/src/css/common.css

EDIT: Changes by Akshay. Match our design for buttons. Move delete back to bottom right because it's destructive.
---

improvement: move toolbar above cell for better gutter usage

---

docs/api/inputs/chat.md
marimo/_plugins/ai/__init__.py
marimo/_plugins/ui/_impl/chat/llm.py

Add `ChatAttachment` to docs, `mo.ai`. Remove some types from docstrings since signatures are already typed.

docs: ChatAttachment

---

frontend/src/components/editor/actions/useNotebookActions.tsx
frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
frontend/src/core/static/download-html.ts

Add an option to export as html without code

improvement: add Download as HTML (no code)

---

docs/api/plotting.md
docs/guides/plotting.md
marimo/_plugins/ui/_impl/plotly.py

Address confusion from users, who suggested we improve our docs.

docs: mo.ui.plotly only supports selecting scatter plots

---

marimo/_server/api/utils.py
marimo/_server/export/exporter.py
marimo/_server/templates/templates.py
tests/_server/templates/test_templates.py

improvement: change the filename in static html export to be just the file basename

---

frontend/src/components/editor/cell/code/cell-editor.tsx

focusout bubbles, blur doesn't.
cc @wasimsandhu

fix: temporarily show code

---

.github/workflows/dev-release.yml
.github/workflows/marimo-bot.yml
.github/workflows/playwright.yml
.github/workflows/release.yml
.github/workflows/test_cli.yaml
tests/_cli/test_cli.py

* use hatch for main release
* add some missing tests for `test_cli.yaml`

chore: use hatch for main release

---

tests/_ast/test_visitor.py

SQL parsing with f-strings is currently broken. This adds tests that XFAIL that demonstrate this.
Fix is not obvious to me, so would like to merge these tests first.

test: SQL parsing with f-strings

---

README_Chinese.md

revise chinese

---

marimo/_cli/sandbox.py
marimo/_smoke_tests/sandbox/git_source.py
tests/_cli/test_sandbox.py

improvement: support uv sources when creating a sandbox requirements.txt

---

.github/workflows/test_cli.yaml
lsp/pnpm-lock.yaml
marimo/_server/sessions.py
pyproject.toml

fix: check lsp in CI after building wheel

---

scripts/pycheck.sh

chore: update hatch mypy command

---

frontend/src/components/data-table/types.ts
frontend/src/plugins/impl/DataTablePlugin.tsx
frontend/src/utils/numbers.ts
marimo/_plugins/core/json_encoder.py
marimo/_plugins/ui/_impl/tables/polars_table.py
marimo/_smoke_tests/issues/2550-search-polars.py
pyproject.toml
tests/_cli/snapshots/ipynb_to_marimo.txt
tests/_cli/snapshots/ipynb_to_marimo_with_output.txt
tests/_cli/snapshots/markdown_to_marimo.txt
tests/_plugins/core/test_json_encoder.py
tests/_plugins/ui/_impl/dataframes/test_handlers.py
tests/_plugins/ui/_impl/tables/test_polars_table.py
tests/_plugins/ui/_impl/test_altair_chart.py

Fixes #2550
* bump polars to 1.9.0
* fix breaks in search and summaries

fix: bump polars to 1.9.0, fix breaks in search and summaries

---

frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
marimo/_plugins/ui/_impl/from_anywidget.py
marimo/_smoke_tests/issues/2506_anywidget_buffer_paths.py
tests/_plugins/ui/_impl/test_anywidget.py

fix: anywidget bytes when on save trait

---

examples/third_party/plotly/scatter_map.py

Add an example of a selectable plotly scatter map

example: plotly scatter map

---

examples/sql/README.md
examples/sql/histograms.py

`uvx marimo edit https://raw.githubusercontent.com/marimo-team/marimo/a2e4be1f2113f26b45679c568d94e1750de0abec/examples/sql/histograms.py`

example: histograms in duckdb

---

frontend/src/components/editor/chrome/panels/datasources-panel.tsx
marimo/_ast/visitor.py
marimo/_data/charts.py
marimo/_data/get_datasets.py
marimo/_data/preview_column.py
marimo/_data/sql_summaries.py
marimo/_runtime/runtime.py
marimo/_sql/sql.py
tests/_data/test_get_datasets.py
tests/_data/test_preview_column.py
tests/_data/test_sql_summaries.py
tests/_sql/test_sql.py

feat: add column summaries for sql tables in the datasources panel

---

marimo/_output/show_code.py

Show output above code

---

examples/ai/tools/chat_with_tools.py
examples/ai/tools/dataset_analysis.py
frontend/src/plugins/impl/chat/chat-ui.tsx

Video: https://x.com/themylesfiles/status/1844462922950639687

example: chat with tools

---

examples/ai/tools/code_interpreter.py

Video: https://x.com/marimo_io/status/1844487050277552197

example: code interpreter

---

marimo/_runtime/packages/module_name_to_pypi_name.py

Added resolver from skvideo to scikit-video.
@akshayka

added skvideo module name (scikit-video package)

---

docs/guides/editor_features/ai_completion.md
frontend/src/components/app-config/user-config-form.tsx
frontend/src/components/editor/ai/add-cell-with-ai.tsx
frontend/src/components/editor/ai/ai-completion-editor.tsx
frontend/src/core/config/__tests__/config-schema.test.ts
frontend/src/core/config/config-schema.ts
marimo/_config/config.py
marimo/_server/ai/prompts.py
marimo/_server/api/endpoints/ai.py
openapi/api.yaml
openapi/src/api.ts
tests/_server/ai/snapshots/system_prompts.txt
tests/_server/ai/test_prompts.py

feat: custom ai assist rules

---

.github/workflows/dev-release.yml
.github/workflows/marimo-bot.yml
.github/workflows/release-marimo-base.yml
scripts/modify_pyproject_for_marimo_base.sh

Consolidate logic for adapting pyproject.toml into a script

chore: move marimo-base logic into bash script

---

examples/misc/seam_carving.py

adapt vincent warmerdam's seam carving example, add to misc/

example: seam carving

---

.github/workflows/dev-release-marimo-base.yml
development_docs/pyodide.md
frontend/src/core/wasm/worker/bootstrap.ts
marimo/_runtime/runtime.py
marimo/_utils/rst_to_html.py
pyodide/build_and_serve.py

Lazy load some dependencies so they don't block the notebook code from rendering.

perf: lazy load completion deps (for WASM)

---

examples/ai/chat/anthropic_example.py
frontend/src/plugins/impl/chat/ChatPlugin.tsx
frontend/src/plugins/impl/chat/chat-ui.tsx
marimo/_plugins/ui/_impl/chat/chat.py

Adds a configurable max_height and scroll to the newest message when it appears.

improvement: add max_height to mo.ui.chat()

---

docs/vercel.json

Through vercel for convenience.

docs: add redirects

---

marimo/_plugins/ui/_impl/dataframes/transforms/handlers.py
tests/_plugins/ui/_impl/dataframes/test_dataframe.py

fix: mo.ui.dataframe with ibis and polars backend

---

.github/workflows/test_be_dagger.yaml
dagger/src/main/backend.py
dagger/src/main/env.py

Fix `dagger call backend test`
Test this PR with `dagger -m github.com/marimo-team/marimo@pull/2652/head call backend test`
Maybe fixes https://github.com/marimo-team/marimo/issues/2554
There were a few missing things in the backend test pipeline causing it to fail:
- The backend tests need index.html to exist
- The backend tests should be run as a non-root user because we try to create files at `/invalid/` and expect it to fail
@mscolnick

dagger: fix backend test

---

frontend/src/plugins/impl/RangeSliderPlugin.tsx

Fixes #2657 as a workaround due to a bug in radix slider

fix: range slider debounce edge-case

---

marimo/_plugins/core/json_encoder.py
marimo/_plugins/ui/_impl/table.py
marimo/_plugins/ui/_impl/tables/table_manager.py
tests/_plugins/core/test_json_encoder.py
tests/_plugins/ui/_impl/test_table.py

Fixes #2662
drop table column limit, just adjust summary defaults

improvement: drop table column limit, just adjust summary defaults

---

GOVERNANCE.md

This PR adds a document outlining the governance structure of the marimo project.

docs: governance

---

docs/guides/outputs.md

Update our outputs documentation:
- console outputs
- progress bars
- threading

docs: outputs

---

docs/guides/deploying/programmatically.md
examples/frameworks/README.md
examples/frameworks/fastapi/README.md
examples/frameworks/fastapi/main.py
examples/frameworks/fastapi/templates/home.html
examples/frameworks/fastapi/templates/login.html

example: add complete fastapi example

---

frontend/src/core/islands/components/web-components.tsx
frontend/src/core/islands/main.ts

Made some changes in https://github.com/marimo-team/marimo/pull/2682 that should have stayed.

fix: lazy initializing islands again

---

frontend/package.json
frontend/pnpm-lock.yaml

Upgrade to pick up this security update: https://github.com/marimo-team/marimo/pull/2693

chore: upgrade mermaid

---

.github/workflows/test_be.yaml
.github/workflows/test_be_dagger.yaml
marimo/_ast/visitor.py
marimo/_cli/development/commands.py
marimo/_config/config.py
marimo/_data/get_datasets.py
marimo/_output/formatters/arviz_formatters.py
marimo/_output/formatters/ipython_formatters.py
marimo/_output/formatters/matplotlib_formatters.py
marimo/_output/formatters/structures.py
marimo/_output/md.py
marimo/_output/md_extensions/external_links.py
marimo/_output/mpl.py
marimo/_plugins/core/json_encoder.py
marimo/_plugins/stateless/mpl/_mpl.py
marimo/_plugins/ui/_impl/anywidget/init.py
marimo/_plugins/ui/_impl/chat/llm.py
marimo/_plugins/ui/_impl/from_anywidget.py
marimo/_runtime/marimo_pdb.py
marimo/_runtime/params.py
marimo/_server/api/endpoints/ai.py
marimo/_utils/marimo_path.py
marimo/_utils/rst_to_html.py
pyproject.toml
tests/_output/formatters/test_matplotlib.py

Add a few libraries in the typechecking env so we can actually type check them

chore: more typechecking

---

frontend/src/plugins/impl/panel/PanelPlugin.tsx
marimo/_plugins/ui/_impl/from_panel.py
marimo/_runtime/functions.py

I regressed some function parsing in panel, this fixes it.

fix: panel function parsing

---

marimo/_data/series.py
marimo/_plugins/ui/_impl/tables/narwhals_table.py
marimo/_sql/sql.py
marimo/_utils/narwhals_utils.py
tests/_data/mocks.py
tests/_data/test_get_datasets.py
tests/_data/test_series.py
tests/_plugins/ui/_impl/charts/test_altair_transformers.py
tests/_plugins/ui/_impl/dataframes/test_dataframe.py
tests/_plugins/ui/_impl/test_altair_chart.py
tests/_utils/test_narwhals_utils.py

Use `nw.to_py_scalar` to clean up some code. and support very basics of `DuckDbRelation` as a "dataframe"

chore: use narhwals to scalar

---

frontend/src/core/codemirror/placeholder/extensions.ts

Fix a regression from https://github.com/codemirror/dev/issues/1457

fix: codemirror regression with placeholder

---

examples/ui/arrays_and_dicts.py
marimo/_plugins/ui/_impl/dictionary.py

fix prior incorrect interpretation of marimo dict
https://github.com/marimo-team/marimo/pull/2712#issuecomment-2436687571

doc: fix prior incorrect interpretation of marimo dict

---

frontend/src/components/scratchpad/scratchpad-history.ts
frontend/src/components/scratchpad/scratchpad.tsx

improvement: add history to scratch pad, persist to localstorage

---

marimo/_tutorials/ui.py

- add concrete examples
- add docs hyperlinks
- remove mo.state()

simplify UI tutorial

---

biome.json
frontend/e2e-tests/components.spec.ts
frontend/e2e-tests/disabled.spec.ts
frontend/e2e-tests/helper.ts
frontend/e2e-tests/kitchen-sink-wasm.spec.ts
frontend/e2e-tests/kitchen-sink.spec.ts
frontend/e2e-tests/layout-grid.spec.ts
frontend/e2e-tests/mode.spec.ts
frontend/e2e-tests/output.spec.ts
frontend/e2e-tests/shutdown.spec.ts
frontend/src/components/data-table/filters.ts
frontend/src/components/editor/chrome/panels/packages-panel.tsx
frontend/src/components/editor/output/ConsoleOutput.tsx
frontend/src/core/cells/collapseConsoleOutputs.tsx
frontend/src/core/codemirror/format.ts
frontend/src/core/hotkeys/actions.ts
frontend/src/core/kernel/handlers.ts
frontend/src/core/static/virtual-file-tracker.ts
frontend/src/plugins/impl/FileUploadPlugin.tsx
frontend/src/plugins/impl/data-frames/python/python-print.ts
frontend/src/plugins/impl/panel/PanelPlugin.tsx
frontend/src/utils/createReducer.ts
frontend/src/utils/id-tree.tsx

Avoid some bikeshedding that I saw on previous PRs

chore: add naming convention lint

---

examples/ai/chat/simplemind_example.py
frontend/src/plugins/impl/chat/chat-ui.tsx

```
uvx marimo edit https://raw.githubusercontent.com/marimo-team/marimo/ms/simplemind-example/examples/ai/chat/simplemind_example.py
```

example: add simplemind

---

frontend/src/components/data-table/data-table.tsx
frontend/src/components/dependency-graph/dependency-graph-minimap.tsx
frontend/src/components/dependency-graph/dependency-graph-tree.tsx
frontend/src/components/dependency-graph/panels.tsx

- allow closing active selection in dep viewer
- fix table memo

fix: allow closing active selection in dep viewer, fix table memo

---

README.md

Add a badge for conda downloads

Add conda downloads badge

---

frontend/vite.config.mts

Fixes #2775 
Makes the errors when developing clearer how to self-fix.

fix: have clearer tips when developing on marimo

---

examples/misc/monotonic_splines.py

- add sandbox dependencies.
- add some mo.stop's

fix: monotonic splines example

---

marimo/_plugins/ui/_impl/table.py
tests/_plugins/ui/_impl/test_table.py

Make sure the type leaving mo.ui.table is not narwhals, but rather the original df

fix: unwrap narwhals type from mo.ui.table()

---

examples/third_party/huggingface/README.md
examples/third_party/huggingface/chatbot.py
examples/third_party/huggingface/text-to-image.py
marimo/_output/formatters/tqdm_formatters.py

HF examples, as they appear on https://huggingface.co/marimo-team

examples: add huggingface examples

---

frontend/src/components/data-table/chart-spec-model.tsx
frontend/src/components/data-table/column-summary.tsx
frontend/src/components/data-table/date-popover.tsx
frontend/src/plugins/impl/DataTablePlugin.tsx
frontend/src/plugins/impl/vega/loader.ts
frontend/src/utils/dates.ts
marimo/_smoke_tests/timezones.py

improvement: clearer dates and datetimes with utc

---

frontend/src/components/app-config/user-config-form.tsx
frontend/src/components/editor/columns/cell-column.tsx

- add lab section so early adopters can try experimental features
- update column width size

improvement: Add labs section in user settings, fix column width

---

frontend/src/components/data-table/__test__/columns.test.tsx
frontend/src/components/data-table/columns.tsx
marimo/_smoke_tests/df_index.py

fix: fix regression of rendering pandas tables with custom index

---

frontend/src/plugins/impl/vega/__tests__/vega.test.ts
frontend/src/plugins/impl/vega/loader.ts
marimo/_smoke_tests/_polars/polars_date_column.py

Safely handle when dates are null or empty

fix: handle empty or null dates in table

---

marimo/_ast/sql_visitor.py
marimo/_ast/visitor.py
tests/_ast/test_sql_visitor.py

This handles some SQL edges cases (but not all). this handles catalogs/schemas, but still missing multiple CTEs and nested joins.

fix: handle some sql edge cases for catalogs

---

marimo/_ast/sql_visitor.py
marimo/_ast/visitor.py
marimo/_runtime/runtime.py
marimo/_smoke_tests/sql/local_db_deps.py
tests/_ast/test_sql_visitor.py

fix: SQL cases for referencing catalog and schema in CREATE table statements

---

README.md
docs/index.md

Our docs landing page had not been updated in a long time. This PR mostly replaces its contents with our README.

docs: replace index.md with readme

---

docs/guides/apps.md
frontend/public/files/wasm-intro.py

Just a small thing 😅. The intro tutorial states the app view is on the bottom left but it's on the bottom right.
@mscolnick OR @Haleshot

docs: update docs to show app view is in bottom right

---

docs/guides/deploying/deploying_marimo_cloud.md

Fix broken hyperlink
Rectify broken contact Calendly link [here](https://docs.marimo.io/guides/deploying/deploying_marimo_cloud.html) to redirect to the correct link.

docs: update calendar links to include full URLs

---

docs/api/app.md
marimo/_runtime/app_meta.py
marimo/_runtime/runtime.py

This PR improves the documentation for the `AppMeta` class and `app_meta()` function by adding clear examples and better explaining their functionality.
- Added practical examples showing how to use `theme` with plotting libraries
- Added examples showing conditional content display based on `mode`
- Clarified return values for both `theme` and `mode` properties
- Ensured consistent documentation style with rest of codebase
- Using `theme` to conditionally set Altair's theme
- Using `mode` to show/hide content based on execution context

docs: improve AppMeta documentation

---

frontend/src/components/editor/file-tree/file-explorer.tsx

Download a file from the file explorer

improvement: add download to File Explorer

---

.gitignore
tests/_cli/ipynb_data/juv.ipynb.txt
tests/_cli/snapshots/converted_arithmetic.py.txt
tests/_cli/snapshots/converted_blank.py.txt
tests/_cli/snapshots/converted_juv.py.txt
tests/_cli/snapshots/converted_markdown.py.txt
tests/_cli/snapshots/converted_multiple_defs.py.txt
tests/_cli/snapshots/converted_unparsable.py.txt
tests/_cli/test_ipynb_to_marimo.py

tests: snapshot ipynb convert tests, add juv test

---

marimo/_runtime/packages/module_name_to_pypi_name.py

Part of #2844, but does not fix it

fix: devtools package resolution

---

marimo/_runtime/packages/package_manager.py
marimo/_runtime/packages/pypi_package_manager.py
marimo/_runtime/packages/utils.py
marimo/_runtime/runtime.py
marimo/_server/api/endpoints/packages.py
tests/_runtime/packages/test_package_managers.py
tests/_runtime/packages/test_package_utils.py
tests/_server/api/endpoints/test_packages.py

Fixes #2844 
Handles a couple edge cases, which should be clear in the tests

fix: package installation for conflicting names, fix for names with brackets

---

docs/guides/scripts.md

Fix doc typo

---

frontend/src/components/editor/Disconnected.tsx
frontend/src/components/editor/app-container.tsx
frontend/src/components/editor/controls/keyboard-shortcuts.tsx
frontend/src/components/editor/header/status.tsx
frontend/src/core/edit-app.tsx
frontend/src/core/run-app.tsx
frontend/src/css/app/Header.css
marimo/_server/sessions.py

improvement: redesign disconnected state

---

marimo/_config/config.py
marimo/_config/packages.py
marimo/_runtime/packages/module_name_to_pypi_name.py
marimo/_runtime/packages/utils.py
marimo/_server/api/endpoints/login.py

1. Try to infer the package manager from the project
2. `umap` -> `umap-learn`
3. `is_python_isolated` is true for docker containers
4. (maybe) fix auth when embedded behind a proxy

fix: QOL improvements when deploying with docker

---

frontend/src/components/data-table/columns.tsx
frontend/src/plugins/impl/vega/__tests__/vega.test.ts
frontend/src/plugins/impl/vega/loader.ts
marimo/_smoke_tests/issues/2817_timezones.py

fix: render dates in table using local tz

---

frontend/src/components/editor/Output.tsx
frontend/src/components/scratchpad/scratchpad.tsx
marimo/_output/formatters/repr_formatters.py
tests/_output/formatters/test_formatters.py

This is what jupyter will do i guess.

improvement: if mimebundle only contains markdown/latex, convert to html

---

frontend/package.json
frontend/pnpm-lock.yaml

Fixes #2337 . Upgrade `plotly.js` by running `pnpm up plotly.js`
@mscolnick

upgrade plotly.js to support maplibre

---

examples/third_party/leafmap/leafmap_example.py

Use leafmap.foliumap, since leafmap.Map is not supported

example: leafmap

---

frontend/src/components/data-table/__test__/columns.test.tsx
frontend/src/components/data-table/columns.tsx

Long continuous text (no spaces) is not wrapped, this change is to force text to wrap. 
- Use `break-words` as it will add line breaks mid-word if needed. (https://tailwindcss.com/docs/word-break#break-words)
- Sample code:
```
df = pl.DataFrame({
"numbers": [list(range(1,100))],
"long_string": ['abc' * 100],
"long_string_spaced": ['abc ' * 30]
})
mo.ui.table(df, wrapped_columns=["numbers", "long_string", "long_string_spaced"])
```
As a result:

force wrap columns in data-table when needed

---

frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx

Make #2918 a little bit easier to override

style: add ids to elements to be more easily customized with css

---

marimo/_runtime/packages/pypi_package_manager.py

Fixes #2923. 
Our Poetry package manager's `list_packages` command was incorrect. Poetry show has no option `--format json`. This PR fixes the command and updates the parsing logic.
Tested locally.

fix: poetry list packages

---

marimo/_cli/cli.py
marimo/_server/api/interrupt.py
marimo/_server/print.py
marimo/_server/sessions.py
marimo/_server/utils.py
pyodide/build_and_serve.py
pyproject.toml
tests/_plugins/ui/_impl/dataframes/test_print_code.py

just so it doesnt slip to production

chore: lint for no print

---

pyproject.toml
scripts/modify_pyproject_for_marimo_base.sh
scripts/validate_base_wheel_size.sh

unfortunately, `artifacts = [` need to be on the same line. i cannot get the `sed` command to work otherwise

fix: marimo-base modification
