marimo-team/marimo

- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/dnd/extension.ts
- frontend/src/core/codemirror/markdown/__tests__/commands.test.ts
- frontend/src/core/codemirror/markdown/commands.ts
- frontend/src/core/codemirror/markdown/extension.ts
Closes #2932 
This allows drag-n-drop or copy-paste of files and images, into markdown or python
> improvement: support smart paste and drag of files

- frontend/src/components/editor/SortableCell.tsx
- frontend/src/core/cells/scrollCellIntoView.ts
- frontend/src/core/codemirror/cells/extensions.ts
Fixes #2941 
Fixes #2940 
This focuses the correct HTML which contains the event listeners
> fix: fix focus element on hidden cells

- frontend/src/components/editor/Output.tsx
- frontend/src/components/editor/cell/cell-context-menu.tsx
- frontend/src/components/export/export-output-button.tsx
- frontend/src/core/cells/__tests__/ids.test.ts
- frontend/src/core/cells/ids.ts
> improvement: copy cell output if user does not select anything

- .github/workflows/dev-release.yml
- .github/workflows/marimo-bot.yml
- .github/workflows/release.yml
Last release failed with npm registry being down
> chore: add npm publish retry

- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_utils/narwhals_utils.py
- tests/_data/mocks.py
- tests/_plugins/ui/_impl/charts/test_altair_transformers.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_utils/test_narwhals_utils.py
> chore: add some more narwhals tests

- .github/workflows/test_be_dagger.yaml
- .github/workflows/test_fe_dagger.yaml
Dagger has been failing (didn't think anything changed in the setup), so just muting it for now
> chore: don't fail on dagger fails

- marimo/_cli/export/commands.py
- marimo/_dependencies/dependencies.py
- marimo/_server/export/__init__.py
- marimo/_server/export/exporter.py
- tests/_cli/snapshots/ipynb_topdown.txt
- tests/_cli/test_cli_export.py
- tests/_server/export/snapshots/empty_notebook.ipynb.txt
- tests/_server/export/snapshots/notebook_top_down.ipynb.txt
- tests/_server/export/snapshots/notebook_topological.ipynb.txt
- tests/_server/export/snapshots/notebook_with_cells.ipynb.txt
- tests/_server/export/test_exporter.py
- tests/conftest.py
> improvement: add --sort option to marimo export ipynb

- README.md
Small detail, but I don't mind having more blue skies.
> Add bluesky link 

- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
> fix: pagination in mo.ui.table() when passed in manually

- docs/recipes.md
Provides recipes for pre-populating forms from examples or query parameters
[New form recipe](https://marimo.app/l/w21a3x?t1=query&t2=params)
Less hacky #2928 :)
> Form with examples

- README.md
- docs/index.md
> docs: dataframes tiny edit

- frontend/src/components/editor/cell/cell-context-menu.tsx
- marimo/_smoke_tests/mpl/basic_image.py
> improvement: add 'Copy image' button

- marimo/_cli/config/commands.py
- marimo/_config/manager.py
> improvement: set default config, if missing

- docs/index.md
Added link to Mastodon
Small change, adding a line in the list of online accounts to the Mastodon account created this year
I scanned the guidelines but this is not a code change. I have not run any tests. I truly hope this patch will not break any code :)
PS. cool project!
> Added link to Mastodon

- marimo/_output/hypertext.py
- marimo/_output/md.py
- tests/_output/test_hypertext.py
- tests/_output/test_md.py
This helps when including outputs in ipynb so they at least show up in jupyter (but won't be interactive)
> improvement: add _repr_markdown_ to Md component, and _repr_html_ to Html component

- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- marimo/_plugins/ui/_impl/from_anywidget.py
- marimo/_smoke_tests/anywidget_examples/esm_rerender.py
- tests/_plugins/ui/_impl/test_anywidget.py
Fixes #3018
We need to hash the js to check for changes, instead of using the url, since the url is not deterministic by its contents
> fix: allow re-rendering anywidget js

- frontend/src/plugins/impl/vega/vega.css
> fix: altair overflow styling

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/ai/ai-completion-editor.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/code/readonly-python-code.tsx
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- frontend/src/css/app/Cell.css
* Add a few tooltips on buttons
* Some css changes for when cell output is below the code
> improvement: add tooltips to some hide/show code, fix markdown when cell output is below

- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/pages/home-page.tsx
- frontend/src/utils/urls.ts
* Add button to create/open a new notebook
* Fix "Return Home"
> improvement: add new-notebook button

- frontend/src/components/chat/chat-panel.tsx
- frontend/vite.config.mts
Autoscroll to the bottom while content is loading
> improvement: autoscroll in chat

- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/editor/ai/completion-utils.ts
- marimo/_data/get_datasets.py
- marimo/_data/models.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/ibis_table.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_server/ai/prompts.py
- marimo/_server/api/endpoints/ai.py
- marimo/_server/models/completion.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_data/test_get_datasets.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
- tests/_plugins/ui/_impl/tables/test_ibis_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_server/ai/snapshots/chat_system_prompts.txt
- tests/_server/ai/snapshots/system_prompts.txt
- tests/_server/ai/snapshots/user_prompts.txt
- tests/_server/ai/test_prompts.py
- tests/_server/api/endpoints/test_ai.py
- tests/_server/session/test_session_view.py
* include samples from datasets in AI prompt (suggestion from @Light2Dark)
* fix AI schema context on followup messages by contacting the messages
* improve prompts / rules (all snapshotted)
> improvement: include samples in AI prompt

- frontend/src/components/editor/Cell.tsx
- frontend/src/css/app/Cell.css
Follow up on #2507 .
- There were also some UI bugs from before that are fixed here. (I didn't account for Cell Output below the cell 🙏)
> improvement: add borderless markdown and some ui fixes

- frontend/src/components/chat/chat-panel.tsx
> fix: theme in chat sidebar

- docs/faq.md
- docs/guides/working_with_data/sql.md
> docs: escaping sql backets

- marimo/_tutorials/dataflow.py
- marimo/_tutorials/for_jupyter_users.py
- marimo/_tutorials/layout.py
- marimo/_tutorials/markdown.py
Small updates to the markdown tutorial and markdown usage in our tutorials in light of recent changes.
> tutorials: update markdown usage

- docs/faq.md
- docs/guides/coming_from/index.md
- docs/guides/coming_from/jupyter.md
- docs/guides/index.md
- docs/index.md
- console commands (got a few questions about this recently)
- installing packages
- FAQ on JupyterBook
> docs: more tips for coming from jupyter

- marimo/_runtime/reload/module_watcher.py
- tests/_runtime/reload/reload_test_utils.py
- tests/_runtime/reload/test_module_watcher.py
- tests/conftest.py
* tests are faster
* module watcher is properly cleaned up
> fix: faster module watcher tests

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/RecoveryButton.tsx
- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/cell/useRunCells.ts
- frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/components/editor/controls/Controls.tsx
- frontend/src/components/editor/header/filename-form.tsx
- frontend/src/components/editor/links/cell-link.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/components/editor/renderers/cells-renderer.tsx
- frontend/src/components/sort/SortableCellsProvider.tsx
- frontend/src/components/ui/tooltip.tsx
- frontend/src/core/MarimoApp.tsx
- frontend/src/core/cells/__tests__/utils.test.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/utils.ts
- frontend/src/core/config/config.ts
- frontend/src/core/edit-app.tsx
- frontend/src/core/layout/layout.ts
- frontend/src/core/saving/Save.tsx
- frontend/src/core/saving/filename.ts
- frontend/src/core/saving/save-component.tsx
- frontend/src/core/saving/state.ts
- frontend/src/core/saving/useAutoSave.ts
- frontend/src/core/state/jotai.ts
- frontend/src/core/variables/state.ts
- frontend/src/hooks/debug.ts
- frontend/src/plugins/core/BadPlugin.tsx
- frontend/src/utils/id-tree.tsx
- frontend/vite.config.mts
This splits up some components and refactors the saving logic for some perf improvements. It also moves more logic into jotai atoms that can prevent re-renders if the value is the same
> improvement: refactors for perf

- marimo/_runtime/runtime.py
- tests/_runtime/test_runtime.py
- tests/_server/export/test_exporter.py
This improves perf a bit from avoiding re-renders when the data is the same.
> improvement: don't send variables if they dont change

- examples/cloud/modal/README.md
- examples/cloud/modal/modal_edit.py
Add a minimal example of launching the marimo notebook and having the ability to run editable marimo notebooks on Modal. 
Update `README.md` in modal examples, and add the example file `modal_edit.py` defining the modal container. 
Note: Not sure what the naming convention is for examples, happy to rename!
@mscolnick
> example: deploy editable notebooks in Modal

- marimo/_cli/development/commands.py
Useful development command that i recently needed
> development: add command to print all routes

- marimo/_server/asgi.py
- tests/_server/test_asgi.py
Adds ASGI middleware support to `with_app` and `with_dynamic_directory`. Also adds a `marimo_app_file` to the scope so middleware can access this without having to figure this out.
> improvement: add asgi middleware to create_asgi_app

- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_smoke_tests/issues/3107-dataframe-perf.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
Fixes #3107 
`.schema` from narwhals or polars is slow if not cached. I didn't expect these to be slow. Due to a refactor we called this from the inner loop each time. This PR fixes that and adds a test. 
Will do some more perf testing on various methods, that get called a lot.
> fix: .schema perf improvements

- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/altair/altair_datetime.py
- tests/_plugins/ui/_impl/test_altair_chart.py
Fixes #3100 
For tests and edge cases for parsing datetime, and with timezones.
> fix: altair datetime selection filtering

- marimo/_output/formatters/holoviews_formatters.py
- marimo/_plugins/ui/_impl/input.py
This should avoid pulling in dependencies if they are not already pulled in.
> perf: check if package has been imported instead of installed

- marimo/_cli/sandbox.py
- marimo/_server/api/lifespans.py
- marimo/_server/print.py
> feat: show network url when running host=0.0.0.0

- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
Fixes #3130 
Uppercase strings were not searchable
> fix: case sensitivity of uppercase searches

- marimo/_output/formatters/altair_formatters.py
> fix: altair chart dark mode toggle

- .github/workflows/test_cli.yaml
- marimo/_cli/print.py
- marimo/_server/print.py
- tests/_cli/test_cli.py
Fix windows testing hanging from colors issue
> test: maybe fix windows cli tests

- marimo/_output/md.py
- pyproject.toml
> fix: lower dep on pymdown

- frontend/src/components/editor/file-tree/file-explorer.tsx
- frontend/src/core/wasm/bridge.ts
- marimo/_server/templates/templates.py
it's likely users won't create an endpoint to save settings
> fix: various wasm fixes for those who self-host

- .github/workflows/pages.yml
Share the example WASM in run mode due to on-save errors in edit.
> gh pages example: run

- marimo/_cli/export/commands.py
Tell users how to test the notebook locally after export
> improve: marimo export html-wasm CLI message

- docs/index.md
Link to our living feedback form.
> docs: feedback link

- marimo/_plugins/stateless/mpl/_mpl.py
- marimo/_server/api/endpoints/health.py
- marimo/_server/sessions.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_server/api/endpoints/test_health.py
> feat: add active connection enpdoint

- docs/guides/exporting.md
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- frontend/src/core/dom/marimo-tag.ts
- marimo/_cli/export/commands.py
- marimo/_server/export/__init__.py
- marimo/_server/export/exporter.py
- marimo/_server/templates/templates.py
- tests/_cli/test_cli_export.py
- tests/_server/export/test_exporter.py
- tests/_server/templates/test_templates.py
Fixes #3171
add --no-show-code to marimo export wasm
> improvement: add --no-show-code to marimo export wasm

- marimo/_ast/names.py
- marimo/_server/recents.py
Fixes #3202 
An uncaught exception was bringing down the server.
> fix: toml parse error for recent notebooks

- docs/api/inputs/chat.md
- docs/api/inputs/data_explorer.md
- docs/api/inputs/nav_menu.md
- docs/api/plotting.md
- docs/guides/working_with_data/plotting.md
> docs: fix wasm embeds

- frontend/src/components/editor/Cell.tsx
- frontend/src/core/hotkeys/actions.ts
- frontend/src/hooks/useHotkey.ts
- frontend/src/utils/events.ts
> fix: Vim keybindings taking precedence over text area keybindings

- marimo/_ast/app.py
- marimo/_ast/cell.py
- marimo/_output/data/data.py
- marimo/_output/formatting.py
- marimo/_plugins/stateless/download.py
- marimo/_plugins/stateless/nav_menu.py
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_runtime/complete.py
- marimo/_runtime/redirect_streams.py
- marimo/_runtime/runtime.py
- marimo/_save/hash.py
- marimo/_server/asgi.py
- marimo/_utils/dataclass_to_openapi.py
- marimo/_utils/parse_dataclass.py
- pyproject.toml
Lint rules to enforce google docs: 
https://www.pydocstyle.org/en/stable/error_codes.html
> docs: final google docs, add lint rules

- docs/api/inputs/dataframe.md
> docs: fix marimo-embed of ui.dataframe

- marimo/_plugins/stateless/lazy.py
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/dataframes/test_dataframe.py
- tests/_plugins/ui/_impl/test_table.py
A few RPCs were accidentally public; this change makes them private.
> chore: make RPCs private methods

- marimo/_cli/sandbox.py
- marimo/_plugins/__init__.py
- marimo/_plugins/ui/_impl/chat/__init__.py
- marimo/_plugins/ui/_impl/dataframes/__init__.py
- marimo/_utils/docs.py
- tests/_cli/test_sandbox.py
Fixes a bug in which users were prompted for sandbox only when editing local files.
> fix: read sandbox dependencies when opening remote files

- docs/vercel.json
I can't test this locally, but it's a suspicion I have. Please close if incorrect. Related to [discord link](https://discord.com/channels/1059888774789730424/1059891311190229082/1319980533106737162)
> add trailing slash for /index.html redirects

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/tracing/tracing.tsx
- frontend/src/core/cells/__tests__/runs.test.ts
- frontend/src/core/cells/runs.ts
Building off @Light2Dark's great work on the tracing panel. Had a few tweaks for perf and show in the **Labs** section of the settings
cc @Light2Dark for review
> improvement: tracing perf, hide charts and skip markdown

- frontend/src/components/tracing/tracing.tsx
using m.VegaLite is fine, but it will throw some browser warnings
> tidy: revert back to using m.Vega

- docs/blocks.py
- docs/faq.md
- docs/guides/expensive_notebooks.md
- docs/guides/reactivity.md
- mkdocs.yml
Rewrite the reactivity guide to be more accessible.
Also, give readers a tip that they can copy/paste notebook files into the editor.
> docs: rewrite reactivity guide

- mkdocs.yml
Update site description for docs.
> docs: Update site description

- .github/workflows/release-marimo-base.yml
> fix: publish all marimo-base releases to test pypi

- .github/ISSUE_TEMPLATE/bug_report.yaml
nest under details; include backticks
> chore: update env section of bug issue template

- marimo/_cli/upgrade.py
- tests/_cli/test_upgrade.py
Flaky test failing once a year
> fix: update check test

- docs/guides/editor_features/overview.md
- docs/guides/reactivity.md
- docs/index.md
- frontend/src/components/app-config/user-config-form.tsx
- mkdocs.yml
> docs: fix title Overview and broken link

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/config/config-schema.ts
- frontend/src/core/config/feature-flag.tsx
- marimo/_server/api/endpoints/ws.py
- pyproject.toml
This PR makes it possible for multiple users to edit the same notebook in real-time. This is using [CRDTs](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) and more precisely [Yjs](https://github.com/yjs/yjs) in the frontend and [pycrdt](https://github.com/jupyter-server/pycrdt) in the backend.
Unlike the "kiosk mode" which only shows a read-only view of the outputs, the collaborative mode allows editing cell inputs. Users can edit the same cell at the same time: CRDTs ensure that all users eventually see the same text, potentially resolving conflicts.
A new WebSocket endpoint is created at `ws/{cell_id}` for each notebook cell. When connecting to it, a cell input represented as a [shared text](https://docs.yjs.dev/api/shared-types/y.text) in the frontend is synchronized …
> Allow real-time cell editing by multiple users

- docs/api/inputs/run_button.md
Thanks @Haleshot for pointing this out!
> docs: fix run button embed

- docs/api/inputs/button.md
- examples/ui/button.py
Add `button.py`
Modify button.md docs with latest mkdocs like syntax by linking to appropriate example.
> docs: Add `button.py` and modify preview

- frontend/src/components/editor/output/MarimoTracebackOutput.tsx
- mkdocs.yml
update links to https://community.marimo.io/
> docs: update community link url

- frontend/src/core/codemirror/keymaps/keymaps.ts
- frontend/src/core/codemirror/keymaps/vim.ts
Fixes #1479 
Removes more keys to support blockwise mode
> fix: vim blockwise mode

- marimo/_smoke_tests/altair/vegafusion_nb.py
- some APIs don't exist
- versions stale, missing packages sandbox
> chore: fix smoke test for vegafusion

- README.md
- docs/guides/editor_features/package_management.md
- docs/guides/index.md
- docs/guides/package_reproducibility.md
- docs/index.md
- mkdocs.yml
Add a top-level guide on package reproducibility using `--sandbox`.
> docs: package reproducibility

- docs/guides/coming_from/jupyter.md
- frontend/src/components/ui/use-toast.ts
- frontend/src/core/codemirror/compat/__tests__/jupyter.test.ts
- frontend/src/core/codemirror/compat/jupyter.tsx
Link to documentation for magic command replacements.
> improvement: toast a link to documenation for magic command replacements

- frontend/src/core/saving/save-component.tsx
> fix: remove toast for notebook saved

- frontend/src/css/app/Cell.css
Fixes #3409 . 
| type                      | example                                                                 |
|------------------|-----------------------------------------------|
| python error         | <img height="200" alt="image" src="https://github.com/user-attachments/assets/0abc89d7-0e82-4690-b8ff-ad424fb8b8ec" /> |
| sql                         | <img height="200" alt="image" src="https://github.com/user-attachments/assets/27de317f-e092-472e-9b8d-44a5058566c6" /> |
| plotly                     | <img height="200" alt="image" src="https://github.com/user-attachments/assets/902c821c-3f78-42ee-a222-aeffb799b2c3" /> |
| table                      | <img height="200" alt="image" src="https://github.com/user-attachments/assets/9a7ad3d7-ab51-4a04-a2a5-af3289aa9844" /> | …
> improvement: improve blur for stale cell outputs

- docs/guides/working_with_data/dataframes.md
Fix typos: `pandas` -> `polars`
Fix typos where `import polars` is incorrectly written as `import pandas`
> Typo: pandas -> polars

- docs/guides/editor_features/watching.md
Fix broken link for Editor Features
> Fix broken link

- .github/workflows/test_be.yaml
- docs/guides/coming_from/jupyter.md
- docs/guides/editor_features/module_autoreloading.md
- docs/guides/publishing/playground.md
- docs/recipes.md
- pyproject.toml
> docs: fix links, add ci

- frontend/src/components/editor/Output.tsx
Fixes #3412 . Adds `align-items: safe center` to prevent overflow of flex item when supported by the browser.
similar issue: [stack overflow](https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container)
Before:
After:
normal text which does not overflow (no change, still centered vertically):
- why fallback? It's supported by all browsers, except Safari 17 (< Jul  2024) https://caniuse.com/?search=align-items:%20safe
- alternative is to use `my-auto` , but this gets overwritten and needs more work imo
> fix: overflow output in fullscreen

- docs/vercel.json
Fixes https://github.com/marimo-team/marimo/issues/3406
> docs: force trailing slash

- docs/guides/configuration/theming.md
- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/Output.tsx
- frontend/src/components/editor/__tests__/data-attributes.test.tsx
This adds data attributes on the cell to serve as selectors. 
Closes #3436
> fix: add data attributes for the cell to serve as selectors

- GOVERNANCE.md
> docs: show CLA in governance.md

- frontend/src/components/editor/chrome/types.ts
- frontend/src/core/config/feature-flag.tsx
- frontend/src/core/websocket/useMarimoWebSocket.tsx
cc @Light2Dark, GAing your feature
> feat: GA tracing panel

- frontend/package.json
- frontend/pnpm-lock.yaml
> chore: pyodide to 0.27.1

- examples/layouts/README.md
- examples/layouts/columns.py
> add example notebook using columns

- frontend/src/components/data-table/__tests__/url-detector.test.tsx
- frontend/src/css/md.css
- marimo/_output/md.py
- marimo/_smoke_tests/markdown_pymdownx.py
Conditionally add new pymdown extensions
> improvement: add details block to pymdown

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/__tests__/data-attributes.test.tsx
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
> fix: add cell data-attributes in read/present

- frontend/src/components/editor/renderers/vertical-layout/__tests__/vertical-layout.test.ts
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
Fixes #3545 
Use the last seen column, not 0
> fix: column grouping

- frontend/src/components/editor/columns/cell-column.tsx
- remove background
- thicken column border
> style: column background

- docs/_static/js/math.js
- mkdocs.yml
> docs: render katex

- frontend/src/components/find-replace/find-replace.tsx
Fixes #3540 . Allow to replace with empty strings + reset matches if replace is succesful.
> fix: allow to replace with empty, and reset matches after replace

- docs/guides/expensive_notebooks.md
Update the caching user guide to account for both decorator/context manager APIs.
> docs: update caching user guide

- marimo/_cli/sandbox.py
- marimo/_server/templates/templates.py
- marimo/_utils/versions.py
- tests/_cli/test_cli_export.py
- tests/_cli/test_markdown_conversion.py
- tests/_cli/test_sandbox.py
- tests/_server/templates/utils.py
- tests/mocks.py
> fix: allow editable installs when devloping locally with sandbox

- CONTRIBUTING.md
- docs/guides/editor_features/watching.md
- docs/guides/exporting.md
- marimo/_cli/export/commands.py
- tests/_cli/test_cli_export.py
Adds `--watch` command to export `html-wasm`, and some docs on how to set up this experience.
Ref: [discord thread](https://discord.com/channels/1059888774789730424/1231697382870093845/1332308364008357888)
> feat: add wasm watch and some docs on set up

- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
Fixes timezone printing of polars in web-assembly. Closes #3581
> fix: handle timezone in samples

- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/altair/map_selection.py
- tests/_plugins/ui/_impl/test_altair_chart.py
Fixes #3549
This adds support for nested maps charts (when used in layers)
> fix: support altair map selection when vconcat or hconcat

- frontend/src/plugins/core/builder.ts
- frontend/src/plugins/core/registerReactComponent.tsx
- frontend/src/plugins/impl/DataEditorPlugin.tsx
- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
> fix: scope ag-grid styles to plugin to avoid style pollution

- docs/guides/editor_features/ai_completion.md
Improve docs for Openapi-compatible providers by showcasing the options which they can use.
Used admonitions and content tabs (nested) to showcase both options using [deepseek](https://api-docs.deepseek.com/) as an example (owing to recent growth/popularity spurts).
WIP/draft stages for now: to see how the docs are previewed.
> docs: add DeepSeek configuration to AI completion guide

- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/sql.ts
- frontend/src/core/codemirror/language/utils/ast.ts
- marimo/_sql/sql.py
Use the lezer AST for SQL parsing instead of regex for better reliability.
> improvement: use ast for sql parsing

- CONTRIBUTING.md
Fixes No mention of CLA in contributing guide #3632
> added CLA notes to the CONTRIBUTING guide

- frontend/src/core/network/types.ts
- frontend/src/plugins/impl/vega/vega.css
> fix: responsive Vega chart sizing with media queries

- docs/faq.md
> docs: typo

- tests/_output/test_try_format.py
Just adding tests so if its changed, we know how its changed.
> tests: add tests for try-format

- scripts/pycopyright.sh
> chore: update year in copyright notice script

- marimo/_ast/sql_visitor.py
- marimo/_plugins/stateless/routes.py
- marimo/_runtime/virtual_file.py
- marimo/_server/sessions.py
- pyproject.toml
- tests/_plugins/stateless/test_image.py
- tests/_runtime/test_validate_graph.py
- tests/_runtime/test_virtual_file.py
Add some free fixes from ruff.
> chore: add PERF ruff rules

- frontend/src/core/codemirror/copilot/getCodes.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/lsp/__tests__/notebook-lsp.test.ts
- frontend/src/core/codemirror/lsp/lens.ts
- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- frontend/src/utils/lru.ts
combine code before sending to LSP, and uncombine after
> poc: lsp server with combining code into a single notebook

- marimo/_server/session/session_view.py
- tests/_server/session/test_session_view.py
Small correctness fix for filtering old datasets from variables
> fix: filtering datasets based on variables

- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- marimo/_dependencies/dependencies.py
- marimo/_server/lsp.py
- pyproject.toml
hopefully directionally right. `pylsp_completions` needs impl and `pylsp_hover` likely can be improved
> poc: lsp server with combining code into a single notebook (#3675)

- marimo/_ai/llm.py
- marimo/_server/api/endpoints/ai.py
Just a quick break from my work
Address
https://github.com/marimo-team/marimo/security/code-scanning/19
https://github.com/marimo-team/marimo/security/code-scanning/20
> fix: code scanning alerts

- marimo/_output/formatters/ai_formatters.py
- marimo/_output/formatters/formatters.py
- marimo/_smoke_tests/ai/gemini_responses.py
- tests/_output/formatters/test_ai_formatters.py
Adds a formatter for gemini outputs
https://github.com/user-attachments/assets/a783c900-f454-446f-a2d6-1ef980a01e4d
> improvement: pretty gemini responses in output, streaming / non-streaming

- examples/cloud/modal/README.md
- examples/cloud/modal/modal_app.py
- examples/cloud/modal/modal_edit.py
- examples/cloud/modal/nbs/notebook.py
Update the modal edit example to use a T4 instance, and to read from a local notebook that queries nvidia-smi.
Outstanding issues:
- No venv installed (package installation not working)
- Edits to remote notebook not currently synced back to local
> examples: GPU notebooks with modal

- tests/_plugins/ui/_impl/tables/snapshots/narwhals.field_types.json
- tests/_plugins/ui/_impl/tables/test_narwhals.py
Narwhals 1.26 ~~comes out later today~~ is out - this PR ensures the test suite keeps passing
We made a couple of changes which affect the test suite but which we don't expect to affect users
~~This fails now (as expected) but that will change once the nw release is published~~
> chore: minor updates for narwhals 1.26

- marimo/_plugins/ui/_impl/dataframes/transforms/handlers.py
- tests/_plugins/ui/_impl/dataframes/test_handlers.py
> fix: polars category filtering

- marimo/_plugins/ui/_impl/from_anywidget.py
- tests/_plugins/ui/_impl/test_anywidget.py
Keeps the full state on the backend, merges partial updates
> fix: merge anywidget partial updates

- marimo/_server/api/endpoints/assets.py
Add a better error message when follow-symlinks fail
> fix: add helpful error when symlink = false

- marimo/_runtime/runtime.py
- tests/_runtime/test_runtime.py
> fix: better fallback for notebook_dir

- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/mime-cell.tsx
- marimo/_smoke_tests/dataframes/dicts_vs_dfs.py
Fixes #3771
Fix displaying nested dictionary in tables. 
This still looks a bit different from polars, but mostly since its quite difficult to json_encode or serialize polars lists/arrays easily (see https://github.com/pola-rs/polars/issues/14029)
> fix: nested dictionary table

- marimo/_output/formatters/ai_formatters.py
- marimo/_output/formatters/formatters.py
- marimo/_smoke_tests/ai/openai_responses.py
- tests/_output/formatters/test_ai_formatters.py
https://github.com/user-attachments/assets/957c535c-97fe-497e-9a82-a500a6c8da0b
> improvement: add openai response formatters

- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_smoke_tests/tables/columnar_tables.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
> fix: table value after sorting, when columnar dictionary

- docs/api/markdown.md
- marimo/__init__.py
- marimo/_output/md.py
- marimo/_smoke_tests/latex/global_defs.py
- tests/_output/test_md.py
> improvement: mo.latex() to load macros

- marimo/_server/api/endpoints/assets.py
- tests/_server/api/endpoints/test_assets.py
> fix: /public path assets for windows (pt 2)

- frontend/src/core/codemirror/rtc/__tests__/cell-manager.test.ts
- frontend/src/core/codemirror/rtc/cell-manager.ts
- frontend/src/core/codemirror/rtc/extension.ts
> fix: disconnect RTC websockets when disconnected from main WS

- marimo/_output/formatters/ipython_formatters.py
- marimo/_smoke_tests/compat/ipython_display.py
- tests/_output/formatters/test_ipython_formatters.py
Some more coverage and tests cases for ipython display. A few edge-cases are still not covered (they are in the smoke-test)
> fix: more ipython display coverage, add tests

- frontend/src/components/editor/output/MarimoTracebackOutput.tsx
QOL improvement to copy the stack trace (i.e. need to put in discord or send to a colleague)
> improvement: copy stacktrace to clipboard

- marimo/_cli/print.py
> fix: muted color in terminal output

- marimo/_cli/sandbox.py
- tests/_cli/test_sandbox.py
Adds support for 3 different ways to configure index-urls in `uv`. `index-url`, `index`, and `extra-index-url`
per #3817
> improvement: support uv index-url and extra-index-url

- marimo/_ast/pytest.py
resolves #3828
toplevel inspect may have been causing issues in pypi imports
> Remove inspect call from top level

- marimo/_utils/health.py
Windows only. Problem posted in #3761
> fix: chrome env check

- marimo/_ast/app.py
- marimo/_ast/codegen.py
- marimo/_convert/ipynb.py
- marimo/_islands/_island_generator.py
- marimo/_runtime/app/kernel_runner.py
- marimo/_save/save.py
- marimo/_server/api/endpoints/ws.py
- marimo/_server/export/exporter.py
- marimo/_server/session/serialize.py
- marimo/_server/templates/templates.py
- marimo/_types/ids.py
- tests/_server/session/test_session_view.py
another typesafe migration for CellId
> chore: typesafe CellId

- frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
- frontend/src/core/codemirror/keymaps/keymaps.ts
> fix: <CR> in vim

- frontend/src/components/databases/icon.tsx
- frontend/src/components/editor/database/add-database-form.tsx
- frontend/src/core/codemirror/language/panel.tsx
- marimo/_messaging/ops.py
- marimo/_runtime/requests.py
- marimo/_types/ids.py
- tests/_server/api/endpoints/test_datasources.py
Tiny bug fix for adding back the biquery logo. 
Some tests and better typesafety
> fix: add back bigquery logo, move help into select dropdown

- frontend/src/components/editor/database/add-database-form.tsx
- frontend/src/components/forms/form-utils.ts
- frontend/src/components/forms/form.tsx
- frontend/src/plugins/impl/data-frames/forms/__tests__/__snapshots__/form.test.tsx.snap
- frontend/src/plugins/impl/data-frames/forms/__tests__/form.test.tsx
- frontend/src/plugins/impl/data-frames/forms/renderers.tsx
- frontend/src/plugins/impl/data-frames/schema.ts
Fixes #3846
Filtering form was regressed when I added database forms
> fix: mo.ui.dataframe filtering

- frontend/src/components/datasources/datasources.tsx
- marimo/_data/get_datasets.py
- marimo/_data/preview_column.py
- marimo/_sql/engines.py
- tests/_data/test_preview_column.py
- tests/_sql/test_sqlalchemy.py
For postgres, it will connect to the default database if unspecified. This fixes the display for that (by finding the default db). For others like Snowflake, it's in a detached state, hence we show 'Not connected'
> improve: minor ui updates, fixes for datasources

- frontend/src/components/editor/__tests__/data-attributes.test.tsx
- frontend/src/components/pages/edit-page.tsx
- frontend/src/core/config/config-schema.ts
- frontend/src/core/constants.ts
- frontend/src/core/edit-app.tsx
Hide chrome and controls via query param
> improvement: Add show-chrome=false

- docs/guides/publishing/playground.md
Fix the snippet for embedding in MDX.
> docs: fix MDX snippet

- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/selection.py
- tests/_plugins/ui/_impl/tables/test_selection.py
- tests/_plugins/ui/_impl/test_table.py
Correctly pass stable row Id to the frontend. At some point I removed the column, which made the frontend check fail.
> fix: stable row id

- tests/_cli/test_cli.py
- tests/_server/api/endpoints/test_execution.py
- tests/_utils/config/test_config_reader.py
just experimenting to see if any tests could be fixed.
> chore: small test fixes

- frontend/src/core/islands/worker/worker.tsx
- frontend/src/core/wasm/worker/bootstrap.ts
- frontend/src/core/wasm/worker/worker.ts
auto install sqlglot when using sql cells
> improvement: auto-install sqlglot when using mo.sql in wasm

- docs/guides/configuration/index.md
- docs/guides/configuration/snippets.md
- mkdocs.yml
> docs: custom snippets

- frontend/src/core/codemirror/keymaps/vim.ts
- frontend/src/utils/idle.ts
Fixes #3197 
This should help with slow switching between keys
> fix: vim switching perf

- marimo/_runtime/dataflow.py
- tests/_runtime/test_dataflow.py
Few more tests for dataflow. Some are xfailed because the test does look right, so going to leave as a todo 
The commented out one hangs
> tests: more tests for dataflow

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/chat/markdown-renderer.tsx
- frontend/src/components/editor/chrome/types.ts
- frontend/src/components/editor/chrome/wrapper/copilot-status.tsx
- frontend/src/core/config/config.ts
- frontend/src/core/config/feature-flag.tsx
> feat: GA chat sidebar

- marimo/_cli/config/commands.py
> fix: marimo config describe format

- marimo/_cli/cli.py
- marimo/_cli/export/commands.py
- marimo/_cli/sandbox.py
- marimo/_server/api/endpoints/assets.py
- tests/_cli/test_cli.py
- tests/_cli/test_cli_export.py
- tests/_config/test_manager.py
In case you don't want to run in a sandbox (for whatever reason), this allows you to omit that. We only prompt when not explicitly provided True/False
> improvement: allow --no-sandbox

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/home/components.tsx
- frontend/src/components/pages/home-page.tsx
- frontend/src/core/constants.ts
> improvement: add helpful resources to the home page and dropdown

- marimo/_server/api/endpoints/ai.py
Also requires an upgrade to the OpenAI sdk
> fix: remove tmp for thinking models

- frontend/islands/vite.config.mts
- frontend/src/plugins/impl/multiselectFilterFn.tsx
- frontend/vite.config.mts
> fix: islands css not showing up

- frontend/src/components/datasources/datasources.tsx
If there are no tables, many requests will be fired for `previewSQLTableList`. We should stop requesting once an initial request has been made.
> fix: prevent many requests for table lists when no tables exists

- docs/guides/exporting.md
- docs/guides/publishing/cloudflare_pages.md
- docs/guides/publishing/index.md
- mkdocs.yml
Added  Cloudflare Pages as option for publishing in documentation 
Resolves : #3954 
I have read the CLA Document and I hereby sign the CLA
@akshayka
> Adding cloudflare pages as an option for publishing

- marimo/_runtime/runtime.py
Fixes #3979
Typo I didn't catch due to manual setting in my config.
> fix: invalid test feature flag

- README.md
Link to the stellar YouTube channel @koaning set up for us
> YouTube link in English README

- examples/cloud/modal/README.md
One line change: fix python filename in README for cloud examples
@mscolnick
> Fix filename in cloud examples readme

- frontend/src/components/data-table/TableActions.tsx
- frontend/src/components/data-table/data-table.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
Fixes #3970. A little bit rough, this adds a backend function to get all row_ids. Prevents search with select all for very large datasets.
> fix: select all on a searched table

- marimo/_cli/cli.py
- marimo/_cli/convert/commands.py
- marimo/_cli/convert/utils.py
- marimo/_cli/development/commands.py
- marimo/_cli/export/commands.py
- marimo/_cli/file_path.py
- marimo/_plugins/core/media.py
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/layout/layout.py
- marimo/_server/export/exporter.py
- marimo/_server/file_manager.py
- marimo/_server/files/os_file_system.py
- marimo/_tracer.py
- marimo/_utils/paths.py
- tests/_cli/test_cli.py
- tests/_cli/test_file_path.py
- tests/_server/api/endpoints/test_files.py
- tests/mocks.py
Prefer `Path().read/write` over `open`
> chore: use Path over open

- docs/guides/editor_features/ai_completion.md
- examples/ai/chat/anthropic_example.py
- frontend/src/components/app-config/constants.ts
updates default anthropic model from `claude-3-5-sonnet-20240620` → `claude-3-7-sonnet-20250219`
updated anthopic model references in docs, example scripts, and frontend constants.
> chore(ai): upgrade default Anthropic model to claude-3-7-sonnet-20250219

- marimo/_cli/convert/commands.py
- marimo/_cli/convert/utils.py
Earlier it used to raise a big error , now handling it with click utility
> Adding a check for file in convert cli. Earliar it used to raise long error

- frontend/src/plugins/impl/vega/__tests__/make-selectable.test.ts
- frontend/src/plugins/impl/vega/make-selectable.ts
- frontend/src/plugins/impl/vega/marks.ts
- marimo/_smoke_tests/altair/boxplot.py
Boxplots are not selectable. We should not fail trying to make them so
> fix: box-plots are not selectable

- codecov.yml
- tests/_sql/test_engines.py
More tests coverage for SQL engines
> tests: sql engines

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/data-table/__tests__/types.test.ts
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/types.ts
- frontend/src/utils/__tests__/dates.test.ts
- frontend/src/utils/dates.ts
- marimo/_smoke_tests/polars/timezones.py
> fix: render polars dates in UTC when a timezone is specified

- marimo/_dependencies/errors.py
- marimo/_plugins/stateless/pdf.py
- marimo/_server/lsp.py
Users may get confused when using with open(...)
> improve: accept Path for mo.pdf()

- marimo/_runtime/packages/module_name_to_pypi_name.py
They [released a new thing](https://github.com/openai/openai-agents-python) and when I tried it I hit my head because of the package name.
> OpenAI Agents support 

- examples/misc/colliding_blocks_and_pi.py
Inspired by 3Blue1Brown. Happy Pi Day!
> example: colliding blocks and pi

- README_Spanish.md
This pull request creates the README_Spanish.md file.
Fixes #4109 
Inside README_Spanish.md file you'll find the translation to Spanish up to the Quickstart section. From then on the subtitles are translated.
@mscolnick
> Created the README_Spanish.md file and translated a section and subtitles.

- README.md
> docs: link to spanish-langauge README.md

- marimo/_plugins/ui/_impl/file_browser.py
- marimo/_plugins/validators.py
- tests/_plugins/ui/_impl/test_file_browser.py
Support the `client` arg used in cloudpathlib
> fix: handle cloudpath client

- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- tests/_plugins/ui/_impl/tables/snapshots/narwhals.field_types.json
[Narwhals#2113](https://github.com/narwhals-dev/narwhals/pull/2113) is going to introduce `Time` dtype, this PR prepares for that
> chore: Add support for narwhals `Time` dtype

- frontend/src/core/wasm/__tests__/state.test.ts
- frontend/src/core/wasm/state.ts
> fix: WASM app with print() finish loading

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/lsp/__tests__/notebook-lsp.test.ts
- frontend/src/core/codemirror/lsp/lens.ts
- frontend/src/core/codemirror/lsp/notebook-lsp.ts
Support variable renaming. 
Few hacks (documented), to get around the fanning out of the edits.
> feat: rename symbols with LSP

- marimo/_server/api/auth.py
- marimo/_server/api/middleware.py
- marimo/_server/api/utils.py
- tests/_server/test_utils.py
Some improvements to the logging in skew protection middleware
> fix: better logging in SkewProtection middleware

- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/dropdowns.py
- tests/_plugins/ui/_impl/test_input.py
Fixes #4171 
Quite a small change for a big benefit. Dropdowns can now support any type
> improvement: allow dropdowns to be any type

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- frontend/src/css/app/codemirror-completions.css
- frontend/src/css/globals.css
Fixes (but still behind feature flag) #3059
Better file completion (from the upgraded package). Added new completion triggers on `/` and `.`
Also some styling and fallback icons.
> improvement: support better file completion

- frontend/src/components/ui/date-picker.tsx
> fix: date-range ui padding

- frontend/src/core/codemirror/copilot/client.ts
- frontend/src/core/codemirror/copilot/extension.ts
Broke when i upgraded `@marimo-team/language-server`, this fixes it.
> fix: fix copilot in LSP extension upgrade

- frontend/src/components/editor/Cell.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/core/codemirror/keymaps/vim.ts
> fix: j/k shouldn't make new cells in vim mode

- frontend/src/components/data-table/__tests__/columns.test.tsx
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/mime-cell.tsx
- frontend/src/components/editor/output/JsonOutput.tsx
- marimo/_output/hypertext.py
- marimo/_smoke_tests/tables/complex_types.py
- marimo/_smoke_tests/tables/rich_elements.py
- tests/_output/test_hypertext.py
Fixes #2656
Shows rich elements, lists and objects correctly in tables, dfs, for both polars and pandas.
- Clamp the height of the json output and fix some styling.
I've documented these behaviours in the smoke test:
- There is a strange bug, when calling` pl.DataFrame(data).transpose()`, the whole kernel crashes. This may exist prior as well.
- It also doesn't correctly render mixed mime & non-mime value items in a list. This happens for plain tables.
> feat: show rich elems in datatables

- marimo/_data/series.py
Completing a Todo which was pending, since this feature is now added in narwhals 
@mscolnick
> Adding IntoSeries which is now implemented in narwhals

- marimo/_config/config.py
- marimo/_server/ai/providers.py
Added the solution as mentioned in the issue i.e option for ssl in openai. 
Resolving : #4071 
@mscolnick
> improvement: Adding config option for SSL/TLS-secured OpenAI-compatible API/AI assistants

- marimo/_server/api/endpoints/assets.py
- marimo/_server/export/exporter.py
- marimo/_server/lsp.py
- marimo/_server/start.py
- marimo/_snippets/snippets.py
- marimo/_utils/paths.py
Small cleanup and DRY `import_files` logic
> chore: cleanup importfiles

- marimo/_ast/pytest.py
- marimo/_dependencies/dependencies.py
- marimo/_runtime/pytest.py
- tests/_ast/test_pytest_scoped.py
- tests/_runtime/script_data/contains_tests.py
- tests/_runtime/test_pytest_runtime.py
- tests/conftest.py
fixes: #4135
fixes: #4140
- More rigorous check in handling report stack traces 
- Expose runtime variables to pytest during static evaluation
- Ensure setup cell exposes values that can be used for test collection
> fix: pytest bugs from user feedback

- marimo/_server/api/endpoints/login.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_server/api/endpoints/test_login.py
Fixes #4231 
* handle base-url using 
* basic security headers
* testing
> fix: auth page redirect when base-url is present, security headers

- frontend/pnpm-lock.yaml
- frontend/src/components/ui/number-field.tsx
> fix: allow more decimals in the table filters

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
- frontend/src/core/codemirror/copilot/extension.ts
- frontend/src/core/codemirror/keymaps/keymaps.ts
Upgrade `@marimo-team/codemirror-ai` for a slighlty updated/improved inline completions
> improvement: hide inline completion when not focused, add Esc hotkey

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/documentation.css
- marimo/_output/mime.py
- marimo/_output/rich_help.py
- marimo/_server/lsp.py
- marimo/_utils/docs.py
- pyproject.toml
- tests/_output/test_rich_help.py
- tests/_server/test_lsp.py
Add a custom converter to convert our google style docstrings to markdown
> improvement: Add custom docstring-to-markdown convert for Google Docs

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/documentation.css
- frontend/src/core/codemirror/completion/Autocompleter.ts
- frontend/src/core/codemirror/completion/hints.ts
- frontend/src/css/app/codemirror-completions.css
- fix: completions no appearing b/c of live docs.
- perf: don't request live-docs unless open 
This was actually the issue behind https://github.com/marimo-team/marimo/issues/2877
> fix: completions no appearing b/c of live docs. don't request live-docs unless open

- docs/api/layouts/index.md
- docs/api/layouts/stat.md
- mkdocs.yml
Not sure why the example isn't showing up for me in the docs. I can provide a simpler example if it's odd. Simple ones seem to work.
> docs: add mo.stat

- marimo/_plugins/stateless/audio.py
- tests/_plugins/stateless/test_audio.py
Couple missing tests for mo.audio
> tests: mo.audio

- docs/api/layouts/stat.md
Percent symbols don't seem to work in mddocs. So, removing those.
> docs: fix example for stat

- marimo/_cli/cli.py
- marimo/_cli/sandbox.py
- tests/_cli/test_sandbox.py
automatically add 'lsp' features in sandbox mode when running 'marimo edit'
> improvement: automatically add lsp in sandbox mode when running 'marimo edit'

- frontend/package.json
- frontend/pnpm-lock.yaml
Fixes #4277
Upgrades the LSP dep that fixes the look back to find the code to replace.
> fix: the lookback that LSP completions replaces

- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- marimo/_smoke_tests/altair/chart_dates.py
- tests/_plugins/ui/_impl/charts/test_altair_transformers.py
Fixes #4264
Use the altair util to fix timezones in vega
> fix: date serialization in altair without timezones

- frontend/src/components/data-table/url-detector.tsx
- marimo/_ai/llm/_impl.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_server/ai/providers.py
- marimo/_smoke_tests/tables/images.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
Include images in mo.ui.table()
> improvement: include PIL images in mo.ui.table()

- frontend/src/core/codemirror/language/markdown.ts
> feat: utf-8 latex completions

- marimo/_runtime/dataflow.py
- tests/_runtime/test_dataflow.py
Improve typings and datastructures. 
Prefer inline list/set compression for hot paths as it can be more optimized.
> improvement: dataflow perf

- marimo/_plugins/stateless/flex.py
> docs: hstack width examples

- examples/third_party/huggingface/chatbot.py
- marimo/_ai/llm/_impl.py
- marimo/_server/ai/providers.py
- tests/_ai/llm/test_impl.py
> fix: use max_completion_tokens instead of max_tokens

- marimo/_output/formatters/bokeh_formatters.py
Fixes #4323
patch `bokeh.io.show` on top of `bokeh.plotting.show`
> fix: patch bokeh.io.show

- marimo/_output/formatters/ai_formatters.py
- marimo/_output/formatters/formatters.py
- marimo/_smoke_tests/_transformers/text_streamer.py
Stream output from `TextIteratorStreamer` from the transformers library
cc @gschoeni
> improvement: add TextIteratorStreamer formatter from Hugging Face

- docs/guides/scripts.md
Update a "running as a script" docs example to point to a notebook that shows how to parametrize argparse with dynamic default values.
> docs: update argparse example

- frontend/src/components/data-table/__tests__/columns.test.tsx
- frontend/src/components/data-table/__tests__/url-detector.test.tsx
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/url-detector.tsx
need to edit tests but not sure what you think about this solution.
- the regex was a global one, hence it maintained state when you called it multiple times. I removed the global tag
- add some failing tests (maybe we can handle mixed content btr in the future)
> fix: image popover regression

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/chrome/panels/secrets-panel.tsx
- frontend/src/components/editor/chrome/types.ts
- frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/components/editor/database/form-renderers.tsx
- frontend/src/core/config/feature-flag.tsx
- marimo/_config/secrets.py
- marimo/_runtime/runtime.py
- marimo/_secrets/env_provider.py
- marimo/_secrets/load_dotenv.py
- marimo/_secrets/models.py
- marimo/_secrets/secrets.py
- marimo/_smoke_tests/tables/images.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_config/test_secrets_config.py
- tests/_runtime/test_runtime_secrets.py
- tests/_secrets/test_load_dotenv.py
- tests/_secrets/test_secrets.py
Secrets panel. Currently only supports **reading** environment variables. 
Next steps will be writing and then different secret providers.
> feat: secrets panel

- marimo/_sql/engines/clickhouse.py
Fixes column names missing for chdb queries. Ref: https://github.com/chdb-io/chdb/issues/317. 
Hey @mneedham, fixing this in the next release!
> fix: col names missing for chdb

- frontend/src/components/editor/chrome/panels/secrets-panel.tsx
- frontend/src/components/ui/links.tsx
- frontend/src/core/islands/bridge.ts
- frontend/src/core/network/connection.ts
- frontend/src/core/network/requests-network.ts
- frontend/src/core/network/requests-static.ts
- frontend/src/core/network/requests-toasting.ts
- frontend/src/core/network/requests.ts
- frontend/src/core/network/types.ts
- frontend/src/core/wasm/bridge.ts
- marimo/_cli/development/commands.py
- marimo/_runtime/requests.py
- marimo/_runtime/runtime.py
- marimo/_secrets/env_provider.py
- marimo/_secrets/load_dotenv.py
- marimo/_secrets/models.py
- marimo/_secrets/secrets.py
- marimo/_server/api/endpoints/secrets.py
- marimo/_server/models/secrets.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_runtime/test_runtime_secrets.py
- tests/_secrets/test_secrets.py
> feat: write env vars from secrets panel

- marimo/_runtime/runtime.py
Corrects some punctuation. Sorry! But this [docs page snippet](https://docs.marimo.io/api/query_params/#marimo.query_params) should be less distracting after this.
See above
- [N/A] I have added tests for the changes made.
- [no] I have run the code and verified that it works as expected.
> Correct minor punctuation error

- frontend/package.json
- frontend/pnpm-lock.yaml
Fix completion when there are no common prefixes
> fix: completion after .

- frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/completion/__tests__/keymap.test.ts
- frontend/src/core/codemirror/completion/keymap.ts
- frontend/src/core/codemirror/language/markdown.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/language/sql.ts
Fix a race between code completion and Escape when using Vim.
Fixes #4351
> fix: race between completion and Escape in Vim mode

- frontend/src/core/codemirror/keymaps/vim.ts
> fix: Vim Ctrl+[ to Escape

- frontend/src/core/vscode/vscode-bindings.ts
Fixes https://github.com/marimo-team/marimo/issues/4372
vscode upgraded electron which broke `document.execCommand("insertText")` for pasting. This adds a workaround for it.
> fix: vscode bindings since they removed execCommand

- docs/_static/js/init_kapa_widget.js
- mkdocs.yml
Integrate the Kapa bot (which has knowledge of our issues, discussions, discord) that can be found on the docs
> docs: kapa widget

- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_smoke_tests/tables/pandas_multi_idx.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/test_table.py
Fixes #4374. Renames columns only in to_json, change to commas. Special handling for table (because narwhals wraps multi-col in tuples).
> fix: pandas multi-idx col names

- frontend/src/plugins/impl/vega/__tests__/resolve-data.test.ts
- frontend/src/plugins/impl/vega/resolve-data.ts
- marimo/_smoke_tests/altair/repeat.py
> fix: loading data in vega charts using 'repeat'

- marimo/_server/ai/prompts.py
- marimo/_server/api/endpoints/ai.py
- tests/_server/ai/snapshots/chat_system_prompts.txt
- tests/_server/ai/snapshots/system_prompts.txt
- tests/_server/ai/test_prompts.py
- tests/_server/api/endpoints/test_ai.py
> add: small fix prompt

- frontend/src/components/editor/ai/__tests__/completion-utils.test.ts
- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/ai/completion-utils.ts
- frontend/src/components/editor/ai/completions.ts
- frontend/src/core/datasets/data-source-connections.ts
- frontend/src/css/app/codemirror-completions.css
Reference variables with `@` in AI prompt inputs. Pass the variables + values to the backend.
> improvement: variables in completion

- marimo/_server/ai/providers.py
Fix for #3631, as this failed for me again
> fix: update roles for o1 models

- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/sql.ts
- frontend/src/core/datasets/data-source-connections.ts
local df's now show up correctly.
@mscolnick
> fix: add completions from local dfs

- marimo/_dependencies/dependencies.py
- marimo/_sql/engines/clickhouse.py
- marimo/_sql/engines/sqlalchemy.py
- tests/_sql/test_sqlalchemy.py
We don't need to discover meta schemas, it can be performed on-demand. This should improve performance.
@mscolnick
> improvement: skip meta schemas for sql datasource discovery

- marimo/_output/data/data.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/ibis_table.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_smoke_tests/tables/big_ints.py
- tests/_output/test_data.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
> fix: sanitize big-ints in table manager

- CONTRIBUTING.md
- Makefile
- marimo/_ast/app_config.py
* Require `uv` for installation.
* Clearer make docs and make help
* Remove make `check-test` (this is too high-level and slow)
> chore: make touchup

- biome.json
- frontend/.eslintrc.cjs
- frontend/src/components/app-config/app-config-form.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/boundary/ErrorBoundary.tsx
- frontend/src/components/editor/chrome/components/contribute-snippet-button.tsx
- frontend/src/components/editor/chrome/components/feedback-button.tsx
- frontend/src/components/editor/database/add-database-form.tsx
- frontend/src/components/editor/output/MarimoTracebackOutput.tsx
- frontend/src/components/editor/package-alert.tsx
- frontend/src/components/home/components.tsx
- frontend/src/components/pages/run-page.tsx
- frontend/src/components/static-html/share-modal.tsx
- frontend/src/components/static-html/static-banner.tsx
- frontend/src/components/ui/links.tsx
- frontend/src/core/codemirror/copilot/copilot-config.tsx
- frontend/src/core/codemirror/language/panel.tsx
> chore: fix https for various urls

- docker/Dockerfile
- docker/README.md
- docs/guides/deploying/prebuilt_containers.md
Switch to `uv` in docker for faster installation
> improvement: use uv in docker

- frontend/src/core/saving/save-component.tsx
Various marimo commands start notebooks from a temporary directory:
- marimo tutorial
- marimo new "your prompt"
This change disables autosaving for notebooks located in temporary directories, instead prompting the user to manually save. This can help prevent lost work when editing notebooks generated with marimo new xxx.
> improve: prompt for save if notebook is stored in a tmp directory

- marimo/_ast/app_config.py
- marimo/_sql/engines/clickhouse.py
- marimo/_sql/sql.py
- tests/_sql/test_clickhouse.py
allow clickhouse to support native, pandas and auto
> improve: add clickhouse support for diff sql output types

- marimo/_output/formatters/plotly_formatters.py
- marimo/_smoke_tests/plotly/fig_show_run_as_script.py
> fix: don't patch plotly show when running as a script

- marimo/_output/formatters/arviz_formatters.py
- marimo/_smoke_tests/third_party/arviz_html.py
> fix: arviz formatter

- examples/sql/duckdb_example.py
For https://github.com/duckdb/duckdb-web/pull/5219
> example: duckdb (for duckdb docs)

- examples/cloud/modal/README.md
- examples/cloud/modal/modal_app.py
- examples/cloud/modal/modal_edit.py
- examples/cloud/modal/nbs/notebook.py
This PR updates Modal API usage in example files to be compatible with Modal's upcoming 1.0 release with some notebook fixes:
Reference Information
This change is based on recommendations in the [Modal 1.0 migration guide](https://modal.com/docs/guide/modal-1-0-migration#modal-10-migration-guide).
- Replace mounts=[modal.Mount.from_local_dir(...)] with image.add_local_dir(...)
- Rename concurrency_limit=N to max_containers=N
- Replace allow_concurrent_inputs=N with @modal.concurrent(max_inputs=N) decorator
- Update minimum Modal SDK version to modal>=0.73.166
- Add GPU availability check logic and provide runtime info snippets in `nbs/notebook.py` as this notebook fails if the modal uses CPU only.
Modified files:
- `examples/cloud/modal/modal_app.py`
- `examples/cloud/modal/modal_edit.py` …
> fix: examples in `modal`

- marimo/_tutorials/sql.py
- tests/_cli/snapshots/sql.md.txt
> tutorial: fix up SQL

- marimo/_server/lsp.py
- marimo/_server/main.py
- marimo/_server/start.py
Don't start LSP servers or create ports in run mode
> fix: disable LSP servers in run-mode

- frontend/src/core/static/__tests__/files.test.ts
- frontend/src/core/static/files.ts
- frontend/src/plugins/impl/DataTablePlugin.tsx
> fix: static pages for tables

- marimo/_runtime/runner/cell_runner.py
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_smoke_tests/issues/4515_ui_id_collision.py
fixes #4515
Minimal repro: https://marimo.app/l/flusuu
> fix: share context with post-hooks to prevent id collisions

- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/header-items.tsx
- frontend/src/css/common.css
Some refactoring to `DataTableColumnHeader` to make it more easily extendible without merge-conflicts
> chore: cleanup DataTableColumnHeader

- docs/guides/testing/pytest.md
Add some clarification regarding testing cells only comprising of `test_`, `Test`
maybe not aggressive enough?
> docs: clarify tests should be exclusive in cells

- marimo/_utils/health.py
More marimo env deps
Closes #4533
> chore: add more deps to `marimo env`

- frontend/src/components/data-table/download-actions.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_output/data/data.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/ibis_table.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
- tests/_plugins/ui/_impl/tables/test_ibis_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_plugins/ui/_impl/test_table.py
Download as parquet in the table editor
> feat: Add download parquet to table

- marimo/_ast/toplevel.py
- marimo/_runtime/runner/hooks_post_execution.py
- tests/_ast/test_toplevel.py
Thanks for the report @akshayka ! :tada:
> fix: regression added in #4538 and relevant test

- examples/ui/data_editor.py
Read dataframe from disk in same cell that creates the data_editor, to avoid spurious overwriting.
> docs: fix data editor example

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/chrome/panels/write-secret-modal.tsx
- frontend/src/components/editor/chrome/types.ts
- frontend/src/core/config/feature-flag.tsx
- marimo/_server/print.py
Release dotenv secrets out of experimental.
> feat: release .env secrets out of experimental

- docs/guides/editor_features/watching.md
- docs/guides/index.md
- docs/guides/library.md
- docs/guides/reusing_functions.md
- marimo/_tutorials/fileformat.py
- mkdocs.yml
Refreshes:
- BYOE (bring your own editor) page
- Fileformat tutorial
Introduces:
- Reusable functions page
> docs: new file format documentation

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/core/config/feature-flag.tsx
- marimo/_ast/codegen.py
- marimo/_ast/toplevel.py
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_runtime/runtime.py
- marimo/_server/print.py
- marimo/_tutorials/dataflow.py
- marimo/_tutorials/for_jupyter_users.py
- marimo/_tutorials/intro.py
- marimo/_tutorials/layout.py
- marimo/_tutorials/sql.py
- marimo/_tutorials/ui.py
- tests/_ast/codegen_data/test_generate_filecontents.py
- tests/_ast/codegen_data/test_generate_filecontents_async.py
- tests/_ast/codegen_data/test_generate_filecontents_async_long_signature.py
- tests/_ast/codegen_data/test_generate_filecontents_single_cell.py
- tests/_ast/codegen_data/test_generate_filecontents_with_syntax_error.py
- tests/_ast/codegen_data/test_long_line_in_main.py
- tests/_ast/test_codegen.py
- tests/_cli/snapshots/converted_multiple_defs.py.txt
- tests/_convert/test_convert_utils.py
- tests/_server/test_file_manager.py
Flag removal to turn on toplevel definitions.
Just in queue
Deps:
#4497 -> #4557 -> this
> feat: release reusable functions

- examples/frameworks/fastapi-endpoint/main.py
- examples/frameworks/fastapi-endpoint/notebook.py
- marimo/_ast/cell.py
- tests/_ast/test_cell.py
fastapi example with direct function calls
Speaking of e2e testing, the example refresh threw an error I couldn't easily seem to replicate through tests, but unsure of how long it's been there @mscolnick
> examples: refresh fastapi example

- docs/guides/reusing_functions.md
- marimo/_tutorials/fileformat.py
Minor edits
* explain returned defs
* simplify reusing functions doc
> docs: minor function fileformat edits

- README.md
- docs/index.md
Point to new usage examples on docs.
> docs: update links to examples and gallery

- tests/_server/api/endpoints/test_files.py
Stop gap for flaky test
Supersecedes https://github.com/marimo-team/marimo/pull/4588
@akshayka
> stop gap: check header for race condition

- README_Chinese.md
This PR updates README_Chinese.md
> docs: Update README_Chinese.md

- marimo/_cli/sandbox.py
- marimo/_runtime/packages/pypi_package_manager.py
- tests/_cli/test_sandbox.py
- tests/_runtime/packages/test_package_managers.py
Found some improvement in start time when using this flag. I should add more tests, just found interesting results.
<details>
Here's my benchmarking:
```python
import marimo
__generated_with = "0.12.10"
app = marimo.App(width="medium")
@app.cell
def _():
return (mo,)
@app.cell
def _():
import time
start = time.perf_counter()
import sklearn
sklearn.__version__
elapsed = time.perf_counter() - start
print(f"Time taken: {elapsed:3f} seconds")
return elapsed, sklearn, start, time
if __name__ == "__main__":
app.run()
```
Then run `marimo edit test.py --sandbox`. I ran this 3 times, cleaning `~/.cache/uv/environments-v2` each time.
| Mode             | Average Installation Time (ms) | Average Compilation Time (ms) | Average Print statement | …
> improve: add --compile and --compile-bytecode flags to uv

- docs/guides/deploying/authentication.md
Fixed a typo
Added a single letter.
> Fix: typo in authentication.md

- marimo/_plugins/ui/_impl/altair_chart.py
> fix: add warning about vegafusion not working with chart selection

- frontend/src/components/editor/app-container.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/issues/4579_mathjax_plotly.py
> fix: add mathjax ignore so code does not get malformed

- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/header-items.tsx
- styling: reduce padding and change icon. fix height in loading and error state
- use Set over list for better perf
- fix select all when there are no options from filtering. 
- fix using `Enter` and click to select rows
> fix: Filter by values styling and selection

- examples/third_party/pyiceberg/data_catalog.py
Example using pyiceberg to connect to a REST-backed iceberg catalog 
Inspired by the walkthrough on [Cloudflare R2 docs](https://developers.cloudflare.com/r2/data-catalog/config-examples/pyiceberg/)
> example: pyiceberg connection

- docs/blocks.py
Add mo cell last if there's a with setup in there
@mscolnick
> fix: block should ad marimo last if there is a setup cell

- marimo/_output/formatters/tqdm_formatters.py
- marimo/_smoke_tests/tqdm_update_test.py
Fixes #4622
Expands support to tqdm by adding update attribute to the marimo patched tqdm
Added update attribute to the tqdm patch so we can use huggingface libraries with marimo and have a nice progressbar rendering.
Video of the solution working:
https://github.com/user-attachments/assets/b0aed94f-f520-472e-930e-419a502c6069
Video of the current version and the error when using update:
https://github.com/user-attachments/assets/5e6925d3-c74e-403d-8e2c-bdafffa7f62c
> feat: extend support to tqdm update()

- frontend/src/components/editor/output/Outputs.css
- marimo/_smoke_tests/issues/4624_markdown_max_width.py
> fix: add more markdown css rules to clamp at desired max-width

- frontend/src/plugins/impl/vega/__tests__/__snapshots__/make-selectable.test.ts.snap
- frontend/src/plugins/impl/vega/__tests__/make-selectable.test.ts
- frontend/src/plugins/impl/vega/make-selectable.ts
- marimo/_smoke_tests/altair/text_selection.py
Fixes #4627
Support `mark_text` selection (which i didn't expect to be a real use-case, but was requested).
> improvement: support mark_text for altair selection

- marimo/_plugins/ui/_impl/altair_chart.py
Noticed a bit of red in ci status
> typechecking: fix ci

- marimo/_server/api/auth.py
- marimo/_server/lsp.py
- pyproject.toml
> fix: remove additional lsp feature-flag check

- frontend/src/components/app-config/app-config-form.tsx
Small edits to section titles.
> tweak: settings menu section titles

- .github/workflows/dev-release.yml
- .github/workflows/marimo-bot.yml
- .github/workflows/playwright.yml
- .github/workflows/release.yml
- .github/workflows/test_cli.yaml
- .github/workflows/test_fe.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- frontend/package.json
- frontend/pnpm-lock.yaml
- lsp/package.json
- openapi/package.json
Ran pnpm self-update and pre-commit autoupdate. These were throwing warnings.
However, I manually changed the typos repo version because it was pointing to a generic version which [pre-commit does not support](https://pre-commit.com/#using-the-latest-version-for-a-repository).
@mscolnick
> chore: upgrade pnpm and pre-commit

- README_Japanese.md
I update README for Japanese
Based on the release notification, I modified the documentation
https://github.com/marimo-team/marimo/pull/4587#issuecomment-2815976436
> docs: update README_Japanese.md with improved links and content clarity

- docs/guides/publishing/cloudflare.md
> docs: fix close admonition

- marimo/_cli/sandbox.py
Broke up construct command to make it more easily called from the plugin
@mscolnick
> tidy: break up the sandbox api for use in quarto

- frontend/src/utils/__tests__/dates.test.ts
- frontend/src/utils/dates.ts
> fix: date rendering resulting in 'Invalid Date'

- tests/_cli/snapshots/marimo_for_jupyter_users.md.txt
- tests/_cli/snapshots/unsafe-doc-old.md.txt
- tests/_cli/snapshots/unsafe-doc.md.txt
There were issues when running tests, this should update the snapshot.
> test: fix snapshots for tests

- docs/guides/state.md
Fixes #4701 
Correct the name of the setter hook in the [Example: tied elements](https://docs.marimo.io/guides/state/#example-tied-elements) 
> docs: fix typo

- marimo/_server/lsp.py
Fixes #4665 
just ignore stderr according to #4665  discussion.
> fix lsp server not work on windows

- frontend/src/components/editor/columns/cell-column.tsx
- frontend/src/components/editor/columns/storage.ts
- frontend/src/css/app/Cell.css
- frontend/src/hooks/__tests__/useResizeHandle.test.tsx
- frontend/src/hooks/useResizeHandle.ts
- frontend/src/utils/localStorage.ts
- bg color on hover
- refactor to hook
> resize touchups

- frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
- frontend/src/core/codemirror/completion/keymap.ts
> fix: esc should always propagate in vim

- marimo/_islands/_island_generator.py
- marimo/_output/formatters/df_formatters.py
- marimo/_output/formatting.py
- marimo/_output/hypertext.py
fixes #4709
Maybe too aggressive with the checks? This seems to work well though with a bit of tweaking on the quarto side.
@mscolnick
> fix: MARIMO_NO_JS is more agressive about formatters

- docs/guides/working_with_data/sql.md
> docs: add ibis backend and list of supported db's

- frontend/src/components/editor/columns/__tests__/storage.test.ts
- frontend/src/components/editor/columns/cell-column.tsx
- frontend/src/components/editor/columns/storage.ts
- frontend/src/hooks/__tests__/useResizeHandle.test.tsx
- frontend/src/hooks/useResizeHandle.ts
- Allows a left handle (which will be used in the future for sidebar)
- Makes the column drag handle slightly thinner
- Prevents element selection underneath (importantt)
@mscolnick
> style: adds left handle & style fixes for resizable component

- frontend/src/core/codemirror/language/__tests__/extension.test.ts
- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/markdown.ts
- frontend/src/plugins/core/RenderHTML.tsx
> fix: more md conversion edge cases

- marimo/_output/formatters/tqdm_formatters.py
- marimo/_smoke_tests/tqdm_update_test.py
- Remove "Loading.." as default title
-  Add support for .close and .write
- Add support for .trange
- Remove "Loading.." as default title. This is more inline with Marimo's progress bar behaviour and tqdm's default behaviour.
- Add support for .close and .write. This allows progress bars to be closed and for the .write tqdm command to work.
https://github.com/user-attachments/assets/a0fc898c-1e3a-4a14-bd79-4b23915fa090
- Add support for .trange
https://github.com/user-attachments/assets/48724ca3-a352-4a57-9a35-2e5ec0a44f9f
- [] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a …
> feat: expand tqdm support

- docs/guides/reusing_functions.md
Fix broken markdown link to overview in reusing_functions.md.
> docs: fix broken link in reusing_functions.md

- marimo/_ast/codegen.py
- tests/_ast/test_codegen.py
> fix: leading whitespace

- frontend/src/components/editor/database/__tests__/__snapshots__/as-code.test.ts.snap
- frontend/src/components/editor/database/__tests__/as-code.test.ts
- frontend/src/components/editor/database/as-code.ts
- frontend/src/components/editor/database/schemas.ts
- marimo/_smoke_tests/sql/ibis_backend.py
> fix: pyspark schema and add example

- frontend/src/components/editor/output/MarimoTracebackOutput.tsx
- frontend/src/components/editor/output/Outputs.css
- marimo/_output/formatters/ipython_formatters.py
- add css underline to traceback links
- remove community forum link (soon to be offline)
> improvement: add css underline to traceback links

- frontend/src/components/debug/indicator.tsx
- frontend/src/components/editor/chrome/wrapper/machine-stats.tsx
- marimo/_server/api/endpoints/health.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_server/api/endpoints/test_health.py
> feat: gpu stats in footer

- frontend/src/__mocks__/tracebacks.ts
- frontend/src/components/editor/output/MarimoTracebackOutput.tsx
- frontend/src/components/editor/output/__tests__/traceback.test.tsx
- frontend/src/core/cells/cell.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/core/codemirror/cells/traceback-decorations.ts
- frontend/src/core/codemirror/utils.ts
- frontend/src/core/state/jotai.ts
- frontend/src/core/state/observable.ts
- frontend/src/css/app/Cell.css
- frontend/src/utils/__tests__/traceback.test.ts
- frontend/src/utils/traceback.ts
> feat: highlight lines when cell has a traceback

- marimo/_ast/load.py
- marimo/_cli/cli.py
Auditing app start up for runtime restructure idea, and noticed some low hanging fruit
@mscolnick
> fix: Do not construct a full app just to check parsing

- marimo/_save/save.py
> fix: mo.cache args for docs

- frontend/src/hooks/__tests__/useResizeHandle.test.tsx
- frontend/src/hooks/useResizeHandle.ts
> fix: default to medium width for columns

- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/context/script_context.py
- marimo/_save/stores/__init__.py
@mscolnick Still compat with pyodide right?
> fix: File level cache settings are not passed to store

- frontend/src/components/editor/columns/cell-column.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/completion/utils.ts
- frontend/src/hooks/__tests__/useResizeHandle.test.tsx
- frontend/src/hooks/useResizeHandle.ts
- frontend/src/utils/id-tree.tsx
I think resizing a column from the left also solves some issues with viewport so it's preferred imo.
The left line is only displayed when hovered. Not sure what the right styles are
> feat: add both left and right resize handlers to a column.

- frontend/src/components/app-config/constants.ts
> fix: update common llm models

- frontend/src/core/codemirror/language/markdown.ts
- frontend/src/core/codemirror/markdown/completions.ts
Cleanup to file, since i plan to make some bigger changes here
> chore: refactor markdown file, pull out completions

- marimo/_sql/engines/ibis.py
- tests/_sql/test_ibis.py
Newer version of ibis has changed the expected datatype response. Also handles some more cases in type conversion.
> fix: ibis data types, from upgrade

- marimo/_runtime/runner/cell_runner.py
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_runtime/side_effect.py
- marimo/_save/hash.py
- marimo/_save/save.py
- tests/_save/test_hash.py
fixes #3876
Issue side effects on cach usage and exceptions
@mscolnick
> fix: Issue side effects to invalidate cache blocks

- frontend/src/components/editor/output/ConsoleOutput.tsx
Only show one `pdb` input. Hide controls on regular `stdin`
> fix: only show one stdin

- frontend/src/core/codemirror/rtc/extension.ts
- frontend/src/core/codemirror/rtc/loro/sync.ts
- frontend/src/utils/Logger.ts
- marimo/_server/api/endpoints/execution.py
- marimo/_server/api/endpoints/health.py
- marimo/_server/rtc/doc.py
* Sync language metadata (markdown prefix, sql dataframe name, sql conection, etc.) between clients. 
* Couple backend fixes when closing
> fix: [rtc] sync language metadata

- marimo/_runtime/marimo_pdb.py
> fix: prevent hanging PDB on interact

- .github/workflows/test_cli.yaml
- frontend/src/components/editor/output/ConsoleOutput.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/components/editor/stdin-blocking-alert.tsx
> improvement: show toast for waiting on stdin

- marimo/_runtime/marimo_pdb.py
- marimo/_server/sessions.py
Still doing a bit of a deep dive into PDB. Worth actually trying to use it and making sure we aren't serving up a broken experience. restart/run failed dramatically- but now actually restart
I think pretty formatting for PDB can be done FE- but like we said probably not worth it just yet.
@mscolnick
> fix: Restart cell in pdb

- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
> fix: narwhals.pyarrow does not support mean/quantile

- docs/examples/index.md
- docs/guides/package_reproducibility.md
- docs/guides/reusing_functions.md
- marimo/_save/save.py
- pixi.lock
> fix: doc errors

- marimo/_ai/llm/_impl.py
The system message was ignored for Gemini; this PR fixes that.
The system message is now passed as an argument to `GenerativeModel`.
In addition, a redundant line has been deleted.
@mscolnick
> Support system message for Gemini

- frontend/src/components/data-table/TableActions.tsx
- frontend/src/components/data-table/data-table.tsx
- frontend/src/components/data-table/row-viewer-panel/__tests__/data-selection.test.tsx
- frontend/src/components/data-table/row-viewer-panel/__tests__/filter-rows.test.ts
- frontend/src/components/data-table/row-viewer-panel/__tests__/row-viewer.test.tsx
- frontend/src/components/data-table/row-viewer-panel/row-viewer.tsx
- frontend/src/components/data-table/row-viewer-panel/use-panel-ownership.ts
- frontend/src/components/editor/chrome/panels/context-aware-panel/atoms.ts
- frontend/src/components/editor/chrome/panels/context-aware-panel/context-aware-panel.tsx
- frontend/src/components/editor/chrome/state.ts
- frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- Change to Row viewer panel
- Adds cell-aware config
- Keyboard shortcuts when element is active
open to name/tooltip suggestions. Context-aware(?), reactive, adaptive
@mscolnick
> feat: updates to row viewer panel

- frontend/src/components/data-table/chart-transforms/storage.ts
- frontend/src/components/editor/chrome/state.ts
- frontend/src/components/editor/columns/storage.ts
- frontend/src/core/wasm/store.ts
- frontend/src/hooks/useLocalStorage.ts
- frontend/src/utils/__tests__/local-storage.test.ts
- frontend/src/utils/localStorage.ts
- Use `key` in FE storage API
- Change charts storage to use `NotebookLocalStorage`
> fix: use keys in fe storage api

- frontend/src/components/chat/chat-panel.tsx
> improvement: add stop button in chat sidebar

- tests/_runtime/test_manage_script_metadata.py
- tests/_runtime/test_patches.py
- tests/_runtime/test_runtime.py
cleanup / simplify patching modules
> tests: cleanup sys.modules patches

- frontend/src/components/data-table/charts/__tests__/spec.test.ts
- frontend/src/components/data-table/charts/chart-spec/encodings.ts
- frontend/src/components/data-table/charts/chart-spec/spec.ts
- frontend/src/components/data-table/charts/chart-spec/tooltips.ts
- frontend/src/components/data-table/charts/components/chart-items.tsx
- frontend/src/components/data-table/charts/components/form-fields.tsx
- frontend/src/components/data-table/charts/constants.ts
- frontend/src/components/data-table/charts/forms/pie.tsx
- frontend/src/components/data-table/charts/types.ts
> feat: add binning to charts

- marimo/_plugins/ui/_impl/tables/pandas_table.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_utils/test_inline_script_metadata.py
Fixes #4883 
I could repro from the code in the issue, but was able to repro in a test. Hopefully this fixes the issue as well.
> fix: to_json for pandas uuid

- frontend/src/components/editor/output/Outputs.css
- frontend/src/plugins/core/RenderHTML.tsx
> fix: code output in markdown

- frontend/src/components/slides/slides-component.tsx
- marimo/_server/api/endpoints/ws.py
- pyproject.toml
- tests/_server/api/endpoints/test_ws_rtc.py
- tests/_server/rtc/test_rtc_doc.py
> fix: gate loro < 3.11

- marimo/_sql/engines/sqlalchemy.py
- marimo/_utils/health.py
- tests/_utils/test_background_task.py
A small patch that would help with: https://github.com/marimo-team/marimo/discussions/4849
> fix: put Inspector in typecheck

- .github/workflows/dev_build.yaml
- frontend/package.json
- frontend/pnpm-lock.yaml
- pixi.lock
- pyproject.toml
- Adds linux-64 to pixi config (was mac only)
- Adds a GH Actions workflow to build frontend & backend using pixi
- Extends max memory allocation for frontend to 4 GB
Pixi is a good idea for providing a more consistent development environment.  Adding linux to the pixi config worked right off the bat.  If the code ever gets to a point where mac and linux need different build dependencies, that is configurable through pixi.
The Github Action required a pixi.lock file. I think it's a good idea to add this anyway so that devs have a reproducible environment. Sometimes lockfiles require a little extra attention to git workflows and maintenance to avoid merge conflicts, but it's worth the tradeoff in my experience (usually just stashing or deleting them when pulling changes works fine).
All of …
> CI build improvements

- marimo/_ast/app.py
- marimo/_save/hash.py
- tests/_save/test_hash.py
@akshayka
should traverse all parents starting from ref definition.
> fix: Fix execution hash regression 

- frontend/src/plugins/impl/common/labeled.tsx
> fix: checkbox width

- frontend/src/core/codemirror/cells/traceback-decorations.ts
> fix: show update when error decorations change

- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- marimo/_smoke_tests/issues/3564_altair_timezone.py
> fix: checkbox width fix: altair timestamp on pandas

- docs/faq.md
Update faq.md; Functions/classes now importable
Update faq.md; Functions/classes now importable
> Update faq.md; Functions/classes now importable

- frontend/src/components/data-table/columns.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
I broke max_columns in https://github.com/marimo-team/marimo/pull/4899 (it wouldn't change the number of field types shown if you change it).
I'm also happy to revert the old PR if this seems hacky.
@mscolnick
> fix: max_columns in tables

- frontend/src/components/slides/slides-component.tsx
- frontend/src/components/slides/slides.css
> fix: slides css for better centering of content

- docs/guides/editor_features/watching.md
Fixes just a couple of small things.
> docs: minor fix to types and autocompletion docs

- docs/api/query_params.md
- docs/guides/deploying/programmatically.md
Small example that shows how to use query parameters with pydantic models, building on what I learned [here](https://github.com/marimo-team/marimo/issues/4878).
https://marimo.app/?g=255&slug=03egkc
- [ x] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ x] I have added tests for the changes made.
- [ x] I have run the code and verified that it works as expected.
> Documentation: pydantic model for query params

- examples/running_as_a_script/textual_app.py
Went to a talk from one of the former textual devs, was happy to see it "just runs"
https://github.com/textualize/textual/
`python textual_app.py`
(still editable with `uvx marimo edit --sandbox textual_app.py`)
@koaning
> example: building a textual app in marimo

- marimo/_output/formatters/altair_formatters.py
- marimo/_plugins/ui/_impl/altair_chart.py
> fix: add alt.LayeredChart to types

- marimo/_server/export/__init__.py
- marimo/_smoke_tests/scripts/logging_in_scripts.py
- tests/_server/export/snapshots/run_until_completion_with_console_output.txt
- tests/_server/export/test_exporter.py
> improvement: print logs when running 'marimo export'

- frontend/src/components/editor/file-tree/types.ts
- frontend/src/components/pages/home-page.tsx
- marimo/_server/file_router.py
Show .qmd files identically to markdown
> fix: Show .qmd files in editor home

- frontend/src/components/data-table/download-actions.tsx
- frontend/src/utils/__tests__/json-parser.test.ts
- frontend/src/utils/json/json-parser.ts
Closes #4991 
Copy table in various way, mainly to copy into excel or google sheets
> feat: copy table values to clipboard, for Excel/Sheets

- marimo/_output/formatters/altair_formatters.py
- marimo/_plugins/core/json_encoder.py
- marimo/_smoke_tests/primitives/_decimal.py
- tests/_plugins/core/test_json_encoder.py
> fix: handle decimal in json serialization

- marimo/_convert/ipynb.py
- tests/_convert/test_ipynb.py
Fixes #5017
See #5017
Test written but not executed
> Fix duplicate `import marimo as mo` in .ipynb conversion.

- marimo/_convert/ipynb.py
- tests/_convert/test_ipynb.py
Another edge case for #5019: 
- inside comments
- inside def
> fix: couple more edge cases for Fix duplicate `import marimo as mo`

- marimo/_output/formatters/altair_formatters.py
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/altair/nested_vconcat.py
- tests/_plugins/ui/_impl/test_altair_chart.py
> fix: set width on nested vconcat charts

- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- tests/_output/formatters/test_altair_formatters.py
> fix: sanitize nan-infs for numeric cols only

- README.md
- docs/index.md
* Update readme and docs landing page to reflect our support for data warehouses and data lakes
* Highlight top-level functions
* Reorganize highlights
> docs: mention data warehouses, data lakes

- marimo/_data/get_datasets.py
Queries for db_names. SHOW ALL DATABASES doesn't work for local + motherduck.
Difficult to add tests without mocking a lot, as local duckdb doesn't support creating a db.
@mscolnick
> fix: inspect empty db's for duckdb

- .github/workflows/dev_build.yaml
- CONTRIBUTING.md
- frontend/src/components/data-table/charts/__tests__/renderer.test.ts
- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/filter-pills.tsx
- frontend/src/components/data-table/header-items.tsx
- frontend/src/components/data-table/renderers.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_plugins/ui/_impl/dataframes/transforms/handlers.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_utils/hashable.py
- pyproject.toml
- tests/_plugins/ui/_impl/dataframes/test_handlers.py
- tests/_plugins/ui/_impl/tables/test_ibis_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
This fixes a few things:
- table wasn't getting updated when totalRows were updated
- display issues with objects
- able to filter nested lists & dicts (but we don't enable this yet)
- update polars version
TODO: refactor the code
@mscolnick
> fixes: enable nested list & dict filtering, better display of filters

- examples/sql/misc/database_explorer.py
Just a quick refresh
but related: #4785
Since it seems return values can point to undefined variables on table creation
@mscolnick
> fix: broken example discovered during bug bash

- .github/workflows/test_cli.yaml
- lsp/index.ts
- scripts/buildlsp.sh
- scripts/test-lsp.sh
GH Copilot path was missing `dist`
> fix: copilot path

- docs/api/inputs/dataframe.md
Update current list of transforms listed for `mo.ui.dataframe`; add request transforms link listed in our dataframe UI in docs.
Update [`dataframe.md`](https://github.com/marimo-team/marimo/blob/main/docs/api/inputs/dataframe.md) with updated list of transformations supported w/ `mo.ui.transform` & add mkdocs themed info for requesting one from docs.
> docs: update `dataframe.md` to include new transforms and request feature link

- marimo/_plugins/ui/_impl/input.py
- tests/_plugins/ui/_impl/test_input.py
> improvement: allow mo.ui.dropdown more than 1000 items

- docs/guides/package_management/using_uv.md
Prefer uv run over manually activating the environment.
> docs: simplify uv guide

- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/core/codemirror/language/extension.ts
Fixes #5088. If we keep code as is, then it doesn't get wrapped in `mo.md` or `mo.sql`.
I may be missing something obvious or something regressed recently..
> fix: convert to markdown & sql

- frontend/src/core/ai/state.ts
Added local ai chat history persistence between sessions.
Resolves #4157 by implementing deeper persistence.
https://github.com/user-attachments/assets/3c973fb5-b2eb-4c8e-a7c7-3233fa412cc0
- Imported atomWithStorage
- Created a KEY value for chatState
- Changed chatStateAtom to point at atomWithStorage (with KEY as the key) rather than atom
@mscolnick
> feat: add ai chat persistence between sessions

- frontend/src/components/datasources/datasources.tsx
- marimo/_dependencies/dependencies.py
- marimo/_smoke_tests/sql/redshift_example.py
- marimo/_sql/engines/clickhouse.py
- marimo/_sql/engines/dbapi.py
- marimo/_sql/engines/doc.md
- marimo/_sql/engines/duckdb.py
- marimo/_sql/engines/ibis.py
- marimo/_sql/engines/pyiceberg.py
- marimo/_sql/engines/redshift.py
- marimo/_sql/engines/sqlalchemy.py
- marimo/_sql/engines/types.py
- marimo/_sql/get_engines.py
- marimo/_sql/sql.py
- marimo/_sql/utils.py
- pyproject.toml
- tests/_sql/test_engines.py
- tests/_sql/test_get_engines.py
- tests/_sql/test_redshift.py
Will clean up some stuff like converting to polars and errors, in follow up PRs.
> feat: add redshift engine

- .github/workflows/marimo-bot.yml
- SECURITY.md
- pyproject.toml
Create general security policy and attribution section (thanks @AlexanderBarabanov @pwntester @s-celles)
> security: Create policy and thank previous reporters

- frontend/src/core/cells/__tests__/ids.test.ts
- frontend/src/core/cells/ids.ts
- marimo/_ast/cell_manager.py
- tests/_ast/test_cell_manager.py
Fixes #1962
Technically #1962 was already fixed on the backend (but now in cases someone creates 750 on the frontend in one session)
> fix: add cell ids to deserialize

- .github/workflows/dev-release.yml
Publish dev releases to test-pypi on main
> chore: publish dev to test-pypi

- .github/workflows/dev-release.yml
> fix: CI pass

- frontend/src/components/editor/chrome/wrapper/footer-items/machine-stats.tsx
- frontend/src/components/pages/run-page.tsx
- frontend/src/components/static-html/static-banner.tsx
> fix: inline favicon

- frontend/src/components/terminal/terminal.tsx
> chore: add suspense for terminal

- docs/guides/understanding_errors/cycles.md
- docs/guides/understanding_errors/import_star.md
- docs/guides/understanding_errors/index.md
- docs/guides/understanding_errors/multiple_definitions.md
- docs/guides/working_with_data/sql.md
After reading the marimo docs, I realized that there were inconsistencies in some of the rendering formats due to  small typos in the .md docs. 
I rearranged some .md files and fix some typos for readability and consistency.
- [] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [] I have added tests for the changes made.
@akshayka
> Modify docs for readability and consistency

- frontend/src/core/runtime/__tests__/createWsUrl.test.ts
- frontend/src/core/runtime/runtime.ts
Runtime separation is currently broken. There may be a better fix, but pushing through such that head is fixed
> fix: home edit mode with separated backend

- frontend/src/components/app-config/constants.ts
Updated the model list to reflect newer more capable models. Removed deprecated models.
- Updated openai models to include o4-mini, o3 and 4.1 variants
- Updated anthropic models to include the proper syntax for claude 4 sonnet and opus
- Updated gemini to correctly point to the 2.5 reasoning models
- Sorted all models from strongest to weakest
@mscolnick
> chore: update ai model list

- marimo/_ai/_convert.py
- marimo/_dependencies/dependencies.py
- marimo/_server/ai/providers.py
- pyproject.toml
- tests/_ai/test_chat_convert.py
- tests/_server/api/endpoints/test_ai.py
Upgraded the backend GoogleProvider implementation to use google-genai python sdk because:
- Enables using the latest google models
- Supports reasoning and reasoning tokens
- google-generativeai sdk has been [deprecated](https://github.com/google-gemini/deprecated-generative-ai-js)
- Updated GoogleProvider and imports to use google-genai and send back reasoning tokens in providers.py
- Updated all google tests to use google-genai sdk instead in test_ai.py
- Added google-genai to extra dependencies for tests in pyproject.toml
- Updated convert_to_google_messages in _convert.py
- Added google_ai_new to DependencyManager in dependencies.py
@mscolnick
> chore: upgrade ai backend from google-generativeai (deprecated) -> google-genai

- marimo/_plugins/ui/_impl/table.py
- marimo/_utils/uv.py
- tests/_plugins/ui/_impl/test_table.py
> fix: table cell styles index error

- frontend/src/components/data-table/column-explorer-panel/column-explorer.tsx
- frontend/src/components/data-table/pagination.tsx
- frontend/src/components/ui/number-field.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/forms/__tests__/__snapshots__/form.test.tsx.snap
- Select input to change page size of tables (this doesn't persist on refresh)
- added a xs variant to number field
- small style refactor for col explorer
> feat: change page size in tables directly

- frontend/src/core/runtime/__tests__/runtime.test.ts
- frontend/src/core/runtime/runtime.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
- frontend/src/core/websocket/useWebSocket.tsx
- frontend/vitest.config.ts
> fix: graceully handle other url protocols

- frontend/src/components/datasets/icons.tsx
- frontend/src/components/datasources/components.tsx
- marimo/_data/charts.py
- marimo/_utils/theme.py
- tests/_data/snapshots/charts-complex.txt
- tests/_data/snapshots/charts_json.txt
- tests/_data/snapshots/charts_json_bad_data.txt
- tests/_data/snapshots/column_preview_categorical_chart_spec.txt
- tests/_data/snapshots/column_preview_str_chart_spec.txt
Styles were not contrasty for dark mode, this fixes that.
@mscolnick
> style: datasource icons dark mode

- .github/workflows/test_be.yaml
- .github/workflows/test_be_dagger.yaml.skip
- biome.jsonc
- frontend/lint/addEventListenerObject.grit
- frontend/lint/removeEventListenerObject.grit
- frontend/src/core/codemirror/readonly/extension.ts
Add some lint rules using gritql + biome
> chore: add biome lint for addEventListener

- frontend/src/components/data-table/renderers.tsx
since we disabled the feature, we should remove it completely.
@mscolnick
> fix: remove select-none, which prevented select on tables

- README.md
- docs/getting_started/quickstart.md
- docs/index.md
- docs/reading.md
- mkdocs.yml
Add a readings and videos tab on our docs that links to key YouTube videos and readings about marimo.
Also add mentions of the marimo concepts playlist to our readme, docs homepage, and quickstart.
> docs: readings and videos

- marimo/_schemas/generated/session.yaml
- openapi/src/session.ts
- scripts/generate_schemas.py
Generate schemas for the patch in #5377
> mo 3226 generate schemas

- marimo/_server/export/__init__.py
- marimo/_server/export/exporter.py
- marimo/_server/session/serialize.py
- marimo/_server/session/session_view.py
Looks like there are 2 issues in #3226 
- [] 2. The first cell is dropped.
Unsure why 2 occurs, but might be fixed with 1. Have not tested
Feel free to hack on this in the meantime. Will be back online at ~2
fixes #3226
> fix: Serialization fix

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/chat/chat-panel.tsx
- frontend/src/core/islands/bridge.ts
- frontend/src/core/network/requests-network.ts
- frontend/src/core/network/requests-static.ts
- frontend/src/core/network/requests-toasting.ts
- frontend/src/core/network/requests.ts
- frontend/src/core/network/types.ts
- frontend/src/core/wasm/bridge.ts
- marimo/_ai/_types.py
- marimo/_cli/development/commands.py
- marimo/_plugins/ui/_impl/chat/utils.py
- marimo/_server/ai/backend_tools/__init__.py
- marimo/_server/ai/backend_tools/sample_tool.py
- marimo/_server/ai/providers.py
- marimo/_server/ai/tools.py
- marimo/_server/api/endpoints/ai.py
- marimo/_server/models/models.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_ai/test_chat_convert.py
- tests/_server/api/endpoints/test_ai.py
Created /invoke_tool endpoint to handle backend/mcp tools for chat-panel. Added it to the frontend requests handlers. Also added ToolManager to handle all tool related logic in the backend along with a sample backend tool as a guide.
- Added ToolManager to tools.py
- Added backend_tools folder with sample backend tool
- Added /invoke_tool endpoint to ai.py
- Added types for /invoke_tool to _types.py. 
- Added ChatMessage parts types and factory function for handling the incoming parts (reasoning, tool call, tool result) to _types.py
- Added throwNotImplemented for anything outside of full application in editor mode
- Added invokeAiUrl types from marimo api
- Implemented invokeAiUrl in requests-network.ts and exported it in requests.ts
- Updated onToolCall to use invokeAiUrl, commented out …
> feat: add tool manager and create invoke-tool endpoint

- marimo/__init__.py
> release: 0.14.7

- frontend/src/components/data-table/column-explorer-panel/column-explorer.tsx
- frontend/src/components/datasources/__tests__/install-package-button.test.tsx
- frontend/src/components/datasources/column-preview.tsx
- frontend/src/components/datasources/install-package-button.tsx
- frontend/src/components/editor/chrome/panels/packages-panel.tsx
- frontend/src/core/packages/toast-components.tsx
- frontend/src/core/packages/useInstallPackage.ts
Just a refactor to install packages with one-click rather than opening the sidebar to install them.
@manzt
> improvement: install packages directly

- marimo/_runtime/capture.py
Noticed an issue in the online documentation, fixed the indentation.
@akshayka
> Fix markdown indentation

- marimo/_cli/file_path.py
Supports various link formats
@akshayka
> chore: Expand remote downloads for a broader range of urls

- frontend/src/components/editor/header/filename-form.tsx
"untitled marimo notebook", not app
> chore: update filename form placeholder text

- frontend/src/components/tracing/tracing-spec.ts
- frontend/src/components/tracing/tracing.tsx
Fixes #5454 .
Also reduce the step size, seems text got adjusted again.
> fix: tracing panel - sort queued cells to bottom

- marimo/_runtime/packages/module_name_to_pypi_name.py
Feels more likely that folks are interested in the new llm library as opposed to the other project that didn't get an update since 2017.
> add lilypad

- lsp/package.json
- lsp/pnpm-lock.yaml
As mentioned in #5427, add `biome` as a dev dependency. I am following the same version and pin strategy as in the root `package.json`. Eventually, we should consider using workspaces.
@mscolnick (General, AI)
@manzt (Widgets, Dependency Management, LSP)
// cc: @nojaf
> chore: add biome as a dev dependency

- marimo/_server/main.py
Leftover clean up from #5427
We no longer depend on the WebSocket LSP path to differentiate between LSPs.
@mscolnick (General, AI)
@manzt (Widgets, Dependency Management, LSP)
// cc: @nojaf
> refactor: remove redundant path rewrite

- frontend/src/hooks/useAsyncData.ts
Add some documentation to `useAsyncData`. I created a base interface so the docs get carried over to the specific result case
> chore: add js docs to useAsyncData

- .github/workflows/test_be.yaml
- frontend/.eslintrc.cjs
- frontend/e2e-tests/global-setup.ts
- frontend/e2e-tests/global-teardown.ts
- frontend/e2e-tests/helper.ts
- frontend/e2e-tests/py/bad_button.py
- frontend/e2e-tests/py/bugs.py
- frontend/e2e-tests/py/cells.py
- frontend/e2e-tests/py/components.py
- frontend/e2e-tests/py/disabled_cells.py
- frontend/e2e-tests/py/kitchen_sink.py
- frontend/e2e-tests/py/layout_grid.py
- frontend/e2e-tests/py/layout_grid_max_width.py
- frontend/e2e-tests/py/output.py
- frontend/e2e-tests/py/shutdown.py
- frontend/e2e-tests/py/stdin.py
- frontend/e2e-tests/py/streams.py
- frontend/e2e-tests/py/title.py
- frontend/e2e-tests/shutdown.spec.ts
- frontend/e2e-tests/test-utils.ts
- frontend/e2e-tests/tsconfig.json
- frontend/playwright.config.ts
- frontend/tsconfig.json
- marimo/_server/session/serialize.py
- tests/_server/api/endpoints/test_files.py
- tests/_server/test_file_manager.py
Refactors and configuration improvements to playright to get it passing again.
* Also skips the flakey e2e test, but adds a new one that tests the same functionality
> tests: get playwright running again

- frontend/src/components/editor/ai/ai-completion-editor.tsx
- frontend/src/utils/__tests__/timeout.test.ts
- frontend/src/utils/timeout.ts
Just a small improvement for the function you created. Feel free to ignore this
> improve: add tests and initial delay for retry with timeout

- frontend/src/components/data-table/range-focus/use-scroll-into-view.ts
Imo, it feels less jarring
https://github.com/user-attachments/assets/34149fc5-6750-4c48-995f-6e6702a63f04
> style: set `scrollToView` to smooth

- marimo/_runtime/patches.py
- tests/_pyodide/test_pyodide_session.py
> fix: use pyodide_http.patch_all

- marimo/_ast/transformers.py
- tests/_ast/test_transformers.py
Added some unit testing around `marimo/_ast/transformers.py`, notably fixing / adding a check for a try block in WithSkip cases.
fixes #5638
> tests: additional unit tests for `test_transformers.py` and fix edge cases

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/data-table/__tests__/__snapshots__/chart-spec-model.test.ts.snap
- frontend/src/components/data-table/__tests__/chart-spec-model.test.ts
- frontend/src/components/data-table/chart-spec-model.tsx
- frontend/src/components/data-table/types.ts
- frontend/src/core/config/feature-flag.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_data/models.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/ibis_table.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- tests/_plugins/ui/_impl/tables/test_ibis_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/test_table.py
https://github.com/user-attachments/assets/f1a2d15d-63c8-48c2-8098-84abb1c0f8bf
> improvement: use backend binning for numeric columns

- docs/guides/editor_features/overview.md
Adds documentation about our recent command mode (and vim bindings)
> Add Command Mode documentation

- marimo/_plugins/ui/_impl/tables/ibis_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_smoke_tests/third_party/pandas/transform_edgecases.py
Convert geopandas back to pandas when rendering in a dataframe or table (to support all the table features)
Fixes #5447
> fix: better support for geopandas in mo.ui.dataframe and table

- marimo/_data/get_datasets.py
- tests/_data/test_get_datasets.py
Fixes #5698 . Adds more time types.
> fix: add more time types for duckdb

- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/dataframes/transforms/print_code.py
- tests/_plugins/ui/_impl/dataframes/test_print_code.py
Fixes #5755 . Updates the columns in place so it will affect subsequent transformations.
Also fixes aggregate function code.
> fix: change columns in place and add tests

- .github/workflows/test_cli.yaml
this test does nothing and is now causing errors
> chore: remove tests examples

- docs/api/inputs/file.md
- marimo/_plugins/ui/_impl/input.py
Fix #5673 
Update documentation for more clarity:
- Accessing upload file's contents/name
- Docstring example updates (with UI element var name as last expression in cell block to render - help resolve ambiguity for some folks on how to store, render and access info).
> docs: fix file upload docs

- pyproject.toml
- tests/_pyodide/test_bootstrap.py
Typcheck broke with 2 conflicting merging PRs
> ci: fix typecheck

- marimo/_tutorials/markdown.py
- marimo/_tutorials/sql.py
- tests/_convert/snapshots/sql.md.txt
Fixing two errors that stuck out to me while reading tutorials.
- mention `polars` dataframes
- fix a typo
I have read the CLA Document and I hereby sign the CLA.
> Two tiny fixes to tutorial text.

- frontend/src/core/wasm/utils.ts
> fix flaky wasm test

- marimo/_sql/engines/sqlalchemy.py
- marimo/_sql/sql.py
- tests/_sql/test_sqlalchemy.py
> fix: check for missing cursor for sqlalchemy native output

- frontend/src/components/editor/ai/ai-completion-editor.tsx
- marimo/_server/ai/prompts.py
- tests/_server/ai/snapshots/system_prompts.txt
No evals, just vibes. This does better than previously (tested on gpt-4o).
Somewhere claude recommended for important rules to include them in the bottom as well.
> ai: improve prompt to not comment on the code

- frontend/src/components/data-table/row-viewer-panel/row-viewer.tsx
> fix: use break-word in row-viewer panel

- frontend/src/core/wasm/utils.ts
> test: check document safely in CI

- marimo/_ast/app.py
- marimo/_ast/cell_id.py
- marimo/_ast/cell_manager.py
- marimo/_save/save.py
- tests/_save/external_decorators/app.py
- tests/_save/test_external_decorators.py
Adds tests to ensure caching works on app embed. Cherrypicked out of #5873 because the solution for checking for a long ID seemed a bit hacky, and I figured the tests were worth isolating. Closes #5312
> fix: allow caching on embedded apps

- frontend/src/core/ai/context/providers/__tests__/__snapshots__/tables.test.ts.snap
- frontend/src/core/ai/context/providers/__tests__/__snapshots__/variable.test.ts.snap
Follow up to #5997. Just runs:
```sh
pnpm test -u
```
> Clear out dead code snapshots

- docs/guides/editor_features/ai_completion.md
This PR addresses the 404 error when configuring Ollama with marimo's AI assistant by adding a clear warning about the required `/v1` endpoint. 
**Fixes #5986**
Users encounter 404 "page not found" errors when using Ollama with marimo's AI assistant, as reported in issue #5986. This occurs because:
- Ollama provides two API endpoints: native (`http://localhost:11434/`) and OpenAI-compatible (`http://localhost:11434/v1`)
- marimo requires the OpenAI-compatible `/v1` endpoint, but this wasn't clearly emphasized in the documentation
- Users may configure `base_url = "http://127.0.0.1:11434"` instead of the correct `base_url = "http://127.0.0.1:11434/v1"`
Added a prominent warning notice in the Ollama setup section of `docs/guides/ai_completion.md` that:
- **Clearly states the `/v1` endpoint …
> docs(ai): Add warning about Ollama /v1 endpoint to prevent 404 errors

- frontend/src/components/editor/ai/add-cell-with-ai.tsx
> add send button for 'Generate with AI'

- .github/actions/install/action.yaml
- .github/workflows/test_fe.yaml
Last run was around ` 8m 24s`. This should reduce the longest run to `4min`.
> ci: split up frontend CI

- marimo/_data/get_datasets.py
- tests/_data/test_get_datasets.py
> check for array types better in duckdb

- frontend/src/components/app-config/ai-config.tsx
> show configured tag when AI provider is configured

- frontend/src/components/slides/slides.css
- frontend/src/core/cells/cells.ts
- frontend/src/plugins/layout/carousel/CarouselPlugin.tsx
Fix null pointer exception when RTC is enabled.
> fix: rtc null pointer

- frontend/src/components/ai/ai-model-dropdown.tsx
- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/ai/ai-completion-editor.tsx
- frontend/src/core/ai/config.ts
- frontend/src/core/config/config-schema.ts
- frontend/src/plugins/impl/chat/chat-ui.tsx
> add AI model dropdown for "Generate with AI"

- frontend/src/core/runtime/config.ts
Health check in static notebooks is blocking and invalid
> fix: Don't do health check in static notebooks

- frontend/src/components/editor/navigation/__tests__/navigation.test.ts
This is mostly for sanity, I saw mocks being set up but not being cleared after the test. Since it's global mocks (`vi.mock` would be better to clean it up)
> clear all mocks for test

- frontend/src/components/editor/chrome/panels/outline-panel.tsx
- frontend/src/components/editor/chrome/panels/outline/useActiveOutline.tsx
Maybe an automated code migration caused this regression
> fix: No outline-solid -> No outline found

- marimo/_server/ai/tools.py
Fix the feature-flag name that enables tools
> preview: fix tools feature flag name

- frontend/src/components/app-config/ai-config.tsx
- frontend/src/components/chat/chat-panel.tsx
This is still internal and not exposed to user's yet
> improvement: cleanup docs on mode dropdown

- marimo/_server/ai/config.py
- tests/_server/ai/test_ai_config.py
- tests/_server/api/endpoints/test_ai.py
More lenient AI config for things that don't require configuration, like `ollama`
> improvement: more lenient AI config, and more descriptive error

- frontend/src/components/datasources/datasources.tsx
- frontend/src/core/datasets/engines.ts
- marimo/_data/get_datasets.py
- tests/_data/test_get_datasets.py
- tests/_sql/test_duckdb.py
- tests/_sql/test_get_engines.py
> Show empty databases, but only for defined duckdb connections

- docs/guides/editor_features/ai_completion.md
The bullet list does not show unless there is a newline.
> Minor fix to docs: show bullet list. 

- frontend/src/core/config/feature-flag.tsx
- marimo/_cli/development/commands.py
- marimo/_cli/envinfo.py
- marimo/_config/config.py
- marimo/_config/manager.py
- marimo/_runtime/runtime.py
- marimo/_runtime/threads.py
- marimo/_save/stores/__init__.py
- packages/openapi/api.yaml
- packages/openapi/src/api.ts
- tests/_server/api/endpoints/test_ws.py
Should prevent wrong flag names use.
> strongly type backend experimental flag

- marimo/_cli/upgrade.py
- marimo/_config/cli_state.py
- marimo/_config/utils.py
- marimo/_loggers.py
- marimo/_server/recents.py
- marimo/_tracer.py
- marimo/_utils/config/config.py
- marimo/_utils/xdg.py
- tests/_cli/test_cli.py
- tests/_cli/test_upgrade.py
- tests/_config/test_config_utils.py
- tests/_utils/config/test_config_reader.py
- tests/_utils/test_xdg.py
Follow-up and consolidation after #6048
> cleanup: xdg config commons and migrate utils to use Path

- frontend/src/theme/useTheme.ts
Allows for VsCode to control light/dark mode.
> Set observer for VsCode theme in `useTheme`

- marimo/_config/config.py
- marimo/_config/manager.py
- packages/openapi/api.yaml
- packages/openapi/src/api.ts
- tests/_utils/test_parse_dataclass.py
> loosen typings for experimental config on the backend

- marimo/_sql/engines/ibis.py
- marimo/_sql/get_engines.py
- tests/_sql/test_get_engines.py
> more try catches for datasource introspection

- marimo/_runtime/runtime.py
Mitigates #6179 by only running top level function analysis in edit mode. A bit worrying they also noticed a performance issue, but this is a reasonable stopgap
> fix: turn off toplevel function post hook in run mode

- marimo/_config/secrets.py
- tests/_config/test_secrets_config.py
Better future-proofing to mask secrets in AI config
> improvement: use * wildcard for matching secret path

- marimo/_server/api/endpoints/health.py
Doesn't need to be async. Starlette will put this in another thread
> make health check non-async

- pyproject.toml
fixes #6195 addressing package breaking issues
> fix: bump-websockets

- frontend/src/__tests__/chat-utils.test.ts
- frontend/src/components/chat/chat-components.tsx
- frontend/src/components/chat/chat-panel.tsx
- frontend/src/core/ai/chat-utils.ts
- frontend/src/core/ai/state.ts
- frontend/src/core/ai/types.ts
- frontend/src/plugins/impl/MicrophonePlugin.tsx
- frontend/src/plugins/impl/chat/chat-ui.tsx
- frontend/src/plugins/impl/chat/types.ts
- frontend/src/utils/__tests__/blob.test.ts
- frontend/src/utils/fileToBase64.ts
- marimo/_ai/_convert.py
- tests/_ai/test_chat_convert.py
https://github.com/user-attachments/assets/48c73b4b-01a3-4eed-be77-12cbf6448dd9
Currently only supports images (haven't checked all types) and text. I have also restricted it to openai, because the backend might need work.
> attachments in chat sidebar

- marimo/_server/api/endpoints/health.py
On a machine where the `nvidia-smi` command exists, but it's execution fails for whatever reason (it cannot communicate with the driver, for example), marimo's console logs are spammed with
`[W 250830 16:25:58 health:265] Failed to extract GPU stats: Command '['nvidia-smi', '--query-gpu=index,name,memory.total,memory.used,memory.free', '--format=csv,noheader,nounits']' returned non-zero exit status 9`
This commit add a check further up the line, so that the warning is displayed on the console only once.
I added a simple invocation of `nvidia-smi` to an already existing function which just used to check for the existence of the binary. If the invocation fails for whatever reason, the warning to the console is only printed once (because the result of the function is cached)
> If the gpu stats command fails, don't run it again on every usage check

- marimo/_ast/visitor.py
- marimo/_runtime/dataflow.py
- tests/_ast/test_visitor.py
- tests/_runtime/test_dataflow.py
> sql cells can't both define and refer to itself

- frontend/package.json
- frontend/src/__tests__/chat-utils.test.ts
- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/chat/chat-utils.ts
- frontend/src/components/chat/tool-call-accordion.tsx
- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/core/ai/chat-utils.ts
- frontend/src/core/ai/state.ts
- frontend/src/plugins/impl/chat/chat-ui.tsx
- frontend/src/plugins/impl/chat/types.ts
- marimo/_ai/_convert.py
- marimo/_ai/_types.py
- marimo/_plugins/ui/_impl/chat/utils.py
- marimo/_server/ai/providers.py
- marimo/_server/api/endpoints/ai.py
- pnpm-lock.yaml
- tests/_ai/test_chat_convert.py
> Upgrade AI sdk to v5

- marimo/_pyodide/pyodide_session.py
This is a temporary fix. `msgspec` only supports discriminated unions, so we need to eagerly parse each variant.
> Eagerly parse `ControlRequest` in pyodide bridge

- frontend/src/components/editor/alerts/startup-logs-alert.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/alerts/state.ts
- frontend/src/core/islands/main.ts
- frontend/src/core/kernel/messages.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
- marimo/_cli/cli.py
- marimo/_messaging/ops.py
- marimo/_server/session/session_view.py
- marimo/_server/start.py
- packages/openapi/api.yaml
- packages/openapi/src/api.ts
- tests/_cli/test_parse_args.py
- tests/_messaging/test_ops.py
- tests/_server/session/test_session_view.py
`--server-startup-command` flag to run a command on startup (non-blocking) and stream to any open sessions. if the command is finished, it will never be shown.
> preview: add `--server-startup-command`

- frontend/src/core/ai/context/providers/__tests__/cell-output.test.ts
- tests/_data/test_charts.py
- tests/_data/test_preview_column.py
Some contributors were facing locally failing tests, this fixes tests related to snapshots for charts being inconsistent across themes.
> mock theme for test

- .github/workflows/docs.yml
- docs/_static/CLAUDE.md
- docs/guides/generate_with_ai/prompts.md
- docs/vercel.json
- mkdocs.yml
Pull out the claude code so 1) its easier to write as a standalone doc, and 2) can grab it easily with 
```
curl https://docs.marimo.io/_static/CLAUDE.md > CLAUDE.md
```
> docs: move claude md to snippets

- marimo/_ai/_tools/base.py
- marimo/_server/ai/providers.py
- marimo/_server/ai/tools/tool_manager.py
- marimo/_utils/once.py
- tests/_ai/tools/test_base.py
- tests/_ai/tools/tools/test_cells.py
- tests/_ai/tools/tools/test_notebooks.py
- tests/_server/ai/tools/test_tool_manager.py
- tests/_utils/test_once.py
Lazier initialization of tools only until needed.
Also adds:
- `@once` decorator
- tests for `ToolManager`
- increase completions timeout to 30s (from 15s)
> improvement: lazyer initialization of tools

- marimo/_utils/parse_dataclass.py
- tests/_utils/test_parse_dataclass.py
fix: handle nested msgspec parsing
> fix: handle nested msgspec parsing

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/ai/completion-handlers.tsx
- frontend/src/components/editor/cell/StagedAICell.tsx
- frontend/src/css/app/Cell.css
> styles: change styles for staged AI cells

- frontend/package.json
- frontend/src/components/chat/acp/agent-panel.css
- frontend/src/components/chat/acp/blocks.tsx
- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/chat/markdown-renderer.css
- frontend/src/components/chat/markdown-renderer.tsx
- frontend/src/components/chat/tool-call-accordion.tsx
- pnpm-lock.yaml
Styling for tool calls. Move to streamdown (shared with the agent panel)
> styles: tool calls styling and streamdown

- frontend/src/plugins/core/RenderHTML.tsx
- frontend/src/plugins/core/__test__/RenderHTML.test.ts
> fix: remove body tags when rendering custom HTML

- docs/guides/editor_features/agents.md
- docs/guides/editor_features/ai_completion.md
- frontend/src/components/app-config/user-config-form.tsx
- mkdocs.yml
This adds docs for the new agents. Will wait to merge just before the release
> docs: Agents docs and feature flag

- pyproject.toml
- tests/_cli/test_file_path.py
- tests/_server/api/endpoints/test_files.py
- tests/_server/test_file_manager_filename.py
- tests/_server/test_templates_filename.py
- tests/_server/test_utils_filename.py
- tests/_utils/test_marimo_path.py
- tests/mocks.py
some tests to validate weird filenames do work
> tests: tests for edge case file names

- frontend/src/core/codemirror/language/languages/sql/sql.ts
- marimo/_runtime/runtime.py
- marimo/_sql/engines/types.py
- marimo/_sql/parse.py
- tests/_runtime/test_runtime_datasets.py
- tests/_sql/test_sql_parse.py
Uses get_connection_for_sql (so we catch DBAPI and other queryEngines).
Adds kernel tests for this codepath.
Update parse tests introduced by Myles, but note that they aren't correct (many queries do not raise ParseErrors by duckdb)
> fix test and add improvements from sql mode PR

- frontend/src/core/codemirror/language/languages/sql/sql.ts
- marimo/_config/config.py
- marimo/_runtime/runtime.py
- marimo/_sql/engines/types.py
- pyproject.toml
- tests/_runtime/test_runtime_datasets.py
- tests/_sql/test_engines.py
- remove parsing for not only_parse
- enable extension internally
- quote the query
> re-enable sql-mode internally

- marimo/_runtime/runner/cell_runner.py
- tests/_runtime/runner/test_cell_runner.py
This hides the traceback for SQL since it is confusing to show python code
> improvement: dont show python traceback for sql errors

- frontend/src/core/codemirror/__tests__/format.test.ts
- frontend/src/core/config/feature-flag.tsx
We can turn this on by default to get more feedback.
> Turns on sql_linter to true by default

- frontend/src/plugins/impl/DataTablePlugin.tsx
This breaks when you do sort/filter
> fix: data-table cellHoverTextSchema validation

- marimo/_cli/upgrade.py
- marimo/_config/cli_state.py
- marimo/_server/api/endpoints/ws.py
Provides mechanism to provide updates and news
> feat: news and notices

- .coveragerc
Had staged, just wanted to push and see
> [ci] testmon

- frontend/src/components/chat/acp/__tests__/context-utils.test.ts
- frontend/src/components/chat/acp/agent-panel.tsx
- frontend/src/components/chat/acp/blocks.tsx
- frontend/src/components/chat/acp/common.tsx
- frontend/src/components/chat/acp/context-utils.ts
- frontend/src/components/chat/acp/session-tabs.tsx
- frontend/src/components/editor/ai/__tests__/completion-utils.test.ts
- frontend/src/core/ai/context/providers/__tests__/__snapshots__/tables.test.ts.snap
- frontend/src/core/ai/context/providers/__tests__/cell-output.test.ts
- frontend/src/core/ai/context/providers/__tests__/datasource.test.ts
- frontend/src/core/ai/context/providers/__tests__/error.test.ts
- frontend/src/core/ai/context/providers/cell-output.ts
- frontend/src/core/ai/context/providers/common.ts
- frontend/src/core/ai/context/providers/datasource.ts
- frontend/src/core/ai/context/providers/error.ts
- frontend/src/core/ai/context/providers/file.ts
- frontend/src/core/ai/context/providers/tables.ts
- frontend/src/core/ai/context/providers/variable.ts
AI Context Improvements
- Improved table context format: added sample values for columns and inline formatting
- Styling of Resource's attached when using the agent (support text/plain, markdown, and images)
- Reorganized completion sections with explicit ranking system (boosts dont apply across sections, so need to rank the sections)
- Hide empty datasources from context menu
Various UI fixes
- Added hover states and improved visual hierarchy for resource and resource-link blocks
- Implemented image preview popover for image resource links
- Added overflow handling to prevent horizontal scrolling in user messages and tool notifications
- Fixed truncation for long accordion titles and adjusted z-index for session tabs
> improvement: better UX for AI context items

- tests/_sql/test_clickhouse.py
- tests/_sql/test_engines.py
- tests/_sql/test_get_engines.py
These tests fail locally but are fine in CI, but this makes it harder to develop on marimo. Skipping temporarily.
> skip chdb (embedded clickhouse) tests as they error locally

- marimo/_data/get_datasets.py
- tests/_data/test_get_datasets.py
Fixes #6688. Also fixes a bug with geometry types.
Looks like an upstream bug, I will try to see if we can find metadata to indicate this is a catalog table.
> support iceberg introspection through duckdb

- frontend/src/components/editor/ai/ai-completion-editor.tsx
- frontend/src/components/editor/ai/completion-handlers.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/ui/switch.tsx
- frontend/src/core/codemirror/language/languages/sql/sql.ts
- pnpm-lock.yaml
For SQL cells, clicking on Fix with AI will instantly trigger completions to generate. There will be a floating label right below the cell (I found it difficult to place this above the SQL footer panel because the state would have to be shared).
Users can also change to "Suggest a prompt" for legacy behaviour.
https://github.com/user-attachments/assets/692d7f68-7a52-4cde-af48-add00fa10748
Todo:
> floating label for AI generations in a cell
