marimo-team/marimo

- frontend/src/plugins/impl/vega/vega-component.tsx
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/altair/timestamp_with_no_timezone.py
- tests/_plugins/ui/_impl/test_altair_chart.py
Converting to js maps will add a timezone when the backend dtypes don't expect one. Converting to epoch millis is better for this. In the case somehow we receive a timezone, we will drop it ourselves (and correct the offset)
> fix: altair chart for datetimes with no timezone expected

- marimo/_ai/llm.py
- marimo/_server/api/endpoints/ai.py
Resolves marimo-team/marimo#3117
As discussed in marimo-team/marimo#3117, I'm inferring whether to instantiate an AzureOpenAI client or a regular OpenAI client based on the format of the base url. I made this change consistently in two places: once for the AI assistant and one for the `llm` class in Chat. 
Note one other change: when streaming, the first response for the "choices" array can sometimes be empty (not sure if this is an Azure thing, or in general). So this also includes a one-line change to handle that case.  
I have verified locally that this change allows the AI assistant to work, as well as the [openai example](https://github.com/marimo-team/marimo/blob/main/examples/ai/chat/openai_example.py) assuming you pass in the same base url. 
> feat: support for Azure OpenAI with AI Assistant

- frontend/src/css/md.css
- marimo/_output/md.py
- marimo/_smoke_tests/markdown_pymdownx.py
> feat: add task list support to markdown

- frontend/src/css/globals.css
- frontend/src/css/md.css
- marimo/_output/md.py
- marimo/_smoke_tests/markdown_pymdownx.py
Enable more markdown features. 
base64 is not enabled (but the code is there as a reference) until we come up with a better approach for it. e.g only allow files in a public/ or assets/ directory
> feat: markdown caption support, tabs, critic, emoji, magic links

- frontend/src/components/editor/output/MarimoErrorOutput.tsx
- frontend/src/components/ui/toast.tsx
- frontend/src/core/cells/logs.ts
- marimo/_cli/development/commands.py
- marimo/_messaging/errors.py
- marimo/_messaging/ops.py
- marimo/_runtime/context/utils.py
- marimo/_server/asgi.py
- marimo/_server/export/__init__.py
- marimo/_server/sessions.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_runtime/test_app_mode.py
- tests/_runtime/test_runtime.py
- tests/_server/export/snapshots/run_until_completion_with_stack_trace.txt
- tests/_server/export/snapshots/run_until_completion_with_stop.txt
- tests/_server/export/test_exporter.py
- tests/_server/mocks.py
- tests/_server/test_session_manager.py
- tests/_server/test_sessions.py
- tests/conftest.py
This hides stack traces when in run mode, and instead propagates up an `error_id` that can be used to grep the server logs.
> improvement: errors should stay internal in marimo run and logged to console

- examples/third_party/anywidget/reactive_quak.py
- frontend/src/components/editor/package-alert.tsx
- marimo/_runtime/packages/module_registry.py
- marimo/_runtime/runtime.py
Fixes #3164
`polars` and `pandas` have a lot of optional deps that throw `ModuleNotFound` errors (e.g. with `pyarrow`). Our auto-installation does not work with nested `ModuleNotFound` this fixes it, however it is not reactive (but you can easily run the offending cells).
```python
import polars as pl
df = pl.read_parquet(
"https://github.com/uwdata/mosaic/raw/main/data/athletes.parquet"
).to_pandas()
```
> fix: nested ModuleNotFound

- frontend/src/components/terminal/terminal.tsx
- frontend/src/core/codemirror/copilot/client.ts
- frontend/src/core/websocket/__tests__/createWsUrl.test.ts
- frontend/src/core/websocket/createWsUrl.ts
- frontend/src/utils/strings.ts
Some older browsers don't support relative websocket urls so we need to resolve them ourselves
Fixes #3167
> fix: resolve relative URL for old browsers

- marimo/_ast/names.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/issues/3187_kernel_dies.py
- tests/_server/test_session_manager.py
Fixes #3187.
Previously we brought down the whole edit server if an edit-mode kernel died unexpectedly. This used to make sense when marimo was 1 server, 1 notebook, but it no longer makes sense today, as it causes the user to lose all their work in other notebooks opened by the server too.
Instead, this change makes it so that the session is closed (and removed from the manager), but the server is still kept alive.
> fix: gracefully close dead sessions in edit mode

- marimo/_plugins/ui/_impl/tables/format.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_plugins/ui/_impl/tables/test_table_utils.py
fix: apply format_mapping to None values in table formatting
Previously, format_mapping functions were not being called when the value was None,
causing inconsistent formatting behavior. This change ensures that:
1. None values are passed through to format_mapping functions rather than being
skipped
2. Format functions can handle None values explicitly and transform them as needed
before:
now:
> fix: apply format_mapping to None values in table formatting

- marimo/_server/print.py
nit: just a little thing that was bothering me
Changes
```
➜  URL: https://example.tld:None?access_token=token
```
to 
```
➜  URL: https://example.tld?access_token=token
```
> fix: formatting for proxied url

- docs/api/cli.md
- docs/faq.md
- docs/guides/apps.md
- marimo/_cli/cli.py
- marimo/_cli/config/commands.py
- marimo/_cli/convert/commands.py
- marimo/_cli/export/commands.py
- marimo/_server/api/endpoints/assets.py
- mkdocs.yml
- pyproject.toml
This adds our CLI docs to docs.marimo.io. 
I needed to reformat our CLI so that they get rendered as markdown properly
> docs: add CLI to the docs, reformat CLI so renders propperly

- marimo/_output/formatters/df_formatters.py
- marimo/_output/formatters/pandas_formatters.py
- marimo/_smoke_tests/series_formatting.py
Fixes #3191 
This PR introduces standardized formatting for pandas and polars Series objects in marimo's output system. 
Key changes:
- Adds dedicated formatters for both pandas.Series and polars.Series
- Implements consistent handling of unnamed Series:
- Pandas: Unnamed Series are displayed with column name "value"
- Polars: Series with None or empty string names are displayed with column name "value"
- Includes comprehensive smoke tests covering:
- Named Series (both pandas and polars)
- Unnamed Series (both pandas and polars)
- Empty-string named Series (polars-specific edge case)
- All Series are rendered using marimo's table component with pagination enabled
- Maintains fallback to native HTML representation if formatting fails
The included smoke tests (`series_formatting.py`) …
> feat(formatters): Add consistent Series formatting for pandas and polars

- frontend/src/core/static/__tests__/files.test.ts
- frontend/src/core/static/files.ts
Fixes #1884
Fixes mo.ui.table does not render in HTML export on Windows Chrome/Edge, by adding `ContentType` to the response and use `fetch` for base64 conversion
> fix: mo.ui.table does not render in HTML export on Windows Chrome/Edge

- marimo/_server/export/exporter.py
- tests/_server/api/endpoints/test_export.py
It's possible the file is not longer in the virtual memory, but this is ok as the export should be valid.
Fixes #3235
> fix: skip gracefully when virtual file is not found

- docs/blocks.py
To make the notebooks clearer, and easier to copy and paste from top to bottom.
> docs: show import marimo as mo at notebook top

- marimo/_ast/app.py
- marimo/_ast/cell.py
- marimo/_runtime/app/script_runner.py
- marimo/_runtime/executor.py
- marimo/_runtime/primitives.py
- marimo/_server/export/exporter.py
- tests/_ast/test_cell.py
- tests/_runtime/test_pytest.py
- tests/conftest.py
I was really interested in having tests in notebooks (re discussion yesterday), so I played around with it a tiny bit this afternoon. As is, pytest does not work out of the box since:
1. the wrapped functions become Cell instances
2. coroutine detection through the `_is_coroutine` spec should be as an attribute
This change enables both of these minor adjustments. Now, pytest will pick up
marimo `test_*` functions, but they will fail since directly invoking a cell is
currently not allowed. I put in a little unit test to fight against a possible
regression until such time when a top level fn spec is enabled (see #2293).
> tidy: Tweaks to enable pytest on marimo nbs

- frontend/src/components/editor/Cell.tsx
Similar to #3220 but for arrow keys. Discovered interacting with a date input.
> fix: arrow key navigation taking precedence in inputs

- docs/api/inputs/dates.md
- marimo/_plugins/__init__.py
- marimo/_plugins/ui/_impl/chat/__init__.py
- marimo/_plugins/ui/_impl/dataframes/__init__.py
- marimo/_utils/docs.py
- tests/_utils/snapshots/docstring_complex.txt
- tests/_utils/snapshots/docstring_summary.txt
- tests/_utils/test_docs.py
Also, show examples right after summary, then args, attrs, ...
I noticed that some (but not all) of the attributes sections had been converted to google-style and weren't rendering properly. This change fixes that.
> improve: parse google-style attributes in docstrings

- docs/guides/exporting.md
- marimo/_cli/export/commands.py
- marimo/_server/export/exporter.py
- tests/_cli/test_cli_export.py
Allow exporting:
```bash
marimo export html-wasm -o out/foo.html
```
e.g. bash script:
```bash
files=("batch_and_form.py" "data_explorer.py")
for file in "${files[@]}"; do
without_extension="${file%.*}"
marimo export html-wasm "$file" -o public/"$without_extension".html --mode run
done
```
Example repo: https://github.com/marimo-team/marimo-gh-pages-template
> improvement: allow non-index.html files and add docs for wasm export

- marimo/_save/save.py
Wrap default filepath in backticks to avoid double underscore rendering as bold
> fix quotes in save.py:persistent_cache docstring

- marimo/_runtime/packages/module_name_to_pypi_name.py
This adds a mapping for the `quaternion` package, which is named `numpy-quaternion` on PyPI.
Just added the key:value pair to the `module_name_to_pypi_name` dict.  I'm hoping a test is not needed for such a simple change, though I have tried it locally and verified that it works by automatically installing `numpy-quaternion`.
@mscolnick
> Add mapping for quaternion -> numpy-quaternion

- marimo/_cli/export/commands.py
- tests/_cli/test_cli_export.py
Fixes #3233
Adds a `--sandbox` flag to the `marimo export html` command that allows running exports in an isolated virtual environment using `uv`. This is particularly useful when:
- Exporting notebooks with specific package dependencies
- Wanting to avoid polluting the global Python environment
- Ensuring reproducible exports by using the exact package versions specified in the notebook
- Added `--sandbox` flag to HTML export command with same behavior as existing sandbox commands
> feat(cli): add --sandbox flag to `marimo export html` command

- frontend/src/components/editor/chrome/panels/constants.ts
- frontend/src/components/editor/chrome/panels/packages-panel.tsx
- frontend/src/components/editor/chrome/state.ts
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/compat/__tests__/jupyter.test.ts
- frontend/src/core/codemirror/compat/jupyter.tsx
When the user types something that matches a common jupyter command, we potentially toast with helpful message (and maybe update some config or open a panel)
> improvement: map jupyter magic to helpful descriptions

- examples/README.md
- examples/ai/README.md
- examples/cloud/README.md
- examples/control_flow/README.md
- examples/layouts/README.md
- examples/markdown/README.md
- examples/misc/README.md
- examples/sql/README.md
- examples/third_party/README.md
- examples/ui/README.md
Simplify instructions for running examples (two steps instead of 3).
> improve: example installation instructions

- docs/api/state.md
- docs/guides/best_practices.md
- docs/guides/interactivity.md
- docs/guides/state.md
- marimo/_runtime/state.py
- mkdocs.yml
Too many of our users fall into callback driven programming which is very ill-suited to marimo. This PR updates the docs to more strongly warn users against using mo.state()/on_change.
> docs: warn users more strongly against using mo.state() and on_change handlers.

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/chrome/panels/snippets-panel.tsx
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/misc/__tests__/dnd.test.ts
- frontend/src/core/codemirror/misc/__tests__/paste.test.ts
- frontend/src/core/codemirror/misc/dnd.ts
- frontend/src/core/codemirror/misc/paste.ts
- frontend/vite.config.mts
This is a big QOL improvement (especially when testing applications). you can no paste full snippets or applications e.g (grab the source code from https://docs.marimo.io/api/inputs/code_editor/ or any issue) and paste in the first cell.
> improvement: allow pasting full marimo applications in a cell

- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_smoke_tests/tables/polars_duration.py
- marimo/_utils/narwhals_utils.py
- tests/_plugins/ui/_impl/tables/snapshots/narwhals.field_types.json
- tests/_plugins/ui/_impl/tables/snapshots/polars.field_types.json
- tests/_utils/test_narwhals_utils.py
Fixes #3267 
This handles narwhals and polars Duration types, by treating them as `floats` and not temporal. We differ in the that we don't show the units for each entry (just at the top).
For pandas, we treat them as strings (with the same formatting as their plain HTML)
> improvement: handle pl.Duration

- biome.json
Setup Biome's VCS integration.
Configures Biome to respect `.gitignore` file using its builtin [VCS
integration](https://biomejs.dev/guides/integrate-in-vcs/).
I'm only opening this PR because this was an option in Biome that I found
surprisingly hard to discover myself in another project. Feel free to
ignore/close if it has already been considered in preference for the explicit
`ignore` list (no explanation needed 😄).
@mscolnick
> Integrate Biome with VCS to simplify ignore patterns

- docs/guides/index.md
- docs/guides/testing/doctest.md
- docs/guides/testing/index.md
- docs/guides/testing/pytest.md
- docs/guides/tests.md
- docs/index.md
- examples/README.md
- examples/testing/README.md
- examples/testing/running_doctests.py
- examples/testing/test_with_pytest.py
- mkdocs.yml
pytest specific docs with #3251
Please feel free to tweak and rewrite (you can add to this branch, I'm not touching it unless there's feedback). Just wanted to provide a starting point.
Also in `CONTRIBUTING.md`, I didn't see any updates to the docs workflow? I know you all have moved off sphinx, but haven't paid too much attention
---
Writing up the fixtures section, I realized it feels a little awkward in practice.
Maybe this would be a better user API?
```python
import marimo
__generated_with = "0.10.6"
app = marimo.App()
@app.cell
def _():
from requests import get as requests_get
requests_fixture = mo.test.fixture(requests_get) # basically wrapper to add type
return requests, requests_fixture
@app.cell
def test_sanity(my_fn, requests_fixture): …
```
> docs: pytest in marimo

- pyproject.toml
If you don't install pyarrow, Marimo will throw a `ModuleNotFoundError` and ask you to install pyarrow. 
Fix is to follow this guide: https://duckdb.org/docs/guides/python/polars.html
Not sure if we can update the versioning of the packages.
> convenience: add pyarrow to polars install

- marimo/_ast/app.py
- marimo/_ast/compiler.py
- marimo/_ast/pytest.py
- marimo/_messaging/context.py
- tests/_ast/test_pytest.py
merry merry 🎄 
---
Slight improvement on pytest errors, by manually running pytest's assertion rewrite magic. So that takes us from this:
to this
Also a little fun- this rewrite can be applied in general and shown in editor.
Not sure the overhead this might have- so not sure about setting it generally, but could set `test_rewrite=True` if the cell name starts with `test_`. Wanted to run this by you all first
> feat: apply pytest rewrites for better testing

- frontend/src/plugins/impl/DataTablePlugin.tsx
Fixes #3306
The table component's showColumnSummaries prop now correctly accepts both boolean
and string literal values ("stats" or "chart"). This fixes the type validation
error when passing string literals to control column summary behavior.
Before
Now
> fix(table): allow string literals for showColumnSummaries

- marimo/_runtime/dataflow.py
- tests/_ast/cell_data/named_cells.py
- tests/_ast/test_cell.py
Solves #3299 
Just making sure it wasn't my recent change.
> fix: typo in run subs

- examples/sql/connect_to_motherduck.py
- examples/sql/connect_to_postgres.py
- examples/sql/connect_to_sqlite.py
- examples/sql/misc/database_explorer.py
- examples/sql/misc/electric_vehicles.py
- examples/sql/misc/sql_cars.py
- examples/sql/parametrizing_sql_queries.py
- examples/sql/querying_dataframes.py
- examples/sql/read_csv.py
- examples/sql/read_json.py
- examples/sql/read_parquet.py
* Migrate the SQL examples to use Polars.
* Can merge when polars in pyodide is supported
> chore: use polars instead of pandas in examples

- marimo/_cli/export/commands.py
Responding to user feedback that `export html-wasm --mode run` should hide code by default.
In contrast, `export html` (without wasm) still shows code by default because this command has no distinction between run and edit mode.
> improve: no-show-code default for html-wasm export

- marimo/_cli/export/commands.py
- tests/_cli/test_cli_export.py
Include a .nojekyll file in the assets exported by marimo export html-wasm to prevent GitHub Pages from interfering with asset resolution.
This issue arose when attempting to manually deploy a directory to GitHub Pages (instead of using an action).
> improve: include .nojekyll file in assets export

- marimo/_runtime/runtime.py
- tests/_runtime/test_runtime.py
When autorun on startup is disabled, running a cell should only run its uninstantiated ancestors, and in particular it shouldn't run the uninstantiated descendants of of uninstantiated ancestors.
This lets the notebook author incrementally run parts of their notebook on startup, even those that include UI elements, without making the entire notebook lazy.
Previously, running a cell would collect uninstantiated ancestors but also uninstantiated descendants, which would often be the entire notebook since uninstantiated ancestors often include imports.
This fix was implemented by keeping track of which execution requests are uninstantiated. This data structure is pruned as cells are run or deleted.
> fix: partially instantiate notebooks when autorun on startup is disabled

- marimo/_ast/sql_visitor.py
- marimo/_dependencies/dependencies.py
- pyproject.toml
- tests/_ast/test_sql_visitor.py
Fixes #3103. Adds sqlglot as an optional dependency to handle complex sql refs parsing. Also supports DML statements (insert, update and delete).
- set sqlglot version to lowest possible (likely >23.4, due to ibis lib)
- If we're keen on supporting dml's, then I could add more tests (I added some here alrdy)
- `def find_sql_def()` can also be modified to use sqlglot in the future, not included in this PR.
- small change: updated duckdb version to 1.1.0 to be synchronised across all installations (some were 1.0 and some were 1.1)
> feat: add sqlglot to parse sql dataflow

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
Fixes #3317 . Should display hidden cells similar to pre-borderless-markdown era. Code may be a bit rough.
> fix: show hidden cells when markdown has no output

- frontend/src/plugins/layout/TexPlugin.tsx
- marimo/_tutorials/markdown.py
I would like to be able to write chemical equations conveniently in marimo. 
This pull request is an attempt at including katex' mhchem extension, which allows for convenient chemical writing through \ce command, but also clean physical unit typesetting with the \pu command (somewhat similar to siunitx in latex). 
Related to https://discordapp.com/channels/1059888774789730424/1318274202507284531
Note : this is the first time I'm trying to contribute to an open-source project, and I honestly don't really know what I am doing, but since the change is very small, I thought I could try. I just tried to make https://katex.org/docs/node#using-mhchem-extension work.
- import katex' mhchem extension
- also add a note on katex in markdown tutorial
I have not tested for performance. Not sure how to …
> Add mhchem

- docs/api/inputs/tabs.md
docs preview for tabs shows repeated graph, thought it would be nice to add `chat` option. Got confused the first time while using tabs whether it was switching or not.
Updated with [chat](https://docs.marimo.io/api/inputs/chat/?h=chat) instead of bar.
> docs: update repeated tabs with chat content tab

- docs/api/inputs/text_area.md
- examples/ui/text_area.py
Fixed the broken text_area preview in docs currently by following mkdocs-preview embedding shown previously.
<details>
</details>
Link to `text_area` in `examples/ui/text_area.py`
> docs: fix broken text_area preview

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/editor/Output.tsx
- frontend/src/components/editor/chrome/panels/error-panel.tsx
- frontend/src/components/editor/errors/auto-fix.tsx
- frontend/src/components/editor/output/ConsoleOutput.tsx
- frontend/src/components/editor/output/MarimoErrorOutput.tsx
- frontend/src/core/cells/__tests__/runs.test.ts
- frontend/src/core/errors/__tests__/errors.test.ts
- frontend/src/core/errors/__tests__/utils.test.ts
- frontend/src/core/errors/errors.ts
- frontend/src/core/errors/utils.ts
- marimo/_smoke_tests/errors/autofix.py
- tests/_runtime/snapshots/docstrings_class.txt
- tests/_runtime/snapshots/docstrings_function.txt
- tests/_runtime/snapshots/docstrings_function_external.txt
- tests/_runtime/snapshots/docstrings_function_google.txt
Part of #3110
This adds two autofixes for different marimo errors. This opens the door for more autofixes as well. Right now this happens on all the frontend because 1) the code transformations are not that difficult and 2) still requires frontend logic like focusing the editor or adding a new cell. We could move some of this to the backend but would prefer to put the auto-fixes into a a proper linting framework + LSP.
The autofixes:
* multiple definitions -> Make this cell's variables local by wrapping the cell in a function.
* missing name -> Add a new cell for the missing import
> feat: add auto-fix for multiple definctions and popular imports

- docs/api/miscellaneous.md
- marimo/__init__.py
- marimo/_runtime/runtime.py
- tests/_ast/test_app.py
- tests/_runtime/test_runtime.py
This adds `mo.notebook_location()`
```py
@mddoc
def notebook_location() -> pathlib.Path | None:
"""Get the location of the currently executing notebook.
In WASM, this is the URL of webpage, for example, `https://my-site.com`.
For nested paths, this is the URL including the origin and pathname.
`https://<my-org>.github.io/<my-repo>/folder`.
In non-WASM, this is the directory of the notebook, which is the same as
`mo.notebook_dir()`.
Examples:
In order to access data both locally and when a notebook runs via
WebAssembly (e.g. hosted on GitHub Pages), you can use this
approach to fetch data from the notebook's location.
```python
import polars as pl
data_path = mo.notebook_location() / "public" / "data.csv"
df = pl.read_csv(data_path)
df.head()
```
Returns:
pathlib.Path | None: A …
```
> feat: mo.notebook_location()

- marimo/_output/formatters/holoviews_formatters.py
- marimo/_plugins/ui/_impl/from_panel.py
- marimo/_smoke_tests/third_party/holoviews_scatter.py
- pyproject.toml
- tests/_plugins/ui/_impl/test_panel.py
Issue from discord: https://discord.com/channels/1059888774789730424/1319756390759141429/1319756390759141429
The issue was:
```diff
- ref, docs_json, render_json = render_component(obj)
+ ref, docs_json, render_json = render_component(self.obj)
```
This PR also adds a fallback and unit tests.
> fix: rendering with panel when not a native panel object

- marimo/_dependencies/dependencies.py
- marimo/_server/errors.py
- marimo/_server/main.py
- marimo/_server/sessions.py
- marimo/_sql/sql.py
- tests/_dependencies/test_dependencies.py
- tests/_server/api/test_middleware.py
- tests/_server/test_errors.py
Fixes #3293 
Somewhat helps with #3113, but we probably want to add buttons in the UI to install. 
This does two things:
1. for `ModuleNotFound` errors thrown in the Kernel by us (via DependencyManager.module.require()`), by adding the `name`, we prompt the user with the installation toast.
2. for `ModuleNotFound` errors thrown in the server (also via the DependencyManager), we similarly show the installation toast.
> improvement: prompt to install missing deps during optional dependency checks

- docs/guides/deploying/deploying_nginx.md
- mkdocs.yml
> docs: nginx instructions

- pyproject.toml
The minimum version requirement ensures compatibility with httpx>=0.28.0,  specifically around the 'proxies' kwarg handling that was fixed in openai 1.55.3. 
Earlier versions of openai conflict with httpx>=0.28.0.
See:
https://github.com/openai/openai-python/issues/1902
https://github.com/openai/openai-python/pull/1905
> chore(deps): set openai dependency to >=1.55.3

- frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/keymaps/keymaps.ts
Fixes #3318 
Remove the "Enter" from the `defaultKeymap`
> fix: vim <CR> carriage return

- frontend/src/components/editor/controls/keyboard-shortcuts.tsx
- frontend/src/core/hotkeys/hotkeys.ts
Fixes #3367 
This was already possible, but just confusing to users when it didn't exist. currently not editable.
Also updates some names to be more explicit
> fix: display toggle line comment in shortcut menu

- docs/guides/editor_features/hotkeys.md
- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/SortableCell.tsx
- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/cell/code/language-toggle.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/core/hotkeys/hotkeys.ts
- frontend/src/hooks/useHotkey.ts
Add two new hotkeys for moving left/right when in multi-column. `Mod+Shift+7`, `Mod+Shift+8`.
Also performance improvements in 3 places that would re-render all cells when moving only one cell
> improvement: add move cell left/right shortcuts of multi-column, various perf improvements

- frontend/src/core/codemirror/cm.ts
Add Alt-J/K (Ctrl-J/K on macOS) shortcuts to navigate through the completion menu, inspired by Vim:
- Alt-J/Ctrl-J: Move down in completion list
- Alt-K/Ctrl-K: Move up in completion list
This provides a more efficient way to navigate completions without using arrow keys.
https://github.com/user-attachments/assets/3c261966-e2cb-454e-9862-d26380d32cdf
> feat(editor): Add keyboard shortcuts for completion navigation

- docs/guides/publishing/playground.md
Vestigial line, also change some iframe heights
> docs: fix typo

- frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/keymaps/keymaps.ts
This is a better and more correct solution
> fix: vim keymap precedence (fix enter in insert mode)

- docs/guides/publishing/github_pages.md
Jekyll interferes with our generated sites.
> docs: tip to include nojekyll if building from a folder

- docs/guides/exporting.md
- docs/guides/publishing/playground.md
- docs/guides/wasm.md
- examples/misc/notebook_dir.py
* Document how to open notebooks hosted on GitHub in the playground
* Document how this gets you access to the repo's entire file tree (!)
* Add a bookmarklet for convenience
> docs: open playground notebooks from GitHub URL

- docs/guides/publishing/playground.md
Fix incorrect bookmark hyperlink redirecting to 404 page.
Create a popup dialog box instructing to open the bookmark/use it to open a marimo notebook on GitHub
> fix: improve bookmarklet functionality for GitHub notebook URLs

- examples/frameworks/fastapi-github/main.py
- examples/frameworks/fastapi/main.py
- examples/frameworks/fasthtml/main.py
- examples/frameworks/flask/main.py
When running the frameworks examples, the app fails to execute the dataframe.py because of vega-datasets missing dependency. This PR adds the vega-datasets package to each main.py script of the frameworks examples.
Add the vega-datasets package to each main.py script of the frameworks examples
> fix: add vega-datasets package to framework examples

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/ai/completion-utils.ts
- frontend/src/core/codemirror/utils.ts
- frontend/src/plugins/impl/chat/chat-ui.tsx
Fixes #3401 . Use codemirror as chatbot input,  `/` triggers autocomplete.
- multiline input
- multiline chat bubble
- removed an unnecessary extension (codemirror-mentions) and implemented custom one
note: dataset atom is not finding any tables, hence `@` is not working.
> fix: better chatbot input & bubble

- marimo/_convert/ipynb.py
- marimo/_convert/utils.py
- tests/_cli/snapshots/converted_markdown.py.txt
- tests/_convert/test_convert_utils.py
I think this looks better, for example https://marimo.app/gh/jakevdp/PythonDataScienceHandbook/master?entrypoint=notebooks%2F03.09-Pivot-Tables.ipynb
> improvement: hide_code for markdown when converting from ipynb

- docs/guides/publishing/embedding.md
- docs/guides/publishing/from_github.md
- docs/guides/publishing/index.md
- mkdocs.yml
This adds a short overview page and navigation entry (publishing > from github) on how to publish/share notebooks from GitHub, for discoverability.
- GitHub pages
- Online playground
- Community Cloud
Analagous to the publishing > embedding page.
> docs: overview page on sharing notebooks from github

- docs/guides/publishing/playground.md
Add a docs subsection on using our "open in marimo" badge for playground notebooks, similar to https://openincolab.com/.
> docs: open in marimo badge

- docs/index.md
Fixes broken links on docs.marimo.io
links inside html elements are not automatically converted to the correct url during the docs build process, leading to 404s on the main marimo docs page: https://docs.marimo.io/#learn-more (see the html table below "check out our guides ...")
@akshayka
> docs: fix broken links in html

- docs/guides/coming_from/jupyter.md
Add a row for %pip installation guide in cell block `Common magic commands replacements` introduced in this PR #3408 
Add the following to the existing table guide (for magic commands replacement):
| Magic Command| Replacement |
|--------|--------|
| %pip| Use the package manager option on the sidebar to install packages| 
> docs: add %pip usage instruction to Jupyter guide

- marimo/_cli/sandbox.py
- marimo/_runtime/packages/pypi_package_manager.py
- tests/_cli/test_sandbox.py
- tests/_runtime/packages/test_package_managers.py
This has a few fixes to be more resilient with `--sandbox`.
1. When installing `marimo[sql]` in the UI, we don't include the version (same as `marimo`)
2. When reading the deps from the notebook, we dedupe `marimo` and any `marimo[extras]`, and add the version correctly.
> fix: handle marimo[extras] in --sandbox and package installation

- marimo/_server/asgi.py
- tests/_server/test_asgi.py
> fix: use relative path in asgi redirect

- marimo/_runtime/runtime.py
This lets sandboxed notebooks be run as scripts with `uv run nb.py` even when they don't import marimo.
> improve: always add marimo in sandbox

- docs/guides/editor_features/watching.md
- frontend/src/core/config/config.ts
- frontend/src/core/saving/save-component.tsx
- mkdocs.yml
Also: fix a bug with autosave override not being respected by the frontend.
For docs:
* Promote to a top-level nav item, and rename to "Using your own editor"
* Other small edits.
> docs: update watching documentation

- docs/faq.md
This PR adds a missing open bracket in the FAQ that broke one of the links.
I added the open bracket
> fix: Add missing open bracket in docs/faq.md

- frontend/src/components/editor/cell/cell-context-menu.tsx
- frontend/src/core/vscode/vscode-bindings.ts
Might fix https://github.com/marimo-team/vscode-marimo/issues/63
> fix: fallback on readText permisisons

- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/cell/useRunCells.ts
- frontend/src/components/shortcuts/renderShortcut.tsx
- frontend/src/core/edit-app.tsx
- frontend/src/core/hotkeys/hotkeys.ts
- frontend/src/core/hotkeys/shortcuts.ts
* Add a re-run all cells action
* Makes it a NOT_SET hokey which allows one to be set, but initially empty
> feat: re-run all cells action (useful for external queries/dashboards)

- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
- marimo/_ast/app.py
- marimo/_ast/cell.py
- marimo/_ast/cell_manager.py
- marimo/_ast/codegen.py
- marimo/_ast/models.py
- marimo/_cli/cli.py
- marimo/_messaging/ops.py
- marimo/_server/file_manager.py
- marimo/_server/session/session_view.py
- marimo/_server/sessions.py
- tests/_ast/test_cell_manager.py
- tests/_server/api/endpoints/test_resume_session.py
- tests/_server/session/test_session_view.py
- tests/_server/test_file_manager.py
Intelligently keep order of cells when running `marimo edit --watch`. We use a text similarity heuristic to figure out how cell ids moved since they were last seen.
We also need to keep track of which IDs were used from reload-to-reload so we don't surface the same ones.
This also has a few bug fixes with session-views.
> improvement: intelligently keep order of cells when running --watch

- .github/workflows/docs.yml
- docs/faq.md
- docs/getting_started/key_concepts.md
- docs/guides/deploying/index.md
- docs/guides/editor_features/ai_completion.md
- docs/guides/interactivity.md
- docs/guides/wasm.md
- docs/index.md
```
run: npx sitefetch https://docs.marimo.io -o site/llm.txt --match "!**/*.{txt,xml}"
```
> docs: add llm.txt file

- marimo/_runtime/runtime.py
We were accidentally adding missing modules instead of missing packages to the installation logic. So for example the installer attempted to install `scikit-learn` and `sklearn` on `import sklearn`, even though the package is just `scikit-learn`.
> fix: missing package detection

- marimo/_cli/sandbox.py
- tests/_cli/test_sandbox.py
- tests/conftest.py
If there are no dependencies (specifically, if uv is not running a script with inline metadata), uv may use a cached venv, even though we are passing --isolated; `--refresh` ensures that the venv is actually ephemeral
> fix: empty notebooks should have empty venvs in sandboxes

- marimo/_ast/transformers.py
- tests/_ast/test_transformers.py
- tests/_convert/test_ipynb.py
The `NameTransformer` wasn't visiting node descendants, leading to incomplete transformations.
Before, when remapping `x` to a local:
```python
x = 1
y = foo(x + 1)
```
was yielding
```python
x = 1
y = foo(x + 1)
```
With this change, it now yields
```python
_x = 1
y = foo(_x + 1)
```
This change also modifies an old test that was testing that the `NameTransformer` respected scoping logic. But it never actually did, or rather only did so because of a bug in which it wasn't visiting entire subtrees. Nothing relies on the `NameTransformer` respecting scoping in our codebase.
> fix: conversion of ipynb files with multiple definitions

- marimo/_cli/sandbox.py
- tests/_cli/test_sandbox.py
Missing parentheses broke command construction. Strengthened tests.
> fix: sandbox command construction

- docs/guides/editor_features/hotkeys.md
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/hotkeys/hotkeys.ts
make keymaps introduced in #3382  configurable
> feat(hotkeys): add configurable completion selection movement

- marimo/_plugins/ui/_impl/data_editor.py
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/validators.py
- tests/_plugins/ui/_impl/dataframes/test_dataframe.py
- tests/_plugins/ui/_impl/test_data_editor.py
- tests/_plugins/ui/_impl/test_table.py
Fixes #3407 . This will raise an error for `data_editor`, `dataframe` and `table` when the `page_size` configured is > 200.
> fix: raise valueError for pageSize > 200

- mkdocs.yml
Adds https://github.com/blueswen/mkdocs-glightbox to images for click effect
> docs: add glightbox

- marimo/_cli/cli.py
- tests/_cli/test_cli.py
Fixes #3445
Even though the value of $SHELL is just "bash" at the command line, it is the full path to the executable in the program. (i.e. 'c:\foo\bar\bash.exe'). The "name" attribute returns "bash.exe" in that case, which doesn't match "bash". Fortunately, pathlib.Path also offers a "stem" attribute which strips the extension. \o/
> Support shells on windows (with extensions)

- marimo/_cli/cli.py
- tests/_cli/test_cli.py
After inspection, only the `shell_completion` did not use click methods to report errors. Fixed and added/updated tests for both internally detected errors.
Fixes #3476
After code inspection, only the `shell_completion` did not use click methods to report errors. Fixed and added/updated tests for both internally detected errors.
```bash
❯ pytest -p no:warnings tests/_cli/test_cli.py::test_shell_completion
===================================================== test session starts =====================================================
platform win32 -- Python 3.13.0, pytest-8.3.4, pluggy-1.5.0
rootdir: C:\Users\hwine\marimo
configfile: pyproject.toml
plugins: anyio-4.8.0
collected 6 items
tests\_cli\test_cli.py ...... …
```
> Ensure return code non-zero on cli error

- frontend/src/core/codemirror/keymaps/keymaps.ts
Fixes #3504 - Restores vim j/k cell navigation that was broken by PR #3395. The issue prevented users from navigating between cells using j/k keys when at the end/start of cells in vim normal mode.
Before:
```ts
Prec.highest(vim({ status: false })),
Prec.highest(vimKeymapExtension(callbacks)),
```
After:
```ts
vim({ status: false }),
Prec.high(vimKeymapExtension(callbacks)),
```
> fix(vim): restore j/k cell navigation broken by #3395

- marimo/_plugins/ui/_core/ui_element.py
- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
Fixes #2736 . Allows user to select some rows by default upon table creation.
```.py
table = mo.ui.table(
{"a": [1, 2, 3], "b": [2, 3, 4], "c": ["apple", "banana", "carrots"]},
label="table",
initial_selection=[2],
)
```
> feat: add initial selection table

- .gitignore
- marimo/_ast/app.py
- tests/_ast/test_app.py
Show the unparseable code in the error message when directly running a
notebook via the python command.
Fixes #2265
@mscolnick
> Improve reporting of unparsable code

- marimo/_runtime/runtime.py
- tests/_runtime/test_manage_script_metadata.py
Fixes #3501 
ibis is supported, but when we do autoinstall (e.g. with micropip), we skip the module mapping logic we have for common packages.
> improvement: use module mapping when running auto-install in micropip

- marimo/_config/config.py
- marimo/_snippets/snippets.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_snippets/test_snippets.py
> load snippets location from config

- README.md
- README_Japansese.md
> chore: add Japanese README file and update main README to link it

- marimo/_convert/ipynb.py
- tests/_convert/test_ipynb.py
- Support magic commands that have arguments (%matplotlib inline)
- Support cells that start with a single-line magic but have Python code after
- Support cells that have multiple single-line magics
> fix: single line magic conversion

- frontend/src/plugins/impl/DataEditorPlugin.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/vega/__tests__/vega.test.ts
- frontend/src/plugins/impl/vega/loader.ts
Fixes #3528
When we add formatting to a column, we still say the data-type is a float/int, but we actually pass a string. So we need to fallback gracefully if so. 
It's likely a better fix is letting the frontend know that the datatype has changed if it was formatted to a string.
> fix: fallback to oringinal string when cannot parse formatted number

- marimo/_ast/models.py
- marimo/_runtime/primitives.py
- marimo/_save/ast.py
- marimo/_save/hash.py
- marimo/_save/save.py
- tests/_save/test_cache.py
- tests/_save/test_hash.py
This has fixes for:
Following PR changes:
-  Detect when execution hash relies on a another hash object (cache breaking) (#3270)
-  Allow for pickle hash as fallback for "unhashable" variables (#3270)
-  Expand `@persistent_cache` api (this shouldn't cache bust, so I might just follow up) (#2653)
> cache iteration: various fixes- will invalidate exisiting cache

- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/components/editor/cell/useSplitCell.tsx
- add split cell to cell dropdown
- command palette
- and fix undo split cell, when using markdown or SQL
> improvement: add split cell to cell dropdown, command palette, and fix undo split cell

- docs/api/status.md
- docs/guides/expensive_notebooks.md
- docs/guides/state.md
- marimo/_plugins/stateless/lazy.py
- replace `mo.ui.accordion` to just `mo.accordion`, fix links
- button needs a  label, if not, the string is considered `on_change` handler
> docs: fix some deprecated links, old components

- marimo/_save/loaders/__init__.py
- marimo/_save/loaders/loader.py
- marimo/_save/loaders/memory.py
- marimo/_save/save.py
- tests/_save/mocks.py
- tests/_save/test_cache.py
fixes #2653 #3471
Enables `persistent_cache` to be used as a decorator for functions, and `cache` to be used as a context block. e.g.
```python
@mo.persistent_cache
def expensive_function_written_to_disk():
...
with mo.cache("expensive_block_in_memory") as c:
...
```
`cache` is also used as the general entry point for custom "Loaders" 
---
The breadth of the API makes the implementation a bit hairy, but I think that if it's a smooth experience for the user then it's worth it.
@akshayka
> feature: allow persistent_cache to be used as a decorator

- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
Fixes #3090 . Previously, the `isEqual` check will always return true.
onInvalidChange -> sets `internalValue` to `newValue` from the form
onChange -> checks whether `newValue` and `internalValue` are the same. Yes, they would be.
https://github.com/user-attachments/assets/936f648d-de7d-43c7-9895-6df070287205
There's some flickering going on (not new issue) when toggling from no cols to 1 col, hard to figure out..
> fix: transforms on dataframe to be reactive

- marimo/_plugins/ui/_impl/from_anywidget.py
Currently, marimo will fail on FIPS-enabled environments where `md5` hashing is disabled for security purposes. This means that `js_hash` cannot be calculated in `marimo/_plugins/ui/_impl/from_anywidget.py`.
Since md5 is being used for file integrity checks, this particular use of md5 can be considered FIPS compliant. Since python 3.9, the *usedforsecurity* flag has been introduced in hashlib functions, which allows for bypassing the FIPS enforcement check. As such, using `usedforsecurity=False` when invoking `hashlib.md5` solves the issue.
Use `usedforsecurity=False` when invoking `hashlib.md5` in `marimo._plugins.ui._impl.from_anywidget.anywidget.__init__`.
I did not add tests because I'm not sure how to go about mocking a FIPS enabled environment, and the change is a noop for non-FIPS …
> fix: support running in FIPS-enabled environments

- docs/guides/editor_features/watching.md
- tests/conftest.py
Tests shouldn't care whether temporary directory cleanup fails.
> chore: deflake tmpdir cleanup in tests

- marimo/_cli/upgrade.py
- tests/_cli/test_upgrade.py
Fixes #3580
- lower timeout in version check
- if check fails, don't retry
> fix: lower timeout in version check

- examples/ai/chat/deepseek_example.py
- examples/ai/chat/groq_example.py
Add an example for chatting with deepseek-reasoner using `mo.ui.chat`
Used `mo.ui.chat`; more specifically `mo.ai.llm.openai` and override the `base_url` since it's OpenAI API compatible. Specified the model along with custom prompts to use.
TODO:
> Add DeepSeek chatbot example

- marimo/_snippets/data/pandas-9.py
Fix error in existing pandas snippet-9.py; (`Pandas: Describe Timestamp values in a column`):
`TypeError: describe() got an unexpected keyword argument 'datetime_is_numeric`
<details>
<summary> Screenshot of error </summary>
</details>
Simplified code snippet.
> fix: Simplify and resolve pandas snippet error

- marimo/_ast/app.py
- marimo/_ast/cell_manager.py
- marimo/_runtime/state.py
- marimo/_save/__init__.py
- marimo/_save/cache.py
- marimo/_save/loaders/__init__.py
- marimo/_save/loaders/json.py
- marimo/_save/loaders/loader.py
- marimo/_save/loaders/memory.py
- marimo/_save/loaders/pickle.py
- marimo/_save/save.py
- tests/_save/test_cache.py
- tests/_save/test_hash.py
- tests/conftest.py
Fixes the issue where the first function call had a different save path from subsequent calls (just inconsistent path setting reported by @akshayka )
Added some tests, and json loader that I was using to debug (also a feature suggestion from @leventov)
> fix: persistent loader save path (+ feat: test tweaks / json loader for interpretability)

- tests/_save/test_cache.py
resolves #3583
Ran with 
```bash
for x in (seq 50);  pytest -vv tests/_save/test_cache.py || break; end
```
Also ran the same command @ 755a8558 (commit before #3595) and got failures at about run 5-10.
In the playground, I was unable to replicate the same failing behavior. Came across cases where the cache object was flushed, but it wasn't continually flushed like previously (https://marimo.app/?v=0.10.18-dev16&slug=tmgyxl)
> tidy: make tests stricter to better capture cache state invalidation

- docs/guides/deploying/programmatically.md
- marimo/_cli/development/commands.py
- marimo/_messaging/context.py
- marimo/_plugins/ui/_impl/chat/chat.py
- marimo/_plugins/ui/_impl/tables/format.py
- marimo/_pyodide/bootstrap.py
- marimo/_runtime/app/kernel_runner.py
- marimo/_runtime/app_meta.py
- marimo/_runtime/context/types.py
- marimo/_runtime/requests.py
- marimo/_runtime/runtime.py
- marimo/_runtime/utils/set_ui_element_request_manager.py
- marimo/_server/api/endpoints/execution.py
- marimo/_server/export/__init__.py
- marimo/_server/models/models.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/requests.py
- marimo/_utils/lists.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_messaging/test_context_vars.py
- tests/_plugins/ui/_impl/tables/test_table_utils.py
- tests/_runtime/test_requests.py
- tests/_server/api/endpoints/test_execution.py
This adds `mo.ui.app_meta().request` object. This object is updated from the last request that ran the cell (`instantiate`, `run`, or `set_ui_element`).
This passes headers, queryparams, and the user object (if there is one). We omit `state` and `session` since that may not want to be exposed
> feat: add mo.ui.app_meta().request

- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/handlers.py
- marimo/_runtime/runtime.py
- marimo/_runtime/threads.py
- tests/_runtime/test_threads.py
- tests/conftest.py
This change lets `mo.Thread`'s actually communicate to the output area. Printing to stdout and stderr still does not work.
Related to #3532 
https://github.com/user-attachments/assets/c8dcc2ff-7e17-4da1-88ef-73510e6388d6
> fix: mo.Thread communication to output area

- marimo/_messaging/print_override.py
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/app/kernel_runner.py
- marimo/_runtime/app/script_runner.py
- marimo/_runtime/context/script_context.py
- marimo/_runtime/patches.py
- marimo/_runtime/runtime.py
- marimo/_runtime/threads.py
- tests/_runtime/test_runtime.py
- tests/_runtime/test_threads.py
- tests/conftest.py
Makes print statements work with mo.Thread by patching the print builtin.
Writing directly to `sys.stdout` and `sys.stderr` does not work, and writing directly to fds 1 and 2 does not work (so standard out from extension libraries like NumPy won't be work). Still, this might be good enough for many use cases.
Supporting `sys.stdout` and `sys.stderr` is possible and can be done in a follow up if there is a need, but prefer to wait and see.
Supporting fds 1 and 2 is possible but requires more work.
Fixes #3532
> fix: printing in mo.Threads

- marimo/_messaging/console_output_worker.py
- marimo/_messaging/ops.py
- marimo/_messaging/streams.py
- marimo/_runtime/runtime.py
- marimo/_runtime/threads.py
This change fixes a memory leak in run mode in which a kernel's globals memory appeared to not be freed on session (thread) exit. However, another (smaller) leak appears to still exist.
This change also makes sure to stop the stream's buffered writer thread when kernel exits.
Also, add a TODO for performance of VariableValue construction -- calling str() on some values, such as a bytearray of size 1GB, can make memory usage spike to 25GB.
Hopefully improves #3623
> fix: kernel globals memory leak in run mode

- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_runtime/runtime.py
- tests/_utils/test_file_watcher.py
Skip broadcasting variables, dataframes, and tables in post-execution hooks
> perf: skip variable broadcast in run mode

- CONTRIBUTING.md
- build_hook.py
- frontend/package.json
- frontend/pnpm-lock.yaml
- pyproject.toml
- tests/_server/api/endpoints/test_terminal.py
This allows you to do stuff like:
```
MARIMO_BUILD_FRONTEND=true uvx --with git+https://github.com/marimo-team/marimo.git@<branch-name> marimo edit
MARIMO_BUILD_FRONTEND=true uvx --with git+https://github.com/marimo-team/marimo.git marimo edit
MARIMO_BUILD_FRONTEND=true uvx --with git+https://github.com/marimo-team/marimo.git@ms/build-hook marimo edit
```
> chore: add hatch build hook to build marimo when installed from github

- marimo/_data/sql_summaries.py
- marimo/_sql/engines.py
- marimo/_sql/sql.py
- marimo/_sql/utils.py
- tests/_runtime/test_runtime.py
- tests/_sql/test_engines.py
> fix: duckdb querying dataframes with engines

- marimo/_messaging/streams.py
- marimo/_runtime/runtime.py
- marimo/_runtime/threads.py
- tests/conftest.py
When console output is not redirected, there is no reason for the stream to start a console writer thread. This affects both the main thread for a session as well as `mo.Thread`s.
> improve: run mode performance for streams

- frontend/e2e-tests/shutdown.spec.ts
- marimo/_output/formatting.py
- tests/_messaging/test_variables.py
- tests/_output/test_try_format.py
This uses repr() instead of str() for formatting. 
Context: https://discord.com/channels/1059888774789730424/1334996923261648998
Specifically this is what Jupyter does and helps disambiguate between `True` and `"True"`, `1` and `"1"`.
This also makes numpy results much better
> fix: correctness of formatting

- marimo/_plugins/ui/_impl/dates.py
- tests/_plugins/ui/_impl/test_dates.py
`date_range` should default to `start` and `stop` according to the docs but it doesn't. This fixes this.
Even though you did a nice job with encapsulating work with `hatch` and `make` I was still surprised how many steps are needed to get a working setup.
With pixi you could install all prerequisites, and replace both hatch and make. Let me know if you'd be interested in a PR for that.  
> fix: date range not defaulting to `start` and `stop`

- marimo/_ast/pytest.py
- marimo/_cli/file_path.py
- marimo/_output/formatting.py
- marimo/_plugins/ui/_impl/tables/format.py
- marimo/_save/ast.py
- marimo/_save/hash.py
- marimo/_server/api/endpoints/terminal.py
- marimo/_server/api/middleware.py
- marimo/_server/export/utils.py
- pyproject.toml
- tests/_output/formatters/test_sympy.py
- tests/_output/test_md.py
- tests/_output/test_try_format.py
- tests/_save/test_cache.py
- tests/_server/api/endpoints/test_ai.py
Enable `preview = true` to get some more helpful rules from ruff.
> chore: enable preview rules from ruff

- docs/guides/outputs.md
- examples/markdown/admonitions.py
- examples/markdown/details.py
- examples/markdown/dynamic_markdown.py
- examples/markdown/emoji.py
- marimo/_output/md.py
Show how to use details, admonitions, and emojis in our docs; also adds a few md usage examples.
Swaps out the deprecated admonitions extension with `pymdown.blocks.admonition` for consistency with details. Technically a breaking change but admonitions were not previously documented.
> docs: markdown extensions

- marimo/_ast/app.py
- marimo/_output/data/data.py
- marimo/_output/formatters/matplotlib_formatters.py
- marimo/_output/mpl.py
- marimo/_output/utils.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- marimo/_runtime/layout/layout.py
- marimo/_runtime/virtual_file.py
- marimo/_server/export/__init__.py
- marimo/_server/export/exporter.py
- marimo/_utils/data_uri.py
- tests/_cli/test_cli_export.py
- tests/_output/test_output_utils.py
- tests/_plugins/ui/_impl/test_data_explorer.py
- tests/_plugins/ui/_impl/test_table.py
- tests/_runtime/layout/test_layout.py
- tests/_server/export/test_exporter.py
- tests/_utils/test_data_uri.py
Fixes #3654 
Fixes #3653
This inlines layouts when exporting WASM, because we aren't shipping the layout files alongside them.
Also fixes a bug when exporting in the same directory.
> improvement: inline layouts when exported to wasm

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/language/python.ts
- marimo/_config/config.py
- marimo/_server/api/lifespans.py
- marimo/_server/lsp.py
- marimo/_server/main.py
- marimo/_server/start.py
This builds on top of LSP PoC https://github.com/marimo-team/marimo/pull/3414.
- Rework `CompositeLspServer`, enabling configuration on per-server basis
- Upgrade `codemirror-languageserver` to pull a fix for completion sorting
- ran `pnpm dedupe` to fix issues after installation of new version
- Extend LSP client from `codemirror-languageserver` to allow adding custom logic
- Emit `workspace/didChangeConfiguration` after `initialize` request succeeds to configure the server
- Change `documentUri` from `file:///marimo` to `file:///__marimo__.py` to fix completions of `marimo` library
- Add `marimo` to `plugins.jedi.auto_import_modules` list to ensure the completions are fast to show up on the first use
@mscolnick
> LSP support improvements

- tests/_save/test_cache.py
Noticed this test is failing 1/26 of the time. Allow flaky edge case, but threw in some logging
I wonder if it's possible to analysis github action logs in bulk? Would be nice to collect some stats about cache eviction stability
> flaky: add warning for flaky test opposed to failure

- marimo/_cli/convert/markdown.py
- marimo/_convert/utils.py
- marimo/_server/export/exporter.py
- marimo/_server/export/utils.py
- marimo/_tutorials/markdown_format.md
- tests/_cli/snapshots/sql-notebook.py.txt
- tests/_cli/test_markdown_conversion.py
SQL engines can be specified with `engine=` and column is now preserved in markdown blocks.
Documented changes in the tutorial file
@mscolnick
> fix: md format fix for columns and sql engine

- marimo/_runtime/packages/module_name_to_pypi_name.py
Fix the issue where `whisper` is not picked up as `openai-whisper`.
> Add openai-whisper to module name list

- marimo/_ast/app.py
- marimo/_utils/data_uri.py
- tests/_ast/test_app.py
This change makes it possible to create copies of an `app` object, for use with `app.embed()` to embed multiple independent copies of the app.
A new public method, `clone()`, is added on `App`.
Usage:
```python
from notebook import app
clone = app.clone()
```
```
await clone.embed()
```
Fixes #3398
> feat: embed independent copies of app objects

- marimo/_server/api/router.py
This PR fixes a naming issue in the router configuration where the packages endpoint was incorrectly named "terminal". The change ensures proper naming consistency with the actual endpoint functionality.
- Updated the router name from name="terminal" to name="packages" for the packages endpoint in marimo/_server/api/router.py
> fix(router): Correct router name from "terminal" to "packages"

- frontend/src/core/codemirror/language/__tests__/extension.test.ts
- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/markdown.ts
This should be a better default and more consistent. We create new markdown cells with `r"` so we should convert to python to markdown with the same string prefix. 
Fixes #3700
> fix: use r-string when converting to markdown

- marimo/_runtime/control_flow.py
Interrupt the kernel using a keyboard interrupt instead of a custom exception, for compatibility with libraries like databricks-connect that do custom handling of keyboard interrupts.
Fixes https://github.com/marimo-team/marimo/issues/3494
> compat: interrupt using KeyboardInterrupt

- frontend/src/css/app/codemirror.css
previously:
now:
I'm not a huge fan of the duplicate selection color too, but couldn't find a good color :/
> fix: set select colour to blue in dark mode

- docs/guides/editor_features/hotkeys.md
Update shortcut key listed in doc webpage from `Mod-Shift-h` to `Ctrl/Cmd-Shift-h` to resolve any ambiguity.
Aligns with format of other docs webpages like [here](https://docs.marimo.io/guides/editor_features/overview/?h=ctr#keyboard-shortcuts) and [here](https://docs.marimo.io/guides/editor_features/ai_completion/?h=ctrl%2Fcmd#custom-ai-rules).
> docs: Update appropriate keyboard shortcut

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/shortcuts/renderShortcut.tsx
- frontend/src/core/codemirror/ai/request.ts
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/config/feature-flag.tsx
- marimo/_server/errors.py
- tests/_server/ai/test_prompts.py
Fixes #3085
This adds continue.dev and cursor-like inline editing using https://github.com/marimo-team/codemirror-ai
This is activated with `Cmd+L`
https://github.com/user-attachments/assets/170790d4-9e31-435e-af79-bbbf0e9fa643
> feat: (experimental) inline edits

- frontend/src/css/app/Cell.css
Borderless mode isn't applied in dark mode, this is to fix that
> fix: apply borderless view in dark mode

- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- frontend/src/plugins/impl/anywidget/__tests__/AnyWidgetPlugin.test.ts
Only send updates of the changed state, otherwise will send the full data when e.g. selection changes
cc @manzt
> fix: anywidget partial updates

- marimo/_messaging/cell_output.py
- marimo/_runtime/requests.py
- marimo/_server/api/endpoints/ws.py
`marimo -d` can be quite noisy because it prints out the output/data/code. This reduces that
> chore: less noisy debug

- examples/frameworks/fastapi-endpoint/README.md
- examples/frameworks/fastapi-endpoint/main.py
- examples/frameworks/fastapi-endpoint/notebook.py
This is a simple example of how to use FastAPI with marimo. This example turns marimo notebooks into an API endpoint, which can be embedded in any FastAPI app.
- Turning functions defined in a notebook into an API endpoint
- Overriding global variables and returning cell outputs
> example: turn a notebok into api endpoints

- frontend/src/components/editor/actions/useHideAllMarkdownCode.ts
- frontend/src/components/editor/actions/useNotebookActions.tsx
QOL action to quickly hide all markdown. Even though we may auto-make markdown hidden at first, this can also help fix older notebooks.
> improvement: hide all markdown action (dropdown and command palette)

- marimo/_output/formatters/bokeh_formatters.py
- marimo/_smoke_tests/third_party/holoviews_scatter.py
This makes the bokeh formatter more specific, only picking up `Plot` instances. Fixes an issue in which Renderer objects returned by functions like `p.scatter(...)` were incorrectly output as blank outputs.
Matches Jupyter:
Context: https://github.com/bokeh/bokeh/issues/13817#issuecomment-2654910127
> fix: more specific bokeh formatter

- docs/guides/deploying/programmatically.md
- marimo/_runtime/requests.py
- marimo/_server/api/auth.py
- marimo/_server/api/middleware.py
- marimo/_server/main.py
- marimo/_smoke_tests/requests.py
- tests/_messaging/test_context_vars.py
- tests/_runtime/test_requests.py
- tests/_server/api/endpoints/test_execution.py
- tests/_server/api/test_auth.py
This overrides the `AuthenticationMiddleware` to preserve the upstream `user` object. Also adds a 'meta' field to let authors include more meta
> fix: preserve user defined user in mo.app_meta().request

- docs/guides/configuration/index.md
- docs/guides/configuration/theming.md
- examples/misc/custom_configuration.py
- marimo/_cli/sandbox.py
- marimo/_config/config.py
- marimo/_config/manager.py
- marimo/_config/reader.py
- marimo/_config/secrets.py
- marimo/_utils/scripts.py
- tests/_cli/test_sandbox.py
- tests/_config/test_manager.py
- tests/_config/test_reader.py
- tests/_utils/test_scripts.py
Fixes #2885
Fixes #2774
This adds inline script metadata (PEP 723) support for marimo configuration, similar to our `pyproject.toml` config.
e.g. can add:
```
```
to the top of the script to add per-notebook configuration. the precedence is
**Script config > pyproject.toml config > user config**
> feat: allow marimo configuration in notebook.py as script metadata (per PEP 723)

- marimo/_output/formatters/bokeh_formatters.py
- marimo/_smoke_tests/bokeh_figure.py
Patches bokeh.plotting.show() to display its first argument in the output area. Other arguments are ignored. This is similar to our patch of `IPython.display.display`.
Not an elegant fix, but should work for many use cases. The proper fix would be to support `bokeh`'s `output_notebook()` — I believe this uses `IPython.display.publish_display_data`under the hood, which we don't yet support.
cc @bryevdv
> fix: basic support for bokeh.plotting.show

- tests/_ast/test_app.py
A couple of app composition tests have been intermittently failing on CI, but I can't reproduce them locally. Some modifications to tests to try to debug/deflake.
- check if set ui element succeeds
- remove randomness
> chore: try to debug/deflake app comp tests

- frontend/src/components/data-table/TableActions.tsx
- frontend/src/components/data-table/__test__/columns.test.tsx
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/data-table.tsx
- frontend/src/components/data-table/types.ts
- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/ibis_table.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_plugins/ui/_impl/tables/selection.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_smoke_tests/dataframe.py
- marimo/_smoke_tests/dataframes/dicts_vs_dfs.py
- marimo/_smoke_tests/tables/booleans.py
- marimo/_smoke_tests/tables/complex_types.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
- tests/_plugins/ui/_impl/tables/test_ibis_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_plugins/ui/_impl/tables/test_selection.py
- tests/_plugins/ui/_impl/test_table.py
Fixes #3610
Previously we would reset selection on sort/filter/search because we didn't have a stable row id for selection. Now, for some dataframes, we add an internal selection column that is opaque to the user but allows us to keep track of the selection across sorting/filtering/searching.
This only works for eager dataframes since we can give them indexes. This won't work for dict/list or lazy dataframes like ibis - for these, we revert to the old behaviour.
> improvement: add index column for stable selection in table, persist across search/filter/sort

- marimo/_plugins/ui/_impl/from_panel.py
`from_panel` was using a private panel API that was recently removed; this caused our tests to fail and presumably broke our Panel integration.
This PR updates the plugin to use a public alternative, copying a recent change made in Panel.
Context: https://github.com/holoviz/panel/pull/7716/
(cc @philippjfr)
> fix: from_panel using private APIs

- frontend/src/plugins/core/registerReactComponent.tsx
- frontend/vite.config.mts
- marimo/_server/templates/templates.py
- marimo/_smoke_tests/theming/custom.css
- marimo/_smoke_tests/theming/custom_css.py
- tests/_server/templates/snapshots/export4.txt
Fix #3816 
This adds a magic title that if starts with `marimo`, then we copy it to our shadow dom. While a bit fragile, it's not too magical.
> fix: copy custom stylesheet

- marimo/_server/api/auth.py
- tests/_server/api/endpoints/test_execution.py
- tests/_server/api/test_auth.py
We don't want to override the user, if it is `None`
> fix: don't override user if it is None

- marimo/_ast/app.py
- marimo/_ast/cell_manager.py
- marimo/_server/sessions.py
- tests/snapshots/api.txt
With multiple clients. It's possible they try to remove each other at the same time from different callsites, so this adds an extra check
> fix: safer check before removing session

- marimo/_output/formatters/iframe.py
- marimo/_output/formatters/repr_formatters.py
- marimo/_smoke_tests/third_party/_treescope.py
- tests/_output/formatters/test_formatters.py
- tests/_output/formatters/test_iframe.py
Fixes #3848
We currently don't parse/run `<script>{content</script>` tags in the frontend. Mostly because we don't want to call `eval`. 
We do allow running arbitrary JS, still, when you pass ``<script src={"https..."} />`
This change at least puts the first case (without a `src` attribute) in an `iframe`. This feels safer and easier to move to away from (rather than the other way)
> improvement: auto iframe html output with <script/> tags

- marimo/_runtime/marimo_browser.py
- marimo/_runtime/patches.py
- marimo/_runtime/runtime.py
- tests/_runtime/test_patches.py
`import webbrowser.open` seems to be broken in WASM (which is fine, I think opening pages is potentially dangerous)- so this loads in a hook to insert an iframe into output if webbrowser is called instead of failing. As a result, the following code now works
```python
import antigravity
```
but with some marimo tweaks that might make for good social engagement on 25/04/01
(PS: this needs a static upload)
Had a spare hour and noticed it when looking through cpython/Lib
Let me know if it's too irreverent and I can walk back the feature- but seems enabling this seems like full python support to me
> compat: Register webbrowser.open hook for pyodide

- marimo/_cli/file_path.py
- marimo/_config/manager.py
If the file encoding is not specified when reading a file, it may cause issues on Windows platforms in certain Asian regions. If the file contains non-ANSI characters, such as Chinese, it can result in a decode error.
---
I have read the CLA Document and I hereby sign the CLA
---
On Windows platforms in Asia, the default file encoding is specific to the region. For example, in Taiwan, the default encoding is CP950. However, Python files are now stored using UTF-8 encoding. If the file content contains only ANSI characters, there will be no issues. However, if a file containing Chinese characters is read using the default encoding, a decode error will occur because Chinese characters encoded in UTF-8 cannot be decoded using CP950. Therefore, this modification primarily adds an explicit …
> Specify the encoding for reading files to keep from encoding error for some Asian Windows platform.

- marimo/_cli/cli.py
- marimo/_tutorials/__init__.py
- marimo/_utils/marimo_path.py
- tests/_ast/test_app.py
- tests/_cli/test_cli.py
This lets `marimo edit` read piped notebook files, e.g.:
```
marimo convert notebook.py | marimo edit
```
Unfortunately, this isn't supported on Windows because `marimo edit`:
* We need to support `marimo edit`, `marimo edit FILENAME`, `... | marimo edit`. 
* That means we need to distinguish between the first and third options, which requires checking if `stdin` is non-empty in a non-blocking way. This isn't possible in Windows as far as I can tell.
> feat: support unix-style piping for marimo edit

- frontend/src/core/dom/uiregistry.ts
- marimo/_plugins/ui/_core/ui_element.py
- tests/conftest.py
This somewhat reverts https://github.com/marimo-team/marimo/pull/3061
While this may be useful for CI, it can break session caching introduced in #3807 
We can enable this `"deterministic" random ids` via env variable if it is desired again.
> fix: non-deterministic random object-ids for session caching

- frontend/src/plugins/impl/chat/ChatPlugin.tsx
- frontend/src/plugins/impl/chat/chat-ui.tsx
- marimo/_plugins/ui/_impl/chat/chat.py
- tests/_plugins/ui/_impl/chat/test_chat.py
Fixes #3763.
Pass in initial messages to the frontend and call `get_chat_history` to get initial messages. Keep the state in the backend and add `delete_chat_history` and `delete_chat_message` from the frontend.
@mscolnick
> fix: persist chat messages

- marimo/_output/hypertext.py
- tests/_output/test_hypertext.py
Fixes a bug in `Html.__format__` when the provided html text has newlines _inside_ an html tag.
Previously, newlines were effectively removed when formatting an Html object. This breaks in cases where html tags are split across multiple lines. For example,
```python
Html("""
<div
style="..."
></div>
""")
```
> join newlines with spaces in Html.__format__

- frontend/src/components/datasources/datasources.tsx
A minor UI fix so that when searching and you collapse the db/schema, the css doesn't apply wrongly. It should only apply when it's expanded + selected.
@mscolnick
> fix: only apply css when selected & expanded for db & schema

- frontend/src/plugins/impl/DataTablePlugin.tsx
> fix: don't show data-types for dict/list tables (again)

- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/ai/completion-utils.ts
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/sql.ts
- frontend/src/utils/__tests__/lru.test.ts
- frontend/src/utils/lru.ts
This brings the new datasources schemas to SQL completion in the SQL cells as well as `@` referencing them in the AI inputs
Couple todos, for later:
> improvement: bring back SQL schema completion and AI '@' reference for datasources

- docs/guides/testing/pytest.md
- marimo/_ast/cell.py
- marimo/_ast/cell_manager.py
- marimo/_ast/compiler.py
- marimo/_ast/pytest.py
- tests/_ast/test_pytest.py
- tests/conftest.py
@koaning had the great idea of bringing tests editor side.
Part of that means being able to run tests that are runtime dependent.
This statically extracts tests and creates a wrapper that will call run on execution.
A little separate from the top level function push, but complimentary.
Works with a bit of a hack that includes injecting TestClasses into scope for pytest.
This was more of a proof of concept I ended up pushing to completion.
I think it's a useful addition- but not anything we explicitly put on our roadmap.
Happy to mark as draft and rethink this
pytest on:
```python
@app.cell
async def _(pytest, x, y, Z):
@pytest.mark.xfail(
reason=("To ensure this doesn't just eval."),
raises=AssertionError,
strict=True,
)
def test_independence():
assert x + y == 0
def …
```
> feat: koaning/motest parity (pytest in blocks)

- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- frontend/src/plugins/impl/anywidget/__tests__/AnyWidgetPlugin.test.ts
Fixes #3888
Support this usage: https://github.com/habemus-papadum/anydiff/blob/main/src/anydiff/index.js#L60
cc @manzt, is this correct. I didn't see any where in the docs or typings that `on("change")` without a key should be a thing. but apparently this works in Jupyter (maybe for the wrong reason)
cc @habemus-papadum
> fix: anywidget emit on any change (without a key)

- marimo/_output/formatters/bokeh_formatters.py
FIX:  marimo don't render GirdPlot as it isn't subclass of Plot
Relax the input type of the formatter from `bokeh.models.Plot` to `bokeh.models.Model|bokeh.document.Document`, according to `bokeh.embed.file_html(models: Model | Document | Sequence[Model])`
> improvement: Support Format for more `Bokeh` objects

- marimo/_ast/compiler.py
- tests/_ast/test_compiler.py
- tests/_runtime/test_runtime.py
This changes our compiler to not inherit the main program's compiler flags; in particular this means that user code is not compiled with deferred/stringified annotations (`__future__.annotations`).
This is technically a breaking change, but it better matches user code.
Note that it is not currently possible to save a notebook file with `from __future__ import annotations`, since Python requires future imports to be at the top of the file. If people want deferred annotations we can make it configurable.
Fixes #3915, #3312
> fix: don't compile code with annotations future flag

- marimo/_ast/cell.py
- marimo/_runtime/app/kernel_runner.py
- marimo/_runtime/runner/hooks_preparation.py
- marimo/_runtime/runtime.py
- tests/_runtime/reload/test_module_watcher.py
- tests/_runtime/test_manage_script_metadata.py
- tests/_runtime/test_runtime.py
Fixes #3438
Previously, when autorun on startup was disabled, running a cell wouldn't transition it out of stale. For long-running cells, this would give the incorrect impression to the user that their cell had not been submitted for execution.
This change updates the kernel to register uninstantiated cells as stale, so they are correctly transitioned out of stale on run.
> fix: cell staleness when autorun on startup is off

- frontend/pnpm-lock.yaml
- frontend/src/components/editor/output/MarimoErrorOutput.tsx
- marimo/_ast/errors.py
- marimo/_ast/visitor.py
- marimo/_cli/development/commands.py
- marimo/_messaging/errors.py
- marimo/_runtime/runtime.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_ast/test_visitor.py
Provide more helpful error messages for import star and multiple definition errors, explaining the reasoning behind these errors.
This PR also changes error description text to be muted instead of red, matching the accordion text, based on feedback that too much red can be stressful. Headlines (which describe the exception type) are still red and bold.
> improve: error messages for import *, multiple definition

- frontend/src/components/chat/chat-panel.tsx
Per discussion on Slack, updated the placeholder to make it clear that the context is only for tables and dataframes for now.
> Better placeholder for dataframe @ context

- marimo/_ast/codegen.py
Explicitly catch IOError for notebook on top level serialization I was tinkering with: https://marimo.app/l/n0s9hn
> fix: top level function serialization broke in wasm example

- docs/guides/configuration/snippets.md
- docs/guides/working_with_data/sql.md
- frontend/src/components/datasources/datasources.tsx
- marimo/_config/config.py
- marimo/_sql/get_engines.py
- openapi/api.yaml
- openapi/src/api.ts
Not sure what you think about this, but this may be a temporary solution for the issue here: https://discord.com/channels/1059888774789730424/1338959377411084390/1344967482577915905. 
By default, we do not introspect tables, we let users opt-in by changing config.
For future MRs:
> fix: default to opt-in for introspection of tables

- frontend/src/core/codemirror/language/panel.tsx
As discussed in #3464, there is currently a bug in the output-variable input field on SQL cells.
The problem is that if you change the variable name and do shift-enter, the name change doesn't propagate to `notebookState` and therefore doesn't persist to disk. When the same notebook is opened again later, therefore, these variable names are lost.
I believe that the reason for this is that there's some kind of race condition between the cell evaluation that occurs when you do shift-enter, and the state-update operation that is supposed to occur in response to the same event. However, I have not been able to track down the root cause of this behavior.
This PR makes the smallest possible change to workaround this problem. It circumvents the race condition by making the variable-update happen …
> Fix blur behavior for output-variable-name input field

- frontend/src/css/md.css
This change adds a background color for code blocks in markdown to improve readability.
Example:
> improve: background color for markdown code blocks

- frontend/src/components/datasources/components.tsx
- frontend/src/components/datasources/datasources.tsx
- frontend/src/components/editor/ai/__tests__/completion-utils.test.ts
- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/ai/completion-utils.ts
- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/sql.ts
- frontend/src/core/datasets/__tests__/all-tables.test.ts
- frontend/src/core/datasets/data-source-connections.ts
- marimo/_data/models.py
- marimo/_sql/engines.py
- marimo/_sql/get_engines.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_sql/test_duckdb.py
- tests/_sql/test_get_engines.py
- tests/_sql/test_sqlalchemy.py
Follow up from #3898 , add the shortest and correct completions to AI & sql completions panel. 
Adds default schema & db introspection + update API.
https://github.com/user-attachments/assets/d418f969-2541-4a59-9b54-c8535c8aacdc
- For default schema & db, we just surface the table name as the completion. Else, use `schema_name.table_name`, for diff databases, use `db_name.schema_name.table_name`
- Small update to the subtext UI
added PK & IDX, and also boosted local tables so that it would appear first
Maybe:
> improvement: better sql completions

- marimo/_messaging/cell_output.py
- marimo/_utils/parse_dataclass.py
- tests/_messaging/test_cell_output.py
- tests/_server/export/test_exporter.py
- tests/_utils/test_parse_dataclass.py
This improves the parsing from #3977, so that we get back `Error` objects instead of a dictionary. 
This makes the parser a bit more strict which does some validation as well. It used to only validate fields, but now validates some values.
> fix: improved parsing of Error object

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/rtc/__tests__/cell-manager.test.ts
- frontend/src/core/codemirror/rtc/cell-manager.ts
- frontend/src/core/codemirror/rtc/extension.ts
- frontend/src/core/config/feature-flag.tsx
- marimo/_server/api/endpoints/ws.py
- marimo/_server/api/lifespans.py
- marimo/_server/print.py
- pyproject.toml
- tests/_server/api/endpoints/test_ws.py
This fixes a few bugs with RTC and syncing. 
1. First the code duplication came from the WebsocketProvider disconnecting after some timeout. Adding the resync timer prevents the disconnect. 
2. Fixes 2 bugs showing stale cells when they were run by another user.
3. Fixes a bug when bringing back a deleted cell
4. Adds print output for the feature flags, so people which are enabled.
5. Changes `rtc` to `rtc_v2` so people can opt back in
> fix: rtc code duplication and disconnection, other syncing bugfixes

- marimo/_ast/cell_manager.py
- marimo/_server/export/exporter.py
- marimo/_server/file_manager.py
- tests/_server/api/endpoints/test_export.py
- tests/_server/api/endpoints/test_resume_session.py
- tests/_server/test_file_manager.py
Fixes #3992 
When we added `--watch` with remapping cell ids (https://github.com/marimo-team/marimo/pull/3451), this didn't make the `ID` of the `Cell` itself (just in the map).  And this failed when updating the `graph`, so there was an inconsistency causing #3992 
This now fixes that and adds a few tests
> fix: auto-export ipynb from reload/remapping

- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- frontend/src/plugins/impl/anywidget/__tests__/AnyWidgetPlugin.test.tsx
- marimo/_smoke_tests/issues/3962-anywidget-partial-state-2.py
- marimo/_smoke_tests/issues/3962-anywidget-partial-state.py
Fixes #3962
Previously, if the JS of an anywidget didn't change, we skipped a re-render. 
This could cause issues if there is initialization code in the render function, because it would not get called when the widget is created again. 
Instead we not just re-render the anywidget whenever it gets created.
> fix: anywidget should re-render whenever re-created

- marimo/_cli/file_path.py
- tests/_cli/test_cli.py
> fix: use encoding='utf-8' for remove marimo notebooks

- marimo/_output/formatters/tqdm_formatters.py
Implements the easier of the two proposed solutions in #4016.
`tqdm.notebook.tqdm` being assigned as a function instead of a class was breaking consumers intending to subclass it. With this update, the patch object's semantics remain unchanged - when called, it parses its inputs and returns a Marimo progress_bar. It's just converted from a function that returns the progress_bar to a subclass of the progress_bar itself.
Before: See example at the bottom of #4016.
After:
@akshayka - https://github.com/marimo-team/marimo/pull/1922
> Convert tqdm.notebook.tqdm monkey patch function to a class

- frontend/src/components/data-table/cell-selection/types.ts
- frontend/src/components/data-table/data-table.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
As a follow up to https://github.com/marimo-team/marimo/pull/3725, I noticed that the cell are not unselect (visually) when change the `selection` in Python code.
This is solved by passing in the cell state, similar to how the rowSelection is passed down.
@mscolnick
> Pass cellSelection to table state

- docs/guides/working_with_data/sql.md
- marimo/_config/config.py
- marimo/_islands/_island_generator.py
- marimo/_sql/engines.py
- marimo/_sql/get_engines.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_save/test_cache.py
- tests/_sql/test_sqlalchemy.py
This adds 'auto' as an option for `auto_discovery`, which is nice for things like `sqlite` so these can be discovered while Snowflake or Bigquery don't need to be.
Should we also do this for `columns`?
cc @Light2Dark 
Cons:
* this could add confusion with the double `auto`
> improvement: add 'auto' as an option for auto_discovery

- frontend/src/components/editor/chrome/wrapper/machine-stats.tsx
psutil docs say percent is (total - available) / total * 100, and seems like `used` not necessarily equal to total - available
https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory
Fixes #4051
> fix: memory available machine stats

- docs/guides/publishing/playground.md
Fix docs for embedding playground notebooks from code.
> fix: embedding from code

- marimo/_output/show_code.py
- tests/_output/test_show_code.py
Added a ``code_first`` boolean to ``marimo.show_code``  to control the order of code and results (default: False, maintaining previous behavior). A new setting for this, as requested in part 2 of the issue, I think is unnecessary.
Related Issue: #3997 
@mscolnick
> Adding a boolean to see the code first, then result in marimo.show_code

- frontend/pnpm-lock.yaml
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/language/extension.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/language/types.ts
- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- marimo/_config/config.py
- marimo/_server/lsp.py
- openapi/api.yaml
- openapi/src/api.ts
Improves LSP integration
- fixes mypy compatibility in face of https://github.com/python/mypy/issues/4746
- fixes a random websocket corruption when redirecting to both stdout and stdin of pylsp to the same sink
- adds `enable_{plugin}` settings
- adds defaults for rules
- moves settings for pylsp closer to when pylsp endpoint is being used to make `NotebookLanguageServerClient` server-agnostic
@mscolnick
> LSP: fix mypy compatibility, websocket corruption, add settings and defaults

- frontend/src/core/wasm/PyodideLoader.tsx
We have some logic that would wait for output when the code is hidden. You could only previously set this from the URL param. We later added to do it from the HTML config, but did not update this logic. 
Fixes #4069
> fix: wait longer in pyodide to render output

- frontend/src/components/app-config/common.tsx
- frontend/src/components/app-config/optional-features.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/codemirror/language/__tests__/extension.test.ts
- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/sql.ts
- frontend/src/core/config/capabilities.ts
- frontend/src/core/kernel/handlers.ts
- marimo/_dependencies/dependencies.py
- marimo/_dependencies/errors.py
- marimo/_messaging/ops.py
- marimo/_runtime/runner/cell_runner.py
- marimo/_runtime/runtime.py
- marimo/_server/api/endpoints/ai.py
- marimo/_sql/engines.py
- marimo/_sql/sql.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_dependencies/test_dependencies.py
- tests/_runtime/test_manage_script_metadata.py
Fixes #3113 
* Remove 'SQL' from KernelCapabilities. If the user tries to run SQL, we will not prompt to install the necessary deps.
* We can now prompt the user for multiple missing deps
* Update `ai` endpoints to throw missing modules so that we can prompt the user as well.
* `Optional Dependencies` panel in the settings menu to show the enabled features and install. This is both for education and ease of installation.
I didn't want to put everything in `KernelCapabilities` since its another source of truth, and requires checking it on startup, which could be a waste of resources/blocking
> improvement: better prompt-to-install when missing deps, grouped installed, Optional Features panel

- frontend/src/core/config/config-schema.ts
Allow any characters in the HTML title.
#1264 added the ability to set a notebook title, in turn setting `document.title`. Currently there is a fairly strict schema in place:
https://github.com/marimo-team/marimo/blob/62cf74d7ae9e8973baa1a0479980c9caa8aaeba6/frontend/src/core/config/config-schema.ts#L168-L170
This means that a title such as "My App 2.0" will get parsed as "My App 2".
The `title` of an HTML document does not have any such restrictions. The HTML spec says to use ["string replace all"](https://dom.spec.whatwg.org/#string-replace-all) when [setting the `title` attribute](https://html.spec.whatwg.org/multipage/dom.html#document.title), which will create a `Text` node, which cannot contain HTML, so anything goes.
Screenshot:
I did not add any test. Let me know if you need that. …
> Allow any characters in HTML title

- marimo/_runtime/runtime.py
Check that we haven't tried installing a package already, before adding it to the list of missing packages.
> fix: only add packages that we haven't already tried installing

- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/sql.ts
Update the SQL language adapter to accept cells that start with hash comments. These comments are preserved on transform back to Python.
While people don't typically write the Python for SQL cells directly, AIs do; this helps accommodate verbose AIs.
> improve: allow header comments in SQL cells.

- marimo/_plugins/ui/_impl/from_anywidget.py
- tests/_plugins/ui/_impl/test_anywidget.py
We cache widgets, but i just came across one that is unhashable (not clear why it is), but in case it is, better to just skip the caching (which is used when rendering the widget twice in two different places)
Related to https://github.com/marimo-team/marimo/issues/4091, but doesn't fix it
> fix: when a widget is unhashable don't cache it

- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
Fixes #4101
This forces re-mounting (not just re-renders) when an anywidget's cell is run again. This makes things flash (un-mount, re-mount), but this is safest because they are 3rd party plugins that we don't have control over.
> fix: always re-mount anywidgets to clear state

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- frontend/src/utils/lru.ts
Add go-to-definition for external files, upgrade our `@marimo-team/codemirror-languageserver`
> improvement: open external document on go-to-definction when LSP is enabled

- marimo/_server/session/serialize.py
- tests/_server/session/test_serialize_session.py
Errors in the output area need to have mimetype application/vnd.marimo+error.
Previously errors were incorrectly deserialized, causing the frontend to render a "Something went wrong" error boundary that wouldn't go away even on re-run.
(cc @delennc)
> fix: session cache error deserialization

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/codemirror/rtc/__tests__/cell-manager.test.ts
- frontend/src/core/codemirror/rtc/cell-manager.ts
- frontend/src/core/codemirror/rtc/extension.ts
- marimo/_server/api/endpoints/ws.py
Fixes a bug where code was duplicated, and when cells were initialized with outside code (e.g. from a snippet)
Another attempt to squash #3554
> fix: RTC duplication bug

- frontend/src/core/cells/cells.ts
- frontend/src/utils/__tests__/id-tree.test.ts
- frontend/src/utils/id-tree.tsx
When using RTC, this will try to keep the column and collapse state intact
> fix: try to preseve the columns/collapse state when new ids come in

- .github/workflows/notify-readme-owners.yml
This adds a workflow that notifies owners of our readme trasnlations when a pull request on README.md is merged.
The notification is a comment on the merged pull request.
> chore: notify readme owners when README.md is updated

- marimo/_save/save.py
- marimo/_utils/with_skip.py
- tests/_save/test_cache.py
@mscolnick re https://github.com/marimo-team/marimo/pull/4038 tests only seem to be failing in coverage. Seems to be because `with_block` does funny things with sys.trace which coverage uses. This mitigates it a bit- but seems to be a bit strange with just the first test which seems to have a messed up code pointer (which may well be a python bug? Seems to always fail on whatever the first test is)
> fix: Enable coverage of _save tests

- marimo/_cli/export/commands.py
- tests/_cli/test_cli_export.py
Fixes #4121
We were accidentally exporting twice (once in the sandbox and once out)
> fix: export ipynb with sandbox

- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
Download is broken for tables because the attribute `_has_any_selection` does not exist. This PR fixes that and adds tests for `download_as` (which I think doesn't exist atm).
> fix: download for tables

- marimo/_runtime/packages/module_name_to_pypi_name.py
When using `import docx` in a marimo notebook, the package discovery detects and installs the[ `docx` package from pypi](https://pypi.org/project/docx/).
That package, though, is unmaintained since 2014, and the repository archived since 2018.
The successor of that package, that still imports as `docx`, is [`python-docx`](https://pypi.org/project/python-docx/) from the same authors.
added the mapping docx -> python-docx to `module_name_to_pypi_name`.
@akshayka
> fix: map docx module to python-docx package

- docs/guides/exporting.md
The script proposed to export multiple notebooks as html-wasm is using the `public` directory as destination,
but that folder is the one that gets copied over to the destination directory to include public assets, resulting in a recursive copy of the same files inside `public/public`.
Using a different output directory like `site`  (I used it because is the default for mkdocs) solves the issue.
changed the output directory of the example script to "site" instead of "public".
@mscolnick
> docs: fix paths for "Exporting multiple notebooks" scripts

- marimo/_runtime/runner/cell_runner.py
We could show a better error when an imported module matches a filename.
This might be crude, but maybe it can inspire a better fix :>
> improvement: add error message when the imported module matches a filename

- marimo/_runtime/packages/module_name_to_pypi_name.py
Another one 😉 
`pdfminer` latest release was on Nov 25, 2019 and the project was archived on Apr 15, 2024.
On the other hand, `pdfminer.six` is still maintained, so this PR sets it as the default choice for the `pdfminer` import.
added pdfminer import to pdfminer.six package mapping.
@akshayka
> fix: map pdfminer module to pdfminer-six package

- docs/guides/editor_features/ai_completion.md
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/core/codemirror/copilot/extension.ts
- frontend/src/core/config/config-schema.ts
- frontend/src/core/kernel/messages.ts
- marimo/_ai/_convert.py
- marimo/_cli/development/commands.py
- marimo/_config/config.py
- marimo/_server/ai/prompts.py
- marimo/_server/ai/providers.py
- marimo/_server/api/endpoints/ai.py
- marimo/_server/models/completion.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_server/api/endpoints/test_ai.py
Fixes #2193 
This adds a "custom" field to the completion config for custom LLMs, such as Ollama.
```python
class CompletionConfig(TypedDict):
"""Configuration for code completion.
A dict with key/value pairs configuring code completion in the marimo
editor.
**Keys.**
- `activate_on_typing`: if `False`, completion won't activate
until the completion hotkey is entered
- `copilot`: one of `"github"`, `"codeium"`, or `"custom"`
- `codeium_api_key`: the Codeium API key
- `api_key`: the API key for the LLM provider, when `copilot` is `"custom"`
- `model`: the model to use, when `copilot` is `"custom"`
- `base_url`: the base URL for the API, when `copilot` is `"custom"`
"""
activate_on_typing: bool
copilot: Union[bool, Literal["github", "codeium", "custom"]]
codeium_api_key: …
```
> feat: custom inline completions provider (ollama, anthropic, openai, gemini)

- frontend/src/core/saving/save-component.tsx
We used to have this but i think i regressed it in a refactor
> fix: add beforeunload event listener to prevent accidental closure on unsaved changes

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/Output.tsx
- frontend/src/components/editor/__tests__/data-attributes.test.tsx
- frontend/src/components/editor/renderers/grid-layout/grid-layout.tsx
- frontend/src/components/editor/renderers/slides-layout/slides-layout.tsx
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- frontend/src/components/scratchpad/scratchpad.tsx
- frontend/src/core/cells/__tests__/cell.test.ts
- frontend/src/core/cells/cell.ts
- frontend/src/css/app/Cell.css
Decrease opacity of stale loading outputs to make staleness more easily parsed visually.
When cells are queued or running (not edited), it needs to be clear that their output is loading and stale. This is important both for editing notebooks and running long-running cells that have big outputs, as well as for app view.
> improve: indication when cell output is loading

- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/components/editor/cell/cell-actions.tsx
- frontend/src/components/editor/cell/cell-context-menu.tsx
- frontend/src/components/editor/renderers/vertical-layout/__tests__/useDelayVisibility.test.ts
- frontend/src/components/editor/renderers/vertical-layout/useDelayVisibility.ts
- frontend/src/utils/__tests__/cell-urls.test.ts
- frontend/src/utils/cell-urls.ts
Closes #3346
Add a new cell action to copy a link to it, and logic to scroll to the cell on startup.
This does require naming the cell. We could maybe later add using the cell-id, but that does change when the order changes.
> feat: add scroll to cell

- marimo/_ast/sql_visitor.py
- tests/_ast/test_sql_visitor.py
This warning was logged with the query: 
```sql
insert into table1 (column1) select distinct column1 from table2 order by random();
```
The result looks correct, so I think it should be ok to remove this warning. cc @Light2Dark
> fix: remove dml warning; add test

- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
Fixes #4173 
This fixes the force-render for anywidget in wasm. Since we pass the esm as a data-uri instead of a URL, we need a better key that causes the re-render.
> fix: anywidget re-render in wasm

- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
Another follow-up on https://github.com/marimo-team/marimo/pull/3725, this time to add support for initial cell selection.
`initial_selection` can also be a list of dict like `initial_selection = [{"rowId":"0", "columnName":"metric2"}, {"rowId":"1", "columnName":"id"}]` after this PR.
@mscolnick
Let me know if this needs further tweaks.
> Add support for initial cell selection

- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
For tables with 10 or fewer rows, don't show column summaries by default. For such little data they are usually not needed and just take up space.
> improve: hide column summaries for very small tables

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/app-config/optional-features.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/config/extension.ts
- frontend/src/core/codemirror/copilot/__tests__/getCode.test.ts
- frontend/src/core/codemirror/copilot/client.ts
- frontend/src/core/codemirror/facet.ts
- frontend/src/core/codemirror/language/__tests__/extension.test.ts
- frontend/src/core/codemirror/language/__tests__/utils.test.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/lsp/lens.ts
- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- frontend/src/core/config/config-schema.ts
- marimo/_config/config.py
- marimo/_server/api/endpoints/packages.py
- marimo/_server/lsp.py
- openapi/api.yaml
- openapi/src/api.ts
- pyproject.toml
- tests/_server/test_lsp.py
Upgrades @marimo-team/codemirror-languageserver to pick up some improvements and adds `DiagnosticsConfiguration` which for now just has enabled/disabled, but in future could include ignore keys
> improvement: diagnostics configuration, upgrade codemirror-languageserver

- frontend/src/components/editor/cell/code/cell-editor.tsx
Regression that we didn't delete from the backend (using the wrong delete callback)
> fix: delete from kernel when deleting using shift+delete

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/copilot/client.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/lsp/__tests__/notebook-lsp.test.ts
- frontend/src/css/app/App.css
- frontend/src/css/app/codemirror-completions.css
- frontend/src/css/app/codemirror.css
- frontend/src/css/globals.css
Coloring and more icons (a few icons were missing)
Also passes down the config to the codemirror-languageserver plugin.
> improvement: style auto-complete, pass down custom config

- docs/guides/editor_features/index.md
- docs/guides/editor_features/language_server.md
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/config/extension.ts
- frontend/src/core/codemirror/language/extension.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/language/types.ts
- marimo/_config/manager.py
- marimo/_server/api/middleware.py
- marimo/_server/lsp.py
- marimo/_server/start.py
- pyproject.toml
- tests/_server/test_lsp.py
Add docs and `marimo[lsp]` to pyproject toml. 
Also add warnings when LSP was requested but cannot be installed.
> experimental: add LSP docs and pyproject.toml requirements

- frontend/src/components/data-table/__tests__/__snapshots__/chart-spec-model.test.ts.snap
- frontend/src/components/data-table/chart-spec-model.tsx
- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/column-summary.tsx
- frontend/src/components/data-table/renderers.tsx
This change makes column summary charts smaller, both width and height, to prioritize fitting more table columns on the screen.
This change also replaces the manual bar width calculation and lets the bin sizes be determined by vega/the chart renderer.
Before: 
After:
> improve: smaller column summary charts

- frontend/src/components/data-table/__tests__/__snapshots__/chart-spec-model.test.ts.snap
- frontend/src/components/data-table/__tests__/chart-spec-model.test.ts
- frontend/src/components/data-table/chart-spec-model.tsx
- frontend/src/components/data-table/column-summary.tsx
- frontend/src/components/data-table/columns.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
* Updates bar charts (histograms) to be quantitative instead of nominal. This fixes an issue in which bars were incorrectly spaced.
* Expands the tooltip areas for bars so that it is possible to view tooltips for even very short bars, using zero opacity full-height bars.
This change does modify how nulls are rendered. I was unable to find a way to robustly layer null counts with a quantitative histogram. Instead, this PR proposes including a count of nulls by the dtype in the header.
Nulls:
Before (incorrect spacing, should not be uniform):
After:
> fix: column summary bars spacing, expand tooltips

- frontend/src/components/data-table/__tests__/__snapshots__/chart-spec-model.test.ts.snap
- frontend/src/components/data-table/chart-spec-model.tsx
- frontend/src/components/data-table/column-summary.tsx
For numerical histograms in column summaries, this PR renders the x-axis with Vega. This makes plots more legible, especially when histograms are sparse.
Some examples:
Large numbers:
> improve: show column summary histogram axes

- marimo/_data/charts.py
- marimo/_data/preview_column.py
- marimo/_output/formatters/altair_formatters.py
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- pyproject.toml
- tests/_output/formatters/test_altair_formatters.py
This defaults the altair charts to be full-width when a width is not given. While it is opinionated, i think it looks much better. 
This can be ignore by providing an actual width. 
This also adds typechecking for altair in our codebase
> improvement: default altair charts to full width, add typechecking

- marimo/_server/utils.py
Fixes one of the potential causes for #4067 
Marimo was getting completely stuck for me, waiting for a timeout that [will never happen](https://docs.python.org/3/library/socket.html#notes-on-socket-timeouts).
(At least for WSL - I have no idea if it worked in other OS, but if it did, I'm confused as for why that was not a problem)
@mscolnick suggested looking into that function in the linked issue
> fix: getting stuck waiting for socket to connect

- frontend/src/plugins/impl/DataTablePlugin.tsx
Add the chartSpecModel as a dependency on the memoized generated columns, fixing a bug in which nulls would sometimes not be rendered in column summaries.
> fix: nulls not showing when toggling app view

- frontend/src/plugins/impl/DataEditorPlugin.tsx
- marimo/_smoke_tests/tables/rich_elements.py
Fixes #4226 . Revert back to csv on the frontend. I could change to json on the backend, but json doesn't work as well for data editor.
I am also checking if we can make the vegaLoader smarter (doesn't need to know format / will correct the format when needed)
@akshayka  or @mscolnick
> fix: change back to csv parsing for data editor

- frontend/src/components/data-table/__tests__/columns.test.tsx
- frontend/src/components/data-table/mime-cell.tsx
- marimo/_output/hypertext.py
- marimo/_smoke_tests/tables/rich_elements.py
- tests/_output/test_hypertext.py
`serialized_mime_bundle` shows up in API docs since it's treated as a public attribute. This PR makes it private and hacks around to create a public copy.
example: https://docs.marimo.io/api/inputs/button/
@mscolnick
> improv: privatize mime bundle

- .github/workflows/dev-release.yml
- .github/workflows/marimo-bot.yml
- .github/workflows/playwright.yml
- .github/workflows/release.yml
- .github/workflows/test_be.yaml
- .github/workflows/test_be_dagger.yaml.skip
- .github/workflows/test_cli.yaml
- .github/workflows/test_fe.yaml
- frontend/src/components/data-table/__tests__/column_formatting.test.ts
- frontend/src/components/data-table/column-formatting/feature.ts
- frontend/src/components/data-table/column-summary.tsx
- frontend/src/utils/__tests__/numbers.test.ts
- frontend/src/utils/numbers.ts
- marimo/_smoke_tests/inputs/sliders.py
Fixes #4229
Don't round the slider when not scientific
> fix: don't round slider if not in scientific notation 

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- frontend/src/core/hotkeys/hotkeys.ts
- frontend/src/css/app/codemirror-completions.css
- tests/_plugins/ui/_impl/dataframes/test_handlers.py
Fixes #2080
* Add signature completion via configurable hotkey (`Mod+Shift+Space`) . 
* Signature parameter get sorted to the top
* Pass down configurable hotkeys to plugin
> improvement: LSP completion inside parens (), and Mod+Shift+Space for signature

- frontend/src/components/data-table/__tests__/__snapshots__/chart-spec-model.test.ts.snap
- frontend/src/components/data-table/chart-spec-model.tsx
- frontend/src/components/data-table/column-header.tsx
Fixes a formatting bug in which the x-axis ticks for numerical column summaries showed an unbounded number of decimals.
> fix: show at most two decimal points in column summary axes

- frontend/src/components/app-config/optional-features.tsx
- marimo/_server/ai/providers.py
- marimo/_server/api/lifespans.py
- marimo/_server/lsp.py
- marimo/_server/start.py
- tests/_server/test_lsp.py
Create the starlette route and ports for each LSP even if they are not configured in the settings, so we can easily turn them on without having to restart the server.
This is simpler and works for 2 LSPs, but can be made lazy if we need to support more than 2.
> improvement: allow turning on the LSP without restarting the server

- marimo/_plugins/stateless/audio.py
Added functionality to handle `numpy` array in mo.audio 
fixes #4197
@akshayka
> improvement : Adding functionality to handle numpy array as src in mo.audio simliar to ipython audio

- marimo/_sql/engines/duckdb.py
- marimo/_sql/engines/sqlalchemy.py
- tests/_sql/test_duckdb.py
The query fails to convert to polars: `select to_days(cast((current_date - DATE '2025-01-01') as INTEGER));`
so we should fallback to pandas conversion instead.
> fix: fallback to pandas sql

- examples/ui/table_advanced.py
- frontend/src/components/data-table/cell-styling/feature.ts
- frontend/src/components/data-table/cell-styling/types.ts
- frontend/src/components/data-table/data-table.tsx
- frontend/src/components/data-table/renderers.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
- tests/_plugins/ui/_impl/test_table.py
Hello, as asked on Discord, we are hoping to add some styling options to the cells of a data-table.
On the Python side, I'm adding a new function that returns a dictionary-style object to describe the cell's style. This nested array of styles is then sent to the client and utilized by another TanStack plugin.
In our Discord conversation, we discussed foreground and background colors. I opted for a style dictionary, which provides more options. I'm not set on this idea, so please share your thoughts on what you think is best.
This is still a work in progress, so I would appreciate your guidance in the right direction.
@mscolnick
> Styling cells

- frontend/src/components/data-table/cell-styling/types.ts
- frontend/src/components/data-table/data-table.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
There is a bug where you are unable to move to next pages in a table / sort / search without an error.
This also fixes styling for dataframes as the row_id is not sequential. Sorted dfs are not handled though.
@nojaf, just fyi if i missed something. I tested with a decently large dataset but may not be correct.
> fix: next page & styling of cells

- marimo/_runtime/packages/module_name_to_pypi_name.py
This pull request adds a module alias to map "ffmpeg" to "ffmpeg-python", enabling marimo to properly detect and install the correct Python package when ffmpeg imports are used in notebooks.
**Added an alias mapping** from "ffmpeg" to "ffmpeg-python" in the package alias configuration. This change allows marimo to:
1. **Correctly identify** the required package when users import the ffmpeg module
2. **Install the proper PyPI package** (ffmpeg-python) instead of attempting to install an incorrect package
3. **Improve user experience** by reducing installation errors and confusion
This is necessary because the module name (ffmpeg) differs from the package name (ffmpeg-python) that needs to be installed via pip.
> add an alias to ffmpeg-python module

- marimo/_server/api/endpoints/ws.py
- marimo/_server/session/serialize.py
- marimo/_server/sessions.py
- tests/_server/session/test_serialize_session.py
- tests/_server/test_sessions.py
This change adds cache invalidation to the session view restoration logic when autorun on startup is disabled. 
The cache is keyed on the notebook code and the marimo version. Invalidating on marimo version change may be more aggressive than needed, it is a proxy for plugin API changes; we can relax this in the future if needed.
> improve: cached session invalidation

- frontend/src/core/codemirror/markdown/__tests__/commands.test.ts
- frontend/src/core/codemirror/markdown/commands.ts
Fixes #4278. When copying/dropping base64 images, it will prompt you and subsequently save the image in the root directory.
Because it's not a react component, I wasn't sure how to use a custom prompt/popup box.
> improvement: support dropping or copying base64 image files

- lsp/package.json
- lsp/tsup.config.ts
- marimo/_server/lsp.py
Fixes #4263
- build copilot lsp as .cjs 
- pipe errors out
> fix: build copilot lsp as .cjs

- docs/guides/scripts.md
- examples/running_as_a_script/with_argparse.py
- examples/running_as_a_script/with_simple_parsing.py
Improve the docs on how to run marimo notebooks as scripts with CLI arguments, using argparse and `simple-parsing`.
This documentation intentionally omits Typer, because Typer leads to notebooks whose execution branches depending on whether running as a script or as a notebook. The included examples have the same control flow for both execution modes (except for the argument parsing logic).
> docs: cli arguments

- frontend/src/core/codemirror/markdown/__tests__/commands.test.ts
- frontend/src/core/codemirror/markdown/commands.ts
- frontend/src/core/saving/filename.ts
- marimo/_server/files/os_file_system.py
- tests/_server/files/test_os_file_system.py
Creates a public folder and then saves the base64 file inside it. If notebook is in a nested directory, it will save it in a public folder next to it.
```
```
@mscolnick
> fix: create public folder and then file

- frontend/src/components/data-table/columns.tsx
- marimo/_smoke_tests/tables/rich_elements.py
Some refactors and display long strings in a popup. Setting an artificial limit of 50 to decide when to use popup (else might be quite complex with useEffects and useRef).
The code feels messy, I will try to refactor.
> improvement: format using popover for long strings

- frontend/src/css/app/Cell.css
This change updates styling so that when a cell that has errors becomes stale (due to editing notebook code, for example), it is styled as a stale cell instead of an errored cell. This makes it easier to see which cells need to be rerun, and makes fixing errors feel less intimidating.
> improve: stale indicator precedence over error

- frontend/src/css/md.css
Fixes #4315 
This PR fixes the formatting of markdown details summaries. Summaries are no longer flex'd or justified, just displayed as text. The expander's styling is updated accordingly (and the expander closed/open position is changed to more conventional).
**Closed.**
**Open.**
> fix: markdown details justification

- frontend/src/components/slides/slides-component.tsx
- marimo/_smoke_tests/slides.py
Fixes #4311 . Only wide elements are affected and scrollable horizontally.
> fix: clamp wide elements in slides

- marimo/_ast/cell_manager.py
- marimo/_ast/codegen.py
- marimo/_ast/compiler.py
- marimo/_ast/toplevel.py
- tests/_ast/codegen_data/test_generate_filecontents_toplevel.py
- tests/_ast/test_app.py
- tests/_ast/test_codegen.py
- tests/_ast/test_toplevel.py
Followup for mep/8. These are minor formatting tweaks needed for broader release.
- Fixes some white space variation between ruff and serialization
- prevents trailing comments from being stripped in top level functions
- allows for unparseable setup cells
> mep/8: Formatting for library serialization

- .github/workflows/test_fe.yaml
- frontend/package.json
- frontend/pnpm-lock.yaml
I can investigate why, but react-hook-form does break `mo.ui.dataframe`. For now, we can just downgrade
> fix: downgrade react-hook-form

- marimo/_ai/text_to_notebook.py
- marimo/_cli/cli.py
- marimo/_cli/upgrade.py
- marimo/_config/cli_state.py
- tests/_cli/test_upgrade.py
This adds marimo's text-to-notebook directly in the CLI.
Users can run `marimo new "notebook to analyze a csv about cars"` that will create a brand new notebook use the same endpoints used in https://marimo.app/ai
For now it defaults to our backed, but in future we can extend to a user's own endpoints.
> feat: marimo new 'prompt to generate notebook'

- marimo/_utils/config/config.py
- tests/_utils/config/test_config_reader.py
Small fix for warning in logs, we shouldn't write None values to toml. Just remove them.
```shell
[W 250403 19:38:22 upgrade:38] Failed to check for updates
Traceback (most recent call last):
File "/Users/shahmir/Development/marimo/marimo/_cli/upgrade.py", line 36, in check_for_updates
_check_for_updates_internal(on_update)
File "/Users/shahmir/Development/marimo/marimo/_cli/upgrade.py", line 64, in _check_for_updates_internal
write_cli_state(state)
File "/Users/shahmir/Development/marimo/marimo/_config/cli_state.py", line 37, in write_cli_state
config_reader.write_toml(state)
File "/Users/shahmir/Development/marimo/marimo/_utils/config/config.py", line 47, in write_toml
tomlkit.dump(asdict(data), file)
File "/Users/shahmir/Library/Application …
```
> fix: remove none vals from being written to toml

- frontend/src/css/app/print.css
Closes #4369
Removes this as digital PDF is way more common than printing. This can be brought back by the various custom CSS features we support.
> fix: change default show href when printing

- frontend/src/components/data-table/renderers.tsx
This change modifies the table to persist selections when clicking on table rows.
Previously, clicking anywhere in a table unselected (in the case of single selection) an existing selection, or added additional selections (in the case of multi).
Even though other tables might do this, this can sometimes be troublesome since selections and unselections trigger code execution that may be expensive. It also makes it not possible to copy text when a row is already selected. One could try detecting for drag, but that doesn't account for double click, and I think this issue would still come up.
In favor of being explicit over implicit, and prioritizing edit mode usage, it makes sense to have selection toggles be limited to the column checkboxes.
Fixes …
> improve: don't unselect rows when clicking in other rows

- frontend/src/components/editor/errors/auto-fix.tsx
- frontend/src/components/editor/output/MarimoErrorOutput.tsx
- frontend/src/core/errors/__tests__/errors.test.ts
- frontend/src/core/errors/errors.ts
This PR improves the presentation of errors in the cell output area.
* Errors are grouped by error type, with all multiple definition errors
appearing in a group, all cycle errors appearing in another group, and
so on.
* Tips are shown once per error group, instead of once per error.
* More informative tip titles.
* Style improvements to make the error output more legible.
In a follow up, I will improve add docs pages with more context for multiple definition errors and import star errors, and will link to them from Tips.
Comparison images below.
**With changes.**
<details>
<summary>Single multiple definition error</summary>
</details>
<details>
<summary>Many multiple definition errors</summary>
</details>
<details>
<summary>Multiple types of errors</summary>
</details>
**Before …
> improve: group error types in error output

- marimo/_tutorials/dataflow.py
- marimo/_tutorials/markdown.py
- marimo/_tutorials/plots.py
- tests/_cli/snapshots/dataflow.md.txt
This sandboxes tutorials and allows users to use the package manager toast to install missing packages, which didn't exist at the time of tutorial authoring.
Fixes #4356
> fix: add tutorial dependencies 

- marimo/_plugins/stateless/flex.py
- tests/_plugins/stateless/test_flex.py
- tests/_server/export/snapshots/notebook_with_outputs.ipynb.txt
This could be a breaking change for some formats. The only cases I can think of:
- people were expecting a wrapping div and created custom css to target this
Currently if no `widths/heights` setting is passed to hstack/stack, then we wrap them in `<div>`s. This can make it hard to style the child element's width/height because the wrapping `div`.
This doesn't change when the output `widths/heights` are passed in.
> fix: don't render hstack/vstack in extra divs if there is no flex config

- docs/guides/deploying/prebuilt_containers.md
Updates docs to reflect that prebuilt containers run on top of `3.13-slim` instead of `3.12-slim`.
> docs: update docker base image info

- docker/Dockerfile
Adds [uv](https://docs.astral.sh/) to the pre-built Docker images.
By including the `COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/` as a base layer in the multi-stage build we ensure that `uv` and `uvx` will be in `PATH` for all build targets.
This change is purely additive, therefore it should not affect the existing image behavior.
@mscolnick
Closes #4403
> feat: make `uv` and `uvx` available in Docker images

- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/ai/ai-completion-editor.tsx
- marimo/_server/ai/providers.py
- tests/_server/api/endpoints/test_ai.py
Handle when the LLM outputs the lang in the codefences
> fix: handle backticks with langs

- marimo/_output/formatters/structures.py
- marimo/_smoke_tests/structures.py
- tests/_cli/test_cli_export.py
- tests/_output/formatters/test_structures.py
- tests/_utils/test_flatten.py
Add support for default dict in `StructuresFormatter` and extra test for `flatten`
> improvement: add support for formatting defaultdict with tree/json output

- docs/guides/understanding_errors/cycles.md
- docs/guides/understanding_errors/multiple_definitions.md
- Link to @koaning's latest YouTube video on multiple definition errors
- Fix an image link
> docs: link to multiple definition explainer video

- frontend/src/components/editor/links/cell-link.tsx
- frontend/src/components/editor/output/MarimoErrorOutput.tsx
Add links to understanding errors docs from common marimo errors.
> improve: link to error documentation

- marimo/_cli/cli.py
- marimo/_tutorials/dataflow.py
- marimo/_tutorials/markdown.py
- marimo/_tutorials/plots.py
This PR adds the ability for `marimo new` to read its prompt from a file. It also supports unix-style piping (but not on Windows).
Example usage:
```
Usage: marimo new [OPTIONS] [PROMPT]
Create an empty notebook, or generate from a prompt with AI
* marimo new                                                     Create an empty notebook
* marimo new "Plot an interactive 3D surface with matplotlib."   Generate a notebook from a prompt.
* marimo new prompt.txt                                          Generate a notebook from a file containing a prompt.
Visit https://marimo.app/ai for more prompt examples.
```
> feat: marimo new prompt.txt

- marimo/_messaging/ops.py
- marimo/_server/ai/prompts.py
- tests/_messaging/test_ops.py
This fixes a case when editing a cell with existing text inside, but we haven't selected anything.
> fix: ai edit cell when there is existing text

- frontend/src/core/codemirror/completion/Autocompleter.ts
- marimo/_runtime/complete.py
This adds completion on `(` and `,` for completions while filling out function/class signatures.
And `/` for filenames
> improvement: jedi completions on paren and comma for signature help

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
Fixes #4362
This expands cells by listening to selection changes. We expand, but don't focus.
> fix: expand cells that are collapsed

- .cursor/rules/python.mdc
- .cursor/rules/react-typescript.mdc
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
Fixes #4381. For narwhals, pandas, polars, the change is straightforward. But it's trickier for default table.
Use tuple is None technique for default table sorting: [stackoverflow](https://stackoverflow.com/questions/18411560/sort-list-while-pushing-none-values-to-the-end)
There is one issue:
Sorting has never worked on dictionary (row-oriented data)
Because it's column names are not 'key' and 'value', so I've made a change to fix this. Not sure if it may lead to other bugs.
> fix: place nulls at last

- examples/ui/code_editor.py
- frontend/src/plugins/impl/CodeEditorPlugin.tsx
- frontend/src/plugins/impl/code/any-language-editor.tsx
- marimo/_plugins/ui/_impl/input.py
Fixes #4085
Adds an boolean flag to `mo.ui.code_editor`, which in turn adds an additional button to copy the code.
@mscolnick
> Add option for copy button in code-editor

- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/dataframes/transforms/handlers.py
- marimo/_plugins/ui/_impl/dataframes/transforms/print_code.py
- tests/_plugins/ui/_impl/dataframes/test_dataframe.py
enables the  mo.ui.dataframe to create python code
Fixes #2267
The `python_print_ibis` function is now able to provide proper ibis code like it is already available for Pandas and Polars.
- [ x] I have added tests for the changes made.
- [x ] I have run the code and verified that it works as expected.
> improvement: print python code output for Ibis in mo.ui.dataframe

- docs/guides/exporting.md
Added a script to the docs that uses [playwright](https://github.com/microsoft/playwright-python) to pre-render static HTML exports.
Fixes #4324
@mscolnick
> Added rendering script  for static HTML exports to docs

- docs/guides/testing/pytest.md
- marimo/_ast/cell.py
- tests/_ast/test_pytest_scoped.py
fixes #4440
Preemptively enabled a capability than only works with library mode.
> fix: bug in pytest scope determination

- development_docs/traces.md
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_data/preview_column.py
- marimo/_output/formatters/df_formatters.py
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/ibis_table.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- marimo/_smoke_tests/tables/lazy_polars.py
- marimo/_utils/narwhals_utils.py
- tests/_data/mocks.py
- tests/_data/test_charts.py
- tests/_data/test_series.py
- tests/_plugins/ui/_impl/charts/test_altair_transformers.py
- tests/_plugins/ui/_impl/dataframes/test_dataframe.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_plugins/ui/_impl/test_altair_chart.py
- tests/_plugins/ui/_impl/test_table.py
- tests/_utils/test_narwhals_utils.py
This adds better support for polars LazyFrame and some tests. 
1. adds formatter for `LazyFrame` to use `mo.ui.table.lazy`
2. adds `mo.ui.table.lazy` for manually creating this 
3. bug fixes for LazyFrame in datasource explorer
TODO
> improvement: better support for polars LazyFrame, mo.ui.table.lazy(df)

- marimo/_cli/cli.py
Opening temporary files twice on Windows requires special care. See https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
> fix: marimo new permission error (Windows)

- marimo/_cli/cli.py
Catch and ignore `OSError`s when trying to determine whether the prompt arg of `marimo new` is a file.
> fix: marimo new handle long prompts

- tests/_sql/test_sqlalchemy.py
Fixes CI, test was running that depended on sqlalchemy
> fix: skip test when sqlalchemy when not installed

- frontend/src/core/codemirror/keymaps/vim.ts
In vim (and codemirror-vim) `S` deletes lines and starts insert. This behavior should not be overridden by default
Removed the line mapping `S` to `:w`
> fix: remove extra save keymap in vim mode

- configs/.vimrc
- docs/guides/editor_features/overview.md
- frontend/src/core/codemirror/keymaps/__tests__/vim.test.ts
- frontend/src/core/codemirror/keymaps/vim.ts
- marimo/_config/config.py
- marimo/_config/manager.py
- openapi/api.yaml
- openapi/src/api.ts
- pyproject.toml
Support reading from the user's vimrc to create custom vim mappings in the editor.
cc @andyrift
> feat: support vimrc from the user config

- marimo/_runtime/runtime.py
- tests/_runtime/test_runtime.py
Always run the setup cell if it is present and stale (making it like a root cell)
@akshayka
> fix: setup cell is a 'root' to all cells

- frontend/src/core/variables/__tests__/state.test.ts
- frontend/src/core/variables/state.ts
The variables table wasn't clearing when the variables message was empty. This only affected notebooks that had just one variable that was then deleted.
> fix: clear variables when message is empty

- frontend/src/core/codemirror/language/python.ts
Depends on https://github.com/marimo-team/codemirror-languageserver/pull/5
This allows basic use of completion snippets, for example on the video below the the cursor is correctly placed within the parentheses:
[before.webm](https://github.com/user-attachments/assets/e58fe13b-51a6-4d8d-9eb4-eed68f09aeb4)
[cursor-goes-within-parens.webm](https://github.com/user-attachments/assets/55ab213d-06d6-4452-933d-90eec395fac6)
This sets values needed for python-lsp-server to provide snippets:
- `include_params` must be true for snippets in completion
- `resolve_at_most` the default is 25, I propose to increase it to make snippets more reliably present
@mscolnick
> Configure jedi completion for snippet support

- frontend/src/components/editor/chrome/panels/tracing-panel.tsx
I don't think tracing panel needs to load on startup, we should load it when it is rendered. I could also have lazily loaded vega stuff, but we shouldn't need to import tracing at all unless it's being used I think.
side note, compile is needed for tracing due to spec not being correct
@mscolnick
> improvement: lazily load tracing panel

- frontend/src/components/ui/button.tsx
- frontend/src/plugins/impl/data-frames/forms/__tests__/__snapshots__/form.test.tsx.snap
Button shadows were a bit big before (buttons are usually small), making things look cluttered.
> style: lighten button shadows

- Makefile
The make command for `fe-lint` was assuming the hatch environment was active when invoking `typos`, this fix allows running `make check` outside of the hatch environment and matches the rest of the Makefile.
Just added `hatch run` before the `typos` invocation.
> ci: run "typos" command with "hatch run" in "fe-check" make command

- marimo/_ast/pytest.py
- tests/_ast/test_pytest_toplevel.py
Didn't have robust enough unit tests, and some faulty logic got in
> fix: pytest decorated class methods fails

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/copilot/client.ts
- frontend/src/core/codemirror/copilot/language-server.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- frontend/src/core/codemirror/lsp/utils.ts
Bump codemirror-language server:
- snippets
- configurable incremental edits
Fixes #4464 
We don't send incremental edits since it breaks copilot. This also adds some fixes for the websocket proxy and multiple LSPs running at once
> chore: bump codemirror-languageserver, fix GitHub Copilot incremental updates

- frontend/src/core/codemirror/language/latex.ts
> fix: ensure valid ranges for delimiter in parseLatex function

- marimo/_ast/app.py
- marimo/_cli/cli.py
- marimo/_server/api/endpoints/home.py
- marimo/_server/models/home.py
- pyproject.toml
fixes #4511
additionally, `hatch run typecheck:tutorials` can be manually triggered to run on tutorials - I didn't add this to CI because there's a lot that lights up- but maybe something to keep in mind (or even isolate a single tutorial for)
> fix: Overload @app.cell for mypy typing

- frontend/src/components/app-config/optional-features.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/ui/kbd.tsx
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/completion/hints.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/config/capabilities.ts
- frontend/src/core/config/feature-flag.tsx
- marimo/_messaging/ops.py
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_server/lsp.py
- marimo/_server/print.py
- openapi/api.yaml
- openapi/src/api.ts
- Move LSP out of feature flag
- Keep it optional by adding it to `KernelCapabilities`. Don't show errors when enabled but not installed (since it is enabled by default)
> feat: move LSP out of experimental,  keep LSP optional

- marimo/_ast/cell.py
- marimo/_ast/cell_manager.py
- tests/_ast/codegen_data/test_get_bad_kwargs.py
- tests/_ast/test_load.py
fixes #4521 
Allow invalid cell config parameters to be passed and only spawn warnings over failure.
> fix: (static parse) warn on bad cellconfig opposed to failing

- frontend/src/plugins/impl/RefreshPlugin.tsx
`mo.ui.refresh()` allows the user to set a period interval down to 0.1 secs but then artificially constrains it to >=1 sec at run time. There doesn't seem to be any downside to removing this constraint as done by this pr/commit.
> fix: fix refresh interval constraint

- Makefile
This commit fixes two errors:
1. pnpm on Arch is version 10.8.0 but was failing the check because it was merely looking for "9.*" but it should look for any version 9 and above.
2. The check was looking for "9." anywhere in the version string but it should only look at major version component.
> fix: correct pnpm version check

- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/copy-column/feature.ts
- frontend/src/components/data-table/copy-column/types.ts
- frontend/src/components/data-table/data-table.tsx
- frontend/src/components/data-table/header-items.tsx
- frontend/src/components/ui/menu-items.tsx
- frontend/src/components/variables/variables-table.tsx
Removes the `Copy column` and `Freeze left/right` menu items from the variable sidebar
> fix: remove copy and pinning from variable table

- frontend/src/plugins/impl/ButtonPlugin.tsx
- frontend/src/plugins/impl/RangeSliderPlugin.tsx
- frontend/src/plugins/impl/SliderPlugin.tsx
- frontend/src/plugins/impl/common/labeled.tsx
- marimo/_smoke_tests/issues/4544_flex.py
Fixes #4544 
Rather than changing how vstack work, this just makes sure the button doesn't stretch without being `full_width`
> fix: button stretch in vstack

- marimo/_ast/toplevel.py
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_schemas/serialization.py
Fixes some of this issues I was seeing when writing the tutorial. Main issue seemed to be unable to discover the setup cell
Note we need actual cell order to properly do resolution, but that i information is not available runner level. Could wire that down, but this is OK for now.
Really needs some e2e tests to properly capture, but the logic in toplevel itself is throughly tested in `tests/_ast/test_toplevel.py`
> fix: pass setup cell to toplevel resolution posthook

- frontend/src/components/editor/documentation.css
- marimo/_data/get_datasets.py
- marimo/_dependencies/dependencies.py
- marimo/_plugins/stateless/style.py
- marimo/_plugins/ui/_impl/data_editor.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_runtime/capture.py
- marimo/_runtime/complete.py
- marimo/_runtime/control_flow.py
- marimo/_utils/docs.py
- tests/_runtime/test_complete.py
Improve docstrings when using our jedi completions (non-LSP)
* use `docstring_to_markdown` if installed, then use `MarimoConverter` as a fallback
* convert some other docstrings to google format
* tiny bit of padding improvements
> improvement: Use docstring_to_markdown and custom MarimoConverter for non marimo docs

- docs/examples/index.md
- marimo/_runtime/control_flow.py
Not exactly about running cells, but close enough — link to the scripts guide, which has two example notebooks.
> docs: run notebooks as scripts example

- frontend/e2e-tests/components.spec.ts
- frontend/e2e-tests/py/components.py
- frontend/src/plugins/impl/FileUploadPlugin.tsx
- frontend/src/stories/file-upload.stories.tsx
These changes ensure that `FileUploadPlugin` displays singularized label when uploading multiple files is disallowed.
That is: `mo.ui.file(kind="area", multiple=False)` will render with label "Drag and drop a file here, or click to open file browser" instead of "Drag and drop files here, or click to open file browser".
- Extended default label construction logic in `frontend/src/plugins/impl/FileUploadPlugin.tsx`
- Added dedicated stories for single file inputs via *area* and *button* variants
- Added E2E test case
> feat: display singular label in `FileUploadPlugin` for single files

- docs/faq.md
(#faq-show-code) was attached to the title  of the show code FAQ 
Original title:
Original link: https://docs.marimo.io/faq/#how-do-i-show-cell-code-in-the-app-viewfaq-show-code
@mscolnick
> Remove (#faq-show-code) from show code FAQ

- .github/workflows/notify-readme-owners.yml
- README.md
The previous workflow used an API that doesn't exist on merged pull requests (`github.event`)
> fix: use context.issue in notify translators

- marimo/_utils/health.py
Fix marimo env when node version is not obtainable. Came up in #4581
> fix: get node version edge case

- mkdocs.yml
Link to the GitHub releases for the changelog, using it as the source of truth. (This is what Polars does too.)
In the future we can mirror the release notes in our docs on a dedicated page. But I didn't want to invest the effort in that right now, and this is still an improvement.
> docs: changelog

- marimo/_server/print.py
`setup_cell=True` was in my marimo.toml
> chore: add setup_cell to released experiments

- marimo/_cli/sandbox.py
- marimo/_server/api/interrupt.py
- marimo/_server/uvicorn_utils.py
Improves if not completely fixes #4224 
uv sends one more SIGINT than the user does after two Ctrl-Cs, which
was causing the server to die without cleanup. This introduces some
hacks to work around that behavior. It's not perfect but appears
much improved.
Tested by manually trying various combinations of:
```
[uv run] marimo tutorial intro --headless
```
followed by multiple ctrl-c's, and various combinations of `y` and `n` to the shutdown prompt.
Also fixes an issue with graceful shutdown with `--sandbox`.
A better solution would be to make shutdown robust to an arbitrary number of interrupts, but that ended up being a headache, so if this is still a problem after this change is merged we can just disable the double ctrl-c-to-exit behavior and tell people to use `Ctrl-D` or the manual …
> fix: improve graceful shutdown when running under uv

- docs/guides/package_reproducibility.md
- Introduce a new section in the package reproducibility guide for specifying alternative package indexes.
- Provide an example of how to use the [[tool.uv.index]] section for custom PyPI servers.
- Explain the use of the explicit flag and the [tool.uv.sources] section.
Add documentation for using alternative package indexes in the package reproducibility guide, enhancing the flexibility of package management configurations.
This PR enhances the package reproducibility guide by:
1. Introducing a new section dedicated to configuring alternative package indexes
2. Adding examples of how to use the `[[tool.uv.index]]` section to specify custom PyPI servers
3. Documenting the `explicit` flag functionality and explaining the `[tool.uv.sources]` section for more advanced index configurations …
> docs(guides)📚: Add section on specifying alternative package indexes

- marimo/_plugins/core/json_encoder.py
- tests/_plugins/core/test_json_encoder.py
Nested tuple wasn't getting captured and causing error serialization to break
> fix: tuples in dataclasses were not picked up for json encoding

- marimo/_plugins/core/json_encoder.py
- tests/_plugins/core/test_json_encoder.py
Sorry this was just bothering me at the post office.
Previous fix didn't account for empty __slots__ (which are feasible)
> nit: account for empty slots

- frontend/src/components/app-config/app-config-button.tsx
- frontend/src/components/app-config/app-config-form.tsx
- frontend/src/components/editor/cell/cell-actions.tsx
- frontend/src/components/editor/cell/cell-context-menu.tsx
- frontend/src/components/ui/context-menu.tsx
- frontend/src/components/ui/dropdown-menu.tsx
- frontend/src/components/ui/popover.tsx
Fixes #4632
Clamp many popovers throughout the app, and make scrollable. Also make the notebook settings 2 columns.
------------
------------
> fix: cell actions and notebook settings scroll

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/codemirror/__tests__/format.test.ts
- frontend/src/core/codemirror/format.ts
- frontend/src/core/codemirror/language/panel.tsx
Adds SQL formatting to the footer of the SQL cell.
This is currently only used by explicitly clicking the format button.
We do not use it for auto-formatting onSave or globally because
SQL formatting is much more opinionated than Python formatting, and we don't want to tie the two together (just yet).
> feat: add sql formatting button to sql cells

- frontend/src/components/data-table/__tests__/__snapshots__/chart-spec-model.test.ts.snap
- frontend/src/components/data-table/chart-spec-model.tsx
- marimo/_plugins/ui/_impl/altair_chart.py
Previously:
Now:
Adds another row in the tooltip, ideally we can put in the same row, but this might require [signals](https://stackoverflow.com/questions/54044721/modify-vega-tooltip-in-spec-to-display-specific-fields) and calculating the field elsewhere..I think.
I'm open to changing the tooltip name, maybe we can do
`colName (start)`
`colName (end)`
> fix: show start to end for datetimes in col summary

- marimo/_cli/sandbox.py
- tests/_cli/test_cli_export.py
`marimo export md mynotebook.py > file`
creates a bunch of noise at the top of the file. Easy way to get the same functionality is just to log to stderr instead of stdout
> fix: sandbox alerts to stderr

- docs/guides/exporting.md
- marimo/_cli/export/cloudflare.py
- marimo/_cli/export/commands.py
- tests/_cli/test_cli_export.py
Deploy to cloudflare in two commands:
marimo export html-wasm notebook.py -o dist --include-cloudflare
To run locally, run:
npx wrangler dev
To deploy to Cloudflare, run:
npx wrangler deploy
> feat: add --include-cloudflare for easy deployment of wasm to cloudflare workers

- frontend/src/components/editor/output/Outputs.css
These elements were previously missed.
Fixes #4658
> fix: max width on md admonition, details

- frontend/src/plugins/impl/CodeEditorPlugin.tsx
Previously, code editor would not refresh when you pass a new value, which I'm not sure is intentional. If this is a breaking change, maybe we can introduce a new argument.
Try:
```python
mo.ui.code_editor(value="HELLO")
```
Then, change to:
```python
mo.ui.code_editor(value="HIYA")
```
The output will still be the old value of HELLO. 
Relevant issue: [discord issue](https://discord.com/channels/1059888774789730424/1364664347917422664/1364964437361954898)
> fix: code editor refresh with new state

- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/markdown.ts
- frontend/src/core/codemirror/language/panel.tsx
Fixes #4573 . Defaults to using r-string.
Fixes #3895, #3884 . Introduce a toggle in markdown cells that can flip between raw string, f-string and raw + f-string.
- possible to use Select, but I felt this was cleaner. If we want to add a plain option, maybe change to a select.
- small lint fix for expressions in while loop (https://biomejs.dev/linter/rules/no-assign-in-expressions/)
> feat: toggle between markdown formats and set r-string as default

- marimo/_ast/app.py
Raising in __exit__ causes double errors, the correct handling is just to let it through
> fix: return 'False' to let normal error handling occur

- frontend/src/components/terminal/terminal.tsx
- frontend/src/components/terminal/xterm.css
I will gladly admit this is a minimum-effort PR that seems to do the trick. 
This is before (not monospace): 
This is after:
It seems the CSS variable was somehow ignored, so the naive fix seems to be just to configure it directly from the component? Will gladly hear it if we prefer to go with the CSS route though.
> Ensure terminal uses monospace font

- marimo/_server/errors.py
- marimo/_server/lsp.py
- marimo/_server/main.py
- marimo/_utils/formatter.py
- pyproject.toml
Fixes #4726
1. make ruff an optional dep
2. fallback to globally installed ruff e.g. `uv tool install ruff`
3. prompt to install by throwing `ModuleNotFound`
> improvement: make ruff optional, fallback to global ruff, prompt to install

- frontend/src/plugins/impl/FileUploadPlugin.tsx
- frontend/src/stories/file-upload.stories.tsx
- marimo/_plugins/ui/_impl/input.py
- tests/_plugins/ui/_impl/test_input.py
Fixes #4723
`mo.ui.file()` takes in a `max_size` argument for the file size
> improvement: configurable max-size for mo.ui.file() upload

- frontend/src/utils/__tests__/id-tree.test.ts
- frontend/src/utils/id-tree.tsx
Created a transformAll function to handle batch transformations in all columns. Partially resolves #4163 by adding a way to transform all columns in one render.
- Added transformAll to the class MultiColumn in id-tree.tsx
- Added a test for transformAll in id-tree.test.ts
@mscolnick
> feat: added a transformAll function to id-tree.tsx

- docs/guides/coming_from/jupytext.md
- docs/guides/editor_features/watching.md
- docs/guides/exporting.md
- docs/guides/package_reproducibility.md
- docs/guides/publishing/index.md
- docs/guides/publishing/mkdocs.md
- docs/guides/publishing/quarto.md
- docs/guides/reusing_functions.md
Update the docs to mention the markdown format in various places, in addition to mentioning the mkdocs and quarto plugins
> docs: document markdown format and add quarto/ mkdocs plugins

- docs/guides/editor_features/watching.md
- docs/guides/reusing_functions.md
Some edits to the file format guide.
* Complete copy-pastable example for setup cell
* Copy-pastable example for types
* Examples that look closer to real notebook (depending on numpy)
* Other stylistc edits
> docs: touch up file format / watching guide

- marimo/_ast/visitor.py
- tests/_ast/test_visitor.py
For each instance of a referenced name, we need to track the blocks it appears in;
previously, references on new blocks (scopes) were evicting
references on other scopes. These newer references could be
resolved but the other ones weren't, leading to us drop references.
Fixes #4742
> fix: per-block reference resolution

- marimo/_plugins/core/json_encoder.py
- marimo/_plugins/ui/_impl/from_anywidget.py
- tests/_plugins/core/test_json_encoder.py
- tests/_plugins/ui/_impl/test_anywidget.py
- this adds `memoryview` to our cusotm json encoder
- and only passed the subset of state changes to `widget.set_state`
> fix: json encode memory view, and anywidget partial updates

- frontend/src/core/codemirror/language/python.ts
- marimo/_ai/_types.py
- marimo/_ai/llm/_impl.py
- marimo/_islands/_island_generator.py
- marimo/_output/data/data.py
- marimo/_output/justify.py
- marimo/_output/md.py
- marimo/_output/show_code.py
- marimo/_plugins/ui/_impl/data_editor.py
- marimo/_plugins/ui/_impl/data_explorer.py
- marimo/_plugins/ui/_impl/dictionary.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tabs.py
- marimo/_runtime/complete.py
- marimo/_runtime/control_flow.py
- marimo/_runtime/output/_output.py
- marimo/_runtime/params.py
- marimo/_runtime/patches.py
- marimo/_save/save.py
- marimo/_utils/docs.py
- tests/_runtime/test_complete.py
Previously the parameters completions would show up empty or with useless `NoneType()` annotation. This PR adds a patch for marimo while awaiting a solution in jedi and/or pylsp. The related upstream issues are:
- https://github.com/python-lsp/python-lsp-server/issues/372
- https://github.com/davidhalter/jedi/issues/2063
- https://github.com/davidhalter/jedi/issues/2061
| Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/7c15395a-1caa-406c-9660-26a1a47688ca) | ![image](https://github.com/user-attachments/assets/d102d432-ab83-4286-b82c-8eb2d7deeb2d) |
| Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/7aa4c741-f0c4-4781-92a1-74f97edb78d8) | ![image](https://github.com/user-attachments/assets/741eac1a-d509-4cca-8a70-dc28fa1df183) | …
> improvement: documentation of parameters as show in the completion box

- marimo/_output/formatters/ipython_formatters.py
- tests/_output/formatters/test_ipython_update.py
Current iPython Display implementation doesn't support updates, it keeps appending to the cell output
This is how it looks today when using HugginFace transformers in notebook mode:
https://github.com/user-attachments/assets/b4c9bb17-9a39-4488-8996-9a6f07d9bae7
This PR expands the support to Python display so it now returns a DisplayHandle and that DisplyHanle has an update function.
This is how the change works when using HuggingFaace Transformers:
https://github.com/user-attachments/assets/a5819222-7cae-401c-bb2c-1f24489df120
> feat: support ipython display update

- marimo/_output/formatters/ipython_formatters.py
Cleanup always expanding dictionary
> fix: cleanup ipython display updates

- frontend/src/utils/__tests__/id-tree.test.ts
- frontend/src/utils/id-tree.tsx
Created a collapseAll function to handle collapsing all expanded nodes including nested children. Partially resolves #4163 by adding a way to collapse all nested expanded nodes
- Created a collapseAll function in id-tree.tsx
- Created tests to ensure it collapses all top-level nodes from leaves to root and some top-level nested nodes
- Create tests for all error cases
@mscolnick
> feat: added collapseAll function to CollapsibleTree to handle collapsing of all nested expanded nodes in one call

- marimo/_output/formatters/ipython_formatters.py
@mscolnick, unfortunately, the WeakValueDictionary broke the iPython update implementation
Now it only outputs the initial empty bar, as it can be seen in the video below
https://github.com/user-attachments/assets/2d591719-119f-44fd-9a25-e788540b3faf
Reverting WeakValueDictionary change while keeping the cleanup functions.
Analysis and issues
- noticed the dictionary adds one record per cell display
- known issue, the iPython is not unpatching, therefore the dictionary is never cleared
Here is a short video where I analyse the current behaviour
https://www.loom.com/share/16a282de56724584ac0c49bc81a68539
> Fix weakvaluedict issue

- marimo/_ast/variables.py
- marimo/_runtime/app/script_runner.py
- marimo/_runtime/dataflow.py
- marimo/_runtime/executor.py
- marimo/_runtime/runner/cell_runner.py
Prefer composition. This will make re-using/mixing executors (e.g. CachingExecutor) much easier.
> chore: cleanup executor, prefer composition

- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
Created an expandAllCells function that runs both transformAll() and expandAll() together. Partially resolves #4163 by adding a way to expand all nested cells in all columns with one command
- Created expandAllCells
- Created tests for nested collapsed cells and multicolumn collapsed cells
- Note: I will replace collapseCell() in each test when I write collapseAllCells() in the next PR
@mscolnick
> feat: added expandAllCells in cells.ts

- frontend/src/components/debugger/debugger-code.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/output/ConsoleOutput.tsx
- frontend/src/components/editor/output/MarimoTracebackOutput.tsx
- frontend/src/core/codemirror/editing/__tests__/debugging.test.ts
- frontend/src/core/codemirror/editing/debugging.ts
Feel free to remove any of these changes.
- When a cell is running, you could click the keyboard shortcut to run, and it will add the same cell to the queue. Which I don't is what we want (since we disable the run button anyways).
- Scroll to breakpoint
- Also added a small gap between the divs.
Before:
After:
@mscolnick
> fix: styles and prevent re-running cells which aren't idle

- frontend/src/components/debugger/debugger-code.tsx
- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/Output.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/output/ConsoleOutput.tsx
- frontend/src/components/editor/output/MarimoTracebackOutput.tsx
- frontend/src/components/editor/output/__tests__/traceback.test.tsx
- frontend/src/components/ui/input.tsx
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cell.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/editing/__tests__/debugging.test.ts
- frontend/src/core/codemirror/editing/debugging.ts
- frontend/src/stories/cell.stories.tsx
This adds a button to insert breakpoints at the notebook line-numbers.
As well as a single one at the bottom to insert one at the most deepest level.
This also improves the `stdin` styling, input, and PDB controls.
> feat: add 'Insert breakpoint' in traceback

- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
Created an collapseAllCells function that runs both transformAll() and collapseAll() together. Partially resolves #4163 by adding a way to collapse all top-level nested cells in all columns with one command
- Created collapseAllCells
- Modified the expandAllCells tests in #4791 to include collapseAllCells as well for both multicolumn and nested testing
@mscolnick
> feat: added collapseAllCells() to cells.ts and tests

- marimo/_dependencies/dependencies.py
- marimo/_runtime/patches.py
- tests/_runtime/test_complete.py
Small follow up to #4673.
Polars often uses a simplified rst format for parameters where it does not include types.
This requires `docstring-to-markdown` v0.17 with:
- https://github.com/python-lsp/docstring-to-markdown/pull/44
For example, before there was only one parameter with description for `polars.io.parquet.functions.read_parquet`, and now all 22 are displayed.
Parameters from functions with overloads such as `polars.io.database.functions.read_database` remain without good suggestions.
@mscolnick
> improvement: support more parameter descriptions, e.g. in `polars`

- marimo/_server/asgi.py
- marimo/_server/registry.py
Remove some eager imports that bring in starlette and break wasm
> fix: remove starlette from top level import

- marimo/_plugins/ui/_core/ui_element.py
This makes it so that the description for `on_change` in the method-level API matches the class-level API.
As mentioned in #4827 :
> The [**class-level** API reference for `marimo.ui.form` ](https://docs.marimo.io/api/inputs/form/#marimo.ui.form)correctly distinguishes the two parameters:
> 
> * **validate** (`Callable[[Optional[JSONType]], Optional[str]]`): A function that takes the form's value and returns an error message if the value is invalid, or None if the value is valid. Defaults to None.
> * **on_change** (`Callable[[Optional[T]], None]`): Optional callback to run when this element's value changes. Defaults to None.
> 
> However, the [**method-level** docs](https://docs.marimo.io/api/inputs/form/#marimo.ui.form.form) wrongly describe **both** parameters as returning an error …
> docs: correct on_change desc in `mo.ui.form.form`

- frontend/src/components/datasources/datasources.tsx
- frontend/src/core/islands/bridge.ts
- frontend/src/core/network/requests-network.ts
- frontend/src/core/network/requests-static.ts
- frontend/src/core/network/requests-toasting.ts
- frontend/src/core/network/requests.ts
- frontend/src/core/network/types.ts
- frontend/src/core/wasm/bridge.ts
- marimo/_cli/development/commands.py
- marimo/_entrypoints/ids.py
- marimo/_entrypoints/registry.py
- marimo/_runtime/requests.py
- marimo/_runtime/runtime.py
- marimo/_server/api/endpoints/datasources.py
- marimo/_server/registry.py
- marimo/_types/lifespan.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_server/api/endpoints/test_datasources.py
Provides a button to refresh datasource connections, except internal duckdb engine.
- Artificially spin the button on click
@mscolnick
> feat: refresh db connections

- marimo/_cli/file_path.py
- tests/_cli/test_file_path.py
Suport for `marimo edit "https://marimo.app/e?slug=oitgic"`
> fix: support mairmo edit on marimo.app

- .github/workflows/playwright.yml
- .github/workflows/test_be.yaml
- .github/workflows/test_be_dagger.yaml.skip
- .github/workflows/test_cli.yaml
- frontend/src/components/editor/cell/CreateCellButton.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/codemirror/completion/utils.ts
- frontend/src/core/codemirror/config/extension.ts
- frontend/src/core/codemirror/config/types.ts
- frontend/src/core/codemirror/language/LanguageAdapters.ts
- frontend/src/core/codemirror/language/__tests__/ast.test.ts
- frontend/src/core/codemirror/language/__tests__/indentOneTab.test.ts
- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/commands.ts
- frontend/src/core/codemirror/language/extension.ts
- frontend/src/core/codemirror/language/markdown.ts
- frontend/src/core/codemirror/language/metadata.ts
- frontend/src/core/codemirror/language/panel.tsx
- frontend/src/core/codemirror/language/panel/markdown.tsx
- frontend/src/core/codemirror/language/panel/sql.tsx
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/language/sql.ts
- frontend/src/core/codemirror/language/types.ts
- frontend/src/core/codemirror/language/utils.ts
- frontend/src/core/codemirror/language/utils/ast.ts
- frontend/src/core/codemirror/language/utils/quotes.ts
- frontend/src/core/codemirror/react-dom/createPanel.tsx
- frontend/src/core/codemirror/rtc/extension.ts
This makes the `LanguageAdapter` stateless and instead adds `LanguageAdapterMetadata` which is a map of state that is easier to access/update. 
This change makes real-time syncing much easier. 
This also adds some new test converge and cleans up some code (moving to to new files)
> chore: make LanguageAdapters stateless, store metadata in EditorState

- docs/index.md
Currently running the provided command will install the dependencies but fail to start the tutorial. 
This change adds `uv run` to the command to ensure we invoke `uv` when starting the tutorial.
```bash
$ uv add marimo && marimo tutorial intro
$ Using CPython 3.13.2 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Creating virtual environment at: .venv
Resolved 24 packages in 964ms
Prepared 22 packages in 5.27s
Installed 22 packages in 87ms
+ anyio==4.9.0
+ click==8.1.8
+ docutils==0.21.2
+ h11==0.16.0
+ idna==3.10
+ itsdangerous==2.2.0
+ jedi==0.19.2
+ marimo==0.13.6
+ markdown==3.8
+ narwhals==1.38.2
+ packaging==25.0
+ parso==0.8.4
+ psutil==7.0.0
+ pycrdt==0.11.1
+ pygments==2.19.1
+ pymdown-extensions==10.15
+ pyyaml==6.0.2
+ sniffio==1.3.1
+ starlette==0.46.2
+ …
```
> fix: uv, start tutorial

- docs/api/outputs.md
Added a relevant YouTube video showcase for `mo.output.replace` function by @koaning!
Tip admonition that links to a YouTube short demonstrating `mo.output.replace` (shown in the prompt and the animation later on). Thought it might be a nice thing to link to (even though the video is based on Zero shotting w/ marimo.app/ai).
> docs: add relevant video for `mo.output.replace`

- marimo/_runtime/runtime.py
- marimo/_smoke_tests/async/background_tasks.py
Fixes #3780 
This gives other async tasks a chance to execute while the control request is empty. For example, we create our own background tasks (e.g. writing session metadata) and sometimes a cell can as well (holoviews does, for example in the datashader)
> fix: don't block on background tasks created in cells

- frontend/src/css/app/Cell.css
The font size for the line numbers remained unchanged when the "Code editor font size" was changed in the user settings. The following video demonstrates the difference when the font size is increased to 16px before and after applying the patch.
https://github.com/user-attachments/assets/63bd8ec5-c380-46a3-9527-843b1eefed89
I added a CSS class that uses the font size for the code editor on the line numbers.
> fix: align font size for line numbers with the code editor

- docs/api/control_flow.md
- docs/api/miscellaneous.md
- docs/guides/outputs.md
- marimo/__init__.py
- marimo/_runtime/threads.py
- tests/_runtime/test_threads.py
- tests/snapshots/api.txt
Closes #4564 
This change adds a `should_exit` property to `mo.Thread` which evaluates to `True`
when the thread's spawning cell lifecycle has ended. This makes it
possible for developers to clean up their threads.
This change also adds a utility method, mo.current_thread(), that
returns the current thread of control if it is a marimo.Thread object,
and raises otherwise. Developers could technically use
threading.current_thread() instead, but this method provides
type safety and validation.
> feat: mo.thread lifecycle

- frontend/src/plugins/impl/SliderPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
Integrated number-field into the slider and added a include_input argument to manage visibility of input. Resolves #4747 by adding the requested feature.
- Added includeInput to SliderPlugin.tsx with validation
- Added include_input to input.py along with a description
- Integrated NumberField into SliderPlugin
- Added a two way data binding between the slider and the integrated number-field
@mscolnick
> feat: added input field to ui slider

- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
> fix: drop internal row id in `table.value`

- marimo/_server/print.py
Maybe a fix for #4871. It won't fail on printing the URL
> fix: don't fail if url does not have port

- .pre-commit-config.yaml
Fixes pre-commit failures following recommendation to set `pass_filenames: false` from https://github.com/crate-ci/typos/issues/926
```
typos....................................................................Failed
- hook id: typos
- exit code: 2
error: `fo` should be `of`, `for`, `do`, `go`, `to`
--> ./codemirror-languageserver-marimo/src/utils.test.ts:117:35
|
117 |         expect(createMockContext("fo").matchBefore(pattern)).toEqual({
|                                   ^^
|
error: `fo` should be `of`, `for`, `do`, `go`, `to`
--> ./codemirror-languageserver-marimo/src/utils.test.ts:120:20
|
120 |             text: "fo",
|                    ^^
|
```
@mscolnick
> fix: `typos` failing on pre-commit CI

- frontend/src/components/ui/slider.tsx
- frontend/src/plugins/impl/SliderPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
- tests/_server/export/snapshots/notebook_with_outputs.ipynb.txt
Added disabled to slider, updated the css so that the disabled style shows properly.
- Changed disabled:[css-class] to data-[disabled]:[css-class] because disabled CSS styles were not rendering in slider.tsx.
- Added disabled as an optional boolean prop with validation to SliderPlugin.tsx
- Mapped disabled to number-field isDisabled prop to handle if include_input == True
- Mapped disabled to slider python args with definition in input.py
@mscolnick
> feat: added disabled prop to slider

- marimo/_output/formatters/df_formatters.py
- marimo/_output/formatters/formatter_factory.py
- marimo/_runtime/patches.py
- tests/_runtime/test_patches.py
Patch polars to fallback to `write_csv` when `write_json` fails in wasm.
> fix: patch polars write_json in wasm with write_csv

- frontend/src/plugins/impl/MultiselectPlugin.tsx
This previously threw an error when max_selections is 1 and you deselected.
> fix: prevent selecting undefined when deselect (multiselect plugin)

- marimo/_cli/sandbox.py
- marimo/_utils/inline_script_metadata.py
- tests/_cli/test_sandbox.py
- tests/_utils/test_inline_script_metadata.py
Fixes #4809
This resolves relative `uv.sources` paths to include the path to the pyproject config
> fix: resolve relateive paths in uv.sources

- frontend/src/components/editor/database/add-database-form.tsx
- frontend/src/core/cells/cells.ts
Scrolling to the bottom is broken on new cell creation hence it can make users confused when adding a cell from the datasource panel or elsewhere.
I removed the special handling because I don't seem to face the issue. If I am wrong, I think it's possible to add `scrollToBottom`. but this was removed here https://github.com/marimo-team/marimo/pull/1782. I'm not sure why.
```typescript
if (index === column.length - 1) {
const cellId = column.last();
state.cellHandles[cellId].current?.editorViewOrNull?.focus();
>> scrollToBottom();
} else {
....
```
> fix: scroll to bottom on createNewCell

- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/row-viewer-panel/__tests__/filter-rows.test.ts
- frontend/src/components/data-table/row-viewer-panel/row-viewer.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
Previously the number of cols were clamped hence not all columns showed up in the panel.
The workaround is to unclamp during search, and also pass all field types and clamp the field types on the frontend.
Alternative: Create a new function to get all field types, so don't need to slice in the frontend.
> fix: row viewer panel for many columns

- marimo/_sql/engines/duckdb.py
When duckdb result failed to convert to polars df, the previous error was confusing as it prompted installation of polars[pyarrow] which wouldn't resolve the issue.
- Show warning instead of info, so users are informed
- Prompt installation of pandas instead
@mscolnick
> fix: prompt pandas installation instead of polars when duckdb parsing fails

- frontend/src/css/index.css
- frontend/src/css/progress.css
- marimo/_output/formatters/ipython_formatters.py
- marimo/_smoke_tests/ipython/progress.py
> improvement: style <progress/> consistently

- frontend/src/plugins/impl/NumberPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
Added disabled to number field.
- Added disabled as an optional boolean prop with validation to NumberPlugin.tsx
- Mapped disabled to isDisabled in number-field.tsx
- Mapped disabled to number python args with definition in input.py
@mscolnick
> feat: added disabled prop to number field

- frontend/src/core/codemirror/language/__tests__/extension.test.ts
- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/extension.ts
- frontend/src/core/codemirror/language/languages/markdown.ts
- frontend/src/core/codemirror/language/languages/python.ts
- frontend/src/core/codemirror/language/languages/sql.ts
- frontend/src/core/codemirror/language/types.ts
In a refactor, we moved metadata to the codemirror state. this regressed some logic when converting python to markdown/sql such that we never initialized this metadata state
> fix: cell language metadata initialization when converting python to markdown/sql

- frontend/src/core/codemirror/language/languages/markdown.ts
Does not fix #4926, but defaults to syntax highlighted. this may return false positives on initialization, but could be better while we find a better solution.
> fix: default to syntax highlighting in markdown when Editor is not ready

- docs/guides/editor_features/overview.md
Adds a link to the the vim-keybindings section, in edtior overview docs.
> docs: Add link to vim keybindings section in overview.md

- frontend/src/components/editor/output/JsonOutput.tsx
Fixes #4936 , but there are still hard to reach edge cases. e.g. `image/:x`. it no longer fails, but hides some info.
This code has existed since the beginning
> fix: json renderer for edge case matching

- frontend/src/components/editor/columns/cell-column.tsx
The blue hover line would sometimes not display on hover.
- This change displays both left and right side handlers, but only when cursor is close to edge (always displaying will overlay the cell-status)
- Increases the z-index so it's always draggable
- slightly reduce invisible widths
https://github.com/user-attachments/assets/0d2b173a-0bdc-4780-985c-95296fa2b54e
> fix: column resize handler not always showing up

- pyproject.toml
There is a fix foward but requires more LOC. This ignores the bad version and `8.2.1` should have the fix
Related: https://github.com/pallets/click/issues/2897
> fix: ignore click 8.2.0

- frontend/src/components/data-table/charts/__tests__/altair-generator.test.ts
- frontend/src/components/data-table/charts/chart-spec/altair-generator.ts
- frontend/src/utils/python-poet/__tests__/poet.test.ts
- frontend/src/utils/python-poet/poet.ts
Some cleanup just branching off the main branch
- removes `objectAsFieldNames` since this does actually work for nested object. but we have this logic, just needed to re-use as `args` in the `FunctionCall`
-  removes `objectsToPythonCode`. i added `Literal` to handling `toCode` so we could compose this a bit better.
> improvement: python poet cleanup

- frontend/src/components/ui/range-slider.tsx
- frontend/src/plugins/impl/RangeSliderPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
Added disabled to range slider, updated the css so that the disabled style shows properly.
- Changed disabled:[css-class] to data-[disabled]:[css-class] because disabled CSS styles were not rendering in range-slider.tsx.
- Added disabled as an optional boolean prop with validation to RangeSliderPlugin.tsx
- Mapped disabled to range-slider python args with definition in input.py
@mscolnick
> feat: added disabled prop to range-slider

- frontend/src/plugins/impl/CheckboxPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
Added disabled to checkbox
- Added disabled to CheckboxPlugin.tsx and made the code more DRY by matching the pattern of **Data** and **T** found in other files like SliderPlugin.tsx
- Mapped the checkbox class in input.py to the disabled property with definition
@mscolnick
> feat: added disabled prop to checkbox and cleaned code

- marimo/_runtime/app/script_runner.py
- tests/_ast/test_app.py
The logic for skipping stopped cells when running as a script was previously broken; wasn't actually skipping cancelled cells.
Fixes #4962
> fix: skip stopped cells when running as a script

- frontend/src/components/editor/output/Outputs.css
Fixes wrapping for md paragraphs that contain tex elements, an issue raised on Discord.
> fix: markdown wrapping for LaTeX

- marimo/_plugins/ui/_impl/table.py
Fixes #4978. Python 3.9 doesn't have support for pipe operators.
Ref: https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype
@mscolnick
> fix: use Union instead of pipe operator for tables

- frontend/src/components/editor/output/Outputs.css
We used to clamp markdown to a max width, regardless of the screen-width. While this may look better in some cases, it caused more bugs than helped. So instead we are removing this.
Fixes #4955
> fix: remove clamped markdown

- frontend/src/plugins/impl/RadioPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
Added disabled to radio
- Added disabled to RadioPlugin.tsx and connected it to existing RadioGroup disabled property
- Mapped radio python class to disabled property with definition
@mscolnick
> feat: added disabled prop to radio

- frontend/src/core/codemirror/completion/keymap.ts
- frontend/src/core/codemirror/copilot/extension.ts
- frontend/src/core/codemirror/utils.ts
This change ensures that hitting escape when an inline (AI) completion is active makes vim leave insert mode.
Additionally, this change fixes a bug in which hitting escape to close overlay completions would make the cell editor lose focus when _not_ in vim mode.
This should fix #4716, but I had difficulty testing the behavior on inline completion — copilot connected at first, but didn't connect thereafter. Similarly I can't get the custom completion to work either.
For copilot:
* I see `Copilot#signInInitiate: Sign-in flow started successfully`
* But `client.signInInitiate` returns `undefined`
For custom completion with api.openai.com, I see:
* `Suggestion fetch error: Error: Internal Server Error`
> fix: exit vim insert mode when closing inline completion hints with escape

- frontend/src/core/rtc/state.ts
When you switch into RTC. The server reinitializes the code as empty, so instead we are caching it on page-load
> fix: cache rtc value to avoid weird initialization states

- marimo/_ast/toplevel.py
- marimo/_ast/visitor.py
- tests/_ast/test_toplevel.py
fixes #4993
`@prop` capture fix is a visitor change, since variables defined in class scope are not bound to be "unbounded" if they're set in the class body. Filtering is done in the loop since this is order dependent.
I think there might be some pretty hairy `global` edge cases I haven't taken the time to think through- but we can reserve it for a "correctness" sprint
@akshayka
> fix: Allow @prop.setter in class definitions

- CODE_OF_CONDUCT.md
Replace personal email with an org-wide email in the code of conduct, for compliance with NumFocus affiliation.
> governance: org-wide code-of-conduct email

- GOVERNANCE.md
Add Bennet Meyers to project maintainers, steering committee.
cc @bmeyers
> governance: add Bennet Meyers

- frontend/src/components/data-table/TableActions.tsx
We don't show the context-aware panel in run mode, so hiding the button for now
> fix: hide row-selection panel in read mode

- marimo/_plugins/stateless/status/_progress.py
- tests/_convert/test_ipynb.py
Fixes #5023 
Modify `marimo/_plugins/stateless/status/_progress.py:_Progress` to allow rate calculation when rate display is disabled.
> Allow progress bar rate calculation when rate display is disabled

- docs/guides/troubleshooting.md
- frontend/src/components/editor/chrome/wrapper/footer-items/copilot-status.tsx
- frontend/src/core/codemirror/copilot/__tests__/copilot.test.ts
- frontend/src/core/codemirror/copilot/client.ts
- frontend/src/core/codemirror/copilot/copilot-config.tsx
- frontend/src/core/codemirror/copilot/extension.ts
- frontend/src/core/codemirror/copilot/language-server.ts
- frontend/src/core/codemirror/copilot/types.ts
- lsp/index.test.ts
- lsp/index.ts
- lsp/package.json
- lsp/pnpm-lock.yaml
- marimo/_loggers.py
- marimo/_server/lsp.py
- tests/_server/test_lsp.py
This migrates to `@github/copilot-language-server`, which given [the license](https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features) should allow use in Conda environments.
Fixes #1883
Todo:
> feat: migrate to @github/copilot-language-server, enable GitHub copilot in Conda environments

- marimo/_plugins/ui/_impl/tables/pandas_table.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
Allows multiindex pandas dataframes with non-string levels to be displayed (otherwise `TypeError: sequence item 0: expected str instance, int found`)
Dataframes with multiindex columns can originate from a pivot on multiple columns; one of the levels may be a number.  Existing code fails in those cases. 
Subbing `",".join(col)` with `",".join([str(level) for level in col])` takes care of it.
> handle multiindex with numeric levels

- frontend/src/plugins/impl/DateRangePlugin.tsx
- marimo/_plugins/ui/_impl/dates.py
Added disabled to mo.ui.date_range
- Added disabled prop to DateRangePlugin.tsx with validation and mapped it to the isDisabled property of DateRangePicker
- Mapped the disabled property to the python class with definition in dates.py
@mscolnick
> feat: added disabled prop to date range plugin

- docs/api/inputs/data_explorer.md
- marimo/_plugins/ui/_impl/data_explorer.py
- tests/_plugins/ui/_impl/test_data_explorer.py
> Add support for initial chart properties in `data_explorer`

- pyproject.toml
DuckDB `1.3.0` break vercel CI. This removes duckdb from the doc's deps, which fixes build in vercel
> chore: maybe fix vercel docs

- docs/getting_started/quickstart.md
- docs/guides/configuration/index.md
- docs/guides/editor_features/ai_completion.md
Fixes #4305
````
You can use your GitHub Copilot for code refactoring or the chat panel. This requires a GitHub Copilot subscription.
1. Download the `gh` CLI from [here](https://cli.github.com/).
2. Create a token with `gh auth token` and copy the token.
3. Add the token to your `marimo.toml` (or configure in the UI settings in the editor).
```toml title="marimo.toml"
[ai.open_ai]
model = "gpt-4o"
api_key = "gho_..."
base_url = "https://api.githubcopilot.com/"
```
````
> docs: using GH Copilot for AI Assist endpoint

- frontend/src/components/databases/icon.tsx
- frontend/src/components/datasources/components.tsx
- frontend/src/components/datasources/datasources.tsx
- frontend/src/core/codemirror/language/__tests__/extension.test.ts
- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/datasets/data-source-connections.ts
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_runtime/runtime.py
- marimo/_smoke_tests/sql/dbapi_sqlite.py
- marimo/_sql/engines/clickhouse.py
- marimo/_sql/engines/dbapi.py
- marimo/_sql/engines/doc.md
- marimo/_sql/engines/duckdb.py
- marimo/_sql/engines/ibis.py
- marimo/_sql/engines/pyiceberg.py
- marimo/_sql/engines/sqlalchemy.py
- marimo/_sql/engines/types.py
- marimo/_sql/get_engines.py
- marimo/_sql/sql.py
- pyproject.toml
- tests/_sql/test_clickhouse.py
- tests/_sql/test_dbapi.py
- tests/_sql/test_duckdb.py
- tests/_sql/test_get_engines.py
- tests/_sql/test_ibis.py
- tests/_sql/test_pyiceberg.py
- tests/_sql/test_sqlalchemy.py
This adds support for [PEP 249](https://peps.python.org/pep-0249/) to auto-discover as a queryable connection.
This also does some refactors to separate the query interface and catalog interface:
```mermaid
classDiagram
BaseEngine <|-- EngineCatalog
BaseEngine <|-- QueryEngine
EngineCatalog <|-- SQLConnection
QueryEngine <|-- SQLConnection
class BaseEngine {
<<abstract>>
+source: str
+dialect: str
+is_compatible(var: Any): bool
}
class EngineCatalog {
<<abstract>>
+inference_config: InferenceConfig
+get_default_database(): str
+get_default_schema(): str
+get_databases(): list[Database]
+get_tables_in_schema(): list[DataTable]
+get_table_details(): DataTable
}
class QueryEngine {
<<abstract>>
+execute(query: str): Any
+sql_output_format(): SqlOutputType
}
class SQLConnection {
Implements …
```
> feat: Support DB API as a SQL connection

- frontend/src/components/editor/output/Outputs.css
Fixes #5039 
We still want to unset max-width for all markdown again.
> fix: markdown clamping again

- pyproject.toml
This removes the `8.2.0` restrictions on `click`, since this breaks pixi's resolver. 
Click did not yank `8.2.0` but they did release a new version. While it's still possible to install a bad version of click (very unlikely), I think its worth the tradeoff of pixi not resolving.
> chore: fix pixi build

- marimo/_runtime/packages/pypi_package_manager.py
- marimo/_smoke_tests/packages/is_in_uv.py
- tests/_runtime/packages/test_pypi_package_manager.py
This detects (to the best of my knowledge) if we are in a uv project and run by the `uv run` command, without it being a temporary venv. If so, we do `uv add` which will add it to the `pyproject.toml` and update the `uv.lock` file
Fixes https://github.com/marimo-team/marimo/issues/3904
@akshayka working on docs to followup the distinction, and different usages
> improvement: detect if in uv project and use 'uv add'

- frontend/src/components/app-config/constants.ts
Their [API docs](https://docs.anthropic.com/en/docs/about-claude/models/overview) don't show a "-latest" variant of the model name yet. But given that the model came out yesterday it might be worth a nice social message to claim support for it right away.
> Add Claude 4 models

- marimo/_cli/sandbox.py
- marimo/_utils/inline_script_metadata.py
- tests/_cli/test_sandbox.py
Sandbox environments currently have trouble reusing cached virtual environments from `uv`, resulting in long startup times for packages like `pandas`.
From my testing, this appears to be caused by the way requirements are parsed and exported via `PyProjectReader`. The new `uv export --script` functionality allows us to defer requirements generation to uv, which seems to lead to better cache hits and improved reuse of environments.
https://github.com/user-attachments/assets/d3de1b57-b9b8-4b1a-845c-f7672457a4e9
Rather than removing `PyProjectReader`, which is still useful in non-uv contexts (pyodide), this PR adds a shortcut: when `uv` is available, we use `uv export --script` to generate requirements.txt directly. If that fails for any reason, we fall back to the existing logic that …
> feat(sandbox): Prefer `uv export` for dumping requirements.txt

- marimo/_loggers.py
- tests/test_loggers.py
This fixes an issue in which the user specified log level had no effect (debug logs were not shown in console nor file);
in addition to setting the handlers' levels, we need to set the logger's level as well.
This also removes the call to logging.basicConfig(): doing anything
with the root logger is considered poor practice for libraries as
it interferes with clients' ability to configure logging for their
application. This is somewhat complicated by the fact that marimo
is both an application and a library but I think still stands.
> fix: respect user log level

- marimo/_loggers.py
- tests/test_loggers.py
We still want to log `INFO` to the file. These will get filtered out by StreamHandler
> fix: still log info to file logging for better debugging

- frontend/src/components/editor/database/schemas.ts
After adding all the fields, the button used to be disabled. This fixes that (but as a side effect you can enter nothing in the below fields, which I think is still better than disabling it).
@mscolnick
> fix: set default type when adding pyiceberg

- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_smoke_tests/tables/pandas_multi_idx.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
Fixes #5085 . There are still a few edge cases we don't handle but this case can be handled by setting the col names to unique empty strings when the index is null. It is a hacky solution.
Case we don't solve:
@mscolnick
> fix: rename all unnamed columns to empty string for pd.multiIndex

- marimo/_server/utils.py
Automatic port selection does not work correctly on multi-user system (specifically HPC cluster node). 
Use `sock.bind` instead of `sock.connect_ex` to check for port availability 
> fix: automatic port selection

- docs/guides/editor_features/watching.md
Updated [(outdated) docs](https://docs.marimo.io/guides/editor_features/watching/#watching-for-data-changes) which linked to issue addressed recently.
- marimo now supports watching data files and automatically refreshing dependent cells using `mo.watch.file()` and `mo.watch.directory()` (relevant [PR](https://github.com/marimo-team/marimo/pull/4884)).
- Added a link to the [watch API documentation](https://docs.marimo.io/api/watch/) for further details.
CC: @dmadisetti
> docs: update `watching.md` to reflect support for data file watching

- marimo/_server/sessions.py
- marimo/_server/tokens.py
- pyproject.toml
- tests/_server/test_session_manager.py
Bug fix where we were using the random skew potection token instead of one based on the code, in run mode.
> fix: skew potection token in run-mode when auth is enabled

- pyproject.toml
- scripts/generate_ipynb_fixtures.py
- tests/_convert/ipynb_data/multiple_definitions.ipynb
- tests/_convert/ipynb_data/multiple_definitions_multiline.ipynb
- tests/_convert/snapshots/convert_multiple_definitions.py.txt
- tests/_convert/snapshots/convert_multiple_definitions_multiline.py.txt
- tests/_convert/test_convert_ipynb.py
This PR adds a script to generate `.ipynb` fixtures for testing `marimo convert`, along with a suite of notebooks and snapshot tests to validate conversion correctness.
For some of the more complex transformations related to combination of cell metadata + source code (e.g., hiding cells), I'd prefer to test using snapshotting instead of unit testing the individual transformations.
- `uv run scripts/generate_ipynb_fixtures.py` creates a set of `.ipynb` files (in `tests/_convert/ipynb_data/`).
- `tests/_convert/test_convert_ipynb.py` iterates through these fixtures and snapshots the Python rendering of the converted marimo notebook IR.
@mscolnick
> Create ipynb fixtures for `marimo convert` and snapshot outputs

- marimo/_convert/ipynb.py
- scripts/generate_ipynb_fixtures.py
- tests/_convert/ipynb_data/cell_metadata.ipynb
- tests/_convert/ipynb_data/hides_markdown_cells.ipynb
- tests/_convert/snapshots/convert_cell_metadata.py.txt
- tests/_convert/snapshots/convert_hides_markdown_cells.py.txt
- tests/_convert/test_ipynb.py
`_transform_sources` is no longer a pure transform (it's wasn't really with the transforms that are source-to-source, followed by some that modify number of cells). It now forms a "pipeline" for converting Jupyter notebook cells to marimo (python-only) format.
This structure lets us handle tags like "hide-code" and cleanly separate source-only and cell-level logic.
The pipeline is:
- A series of source-to-source transforms
- One source → CodeCell binding step (binds/resolve source with ipynb metadata to create `CellConfig`)
- A series of cell-to-cell transforms (may add/remove cells)
I had to update some tests... I chattted with @mscolnick about maybe updating some of these tests with snapshotting since this is so internal.
@mscolnick
> Support some JupyterBook cell tags in marimo convert

- marimo/_config/packages.py
- tests/_config/test_config_packages.py
Fixes #5185. Changes the default package manager to `uv` when marimo is launched from `uv` executable (e.g., `uv run marimo` in a project, or `uvx marimo`). Expect behavior with this PR (without setting a package manager):
```py
uv init foo && cd foo
uv add marimo
uv run marimo edit test.py
source .venv/bin/activate
marimo edit test.py
```
```py
uvx marimo
```
We could probably try to be smarter in the case above where it defaults to `pip` (since `uv` environments don't have `pip` installed), but I think this is the safest and has the nice property of the `uvx marimo` for the first time use case preferring uv.
`uv run` and `uv tool run` (aka `uvx`) sets `UV` to the `uv` executable path (https://github.com/astral-sh/uv/pull/11326), which we inspect to infer the preferred default package. …
> Default to `uv` package manager when launched from `uv`

- marimo/_cli/sandbox.py
- marimo/_runtime/packages/pypi_package_manager.py
- marimo/_utils/uv.py
- tests/_cli/test_cli_export.py
Use the `UV` environment variable set by uv to resolve the binary path, rather than assuming "uv" is available on the system path.
This PR replaces hardcoded "uv" subprocess calls with a utility function `find_uv_bin()`, which checks the `UV` environment variable. When a process is launched via `uv`, it sets `UV` to the executable path of the binary. The naming is taken from [`uv` python package](https://github.com/astral-sh/uv/blob/0109af1aa510bd4f0759b0d53d842c3716e5cc3f/python/uv/_find_uv.py#L8), which we could replace in the future.
For sandboxing, in cases where `find_uv_bin()` returns the unresolved string "uv" (i.e. `UV` isn't set), we still explicitly check that it's available in the system path before proceeding.
> Discover `uv` executable with `UV` environment variable

- marimo/_cli/sandbox.py
Fixes #4999
I think there could be an opportunity to try to read from `pyproject.toml` ourselves... but honestly I'd rather defer to recommending users use `uv` to bootstrap the environment in that case.
Their project discovery is very robust, and it would ensure alignment. For example:
```py
uv init my_project && cd my_project
uv add polars duckdb
uv run --with=marimo marimo . # will have polars and duckdb installed
mkdir notebooks
cd notebooks
uv run --with=marimo marimo . # will also have polars and duckdb installed
```
> fix: Skip PEP 723 check on directories

- frontend/src/components/chat/reasoning-accordion.tsx
Added markdown rendering inside the ReasoningAccordion because both GoogleProvider and AnthropicProvider return thinking tokens as markdown.
- Added MarkdownRenderer to reasoning text inside ReasoningAccordion
- Removed scroll area so that when expanded you see the full thoughts
- Made text italic and muted to differentiate the style of thoughts from the style of responses
@mscolnick
> feat: add MarkdownRenderer to ReasoningAccordion

- marimo/_server/api/endpoints/export.py
- marimo/_server/export/exporter.py
I didn't actually test the perf, but did notice when this was running that other requests could get blocked
> fix: don't block when writing auto-export files

- frontend/src/plugins/impl/DataTablePlugin.tsx
Not sure why this shows up in the playground, but providing defaults as a fallback should fix it
> chore: add defaults to table args

- frontend/src/components/app-config/optional-features.tsx
- frontend/src/components/data-table/charts/charts.tsx
- frontend/src/components/data-table/column-explorer-panel/column-explorer.tsx
- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/datasources/datasources.tsx
- frontend/src/components/editor/chrome/panels/packages-panel.tsx
- frontend/src/components/editor/chrome/panels/secrets-panel.tsx
- frontend/src/components/editor/chrome/panels/snippets-panel.tsx
- frontend/src/components/editor/chrome/wrapper/footer-items/backend-status.tsx
- frontend/src/components/editor/database/form-renderers.tsx
- frontend/src/components/editor/file-tree/file-explorer.tsx
- frontend/src/components/editor/file-tree/file-viewer.tsx
- frontend/src/components/editor/header/filename-input.tsx
- frontend/src/components/editor/package-alert.tsx
- frontend/src/components/pages/home-page.tsx
- frontend/src/core/wasm/PyodideLoader.tsx
- frontend/src/hooks/__tests__/usePackageMetadata.test.tsx
- frontend/src/hooks/useAsyncData.ts
- frontend/src/hooks/usePackageMetadata.ts
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/FileBrowserPlugin.tsx
- frontend/src/plugins/impl/data-explorer/ConnectedDataExplorerComponent.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- frontend/src/plugins/impl/data-frames/forms/renderers.tsx
- frontend/src/plugins/layout/LazyPlugin.tsx
Migrates the async data state management to align with [React Query](https://tanstack.com/query/latest/docs/framework/react/overview) conventions, replacing the previous implementation that allowed ambiguous states.
Updated to use React Query-like state patterns with explicit status types:
- **Pending**: `{ status: "pending", isPending: true, isFetching: true, data: undefined, error: undefined }`
- **Loading**: `{ status: "loading", isPending: false, isFetching: true, data: T, error: undefined }`
- **Error**: `{ status: "error", isPending: false, isFetching: false, data: undefined, error: Error }`
- **Success**: `{ status: "success", isPending: false, isFetching: false, data: T, error: undefined }`
- Updated all components using `useAsyncData` to use new property names
- …
> Make async data states impossible to misrepresent in `useAsyncData`

- marimo/_runtime/packages/import_error_extractors.py
- marimo/_runtime/runtime.py
- tests/_runtime/packages/test_import_error_extractors.py
Trying to handle all possible import patterns is a bit pathological—there’s no strong convention across packages. For instance, `fsspec` is [all over the place](https://github.com/fsspec/filesystem_spec/blob/26f1ea75351e39a80b29b27bea792351f3e8da9f/fsspec/registry.py#L62-L230). There’s a loose pattern, but it’s not consistent enough to catch reliably.
That said, I think we now have a solid approach for the common case where an error is explicitly re-raised from a failed import:
```py
except ImportError as err:
raise ImportError("You can install this another way") from err
```
Moreover, I set up a few "passes" for package extractors (i.e., functions of the form `(error_message: str) -> list[str] | None`) that can eagerly "handle" an error. This makes it easy to add special cases, or even …
> feat: enhance `ImportError` handling for better package suggestions

- frontend/src/core/runtime/runtime.ts
Websockets get flaky on proxy, and this seems just better anyway
> fix: allow for base url redirects

- marimo/_tutorials/dataflow.py
I have read the CLA Document and I hereby sign the CLA.
> Fixed typo in dataflow.py (ampltitude -> amplitude)

- frontend/src/components/editor/chrome/wrapper/footer-items/backend-status.tsx
Wasm doesn't have a health endpoint so its always connected
> fix: show wasm always always connected

- frontend/src/components/datasources/column-preview.tsx
- frontend/src/components/editor/output/JsonOutput.tsx
- marimo/_smoke_tests/tables/complex_types.py
- marimo/_smoke_tests/tables/rich_elements.py
Browser crashed because there were too many elements rendered at once in the json viewer (one array containing many nested arrays recursively).
This fix groups them by 50 (and only when exceeding 50),  which isn't ideal because it looks like there are nested arrays.
Normal
Maybe an alternative is to extend jsonviewer with some custom rendering.
> fix: dark mode charts and json viewer crashing

- frontend/src/core/constants.ts
- frontend/src/mount.tsx
Extends the `view-as` URI parameter to acommodate `view-as=present`. This causes the notebook to be shown in the `present` or "app" view by default when served in edit mode.
This is useful because it gives a clean UI by default while still allowing the user to drop into the `edit` mode if they so desire. 
When the user runs `marimo edit notebook.py` and navigates to `http://localhost:2718?view-as=present`, the notebook will start in app view mode (aka present mode) instead of edit mode. 
- This is a small change
- This change is well covered by the existing URI parameter tests
> Extend `view-as` URI parameter to handle app view in edit mode

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/__tests__/data-attributes.test.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/components/scratchpad/scratchpad.tsx
- frontend/src/stories/cell.stories.tsx
This autoscroll logic might be old and unused since we still get auto-scroll via the `scrollKey` logic in the cell action/reducer. 
This autoscroll was triggered incorrectly when connection is delayed or RTC, but no longer seems needed.
> fix: remove autoscroll

- frontend/.eslintrc.cjs
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/editor/file-tree/renderers.tsx
- frontend/src/components/editor/output/ConsoleOutput.tsx
- frontend/src/components/editor/output/VideoOutput.tsx
- frontend/src/components/ui/typography.tsx
- frontend/src/hooks/useSelectAllContent.ts
`Ctrl-A` in console output selects all the output. This is nice for copying out out marimo
* also removed eslint for a11y since its covered by biome
> improvement: Ctrl-A in console output selects all the output

- marimo/_server/ai/tools.py
- marimo/_server/session/serialize.py
- marimo/_utils/async_path.py
- marimo/_utils/files.py
- tests/_utils/test_async_path.py
This adds an `AsyncPath` class that implements `Path` but puts each operation in a thread (non-blocking the event loop) and makes it async. This is useful when the FS is mirror to a cloud bucket which operations can take longer (200-400ms) due to network latency. 
This uses `asyncio.to_thread` (introduced in 3.9+).
> pref: async path

- frontend/src/components/editor/alerts/connecting-alert.tsx
- frontend/src/components/icons/loading-ellipsis.tsx
- frontend/tailwind.config.cjs
A more subtle, but still quite visible, connecting alert. The previous connecting alert clipped over the first cell / output, and distracted from looking at the notebook.
(cc @dmadisetti) 
https://github.com/user-attachments/assets/47cf0a36-5637-4cff-958e-04dadfb136ad
> style: runtime connecting indicator

- marimo/_server/session/serialize.py
Demote log warning when serializing the session view to a log info.
* The session cache writer does not seem to know the notebook-order of cells. This doesn't seem to be a problem in practice (can run a notebook and hydrate from a cached session view object just fine). But it's odd that not having the notebook order does pose a problem when hydrating an exported HTML object.
@akshayka
> logging: downgrade warning to debug for session cache serialization

- frontend/src/components/chat/chat-panel.tsx
Chat messages were appearing duplicated in the AI chat panel when users sent their first message in a new conversation. I believe this regression was introduced in a2d62b3b.
The duplication occurs because `createNewThread` was pre-populating the persistent chat storage with the initial message and then calling `append()` to add the same message to `useChat`. Since `useChat` loads its `initialMessages` from persistent storage, the message appeared twice.
Fixed by removing the pre-population of messages in `createNewThread`. Now the flow is: create empty chat → `append()` adds message to `useChat` → `handleChatInputSubmit` syncs to persistent storage.
> fix: resolve chat message duplication on first message send

- marimo/_cli/print.py
Replace common unicode characters with ASCII on UnicodeEncodeError encountered while printing to console.
Should fix failing CLI test on CI.
> fix: CLI print for non UTF-8 terminals

- frontend/src/utils/assertNever.ts
- frontend/src/utils/invariant.ts
I do this often during development and find it really useful for debugging invariant failures. Thought I'd share this either to show other folks or check it into the repo so other developers can use it too.
The conditional `debugger` statement to the `invariant()` utility only runs in development. When an invariant fails, it automatically triggers a breakpoint in the browser before throwing the error. This immediately allows you to step into where some assertion failed.
The nice property is that the entire `if (import.meta.env.DEV)` block gets stripped out in production builds (e.g., `vite build`) since the bundler resolves to `if (false) {}`.
> chore(frontend): Add `invariant` debugger statement for development

- frontend/src/components/editor/cell/code/cell-editor.tsx
Fixes #5367 . Targets the inner div and corrects the css. This issue only affects safari (the parent height doesn't seem to be respected).
@akshayka
> fix: set cell editor height and overflow to hidden when hidden

- frontend/islands/vite.config.mts
- frontend/package.json
- frontend/src/core/dom/htmlUtils.ts
- frontend/src/core/islands/utils.ts
- frontend/src/core/websocket/StaticWebsocket.ts
- frontend/vite.config.mts
quarto `0.14.7` is broken.
I'm having trouble confirming this is the issue by replicating it locally, since I can't replicate the breakage. My dev served assets seem to work in general. But `being islands` != `being wasm` as is, and I think some of the logic around sockets gets lost (0.14.6 works, so this may be the offending PR: #5403)
@akshayka
> dev: Use islands as local asset server

- frontend/src/core/codemirror/lsp/notebook-lsp.ts
- frontend/src/core/codemirror/lsp/types.ts
Adds a custom type guard for the protected `notify` method on
`LanguageServerClient`s. Removes the need for a type assertion and
ignoring eslint rule.
> chore(frontend/lsp): Replace "as `any`" type assertion with a type guard

- frontend/src/components/data-table/chart-spec-model.tsx
- frontend/src/plugins/impl/vega/vega-component.tsx
Replaces direct import from "vega" with "vega-loader" to prevent module
graph issues introduced by chart summary (#5390). Fixes build error
related to island generation.
> fix(islands): Replace "vega" runtime imports with "vega-loader" to resolve build issues

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/data-table/charts/chart-spec/encodings.ts
- frontend/src/components/data-table/charts/chart-spec/spec.ts
- frontend/src/components/data-table/charts/constants.ts
- frontend/src/components/data-table/charts/types.ts
- frontend/src/components/tracing/tracing-spec.ts
All runtime uses of "vega" were replaced with "vega-loader" in #5449,
and now the only remaining usage is for types.
This change removes "vega" entirely as a direct dependency and switches
to extracting necessary types from "vega-lite" (which we are using
directly and extensively). It should also simplify future updates, since
we no longer need to keep "vega" and "vega-lite" in sync: all types are
now derived from what "vega-lite" exports. Should also prevent
accidental re-imports from "vega" in the future.
> chore(frontend): Remove "vega" as top-level dependency

- marimo/_utils/formatter.py
We integrate with different package managers, so suggesting a specific one
(like `pip`) may not be relevant or helpful for users.
While we could tailor suggestions based on user settings, the simpler approach
is to keep the message package-manager agnostic. In the UI, users are already
prompted with a separate package alert that lets them use their preferred
package manager.
Previously, users would see something like this in sandbox mode: Alert to click (uv) install ruff, suggestion to manually `pip install` ruff or black.
> Make formatting failure message package-manager agnostic

- pyproject.toml
We're dogfooding auto instantiation off, and considering making that the default to make onboarding to marimo easier for Jupyter users.
> chore: auto_instantiate=false for our project settings

- marimo/_runtime/dataflow.py
- marimo/_runtime/runner/cell_runner.py
- marimo/_runtime/state.py
- tests/_runtime/test_state.py
The `retain_active_states` method of the `StateRegistry` class was incorrectly removing elements from the `_inv_states` instance variable when they had been marked as active due to a confusion between `State` and `StateItem` references.
This PR is primarily to address the above error by getting the `id` reference of the underlying `State` item when marking states are active instead of using the `id` of the `StateItem` reference itself.
When a state is registered, the reference in the `_states` instance variable is a `StateItem`, not the `State` itself.
```python
state_item = StateItem(id(state), weakref.ref(state))
self._states[name] = state_item
```
The prior logic in `retain_active_states` marked a state as active by storing the `id` of the element in `_states`, and checking that …
> Fix StateRegistry retain_active_states

- marimo/_pyodide/bootstrap.py
We were accidentally providing an extra argument to `argv` in WASM, which was breaking the argparse example in the docs.
> fix: wasm kernels don't have argv

- frontend/src/core/cells/cells.ts
Fixes regression from #5344 where shift-enter on the last cell created a new
cell but didn't focus it. `moveToNextCell` now sets `scrollKey` for new cells
at notebook boundaries, restoring focus behavior without (I think)
reintroducing autoscroll.
> Fix shift-enter not focusing new cell at end

- tests/_server/api/endpoints/test_files.py
- tests/_server/export/test_exporter.py
* `test_file.py::test_save_*` tests are flaky because we appear to read before the file is actually written sometimes.
* `test_run_until_completion_with_console_outputs` is flaky for a similar reason
This change just adds a few retries and sleeps in an attempt to deflake.
> chore: deflake flaky i/o tests

- marimo/_server/ai/providers.py
Fixed the deepseek empty tool list error. The error was mentioned [here](https://discord.com/channels/1059888774789730424/1387766267792068821)
- Decoupled OpenAIProvider config from AnyProviderConfig class
- Add tools only if the tool list length is 1 or more
_Note: This is only necessary for the OpenAI sdk since it has a broader market of OpenAI compatible endpoints that might error if the tool list is empty. I already tested this with the Google and Anthropic sdks and they don't have this issue_
@dmadisetti
> fix(openai): empty tool list error for openai compatible endpoints

- frontend/index.html
- marimo/_server/templates/templates.py
Fixes #5428 
The changes in #5120 removed passing configuration data via HTML DOM
elements. However, the marimo VS Code extension depends on these
DOM-based attributes, leading to a regression.
These changes restore the minimal set of DOM data attributes
(`marimo-version`, `marimo-user-config`, `marimo-server-token`) required
by the extension to function correctly. These additions are marked as
temporary and should be removed once the extension is updated to no
longer rely on them.
> Restore DOM-based metadata for VS Code extension compatibility

- frontend/src/core/codemirror/go-to-definition/__tests__/commands.test.ts
- frontend/src/core/codemirror/go-to-definition/commands.ts
Removed overly aggressive early return introduced in #5415. Adds tests for
variables in different scopes, function declarations.
> Fix go-to-definition for function declarations

- frontend/src/components/editor/cell/CreateCellButton.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
Users can right-click the create cell button to get a context menu with Python, SQL, and Markdown cell types, but I would guess most users don't know this. This change adds a signifier on hover letting them know about the context menu.
This change also fixes a usability bug in the create markdown and sql actions by importing marimo as needed when the markdown/sql cells are created.
This is the context menu (which already existed):
> enhancement: add a signifier for the create cell context menu

- frontend/src/components/editor/cell/CreateCellButton.tsx
Fixes #5490
The create cell button tooltip was appearing behind the sidebar panel because it had `usePortal={false}`, which kept it within the button's stacking context.
Removing this prop allows the tooltip to render in a portal at the document root, ensuring it appears above all panels. I'm not sure of the original reason for disabling the portal, but in my testing, removing seems to resolve the layering issue and doesn't introduce any obvious regressions.
> Ensure cell action tooltip appears above sidebar panel

- docs/guides/package_management/using_uv.md
Fixing a minor typo in the uv documentation page.
https://docs.marimo.io/guides/package_management/using_uv/ previously read: "The --sandbox flag what tells marimo to keep track of your dependencies and store them in the notebook file." 
It now reads: ""The --sandbox flag is what tells marimo to keep track of your dependencies and store them in the notebook file." 
@akshayka
> Minor typo fix in uv docs

- .github/PULL_REQUEST_TEMPLATE.md
Updating the PR template such that the issues can hopefully become more naturally delegated. I don't want to put anyone in a box, please expand or contract your surface area a as you see fit
--- 
```
```
> chore: Add additional contributors for PR issues

- pyproject.toml
Pillow 11.3.0 doesn't have manylinux2014 wheels and was breaking our docs CI.
See https://github.com/python-pillow/Pillow/issues/9057 for context. Future versions will (apparently) restore manylinux2014 support.
> chore: docs CI cannot use pillow 11.3.0

- frontend/src/core/network/__tests__/api.test.ts
- frontend/src/core/network/api.ts
- frontend/src/utils/strings.ts
I traced failing endpoints in WASM to malformed urls (e.g. `marimo.app/eapi`). Quick fix to prevent this, with a sanity check test to prevent regression
> fix: Invalid base url in api resolution

- marimo/_runtime/dataflow.py
- marimo/_runtime/runner/cell_runner.py
- marimo/_runtime/state.py
- tests/_runtime/test_state.py
This reverts commit 9ec52a69a7938f2552cdb3b08ccf400157edbafc (PR #5435).
This change introduced a regression in which cells can become involved in infinite loops. While I have not root-caused this, it can be seen in marimo/_smoke_tests/query_params.py. 
The video below shows the regression.
https://github.com/user-attachments/assets/16bd3cc4-00b4-4c6e-a19b-7b752f62466a
> fix: infinite loops with query parameters and UI elements (revert "Fix StateRegistry retain_active_states (#5435)")

- scripts/generate_bash_focus.py
Run
`uv run scripts/generate_bash_focus.py <since-tag>`
to print a list of all PRs labeled with `bash-focus`.
Example output:
```
Using latest tag: 0.14.9
Fetching PRs with label 'bash-focus' since 0.14.9...
Found 4 PR(s) with label 'bash-focus':
#5515: fix: reuse ports that are available but recently closed
Author: @akshayka
Link: https://github.com/marimo-team/marimo/pull/5515
Merged: 2025-07-02T15:52:50Z
#5507: fix: include all query params in WebSocket connection
Author: @harterrt-shopify
Link: https://github.com/marimo-team/marimo/pull/5507
Merged: 2025-07-01T17:41:15Z
#5491: Ensure cell action tooltip appears above sidebar panel
Author: @manzt
Link: https://github.com/marimo-team/marimo/pull/5491
Merged: 2025-06-30T18:09:19Z
#5474: register UIElement on change if it is missing from …
```
> chore: script to generate bash focus PRs

- .github/ISSUE_TEMPLATE/feature_request.yaml
Update the description of the PR section in the issue template for feature requests to ask contributors to confirm with us before submitting PRs for new features. This is to make sure that contributors and the core team are aligned on the product roadmap.
> chore: update issue template pr section

- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/core/cells/cells.ts
The user is likely just trying to get the cell out of the way, especially when moving it to the bottom. So don't scroll to the bottom.
Scrolling still might still sense if using a hotkey since the user may type it accidentally (and then wonder where the cell went); or, when using a hoteky, the user is more likely to be actively editing the cell.
This is just a small usability change, but something I noticed while working on slides.
> enhancement: don't auto scroll when sending cell to top/bottom from menu

- .github/labeler.yml
- .github/workflows/labeler.yml
Auto-label PRs based on file changes (e.g. `documentation` or `bash-focus`)
> ci: add GitHub auto labeler based on file changes

- frontend/src/components/editor/chrome/wrapper/footer-items/runtime-settings.tsx
- frontend/src/components/editor/chrome/wrapper/footer.tsx
Fixes #5495
Fixes bottom toolbar overflow issue on small displays by implementing
responsive design that groups runtime settings into a settings dropdown.
When screen width is below `md` (768px), the footer shows a settings icon
instead of individual runtime controls, preventing text overlap.
https://github.com/user-attachments/assets/805819de-a8b8-4d9e-8ef0-b6c26a72961b
> Make reactivity options in footer responsive for small screen widths

- marimo/_ai/text_to_notebook.py
- marimo/_cli/convert/utils.py
- marimo/_cli/file_path.py
- marimo/_cli/upgrade.py
- marimo/_server/export/exporter.py
- marimo/_utils/requests.py
- tests/_cli/test_file_path.py
- tests/_utils/test_utils_request.py
Add a few request utils for a better API for fetching (similar to the `requests` lib).
Pass `marimo/__version__` as the user agent when fetching remote notebooks
> internal: request utils, make remote file send marimo user-agent

- frontend/src/components/data-table/range-focus/__tests__/atoms.test.ts
- frontend/src/components/data-table/range-focus/atoms.ts
- frontend/src/components/data-table/range-focus/cell-selection-indicator.tsx
- frontend/src/components/data-table/renderers.tsx
https://github.com/user-attachments/assets/92337c8d-1250-4bc1-92b4-e3291f3fae5b
> fix: allow select on table cells

- frontend/src/components/data-table/__tests__/columns.test.tsx
- frontend/src/components/data-table/__tests__/types.test.ts
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/types.ts
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
Fixes #5524 . 
Also provides the datetime viewer for these columns.
> fix: detect datetime and handle timezones for pandas

- biome.jsonc
- frontend/lint/preferObjectParams.grit
Follow up to #5492
Warns against functions with three or more positional parameters. Encourages use of an options object pattern, e.g., `fn(options)` or `fn(arg, options)`.
> Add linting rule to prefer options object over multiple positional args

- frontend/tsconfig.json
The `tsBuildInfoFile` configuration was present but inactive without the
`incremental` flag. Enabling incremental compilation allows TypeScript
to cache type information between builds, speeding up subsequent type
checks (~4x in my testing).
```sh
❯ hyperfine "pnpm tsc" "pnpm tsc --incremental"
Benchmark 1: pnpm tsc
Time (mean ± σ):     10.448 s ±  0.459 s    [User: 15.896 s, System: 1.129 s]
Range (min … max):    9.443 s … 11.088 s    10 runs
Benchmark 2: pnpm tsc --incremental
Time (mean ± σ):      2.841 s ±  0.138 s    [User: 4.680 s, System: 0.522 s]
Range (min … max):    2.700 s …  3.076 s    10 runs
Summary
pnpm tsc --incremental ran
3.68 ± 0.24 times faster than pnpm tsc
```
An alternative is just to make everyone aware of the `--incremental` flag.
> Enable TypeScript incremental compilation

- marimo/_ast/cell_manager.py
- marimo/_ast/compiler.py
- marimo/_utils/requests.py
- tests/_ast/codegen_data/test_with_bad_decorator.py
- tests/_ast/test_cell.py
- tests/_ast/test_load.py
fixes #5570
Certain wrapper decorators, like `functools.cache` return an object, not a function - which breaks compilation.
This adds a check that captures the functool case, and also generalizes cell registration to handle any object.
Also added a test to confirm static parsing can in fact load any decorated value.
> fix: Expand checks around decorated functions to enable functools usage

- frontend/src/components/chat/markdown-renderer.tsx
- frontend/src/components/datasources/column-preview.tsx
- frontend/src/components/datasources/datasources.tsx
- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/components/editor/cell/CreateCellButton.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/cell/useAddCell.ts
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/cells/__tests__/add-missing-import.test.ts
- frontend/src/core/cells/add-missing-import.ts
Used TypeScript's "Convert parameters to destructured object" code action to clarify arguments at call sites. Changes:
```ts
maybeAddMarimoImport(true, createNewCell, lastFocusedCellId);
```
to
```ts
maybeAddMarimoImport({
autoInstantiate: true,
createNewCell,
fromCellId: lastFocusedCellId,
});
```
JS's lack of keyword arguments can make reading call sites challenging. I'd prefer to avoid ambiguous arguments. It probably be best to enforce with a lint rule, though, I suspect it would be noisy across the codebase, so just updated these helpers (seen in #5489 review).
> Convert import helpers to use named parameters

- marimo/_plugins/ui/_impl/from_anywidget.py
Fixes https://github.com/marimo-team/marimo/issues/5133
Add explicit `__deepcopy__` method to widget class.
- [Y] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [N/A] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [No] I have added tests for the changes made.
- [No] I have run the code and verified that it works as expected.
I am having trouble with dev setup (locked-down corporate laptop). Was only able to test by monkey-patching, not building and running full test suite.
@mscolnick
> Fix deepcopy in from_anywidget.py

- frontend/src/components/editor/actions/useConfigActions.tsx
Makes the display setting easier to find / change, outside of the Settings > User Settings > Display flow.
> Add quick actions to change cell output area

- frontend/src/core/codemirror/reactive-references/__tests__/analyzer.test.ts
- frontend/src/core/codemirror/reactive-references/analyzer.ts
Improves how class-scoped assignments are resolved when analyzing
reactive references. Previously, class attributes like `bar = 10` could
be incorrectly highlighted as reactive if a global `bar` existed, due to
improper scoping resolution. The fix ensures that class-level variables
are interpreted in declaration order, mirroring Python's evaluation
semantics. This avoids false positives in cases involving
self-references or forward references within the class body. Additional
tests cover sequential assignment, references to undefined variables,
and repeated assignments. If anyone has more pathological examples, I'm
happy to add them to the test suite.
> Fix handling of class attribute references for reactive variables

- frontend/src/core/codemirror/keymaps/vim.ts
Adds a CodeMirror event handler that converts `Ctrl+[` to synthetic
`Escape` when vim keybindings are enabled. This allows `Ctrl+[` to work
as `Escape` for all vim operations, including exiting from cell editor
to command mode.
> Propagate `Ctrl+[` as `Escape` to enter command mode with vim keybindings

- frontend/src/components/editor/navigation/navigation.ts
- frontend/src/components/editor/navigation/vim-bindings.test.ts
- frontend/src/components/editor/navigation/vim-bindings.ts
Adds `gg` to jump to first cell and `G` to jump to last cell in command mode,
matching standard vim behavior. Also refactors vim keybindings into a dedicated
handler with declarative binding definitions, making it easy to add more vim
commands in the future.
> Add vim bindings for top/bottom cell navigation: `gg` and `G`

- frontend/src/components/app-config/is-overridden.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/chrome/wrapper/footer-items/runtime-settings.tsx
This adds some visual detection for why you cannot override settings that come the `pyproject.toml`.
- Introduced `useIsConfigOverridden` hook to check if user config values are overridden by project config.
- Added `DisableIfOverridden` component to wrap UI elements, displaying tooltips when settings are overridden.
- Updated `user-config-form` and `runtime-settings` components to utilize the new override detection
> improvement: add config override detection and UI components

- frontend/src/components/editor/navigation/multi-cell-action-toolbar.tsx
Add shortcuts to the floating multi-select bar.
> improvement: enhance multi-cell action toolbar with new shortcuts and actions

- frontend/src/components/editor/chrome/wrapper/sidebar.tsx
I prefer to do everything with a keyboard shortcut instead of using the mouse. And here's a nice example. 
Notice how there's stuff that I could click here? Well, there's an app called "Homerow" that lets me hit a shortcut and then this appears. 
I can then type the two characters to move the mouse and to do the mouse click. This really does wonders because my wrist does not like the trackpad. 
However, the buttons on the sidebar would never really light up. Until now!
Major improvement to anyone with a similar wrist issue!
> Sidebar buttons are accessible now

- marimo/_ast/app.py
- marimo/_pyodide/pyodide_session.py
- marimo/_server/api/endpoints/export.py
- marimo/_server/export/__init__.py
- marimo/_server/export/exporter.py
- marimo/_server/session/serialize.py
- marimo/_server/session/session_view.py
- tests/_ast/test_app.py
- tests/_server/api/endpoints/test_export.py
- tests/_server/export/test_exporter.py
- tests/_server/session/test_session_view.py
If session views are empty, just skip writing it. 
Refactor to clean up the args to just pass down the `App` instead of `AppFileManager`
> fix: don't write snapshots on empty session views

- frontend/src/components/editor/cell/PendingDeleteConfirmation.tsx
Prevents Cell's keyboard event handler from intercepting Enter key
presses within the delete confirmation UI. The Cell component's
`resumeCompletionHandler` was refocusing the editor on any keypress,
preventing the Delete button from responding to Enter when focused via
Tab navigation.
> Fix `Enter` key handling for delete confirmation button

- frontend/src/core/cells/__tests__/utils.test.ts
- frontend/src/core/cells/cells.ts
In multi-col notebooks, we incorrectly detect the notebook as needs saving eventhough it is saved.
The fix is to set column to null by default, reasoning explained previously: #2631
> fix: save button in multi-col notebooks lighting up

- frontend/src/core/codemirror/vim/cursor-visibility.ts
#5457 addressed multiple visible cursors with Vim bindings using the last focused editor, but modal editing #5614 introduced new states we didn't account for. This lead to awkward multiple cursors states based on where command mode was entered and exited.
This PR ensures vim block cursors are hidden entirely while in command mode, deferring to blue ring as the indicator of "selected". I find it much less distracting.
**Before**
**After**
> Hide vim cursor(s) when in command mode

- Makefile
- pnpm-workspace.yaml
TIL: https://pnpm.io/next/settings#verifydepsbeforerun
This setting allows the checking of the state of dependencies before
running scripts. The check runs on `pnpm run` and `pnpm exec` commands,
automatically running install if `node_modules` is not up to date.
Means you can also just clone marimo and run `pnpm build` without install step.
> Auto sync deps before running pnpm run/exec

- frontend/src/core/codemirror/copilot/__tests__/getCodes.test.ts
- frontend/src/core/codemirror/copilot/getCodes.ts
- frontend/src/core/codemirror/lsp/__tests__/notebook-lsp.test.ts
- frontend/src/core/codemirror/lsp/lens.ts
Fixes #5549
This fixes 2 bugs:
1. the LSP lensings was incorrect. The cellIds were ordered, but the text was not. This led to incorrect hover and completions.
2. the topological sort was correct but not as optimal. We now put cells without deps (likely a new cell) at the bottom. This will solve the case for:
a. `import marimo as mo`
b. add a cell above
c. `mo.<completion>`
> fix: lsp lensing

- frontend/src/components/editor/navigation/multi-cell-action-toolbar.tsx
- frontend/src/components/editor/navigation/navigation.ts
We didn't support focusing the multi-cell deletion confirmation before
with `FocusScope` because `autoFocus` triggered the cells' blur
handlers, which in turn cleared the pending delete state. When
attempting to focus the confirmation UI, blur events from the selected
cells would clear the pending delete service before the dialog could
render.
The fix removes `pendingDeleteService.clear()` from the cell's
`onBlurWithin` handler to prevent premature clearing and wraps the
confirmation buttons in `FocusScope` with `restoreFocus` to
automatically return focus to the previously focused element when the
dialog is dismissed.
([react-aria](https://react-spectrum.adobe.com/react-aria/index.html) / `FocusScope` is really nice quality of life improvement)
> Properly focus (and unfocus) multi-cell delete confirmation

- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
Fixes #2902 . Pass a `show_data_types` param in mo.ui.table() to control display of dtypes.
If we are not keen to add another param, we could make this a global config instead.
> improvement: add param to show dtypes in table header

- frontend/src/components/editor/chrome/wrapper/minimap.tsx
- frontend/src/core/hotkeys/hotkeys.ts
We avoided `Mod-m` (doesn't work Safari), `Mod-Shift-m` (taken for markdown), and `Mod-Shift-n` (browser override for new incognito). The "i" wasn't taken and very loosely stands for "inspect".
> Add hotkey to toggle minimap (`Mod-Shift-i`)

- frontend/src/components/editor/chrome/wrapper/minimap.tsx
The minimap renders connection paths between cells to visualize dependencies, but all SVG elements were at the same z-index level. This caused visual issues where unselected cell indicators could overlap and obscure the selected cell's connection paths.
> Ensure cell connections render above unselected cells in minimap

- .github/workflows/dev-release.yml
- .github/workflows/marimo-bot.yml
- .github/workflows/release-marimo-base.yml
- .github/workflows/release.yml
- .github/workflows/test_be.yaml
- .github/workflows/test_cli.yaml
- Makefile
Simplifies the development toolchain by removing the requirement to install `hatch` separately. Devs are still free to install hatch CLI directly (`uv tool install hatch`), but not required.
All hatch commands can now run through `uvx hatch`, and building uses `uv build` directly. This reduces the number of tools required for developers install.
> Remove global `hatch` CLI as required development dependency

- marimo/_runtime/complete.py
- tests/_runtime/test_complete.py
Implements key autocompletion (issue #4539). Now, `dataframe["` will suggest column names, dictionaries will suggest keys, etc.
Existing autocompletion features rely on `jedi`, which is a static analysis tool. It works using the source code / AST or by loading and inspecting an isolated copy of the module. It never accesses the user's namespaces (i.e., where the variable from the notebook live). Key completion requires accessing the object instance in the user namespace. 
`_maybe_get_key_options` was added and is called from the existing `complete()` function (main entrypoint). This identifies the name of the variable being completed, retrieves it from the already available `glbls` namespace and retrieves keys from the instance
- non-`str` dictionary keys aren't show as suggestions. When …
> feat: interactive key completion

- frontend/src/components/editor/chrome/wrapper/minimap-state.ts
- frontend/src/components/editor/chrome/wrapper/minimap.tsx
The minimap previously rendered all cells without connections default foreground color when no cell was selected, making them visually prominent despite being isolated from the dependency graph.
This change distinguishes between "non-referenceable" cells (i.e., markdown-only, no variable declarations) from cells that declare variables not used by any other cells. Non-referencable cells are rendered with a smaller dot and are deemphasized with gray coloring when no cell is selected.
Also refactors some of the rendering logic to be more readable.
| Before    | After |
| -------- | ------- |
| <img width="300" alt="image" src="https://github.com/user-attachments/assets/ea4b96bd-fb9f-41f6-accf-de0e4d064aa7" /> | <img width="300" alt="image" …
> Deemphasize unreferenceable cells in minimap when no cell is selected

- marimo/_cli/file_path.py
- tests/_cli/test_file_path.py
I noticed that opening a remote markdown file didn't work (because it was incorrectly assumed to be a .py).
Added a more inclusive file format detection for unknown files + adds a test
> fix: allow marimo to open the markdown file format over http

- frontend/src/components/editor/chrome/state.ts
- frontend/src/components/editor/chrome/wrapper/footer-items/minimap-status.tsx
- frontend/src/components/editor/chrome/wrapper/minimap-state.ts
- frontend/src/components/editor/chrome/wrapper/minimap.tsx
Because it hides parts of the UI when open, persisting minimap open/closed state to localStorage is a bit awkward. Sometimes you close a notebook with a complex minimap, then open a fresh one with no cells (empty minimap). I think a better UX is to just have global state per page reload.
> Don't persist minimap state open/closed state between page reloads

- frontend/src/components/editor/navigation/__tests__/navigation.test.ts
- frontend/src/components/editor/navigation/navigation.ts
Instead of going to first, it finds the closest adjacent cell by index. It's not perfect but imo slightly better than going to first, especially for long column notebooks.
> Support keyboard navigation across columns in command mode

- frontend/src/components/data-table/charts/charts.tsx
- frontend/src/components/data-table/charts/components/chart-items.tsx
- frontend/src/components/data-table/charts/components/chart-states.tsx
- frontend/src/components/data-table/charts/lazy-chart.tsx
- frontend/src/components/editor/Output.tsx
- marimo/_output/formatters/altair_formatters.py
There was an issue with the notebook flickering due to loading vega. This adds a suspense and minor refactor on the frontend.
This also applies some auto-options for vegafusion charts (like making the width full). 
- I wanted to fix the background colour bug (which only happens with vegafusion), but vegafusion by default sets it to white so I'm not keen to overwrite it (we may clash with user specified background). We could 'smartly' check if theme == dark, then set to black, but it's a bit hacky and imo we are interfering with defaults.
> fix: add suspense for vega charts

- frontend/src/components/editor/Output.tsx
- marimo/_messaging/mimetypes.py
- marimo/_schemas/generated/session.yaml
- packages/openapi/api.yaml
- packages/openapi/src/api.ts
- packages/openapi/src/session.ts
Better warning for unsupported ipywidgets. Instead redirect them to anywidget
> fix: better jupyter widget warning for unsupported

- .github/workflows/dev-release.yml
- .github/workflows/marimo-bot.yml
- .github/workflows/release-marimo-base.yml
The shebang in the `scripts/modify_pyproject_for_marimo_base.py` from #5778 is failing in CI. We should just be able to call `uv run`.
> Use explicit `uv run` for dev build script in CI

- frontend/src/__mocks__/common.ts
- frontend/src/components/editor/navigation/__tests__/clipboard.test.ts
- frontend/src/components/editor/navigation/clipboard.ts
Fix mimetype for copy paste. Custom mime needs to be prefixed with `"web "`. 
This also adds pasted cells in reverse order. This fixes copy pasting from one browser tab to another
> fix: copy-paste cell mime-type

- packages/lsp/index.ts
- packages/lsp/package.json
- pnpm-lock.yaml
Bit of a drive-by change, feel free to ignore, but was looking at our LSP deps and found we are on `@sourcegraph/vscode-ws-jsonrpc` which hasn't been updated in 7 years. I noticed `vscode-ws-jsonrpc` exists and has been actively maintained and updated (latest version 3.4.0, updated 7 months ago).
In case there is some reason I'm not aware of (tried digging through the git history and couldn't find anything) maybe worth considering switching over.
> Migrate LSP from `@sourcegraph/vscode-ws-jsonrpc` to `vscode-ws-jsonrpc`

- frontend/src/core/codemirror/cells/extensions.ts
Adds move left and right into the cell-editor hotkeys
> fix: move cell left/right in edit mode

- README_Traditional_Chinese.md
Follow  #5809
- Traditional Chinese translation for Share cloud-based notebooks
This PR adds Traditional Chinese (zh-tw) translation for the "Share cloud-based notebooks" documentation section, improving accessibility for Traditional Chinese-speaking users in the marimo community.
> docs: add zh-tw translation section for sharing cloud notebooks

- frontend/src/components/editor/controls/keyboard-shortcuts.tsx
- frontend/src/components/editor/navigation/__tests__/navigation.test.ts
- frontend/src/components/editor/navigation/navigation.ts
- frontend/src/core/codemirror/keymaps/vim.ts
Adding an additional mode to vim has proven problematic, both for our team and community members. It's also been reported as confusing in jupyterlab-vim.
Refs:
- https://github.com/marimo-team/marimo/pull/5614#issuecomment-3131185317
- jupyterlab-contrib/jupyterlab-vim#149
This suggests a **poor default experience** for vimmers which we are changing.
Vim keybindings now require `Shift+Escape` to exit to command mode, adding an addition modifier key. This is a breaking change, but should prevent accidently entering **command mode** out of habit of bashing the `Escape` key. Non-vim keybindings continue using regular `Escape` to enter command mode.
This change removes `Ctrl+[` for entering command mode. The `Ctrl+[` keybinding worked previously because `Ctrl+[` _equals_ `Escape` in …
> Require `Shift+Escape` to enter command mode with vim keybindings

- frontend/src/components/editor/navigation/__tests__/navigation.test.ts
- frontend/src/core/hotkeys/shortcuts.ts
Cell movement shortcuts (`Ctrl+Shift+7/8/9/0`) weren't working on Windows and Linux because these keyboards produce shifted characters like "&" instead of "7" when Shift is held. The shortcut parser was comparing against the literal digit, causing matches to fail.
This fix uses the physical key code for shifted digit combinations, making the shortcuts work consistently across keyboard layouts. Note: `Ctrl+Shift+0` may still be intercepted at the system-level Windows.
> Fix cell movement shortcuts on non-Mac keyboards

- frontend/src/components/editor/cell/code/cell-editor.tsx
The bottom panels show up when the cell is hidden
Before:
Now:
> don't show sql bottom panel when cell is hidden

- docs/guides/editor_features/overview.md
- frontend/src/components/editor/controls/keyboard-shortcuts.tsx
- frontend/src/components/editor/navigation/__tests__/navigation.test.ts
- frontend/src/components/editor/navigation/navigation.ts
On Linux systems, `Shift+Escape` triggers unintended behavior that interferes with marimo's command mode transition. This makes the current keybinding unusable for Linux users trying to exit vim's insert mode to marimo's command mode.
Following the changes from #5815 which introduced `Shift+Escape` to prevent accidental exits from vim mode, we're now switching to `Ctrl+Escape` (or `Cmd+Escape` on macOS) as a more reliable cross-platform solution.
> Change vim mode command entry from `Shift+Escape` to `Ctrl/Cmd+Escape`

- marimo/_convert/ipynb.py
- scripts/generate_ipynb_fixtures.py
- tests/_convert/ipynb_data/pip_commands.ipynb
- tests/_convert/snapshots/convert_pip_commands.py.txt
Fixes #5819
The `transform_exclamation_mark` transform was introduced in 59338be but was accidently omitted from the transforms pipeline (`_transform_sources`). The pipeline was later refactored in 92e6a04, but the transform remained missing. This caused `!pip` commands to end up in unparsable cells instead of being properly commented.
Added the missing transform to the pipeline and test coverage. Note: The function name `transform_exclamation_mark` is a little misleading since it only handles `!pip` commands, not all exclamation-mark commands.
> Fix missing `!pip` transform in notebook converter

- frontend/src/components/ui/combobox.tsx
- frontend/src/plugins/impl/SearchableSelect.tsx
- frontend/src/plugins/impl/data-frames/forms/__tests__/__snapshots__/form.test.tsx.snap
Fixes #5341 .
Need to do more testing with other components that use combobox, but this allows text in dropdown to be limited to the width set.
By default, it shouldn't wrap
If set full_width to True, and style the width, it will truncate the text
> style: set combobox to truncate

- frontend/src/components/editor/Cell.tsx
Now only the "reusable" text and the icons are clickable links. Previously, the entire output area block was clickable as a hyperlink when a cell contained a reusable definition. This made it easy to accidentally navigate away when clicking anywhere in that area, even though most of the block is not visually indicated as a link.
> Make reusable cell link only clickable on text, not entire block

- docs/guides/configuration/runtime_configuration.md
- docs/guides/package_management/index.md
- docs/guides/package_management/notebooks_in_projects.md
- mkdocs.yml
Fixes #3008
Adds a new guide explaining how to use marimo notebooks within existing Python projects. The guide clarifies two approaches: sandbox notebooks for self-contained examples with isolated dependencies, and project notebooks that share the project's environment.
Think there is probably some overlap with the [uv's integration guide](https://docs.astral.sh/uv/guides/integration/marimo/) and our own [using uv](https://docs.marimo.io/guides/package_management/using_uv/) section. Think this could use a pass to make more agnostic of package manager.
> Document working with marimo notebooks in existing projects

- frontend/src/components/editor/Cell.tsx
- marimo/_ast/app.py
- marimo/_ast/cell_manager.py
- marimo/_ast/codegen.py
- tests/_ast/test_app.py
Fixes #5727
The setup cell is often used for lengthy imports and configuration that users don't need to see when viewing a notebook. This change allows users to hide the setup cell's code while keeping it functional, just like regular cells.
The implementation maintains backward compatibility by supporting both property access (`with app.setup:`) and method calls (`with app.setup(hide_code=True):`).
> Support hiding code in setup cells

- frontend/src/core/cells/pending-delete-service.ts
Fixes root of #5883 
The `usePendingDeleteService` hook was subscribing to `notebookAtom` and `variablesAtom`, causing all cells to re-render when any cell was edited.
Fixed by using imperative getters (`getNotebook()` and `getVariables()`) _within_ the submit callback instead of reactive subscriptions. This was a perf regression introduced in #5664.
> Avoid dependency on notebook/variables in `usePendingDeleteService`

- marimo/_server/ai/mcp.py
- marimo/_server/api/lifespans.py
- tests/_server/ai/test_mcp.py
Fix error where MCP servers don't disconnect during shutdown of Marimo backend. The error happens because the task that connects the MCP server is not the same task that disconnects it.
- Created _connection_lifecycle method to handle both connection and disconnection of the same server using the same task in mcp.py
- Updated all connection and disconnection logic to use the new method
- Added disconnect_from_all_servers to lifespans.py after yield
- Added tests for MCP disconnection with edge cases in test_mcp.py
> fix(mcp): disconnect server fix and tests

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/__tests__/data-attributes.test.tsx
- frontend/src/components/editor/cell/cell-context-menu.tsx
- frontend/src/components/editor/chrome/wrapper/minimap-state.ts
- frontend/src/components/editor/chrome/wrapper/minimap.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/edit-app.tsx
- frontend/src/stories/cell.stories.tsx
Follow up to #5894. Cells now access their state through atoms (via specialized `useCellData` / `useCellRuntime` / `useCellHandle` hooks) instead of props, eliminating the large props interface. This achieves better render isolation – cells only re-render when their own state changes, and the containing `CellArray` no longer has a dependency on the notebook atom.
It's worth noting this refactor makes the `Cell` slightly harder to test in isolation, since you now need to mock a `NotebookState` instead of just passing down props. However, think the rendering benefits are justified and the dataflow is slightly more clear now that we aren't prop-drilling/spreading.
| Before                                                                          | After …
> Refactor `CellArray`/`Cell` to use atom-based state management

- marimo/_ast/app.py
- marimo/_runtime/app/kernel_runner.py
- marimo/_runtime/runtime.py
- tests/_ast/app_data/notebook_filename.py
- tests/_ast/test_app.py
- tests/_runtime/test_runtime.py
- tests/conftest.py
Fixes #5850
When embedding notebooks with `app.embed()`, the `__file__` special variable was returning `"<unknown>"` instead of the actual file path. This broke relative path operations in embedded notebooks.
The issue was that `AppKernelRunner` hardcoded `filename = "<unknown>"` when creating the execution context for embedded apps. Now it uses the filename from the app being embedded.
> Fix `__file__` in embedded notebooks

- frontend/src/core/cells/pending-delete-service.ts
Replaces React state primitives (`useState`, `useEffect`) with a reducer-based approach, eliminating race conditions from effect-based state synchronization. Auto-deletion of "simple" cells now happens synchronously within the reducer action.
We could move the computed properties into the reducer state, but for now I just wraped the existing API to preserve the computed properties (`idle`, `shouldConfirmDelete`).
> Refactor pending delete service with reducer pattern

- marimo/_server/ai/tools.py
If no MCP servers are enabled (currently they are only on by a preview flag), then don't attempt to find tools and check for the `mcp` dependency.
> fix: skip mcp requirements if no tools are enabled

- tests/conftest.py
Changes in #5854 fixed FileStore issues by providing a dummy path when
pytest.exe appears in `__file__`, but this broke multiprocessing tests
because the dummy file didn't exist for child processes to import.
This fix creates an actual dummy Python file that both satisfies
FileStore's need for a valid path and allows multiprocessing to
successfully spawn processes on Windows.
> Fix Windows multiprocessing test hanging after pytest path fix

- marimo/_runtime/runtime.py
- tests/conftest.py
An alternative to our test patches in #5903 and #5854 is to just find
the first parent that is a directory for the edge case where a parent
path is actually a file (like `pytest.exe\__main__.py`).
> Find first directory parent for `__file__` in `mo.notebook_dir`

- frontend/src/core/codemirror/keymaps/vim.ts
`Ctrl+[` is a vim escape sequence that needs browser emulation. Our current keymap only handles this for Linux. This change adds the same keymap for Windows.
> Enable `Ctrl+[` vim escape on Windows

- frontend/src/components/data-table/__tests__/__snapshots__/chart-spec-model.test.ts.snap
- frontend/src/components/data-table/__tests__/chart-spec-model.test.ts
- frontend/src/components/data-table/column-summary/chart-spec-model.tsx
- frontend/src/components/data-table/column-summary/utils.ts
This fixes the browser crash when the binValues were too large, but bin step is too small.
similar issue: https://github.com/vega/vega-lite/issues/9416
> fix: bin step was too small for large bin values

- marimo/_server/ai/providers.py
This PR fixes the inline completions parsing error where `:{"finishReason": "stop", "usage": {"promptTokens": 0, "completionTokens": 0}}` appears at the end of every completion. It is mentioned in a [discord thread](https://discord.com/channels/1059888774789730424/1402597432432263188)
- Add **StreamOptions(text_only=True)** to collect_stream function so that it ignores all formatting and meta data used by the Chat Panel.
> fix: inline-completions parsing issue

- marimo/_plugins/ui/_impl/from_anywidget.py
- tests/_plugins/ui/_impl/test_anywidget.py
The improved cache works for all types of widgets and avoids a race condition.
* Created `class WeakCache` to handle caching of widget --> anywidget
* Allows caching of all widgets
* avoids try/except
* avoids further errors present in LOGGING during except
* squashes small/unlikely race condition
ping: @ayjayt
~- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).~
> Improve cache for anywidget:

- marimo/_output/formatting.py
- tests/_output/formatters/test_formatters.py
Fixes #5946
svg mime starts with `image` but should be treated differently
> fix: as_html for svg and add tests

- frontend/src/components/editor/chrome/panels/snippets-panel.tsx
Previously once a snippet was open, it could not be closed, making it difficult to explore other snippets.
> improve: make it possible to close open snippet

- docs/guides/expensive_notebooks.md
- docs/guides/reactivity.md
- marimo/_ast/app.py
- marimo/_ast/errors.py
- marimo/_cli/development/commands.py
- marimo/_messaging/errors.py
- marimo/_runtime/dataflow.py
- marimo/_runtime/runner/cell_runner.py
- marimo/_runtime/runner/hooks_on_finish.py
- marimo/_runtime/validate_graph.py
- packages/openapi/api.yaml
- packages/openapi/src/api.ts
- tests/_ast/test_app.py
- tests/_messaging/test_messaging_errors.py
- tests/_runtime/test_dataflow.py
- tests/_runtime/test_runtime.py
- tests/_runtime/test_trace.py
- tests/_runtime/test_validate_graph.py
This change makes it possible to delete variables that were defined in another cell.
The motivation for this change is to allow advanced users to reclaim
memory. Especially when dealing with tensors or large datasets, either
reusing a variable name or explicitly deleting it with `del` are
traditionally used to reclaim memory. Reusing variables is not allowed
in marimo, and before this change `del` was not either, since it wasn't
clear how to order cells.
This change allows the `del` operator by introducing the following rule:
If a cell deletes a variable, it becomes a child of all other cells
that reference that variable.
For example:
**cell u**
```
x
```
**cell v**
```
del x
```
In this case, **v** becomes a child of **u**.
This has the (desired) consequence that two cells cannot delete …
> Allow deleting variables defined by other cells

- .github/workflows/test_fe.yaml
- .github/workflows/test_fe_dagger.yaml.skip
- frontend/src/components/editor/output/MarimoErrorOutput.tsx
The backend changes in #5966 removed the `delete-nonlocal` error variant from the API schema, but the frontend still had code attempting to handle this error type. This caused TypeScript errors because the type narrowing created a `never` type when filtering for a non-existent variant, making the error object properties inaccessible.
> Remove handling for deleted `delete-nonlocal` error type

- frontend/src/css/globals.css
Biome formatter was breaking multi-value box-shadow declarations across multiple lines, which caused Tailwind v4 ring utilities and shadow variants to fail. Updated biome-ignore comments to clarify that these definitions must stay on single lines to work with Tailwind variants, not due to tool conflicts.
> Keep box-shadow CSS definitions on single lines

- frontend/package.json
- frontend/src/components/chat/markdown-renderer.tsx
- pnpm-lock.yaml
This PR adds `remark-gfm` in order to support tables in the chat sidebar.
> improvement: support tables in AI chat sidebar

- frontend/package.json
Adds an `./unstable_internal/*` subpath export to allow importing from source within `@marimo-team/frontend`. This package is not published, and the subpath should be considered internal-only.
> Define package exports for `@marimo-team/frontend`

- frontend/package.json
- frontend/src/core/codemirror/copilot/__tests__/trim-utils.test.ts
- frontend/src/core/codemirror/copilot/extension.ts
- frontend/src/core/codemirror/copilot/trim-utils.ts
- frontend/src/core/network/api.ts
- marimo/_server/ai/prompts.py
- marimo/_server/api/endpoints/ai.py
- pnpm-lock.yaml
- tests/_server/ai/snapshots/edit_inline_prompts.txt
- tests/_server/ai/test_prompts.py
- tests/_server/api/endpoints/test_ai.py
This improves the FIM (fill-in-the-middle) prompting for the common way to prompt these models. 
I used `codegemma` in my testing: https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/codegemma
This also adds some testing and improvements to the codemirror plugin:
- shorter delay on requesting
- ignore if not focused or the cursor has moved
> improvement: better fill-in-the-middle prompting

- docs/reading.md
Update our readings & videos docs page with the new dataflow blog, and fix the link to the reddit launch post.
> docs: add dataflow blog, fix reddit link

- tests/_plugins/ui/_impl/tables/test_narwhals.py
As per title: when converting from narwhals dataframe to dict use `as_series=False` to avoid comparing narwhals Series.
This change is needed since comparing series (and exprs) won't be allowed once https://github.com/narwhals-dev/narwhals/pull/2985 is merged. This emulates the behavior of Polars, pandas and numpy.
> fix(tests): Use `as_series=False` in `assert_frame_equal` to compare Narwhals dataframes

- tests/_runtime/test_dataflow_cases.py
This is the start of test cases aimed to cover more dataflow cases not covered in tests (especially SQL). There are 2 existing xfail which should be fixed by https://github.com/marimo-team/marimo/pull/5992
> tests: add dataflow test cases

- frontend/src/core/runtime/__tests__/config.test.ts
- frontend/src/core/runtime/config.ts
Small fix when the `baseURI` is `blob:https://..`
> fix: handle blob protocol in runtime manager

- frontend/src/core/static/__tests__/files.test.ts
- frontend/src/core/static/files.ts
This re-uses some code for finding the correct virtual file from the `patchVegaLoader` to the `patchFetch`
> fix: patch fetch with more leniant file matching

- frontend/src/core/config/config.ts
We not can pick up keys via environment variables or internal endpoints, so we can just check based if any models are defined.
> update logic for determining when AI is enabled

- frontend/src/components/editor/ai/ai-completion-editor.tsx
Fixes #5135 .
Sets height to full, so now it defaults to the max height of parent container, which is 400px
https://github.com/user-attachments/assets/fcab8e49-eae9-4ca9-a88b-2a227ce4e10e
> clamp height for prompt input in generate height

- marimo/_cli/cli.py
Add support for the `-h` flag as an alias for `--help` in the marimo CLI to improve user experience and follow standard command-line conventions.
Currently, `marimo -h` fails with "No such option: -h", which is unexpected behavior since `-h` is the standard short form for help across most CLI tools.
**Before:**
```bash
$ marimo -h
Error: No such option: -h
```
**After:**
```bash
$ marimo -h
Usage: marimo [OPTIONS] COMMAND [ARGS]...
Welcome to marimo!
$ marimo run -h
Usage: marimo run [OPTIONS] NAME [ARGS]...
Run a notebook as an app in read-only mode.
```
> feat(cli): support -h flag for help in CLI

- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/ai/ai-completion-editor.tsx
- frontend/src/components/editor/ai/completion-handlers.tsx
Hotkey for accept/reject. These are not configurable, but do match Cursor's for familiarity.
> improvement: add hotkeys to AI completion

- marimo/_utils/config/config.py
Closes https://github.com/marimo-team/marimo/issues/4572
The default root dir is ".marimo" and cannot be modified, it will autocreate ".marimo" folder at the user's home in Linux platform.
Add the environment variable XDG_STATE_HOME to support the Linux XDG Base Directory.
1. Get XDG_STATE_HOME environment variable as ROOT_DIR value
2. If it is not set by the user, using the default XDG_STATE_HOME value “~/.config/state”.
3. If the user's system is Windows or others, using default value ".marimo".
4. I don't know if there is a standard for Dir in Windows or other systems, so I use the default value and make it easy for other contributors to modify it.
> Using XDG_STATE_HOME environment variable to support the Linux XDG Base Directory

- marimo/_data/preview_column.py
- marimo/_server/ai/constants.py
- marimo/_server/ai/ids.py
- tests/_data/test_preview_column.py
previously duration types were not supported, this adds support by converting the column type.
> fix: convert time duration to numeric for column explorer

- mkdocs.yml
Fixes #6104 
I delete the excess part of `mkdocs.yml` about dark mode button. It corrects the action of dark mode button.
#6104 
https://github.com/user-attachments/assets/9453dce3-b5ca-4ba5-af14-8258c80ba007
https://github.com/user-attachments/assets/a1e284c8-b695-437c-9eab-7f60e5476100
I have read the CLA Document and I hereby sign the CLA
> fix: fix mkdocs.yml to correct docs darkmode button action

- frontend/src/css/katex.min.css
Fixes #5909
Katex in blockquotes makes it italics which gives it random/unknown characters. This forces `font-style: normal`.
> fix: katex can't be italics

- frontend/src/components/editor/actions/name-cell-input.tsx
- frontend/src/components/editor/output/ConsoleOutput.tsx
- tests/_runtime/test_runtime.py
- tests/_runtime/test_trace.py
Fixes #5964 
The precommit fixed spell "unaccessible" -> "inaccessible" automatically.
I add a Logical AND `&&` to make sure that the 2 button of `Copy all` and `Warp text` only appear when there is any output content.
https://github.com/user-attachments/assets/7fdeac72-9dcd-4afe-a678-5a5426938746
> Fix cellname overlap

- frontend/src/components/ai/ai-model-dropdown.tsx
- frontend/src/components/ai/display-helpers.tsx
- frontend/src/components/app-config/ai-config.tsx
- frontend/src/components/app-config/app-config-button.tsx
- frontend/src/components/app-config/app-config-form.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/core/ai/__tests__/model-registry.test.ts
- frontend/src/core/ai/model-registry.ts
- frontend/src/hooks/useDebounce.ts
- Add tab to configure "Displayed models" in the AI configuration
- Debounce config to avoid DOS the backend on rapid config changes
- Edge case where displayed models could filter out all models. In this case, we revert to showing all models.
> improvement: add tab to configure "Displayed models" in the AI configuration

- pyproject.toml
Narwhals in 2.2.0+ breaks mypy. mostly on call overloads, but a few other places too. I am putting an upperbound, just on the typechecking for now.
We we upgrade to 2.0, i can look to remove this. Again, this is only on the type-checking, but not our published package.
> types: pin narwhals in typecheck

- README_Traditional_Chinese.md
Fixed improper link in the Traditional Chinese, properly links to English.
> Update language links in README_Traditional_Chinese.md

- frontend/src/__mocks__/notebook.ts
- frontend/src/components/editor/ai/__tests__/completion-utils.test.ts
- frontend/src/components/editor/ai/completion-utils.ts
- frontend/src/core/ai/context/__tests__/registry.test.ts
- frontend/src/core/ai/context/__tests__/utils.test.ts
- frontend/src/core/ai/context/context.ts
- frontend/src/core/ai/context/providers/__tests__/__snapshots__/error.test.ts.snap
- frontend/src/core/ai/context/providers/__tests__/__snapshots__/tables.test.ts.snap
- frontend/src/core/ai/context/providers/__tests__/__snapshots__/variable.test.ts.snap
- frontend/src/core/ai/context/providers/__tests__/error.test.ts
- frontend/src/core/ai/context/providers/common.ts
- frontend/src/core/ai/context/providers/error.ts
- frontend/src/core/ai/context/providers/tables.ts
- frontend/src/core/ai/context/providers/variable.ts
- frontend/src/core/ai/context/utils.ts
- frontend/src/core/cells/cells.ts
- marimo/_server/ai/prompts.py
- marimo/_server/models/completion.py
- packages/openapi/api.yaml
- packages/openapi/src/api.ts
- tests/_server/ai/snapshots/chat_system_prompts.txt
- tests/_server/ai/snapshots/system_prompts.txt
- tests/_server/ai/test_prompts.py
This adds a new context provider for Notebook Errors. It currently grabs all errors as a single entry. In the future we could group errors by type or single errors, but i don't think we need to explode out the errors into more choices.
> Add "Notebook Errors" as a context in any AI input

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/navigation/navigation.ts
- frontend/src/components/editor/navigation/state.ts
This removes the usage of `jotai-scope` due to this bug https://github.com/jotaijs/jotai-scope/issues/25
This would 1) cause unnecessary work (not terrible), and 2) re-execute side-effectful atoms. 
We probably should not have side-effectful atoms but one was the runtime-manager which would check if it was healthy on creation. So each new cell would trigger a `/healthy` check
> fix: remove unecessary work in scoped state

- frontend/src/core/islands/islands.css
- frontend/src/core/islands/main.ts
The islands build was emitting a warning:
```sh
Error: Can't resolve '../css/globals.css' in '/Users/manzt/github/marimo-team/marimo/frontend/src/core/islands'
```
Which led to tailwind styles not being included in the build.
This happened because when islands.css imports other CSS files (common.css, md.css, etc.), those files each contain `@reference "../css/globals.css"` on line 1. During the islands library build, these @reference paths were being resolved from the wrong context - from /src/core/islands/ instead of from each CSS file's actual location in /src/css/.
The fix changes the import syntax in islands.css from `@import` to `@import url()`, which prevents the bundler from trying to resolve the nested @reference directives during the build process. This allows Tailwind v4's …
> Resolve CSS path issues in islands build

- frontend/.storybook/preview.tsx
- frontend/.storybook/sb.css
Currently, when I run storybook with `make storybokk`, I see 2 issues in the console related to TailwindCSS 4 compatibility:
Issue 1: Missing "./tailwind.css" specifier
- The import "tailwindcss/tailwind.css" tried to access a non-existent file
- TailwindCSS 4 changed its export structure - tailwind.css doesn't exist
Issue 2: Unknown utility class !important
- TailwindCSS 4 changed how !important works with @apply
- The syntax @apply text-foreground !important is no longer valid
-  Fixed by using new syntax !text-foreground;
Issue 1 is fixed by importing just "tailwindcss" which uses the main entry point
Issue 2 is fixed by using new syntax !text-foreground;
> Storybook tailwind compatibility fixes

- marimo/_cli/cli.py
- marimo/_server/api/deps.py
- marimo/_server/api/endpoints/assets.py
- marimo/_server/start.py
- marimo/_server/templates/templates.py
- tests/_server/templates/test_templates.py
Hidden url `--asset-url` option in CLI to load assets from a CDN (instead of the marimo server). useful if your server is not set up to be a CDN
`uv run marimo edit notebook.py --asset-url="https://cdn.jsdelivr.net/npm/@marimo-team/frontend@{version}/dist"`
> feat: add asset URL support for templates and server

- frontend/src/css/app/Cell.css
Fixes #6020
I've added `overflow:auto` to the `output-area` element. This fixes the setup shown in `Read Mode - Code Shown` story in the `one-column.stories.tsx` file:
and in the published mode, I reset overflow to visible again:
so that the scroll-bar is applicable to the entire notebook, and not the text inside the container.
Also, there was [a comment](https://github.com/marimo-team/marimo/blob/310e3a3c841604e896bdc5db6024657ef738512d/frontend/src/css/app/Cell.css#L408) previously:
>   TODO: Find a way to accommodate large elements, ideally in a way that
>     - doesn't break margin collapse. Setting overflow (eg, overflow: auto)
>     - breaks margin collapse. */
My understand is that it was referring to this case of a child block inside the cell container with a margin:
But it seems …
> fix 6020: output cell fails to wrap text in HTML export

- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
In my findings, this is how rendering pipeline looks like if marimo is runing as regular notebook (not static):
```
mode:
- edit
runner: EditPage → EditApp
cells_renderer: CellsRenderer (wraps children when mode="edit")
children: CellArray (EditableCellComponent | ReadonlyCellComponent | SetupCellComponent)
- read
runner: RunPage → RunApp
cells_renderer: CellsRenderer (mode="read")
plugin: VerticalLayoutPlugin | GridLayoutPlugin | SlidesLayoutPlugin
```
so, vertical-layout.tsx, which is part of `VerticalLayoutPlugin `, where this piece of code is,
```
const className = cn(
"marimo-cell",
"hover-actions-parent empty:invisible",
{
published: published,
interactive: mode === "edit",   <----------------
"has-error": errored,
stopped: stopped,
borderless: isPureMarkdown && !published,
},
); …
```
> Vertical layout cleanup for read mode rendering pipeline

- marimo/_messaging/msgspec_encoder.py
- marimo/_server/api/endpoints/ai.py
- marimo/_server/responses.py
- marimo/_server/router.py
msgspec takes care of our entire struct -> JSON string pipeline. Using the `JSONResponse` from starlette dual encoded our data structures on the frontend.
> Directly create `Response` with encoded JSON instead of `JSONResponse`

- marimo/_data/models.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
The narwhals table provider expects `__dict__` on the struct, which must be enabled explicitly. We ideally could just avoid mutation / dunder methods and just normalize the `ColumnStats` directly.
> Fix `ColumnStats` normalization for msgspec

- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/editor/ai/completion-utils.ts
- frontend/src/core/ai/context/__tests__/registry.test.ts
- frontend/src/core/ai/context/context.ts
- frontend/src/core/ai/context/providers/__tests__/cell-output.test.ts
- frontend/src/core/ai/context/providers/__tests__/error.test.ts
- frontend/src/core/ai/context/providers/cell-output.ts
- frontend/src/core/ai/context/providers/common.ts
- frontend/src/core/ai/context/registry.ts
- marimo/_ai/_convert.py
This PR adds a new `@` context type for cell output. For text or json output, we just include that in the context body. For media types (image, video, charts, tables) we convert from DOM →  PNG and include the attachment.
> feat: cell output for `@` context w/ attachments for media output

- marimo/_server/sessions.py
- marimo/_server/types.py
This change shifts the typing model for `QueueType` from nominal subtyping to structural subtyping. Instead of using a nominal union type (`mp.Queue[T] | queue.Queue[T]`), we define a structural interface via `typing.Protocol[T]`.
The union approach ties type checking to specific classes, even though they expose nearly identical APIs. By introducing a `Protocol`, we specify the minimal structural contract marimo relies on. Any object implementing that contract is valid (including custom queue-like implementations (e.g., a ZeroMQ wrapper) or stubs in marimo-lsp).
> Switch to structural typing for `QueueType`

- marimo/_plugins/ui/_impl/file_browser.py
- tests/_plugins/ui/_impl/test_file_browser.py
Added support for `ignore_empty_dirs` option in directory traversal for the `mo.ui.file_browser`.
Closes #6093
- Hides directories that contain no files (recursively)  
- Scans up to 100 levels deep to prevent stack overflows  
- Skips directory symlinks to avoid infinite loops  
- Applies filetype filtering recursively (case-insensitive)
> feat [6093]: mo.ui.file_browser ignore empty directories

- marimo/_mcp/server/tools/cells.py
- tests/_mcp/server/tools/test_cells.py
During migration of the mcp-server from TypedDict to dataclass `VariableValue` caused a pydantic parsing error due to `mgspec.Struct` not being a pydantic-compatible type. I resolved this by creating a type called `CellVariableValue` that mirrors `VariableValue` but is pydantic-compatible.
> fix(mcp-server): create dataclass wrapper for VariableValue to resolve Pydantic compatibility

- frontend/src/core/codemirror/theme/dark.ts
- frontend/src/css/app/codemirror.css
- frontend/src/css/globals.css
Fixes #6154. Adds background colour and border colour (which is not visible in dark mode)
Before border-colour:
> set sql footer's background colour and border color

- marimo/_ai/_convert.py
We should cast `asdict` using our own encoder which handles both dictionaries and dataclasses
> fix: ai endpoints from msgspec migration

- frontend/src/components/ai/ai-model-dropdown.tsx
- frontend/src/components/app-config/ai-config.tsx
- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/ai/ai-completion-editor.tsx
- frontend/src/components/editor/ai/completion-utils.ts
- frontend/src/core/ai/config.ts
- Display a icon-only model dropdown for users to switch AI model in the inline Generate with AI
- Add @ button,
- Small refactor for AI model dropdown, so we don't need to call atoms in each component that uses this.
> Visibility for @ in Generate with AI, also add model dropdown

- marimo/_ast/pytest.py
- tests/_ast/test_pytest.py
Enables async tests for in notebook auto-testing, e.g.
```python
async def my_test():
assert True
```
Previously, this was only caught by pytest, not within the notebook itself
Instead of ignoring the type of the result of run for a test cell, and assuming that it's synchronous, check for whether it's awaitable, and await it if so.
> fix: allow test cells in the presence of async cells

- development_docs/adding_lint_rules.md
- docs/guides/lint_rules/index.md
- docs/guides/lint_rules/rules/invalid_syntax.md
- marimo/_lint/rules/breaking/__init__.py
- marimo/_lint/rules/breaking/syntax_error.py
- mkdocs.yml
- tests/_lint/snapshots/syntax_errors.txt
- tests/_lint/test_files/syntax_errors.py
- tests/_lint/test_runtime_errors_snapshot.py
Example: Syntax Error Check Rule
The new syntax error rule (MB005) demonstrates the ideal pattern:
- Small footprint: Minimal, focused implementation
- Complete docstring: Structured sections with clear examples
- Proper metadata: Follows MB### pattern with BREAKING severity
- Auto-integration: Automatically appears in generated docs
This rule serves as the perfect reference implementation for future contributors.
See development_docs/adding_lint_rules.md for the complete guide on adding new lint rules, including:
- Required docstring structure
- Metadata requirements
- Testing patterns
- Code assignment guidelines
> feat: syntax error `check` rule as a base example

- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
Related to https://github.com/marimo-team/marimo/pull/3725.
We would like to download the table when selection is `single-cell` or `multi-cell` regardless of the selection.
Download is now failing, after these changes it works again.
> Download table regardless of cell selection

- frontend/src/components/terminal/terminal.tsx
Fixes context menu displaying above the cursor when at the bottom of the screen. Since there is no space, we can display above instead of below.
Normal placement
Above placement
> show terminal above when there is no space

- marimo/_ast/variables.py
- tests/_ast/test_toplevel.py
closes: #6386
Quick fix to add `__class__` as a builtin for toplevel function resolution. To properly resolve `__class__` in its given context a fair bit more complexity, so this simple fix should suffice.
> fix: add '__class__' as a builtin

- marimo/_cli/envinfo.py
- marimo/_server/lsp.py
- tests/_server/test_lsp.py
If a user creates a virtual environment in `/a path with spaces/` then the copilot lsp location may not be properly resolved. This adds string release to properly pass in the binary location.
Additionally, added the `location` key to environment to help debug in the future.
> fix: shelex paths for lsp

- frontend/src/components/terminal/__tests__/state.test.ts
- frontend/src/components/terminal/terminal.tsx
On refresh, the terminal command would not be sent as the isReady would be false. This setsReady when the websocket state is opened.
As a drive-by, adds test
> Properly set terminal to ready to send command

- marimo/_ast/visitor.py
- marimo/_cli/print.py
- marimo/_lint/formatter.py
- marimo/_lint/rules/breaking/syntax_error.py
- tests/_lint/snapshots/multiple_definitions_errors.txt
- tests/_lint/snapshots/star_import_errors.txt
- tests/_lint/snapshots/syntax_errors.txt
- tests/_lint/test_files/star_import.py
- tests/_lint/test_runtime_errors_snapshot.py
`import *` was handled strangely, because visitor throws it as a syntax error:
We now explicitly handle it for more context:
Wanted to get this patched before release since all our "major" marimo specific errors are now covered (https://docs.marimo.io/guides/understanding_errors/)
> fix: Handle 'import *' correctly for marimo check

- docs/_static/CLAUDE.md
- frontend/src/components/chat/acp/__tests__/__snapshots__/prompt.test.ts.snap
- frontend/src/components/chat/acp/prompt.ts
- marimo/_server/ai/prompts.py
- tests/_server/ai/snapshots/chat_system_prompts.txt
- tests/_server/ai/snapshots/system_prompts.txt
- Use polars instead of pandas
- Altair instead of pyplot
- Add a short sql cell guide (don't return df, pass in engine name)
> update system prompt & claude.md

- marimo/_sql/engines/ibis.py
- marimo/_sql/engines/redshift.py
- marimo/_sql/engines/sqlalchemy.py
Fixes #6436 . Looks like an upstream sqlalchemy bug.
> check if default schema and db is string, for engines

- marimo/_sql/sql.py
- marimo/_sql/utils.py
- tests/_sql/test_sql.py
> display plain output for explain queries in duckdb

- .github/workflows/test_cli.yaml
- examples/ai/tools/chat_with_tools.py
- examples/misc/bayes_theorem.py
- examples/misc/colliding_blocks_and_pi.py
- examples/misc/compound_interest.py
- examples/misc/mortgage_calculator.py
- examples/misc/movies_by_the_decade.py
- examples/sql/misc/electric_vehicles.py
- examples/sql/misc/sql_cars.py
- examples/sql/parametrizing_sql_queries.py
- examples/sql/querying_dataframes.py
- examples/sql/read_csv.py
- examples/sql/read_json.py
- examples/sql/read_parquet.py
- examples/third_party/cvxpy/regularization_and_sparsity.py
- examples/third_party/huggingface/chatbot.py
- examples/third_party/motherduck/embeddings/embeddings_explorer.py
- examples/third_party/pymde/complete_graph.py
- examples/ui/batch_and_form.py
- examples/ui/table_advanced.py
- marimo/_cli/cli.py
- marimo/_lint/__init__.py
- marimo/_lint/linter.py
- marimo/_smoke_tests/async_iterator.py
integrates `marimo check` for examples ci. Highlighted in upcoming post
PR is a little noisy so best examined commit by commit:
https://github.com/marimo-team/marimo/commit/4586e10c878c2c7c574d53245fb024e130e8902b
- adds `--ignore-scripts` flag, such that clearly non-marimo files do not count as errors
- changes requirement for updating to ignore `__generated_with` since bumping version numbers is just noise
https://github.com/marimo-team/marimo/commit/b1c42cf409848a00251fa44ed7e276891e2992ef
- ran `--fix --unsafe-fixes` on examples (cleaning up empty cells)
- Changed relevant strings to r strings to prevent errors
https://github.com/marimo-team/marimo/commit/2e8ca238d6c894db5b0d0ae2fb7f3de27821d559
- Added basic CI for examples (We just had a stub for them previously)
> ci: run check on examples

- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/chat/tool-call-accordion.tsx
- marimo/_ai/_tools/tools/datasource.py
- marimo/_ai/_types.py
Displaying the tool arguments will allow easier debugging and visibility.
Previously:
Now:
> display tool inputs for tool accordion

- marimo/_ast/visitor.py
- marimo/_utils/strings.py
- tests/_ast/test_codegen.py
fixes #6446
Fixes quotes in complex annotation types, removing ast default of preferring `'`.
e.g.
`Literal["foo", 'bar']` -> `Literal["foo", "bar"]`
where previously
`Literal["foo", 'bar']` -> `Literal['foo', 'bar']`
> fix: preserve literal strings in type annotations

- frontend/src/components/editor/cell/CreateCellButton.tsx
- frontend/src/components/editor/cell/code/language-toggle.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/codemirror/language/LanguageAdapters.ts
Previously new adapters were created on every keystroke, this only triggers the initialization once. We have to use getters for circular deps issues.
> prevent new language adapter instances being created on keypress

- marimo/_output/md.py
- marimo/_smoke_tests/markdown/codeblocks.py
- marimo/_smoke_tests/markdown/latex_highlighting.py
- marimo/_smoke_tests/markdown/markdown_size.py
- tests/_output/test_hypertext.py
- tests/_output/test_md.py
> return original markdown text, override format

- frontend/src/components/editor/renderers/slides-layout/slides-layout.tsx
- frontend/src/components/slides/slides-component.tsx
- frontend/src/components/slides/slides.css
- marimo/_smoke_tests/slides_examples/centered_slides.py
- marimo/_smoke_tests/slides_examples/layouts/centered_slides.slides.json
Fixes #6463
* Slides are centered better for iframe content 
```
/* If the first output is the only child, make it flex 1 */
> *:only-child > .output:only-child {
flex: 1;
}
```
* Better bottom padding when content overflows
```
min-height: fit-content;
```
* Use more real-estate when slides is not in full screen:
```
return <div className="pr-18 pb-5 flex-1 flex flex-col">{slides}</div>;
```
> fix: center slides better for iframed content

- pyproject.toml
Fixes #6453
Updated the uvicorn dependency in pyproject.toml to specify a version range of >=0.22.0,<0.36.0 to prevent issues with notebook creation introduced in version 0.36.0.
> fix: restrict uvicorn version to avoid notebook creation issues (#6453)

- frontend/src/core/ai/staged-cells.ts
- frontend/src/core/cells/add-missing-import.ts
- frontend/src/core/cells/cells.ts
> add maybe import marimo to Generate with AI

- marimo/_server/lsp.py
- marimo/_utils/strings.py
- tests/_utils/test_strings.py
Incorporates some of https://github.com/smoofra/mslex/blob/master/mslex (Apache 2 with attribution) for correct string quoting on windows to fix copilot
Closes: #6388
> fix: string quoting for marimo

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/errors/sql-validation-errors.tsx
- frontend/src/components/editor/output/MarimoErrorOutput.tsx
- marimo/_smoke_tests/sql_error_handling.py
- marimo/_sql/engines/types.py
- marimo/_sql/utils.py
- tests/_sql/test_sql.py
marimo error:
no more explain for validate mode:
> strips explain, better error output for sql error

- marimo/_ast/transformers.py
- marimo/_convert/comment_preserver.py
- marimo/_convert/ipynb.py
- tests/_convert/ipynb_data/comments_preservation.ipynb
- tests/_convert/snapshots/convert_comments_preservation.py.txt
- tests/_convert/snapshots/convert_multiple_definitions.py.txt
- tests/_convert/test_ipynb.py
Previous comments were removed on jupyter conversion, this will maintain them
> fix: preserve comments in jupyter conversion

- marimo/_output/md.py
- marimo/_output/md_extensions/__init__.py
- marimo/_output/md_extensions/breakless_lists.py
- marimo/_output/md_extensions/flexible_indent.py
- marimo/_smoke_tests/markdown/sane_lists.py
- pyproject.toml
- tests/_output/test_md.py
Fixes #6510 
This loosens some markdown limitations to act more like GitHub Flavored markdown (GFM) such that we allow:
- 2 spaces for tabs 
- Lists can start after paragraph without an empty line
```
uv run marimo edit marimo/_smoke_tests/markdown/sane_lists.py
```
> improvement: support 2-space markdown and paragraphs without newline before lists

- frontend/src/core/dom/events.ts
- frontend/src/core/dom/uiregistry.ts
- frontend/src/core/islands/main.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- frontend/src/plugins/impl/anywidget/__tests__/AnyWidgetPlugin.test.tsx
- frontend/src/plugins/impl/anywidget/__tests__/model.test.ts
- frontend/src/plugins/impl/anywidget/model.ts
- frontend/src/utils/__tests__/data-views.test.ts
- frontend/src/utils/data-views.ts
- frontend/src/utils/json/base64.ts
- marimo/_messaging/ops.py
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_plugins/ui/_impl/comm.py
- marimo/_smoke_tests/anywidget_smoke_tests/mosaic_example.py
- marimo/_smoke_tests/anywidget_smoke_tests/uchimata_example.py
- packages/openapi/api.yaml
- tests/_messaging/test_ops.py
- tests/_plugins/ui/_impl/test_anywidget.py
- tests/_plugins/ui/_impl/test_comm.py
Fixes #6499 
The `msgspec` migration changed how we encode "buffers" (aka binary blobs) in the `UIElement.text`, causing our frontend to dual-encode the responses.
This commit properly decodes buffers at system boundaries by converting base64 strings to `DataView` objects at two key points:
- When extracting buffers from `SendUIElementMessage` operations in the WebSocket handler
- When resolving the initial value from HTML attributes in the AnyWidgetPlugin component
I added several tests were we missed these changes, verifying that buffers are correctly encoded as base64 in HTML and properly handled in the Python backend.
> Fix anywidget initial buffer handling regression

- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/languages/sql/completion-builder.ts
- frontend/src/core/codemirror/language/languages/sql/completion-sources.tsx
- frontend/src/core/codemirror/language/languages/sql/completion-store.ts
- frontend/src/core/codemirror/language/languages/sql/renderers.tsx
- frontend/src/core/codemirror/language/languages/sql/utils.ts
This adds a completion info (unstyled for now) to the table completion.
Also
- utilities for building the `SQLNamespace`
- include default DB in name (not just the tables)
> improvement: add completion info to SQL table completions

- marimo/_runtime/runtime.py
- marimo/_sql/parse.py
- tests/_sql/test_sql_parse.py
Adds more try-catch. Also avoids CAST unless duckdb-version is low.
> runtime fixes for parse_sql, if duckdb not installed

- marimo/_sql/sql.py
We would unecessarily run sqlglot parse even when a default limit is not specified. 
This improves perf, and is less annoying for fresh notebooks (do not require multiple installation popups)
> only run sqlglot limit check when user sets a limit

- marimo/_ai/_tools/tools/cells.py
- marimo/_ai/_tools/tools/tables_and_variables.py
- marimo/_data/models.py
- marimo/_messaging/ops.py
- marimo/_utils/msgspec_basestruct.py
- pyproject.toml
- tests/_ai/tools/tools/test_cells.py
- tests/_ai/tools/tools/test_tables_variables.py
- tests/_utils/test_msgspec_basestruct.py
Create BaseStruct to make msgspec.Struct types compatible with pydantic typechecking (for MCP Server tools). Update old code to now use this and remove redundant types.
This PR reverses the temporary fix implemented in #6265 
- Create BaseStruct with __get_pydantic_core_schema__ in marimo/_utils/msgspec_basestruct.py
- Update datatypes in marimo/_data/models.py to use BaseStruct for marimo/_ai/_tools/tools/tables_and_variables.py tool
- Update CellVariableValue -> VariableValue(BaseStruct) in tables_and_variables.py and cells.py
- Update tests to use VariableValue, inherit Session for type saftey, and use correct DataType enums
- Add pydantic >2 as mcp dependency in pyproject.toml
- Add test that checks if all exposed msgspec.Struct classes exposed to tools Args or Output use BaseStruct
> enhancement(msgspec): create BaseStruct with __get_pydantic_core_schema__ class method and refactor MCP msgspec.Struct types to use it

- marimo/_config/manager.py
- marimo/_server/start.py
- tests/_server/test_sessions.py
Fixes #6534
Closes https://github.com/marimo-team/marimo/issues/4194
Closes https://github.com/marimo-team/marimo/issues/4196
This updates the behavior of watch mode in the server configuration to ensure that user-defined auto-save is kept, rather than being forcibly overridden. We had this originally enabled to avoid conflicts between the server's view of the file and external changes made from the filesystem. Since the cell matching has improved (https://github.com/marimo-team/marimo/pull/6127), I don't expect this to cause issues.
We can in a followup handle overwrites and show the user (similar to how vscode or other IDEs might handle this)
> don't override auto-save by when in --watch mode

- docs/guides/configuration/llm_providers.md
- marimo/_server/ai/config.py
- marimo/_server/ai/providers.py
- tests/_server/ai/test_ai_config.py
- tests/_server/api/endpoints/test_ai.py
This makes the Google API Key optional so you can use hit Google Vertex using environment variabes and application default credentials (ADC)
> improvement: google vertex support, make google key optional

- marimo/_mcp/server/lifespan.py
Update lifespan function for mcp-server to handle errors rather than raising them to the parent server.
Now if an error occurs it won't block marimo backend server from starting, but rather just log it like this:
- Update except block in marimo/_mcp/server/lifespan.py to handle unknown errors internally rather than raising it to parent Starlette app.
> fix(mcp-server): make mcp-server lifespan and startup non-blocking for marimo server

- marimo/_cli/file_path.py
- tests/_cli/test_file_path.py
Adds support for editing files from a Github Gist url. Closes #5950.
There are two ways to enter a Gist url:
1. Direct Raw URLs (`gist.github.com/user/gist_id/raw/file_id/filename`): We fetch them directly.
2. Standard Gist URLs (`gist.github.com/user/gist_id`): For these, we make a request to the GitHub Gist API (`api.github.com/gists/gist_id`) to retrieve metadata. Then we parse the response to find the raw URL of the first Python or Markdown file in the gist.
The code is organized like the Github url flow, with the exception that the extension check is not in the `can_read` function but in the `read` function.
> feat: edit files from a Gist url

- Makefile
Makes `make dev` fail explicitly when marimo can't get the port `pnpm` expects it to use, instead of telling the user to open a `http://localhost:3000` address that doesn't work.
Added `--port 2718` to the command `marimo` in `make dev`
- I have added tests for the changes made.
- I tested this manually, and am not sure if any other test is needed for such a micro change
> devops: make dev explicitly uses the port the pnpm expects (fix #6565)

- docs/getting_started/installation.md
- pyproject.toml
`sqlglot[rs]` is much faster and their readme recommends to install that instead
> Update sqlglot dependency to include 'rs' variant in for better perf

- frontend/src/components/editor/renderers/CellArray.tsx
> always show generate with ai in column mode when opened

- frontend/islands/validate.sh
- frontend/src/hooks/__tests__/useDebounce.test.tsx
- frontend/src/hooks/useDebounce.ts
- frontend/src/plugins/impl/__tests__/NumberPlugin.test.tsx
Fixes #6485
I tried removing the effect altogether, but was getting inconsistent state / infinite loops
Supersedes #6571
> fix: debounce infinite loop

- frontend/src/plugins/impl/DataTablePlugin.tsx
- pnpm-lock.yaml
fix type errors for CI and ran pnpm dedupe
> fix zod schema type errors for data-table

- frontend/src/components/databases/namespace-icons.ts
- frontend/src/components/datasources/datasources.tsx
- frontend/src/core/codemirror/language/languages/sql/renderers.tsx
> standardize db icons for sql

- CONTRIBUTING.md
- marimo/_data/preview_column.py
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- marimo/_utils/narwhals_utils.py
- tests/_data/test_preview_column.py
- tests/_plugins/ui/_impl/charts/test_altair_transformers.py
- tests/_plugins/ui/_impl/test_altair_chart.py
- tests/_plugins/ui/_impl/test_data_explorer.py
- tests/_plugins/ui/_impl/test_table.py
- tests/_utils/test_narwhals_utils.py
After moving to narwhals v2, we can support more dataframe types in certain codepaths and tests.
This also makes multi-step operations lazy to avoid incremental df states
> improvement: use lazy-frames for multi-step processing, include more tests

- marimo/_utils/files.py
- tests/_lint/test_run_check.py
Use `os.sep` for correct globbing mechanism.
Fixed old tests that ignored windows
> fix: windows globbing for check

- marimo/_server/ai/providers.py
This PR fixes the issue of premature client closing for all gemini models which is a blocking issue for using gemini with chat.
- Add _client variable in GoogleProvider
- Update `get_client()` to cache client when first invoked, then reuse the cached client to ensure that between stream iters, the same GoogleClient is used and and the client will not be closed prematurely.
- Also add ignore to return type error for google since it doesn't affect functionality but throws a type error.
> fix (gemini): premature client close error when using gemini models in chat

- frontend/src/components/app-config/mcp-config.tsx
- frontend/src/components/chat/chat-panel.tsx
- frontend/src/components/editor/database/schemas.ts
- frontend/src/components/forms/__tests__/form-utils.test.ts
- frontend/src/components/mcp/hooks.ts
- frontend/src/components/mcp/mcp-status-indicator.tsx
- frontend/src/core/network/CachingRequestRegistry.ts
- marimo/_cli/development/commands.py
- marimo/_server/api/endpoints/ai.py
- marimo/_server/api/endpoints/export.py
- marimo/_server/models/models.py
- packages/openapi/api.yaml
- packages/openapi/src/api.ts
- tests/_server/ai/test_mcp.py
- tests/_server/api/endpoints/test_ai.py
Add MCP status indicators and a refresh button to the Chat Panel
> feat: add mcp status and refresh

- frontend/src/components/editor/output/MarimoErrorOutput.tsx
- marimo/_sql/error_utils.py
- marimo/_sql/sql.py
- tests/_sql/test_sql_error_handling.py
There is poor formatting and column positioning for previous SQL errors, I think we can just return the error message, it contains all the information. Also easier to pass to the AI as context.
> sql errors, just return error message for better formatting

- marimo/_mcp/server/lifespan.py
- marimo/_mcp/server/main.py
- marimo/_plugins/stateless/mpl/_mpl.py
- marimo/_server/api/endpoints/mpl.py
Some of the refactors to `mpl` brought in starlette top-level which does not work for work in wasm
> fix: wasm with starlette issue

- frontend/src/__tests__/chat-history.test.ts
- frontend/src/components/chat/chat-history-popover.tsx
- frontend/src/components/chat/chat-history-utils.ts
- frontend/src/components/chat/chat-panel.tsx
This PR doesn't change the chatState and how many chats we store, we can probably do that in follow-ups.
Might be better to use cmdk for perf when searching but this seems to work fine
https://github.com/user-attachments/assets/697c3441-5cea-413c-9ee3-b3809fb83d51
> group chat history by date, add search bar

- tests/_runtime/reload/test_module_watcher.py
minimal tests seems to fail with `tests/_runtime/reload/test_module_watcher.py::test_disable_and_reenable_reload[k] - KeyError: 'dbm.gnu'` somewhat frequently
> ci: improve minimal flakiness

- marimo/_save/cache.py
- marimo/_save/loaders/loader.py
- marimo/_save/loaders/memory.py
- marimo/_save/save.py
- marimo/_save/stores/file.py
- marimo/_save/stores/store.py
- tests/_save/stores/test_file.py
- tests/_save/test_cache.py
Adds `cache_clear` and `cache_info` functions to relevant cache objects, exposing cache `hits`, `misses`, `time` saved and some of the other defaults present on `functools.cache`
> feat: expand cache api to match functools api

- frontend/src/components/chat/chat-utils.ts
- marimo/_server/ai/providers.py
- tests/_server/ai/test_providers.py
- tests/_server/api/endpoints/test_ai.py
Updated the backend to accomodate multi-tool support for all providers. Updated frontend to check all tool responses before reinvoking automatically.
Resolves #6295 
- Make `extract_content()` return list
- Update tool handling in `as_stream_response()`
- Update frontend to check all tool responses
> feat(ai): Add multi-tool support for all providers

- frontend/src/components/editor/ai/ai-completion-editor.tsx
- frontend/src/components/editor/ai/completion-handlers.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
Adds a run button to accept and immediately run the cell for an AI completion
https://github.com/user-attachments/assets/24db2501-27e2-4fb3-b0b1-091b9a98a0f2
> add run button for floating AI label
