- frontend/index.html
- frontend/src/components/app-config/app-config-form.tsx
- frontend/src/core/config.ts
- frontend/src/css/Cell.css
- frontend/src/editor/renderers/CellArray.tsx
- marimo/_ast/app.py
- marimo/_ast/codegen.py
- marimo/_ast/test_app.py
- marimo/_ast/test_codegen.py
- marimo/_cli/cli.py
- marimo/_cli/test_ipynb_to_marimo.py
- marimo/_server/api/__init__.py
- marimo/_server/api/instantiate.py
- marimo/_server/api/save.py
- marimo/_server/api/save_app_config.py
- marimo/_server/server.py
- marimo/_server/sessions.py
- pyproject.toml
This change adds a private API for per-app configuration:
- Configuration is specified via keyword arguments to the App object. This is a private API (for now).
- Edit-mode only handler for saving app config added.
To start we have just one setting, the width of the app (normal or full). For example,
```python
import marimo
app = marimo.App(width="full")
```
> App config

- .github/workflows/release.yml
When a tag with a version-like name is pushed, builds and uploads a new marimo release to PyPI.
> Add workflow that publishes a release on new tag

- docs/api/misc.md
- frontend/src/core/kernel/messages.tsx
- frontend/src/core/model/cells.ts
- frontend/src/core/state/__tests__/__snapshots__/cells.test.ts.snap
- frontend/src/core/state/__tests__/cells.test.ts
- frontend/src/core/state/cell.ts
- frontend/src/editor/Cell.tsx
- frontend/src/editor/output/MarimoErrorOutput.tsx
- frontend/src/editor/renderers/CellArray.tsx
- frontend/src/stories/cell.stories.tsx
- marimo/__init__.py
- marimo/_messaging/errors.py
- marimo/_runtime/cell_runner.py
- marimo/_runtime/control_flow.py
- marimo/_runtime/runtime.py
- marimo/_runtime/test_control_flow.py
- marimo/_smoke_tests/stop.py
- Add a function `stop(predicate, output)` that stops execution of a cell when `predicate` is `False`
When `predicate` is `True`, this function stops execution of the current cell and makes `output` its output. Any descendants of this cell that were previously scheduled to run will not be run, and their defs will be removed from program memory.
Example:
```python
mo.stop(form.value is None, mo.md("**Submit the form to continue.**"))
```
- Invalidate descendant state on `MarimoInterrupt` (manual stop), for consistency with how other exceptions are handled
- Refactor runtime
> mo.stop; interrupt => state invalidation

- marimo/_runtime/cell_runner.py
- marimo/_runtime/control_flow.py
> Don't print a traceback on mo.stop()

- frontend/src/core/websocket/useMarimoWebSocket.tsx
- frontend/src/utils/Logger.ts
This could be an initial network error. Noticing this in the cloud deployments. We can prevent the initial network error, but as an extra layer of defense, we can try to reconnect
> Add logging for WebSocket closure. Try to reconnect on ws error

- frontend/src/css/md.css
> Add styling for blockquotes in markdown CSS

- frontend/e2e-tests/components.spec.ts
- frontend/src/plugins/impl/CheckboxPlugin.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/DatePickerPlugin.tsx
- frontend/src/plugins/impl/DropdownPlugin.tsx
- frontend/src/plugins/impl/FileUploadPlugin.tsx
- frontend/src/plugins/impl/FormPlugin.tsx
- frontend/src/plugins/impl/Label.styles.ts
- frontend/src/plugins/impl/MultiselectPlugin.tsx
- frontend/src/plugins/impl/NumberPlugin.tsx
- frontend/src/plugins/impl/RadioPlugin.tsx
- frontend/src/plugins/impl/RefreshPlugin.tsx
- frontend/src/plugins/impl/SliderPlugin.tsx
- frontend/src/plugins/impl/SwitchPlugin.tsx
- frontend/src/plugins/impl/TextAreaPlugin.tsx
- frontend/src/plugins/impl/TextInputPlugin.tsx
- frontend/src/plugins/impl/common/labeled.tsx
There shouldn't be any visual changes. But some components are spaced a bit better (i.e. using gap instead of margins).
I used this snippet to update the `construct_element` cell in  `marimo tutorial ui` to compare:
```
def construct_element(value):
if value == mo.ui.array:
return mo.ui.array([mo.ui.text(), mo.ui.slider(1, 10), mo.ui.date()])
elif value == mo.ui.batch:
return mo.md(
"""
- Name: {name}
- Date: {date}
"""
).batch(name=mo.ui.text(label="something"), date=mo.ui.date(label="something"))
elif value == mo.ui.button:
return mo.ui.button(
value=0, label="click me", on_click=lambda value: value + 1
)
elif value == mo.ui.checkbox:
return mo.ui.checkbox(label="check me")
elif value == mo.ui.date:
return mo.ui.date(label="something")
elif value == mo.ui.dictionary:
return …
```
> DRY up labels in ui plugins

- frontend/src/hooks/useDebounce.ts
- frontend/src/plugins/impl/NumberPlugin.tsx
- frontend/src/plugins/impl/SliderPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/buttons.py
- marimo/_smoke_tests/debounce.py
- smoke test included to easily verify
API
- `debounce` is a true/false instead of a delay. ideally we abstract away too many details and we can always at a `debounce_delay` later.
Impl
- for slider, the debounce isn't a time, but rather on mouse up
- for number, the default is 200ms
- although they are different implementations, they achieve the same thing so i think we should keep the naming (`debounce`) consistent
> feat: add debounce to slider and number input

- marimo/_plugins/ui/_impl/array.py
- marimo/_plugins/ui/_impl/dictionary.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_plugins/ui/_impl/refresh.py
- marimo/_plugins/ui/_impl/switch.py
Optional args belonging to the parent `UIElement` class will be made keyword-only going forward.
- Makes it easier to extend APIs with new args
- More readable than **kwargs
> Make `label` a keyword-only arg to UI plugins

- marimo/_server/server.py
if Secure=True and on https, safari just strips these, while chrome does not
> fix: remove cookie Secure=True  to fix safari development

- examples/ai/data_labeler.py
- examples/optimization/signals/app.py
- examples/optimization/signals/modules/dataloaders.py
- examples/optimization/signals/modules/problems.py
- examples/task_list.py
- frontend/src/core/RuntimeState.ts
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_plugins/ui/_impl/array.py
- marimo/_plugins/ui/_impl/batch.py
- marimo/_plugins/ui/_impl/dictionary.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_plugins/ui/_impl/switch.py
- marimo/_plugins/ui/_impl/test_input.py
- marimo/_smoke_tests/state.py
- marimo/_tutorials/ui.py
Adds an optional argument to the `UIElement` class:
```python
on_change: Optional[Callable[[T], None]]
```
where `T` is the type of the element's value.
When not `None`, this function is called right after a `UIElement`'s value is updated with the new value of the element provided as its argument.
Motivation: Lets users colocate side-effecting code, including calling a `State` instance's setter, with the element's construction. This makes code more readable and less error-prone (the alternative is to put side effects in a separate standalone cell that refs the element). It's also needed to support tying two or more elements.
> feat: on_change callback on `UIElement`

- frontend/src/core/codemirror/extensions.ts
- frontend/src/editor/Cell.tsx
Let users accept the smart placeholder with tab, in addition to arrow right. Motivated by watching a user attempt to accept it with tab.
> feat: tab to accept "import marimo as mo" placeholder

- pyproject.toml
> remove python 3.7 from classifier

- marimo/_output/formatters/formatters.py
- path, target args should be optional
- without this fix importing some packages (like dill) fails
> fix: find spec args optional

- marimo/_runtime/cell_runner.py
- marimo/_runtime/test_state.py
we want to check for object identity, not equality. checking for equality can break the kernel if an object overrides __eq__ .
> fix: check for state getter using is operator

- frontend/src/components/ui/input.tsx
- frontend/src/components/ui/textarea.tsx
- frontend/src/plugins/impl/TextAreaPlugin.tsx
- frontend/src/plugins/impl/TextInputPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/inputs.py
> enhancement: add max-length, disabled to text and text_area

- marimo/_server/api/model.py
- marimo/_server/api/test_model.py
- marimo/_smoke_tests/inputs.py
This change extends `parse_raw` to handle nested dataclasses, supporting basic container types:
- `list`, `tuple`, `set`, `dict`
> fix: extend dataclass parsing to handle container types

- marimo/_server/api/format.py
- marimo/_server/api/instantiate.py
- marimo/_server/api/run.py
- marimo/_server/api/save.py
- marimo/_server/api/save_app_config.py
- marimo/_server/api/set_ui_element_value.py
parse_raw now requires python 3.8 style type hints for py3.8 compatibility
> fix api dataclass types

- marimo/_ast/app.py
- marimo/_ast/cell.py
- marimo/_ast/codegen.py
- marimo/_ast/test_codegen.py
- marimo/_config/config.py
- marimo/_messaging/message_types.py
- marimo/_messaging/messages.py
- marimo/_runtime/cell_runner.py
- marimo/_runtime/conftest.py
- marimo/_runtime/dataflow.py
- marimo/_runtime/runtime.py
- marimo/_runtime/test_runtime.py
- marimo/_utils/deep_merge.py
Implements disabled cells in the runtime.
- Marking a cell as disabled means it and the tree rooted at it can't run
- If a disabled cell (or its descendant) is triggered for a run, it is marked as stale
- When re-enabled, if stale, cell runs
Enhances the kernel to keep track of cell metadata separately from the graph. When we remove cells from the graph due to errors, we still want to hang onto their configs.
> feat: disable cell (runtime implementation)

- pyproject.toml
But no upper/lower bound; no-op if user's version incompatible with API we're calling.
> Add black as a dependency for formatting

- frontend/src/core/RuntimeState.ts
- marimo/_runtime/runtime.py
- marimo/_tutorials/intro.py
Kernel was sending completed-run when frontend hadn't registered a new run (on delete cell and on set cell config). This sent runningCount < 0 in the frontend, causing UI updates to be sent when they should have been buffered.
This is just a fix to hold us over to when we merge UI updates in the kernel ...
> fix: remove unexpected completed-run messages

- docs/api/index.md
- docs/api/markdown.md
- docs/api/media/index.md
- docs/api/media/plain_text.md
- marimo/__init__.py
- marimo/_output/builder.py
- marimo/_output/test_builder.py
- marimo/_plugins/stateless/plain_text.py
Create fixed-width preformatted text with `mo.plain_text`.
Other names considered:
- `mo.monospace` - many of our users won't know what this means
- `mo.pre` - even fewer of our users will know what this means
- `mo.text` - confusing to have `mo.ui.text` and `mo.text`
- `mo.plaintext` - clashes with cryptography
> feat: mo.plain_text

- docs/api/console.md
- docs/api/index.md
- marimo/__init__.py
- marimo/_messaging/streams.py
- marimo/_runtime/capture.py
- marimo/_runtime/conftest.py
- marimo/_runtime/redirect_streams.py
- marimo/_runtime/runtime.py
- marimo/_runtime/test_capture.py
Utilities to capture stdout and stderr.
> feat: capture stdout and stderr utilities

- frontend/.gitignore
- frontend/e2e-tests/layout-grid.spec.ts
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/config/config.ts
- frontend/src/editor/renderers/grid-layout/grid-layout.tsx
- frontend/vite.config.ts
- remove vertical compaction
- prevent collisions from moving your widgets around
- configurable row height and # of columns
- add grid lines
- make widgets scrollable (if they don't fit)
> grid layout improvements

- marimo/_runtime/runtime.py
- marimo/_server/sessions.py
- Prevent signals intended for server process from interfering with kernel
- Fixes a bug in which Ctrl+C sent to terminal interrupted kernel
- Won't fix Windows ...
> Detach kernel process from server

- .github/workflows/test.yaml
- .github/workflows/test_cli.yaml
- marimo/_ast/test_codegen.py
- marimo/_cli/test_ipynb_to_marimo.py
- marimo/_output/data/data.py
- marimo/_plugins/stateless/pdf.py
- marimo/_runtime/runtime.py
- marimo/_runtime/test_virtual_file.py
- marimo/_runtime/virtual_file.py
- marimo/_server/api/__init__.py
- marimo/_server/api/virtual_file.py
- marimo/_server/server.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/pdf.py
- pyproject.toml
This change adds "virtual files" — files served by the marimo server, accessed via a route `/@file/{filename}`.
- This enables plugins like `mo.pdf` and `mo.image` to take URLs to virtual files instead of binary data in their HTML attributes
- Care is taken to make virtual filenames unique within kernel thread (by using random filenames) and across kernel threads (by prepending a thread ID)
- The mimetype of the file is inferred from its extension
- We use Python's `shared_memory` module to make the virtual file data accessible to the server (it's registered in the kernel) — this is really only needed in edit mode, in which the kernel is a separate process instead of a thread. In run mode, we could in the future add a simpler path just use (lock-protected) global memory ...
- Virtual …
> Shared memory for virtual files

- frontend/src/components/ui/combobox.tsx
- frontend/src/core/codemirror/extensions.ts
- frontend/src/plugins/impl/ButtonPlugin.tsx
- frontend/src/plugins/impl/DatePickerPlugin.tsx
- frontend/src/plugins/impl/DropdownPlugin.tsx
- frontend/src/plugins/impl/MultiselectPlugin.tsx
- frontend/src/plugins/impl/NumberPlugin.tsx
- frontend/src/plugins/impl/TextAreaPlugin.tsx
- frontend/src/plugins/impl/TextInputPlugin.tsx
- frontend/src/plugins/impl/common/labeled.tsx
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/full_width.py
Added to these elements
- mo.ui.text,
- mo.ui.text_area
- mo.ui.button
- mo.ui.number
- mo.ui.dropdown
- mo.ui.multiselect
- mo.ui.date
Note in the smoke test, full width does not apply when its parent is flex (e.g. a hstack). There is a fixable solution by making it `flex: 1` and then updating a few components to be `display: contents`. but this can break other elements. easier to show live, but my guess is we can support this later
> improvement: support full-width input UI elements

- frontend/src/App.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/core/codemirror/format.ts
- frontend/src/core/config/config.ts
- frontend/src/editor/renderers/CellArray.tsx
- frontend/src/stories/cell.stories.tsx
- frontend/vite.config.ts
- marimo/_config/config.py
- marimo/_config/test_config.py
format on save when the user saves the code. default to `False` in case they dont have a formatter installed
> feat: format on save

- marimo/_ast/test_visitor.py
- marimo/_ast/visitor.py
This fixes a bug in importing nested modules (import a.b.c); previously, a.b.c was being treated as the def, whereas it should just be a (since we don't track attributes). This bug broke an assumption in marimo's loading of an app file.
> fix: fix importing nested modules

- frontend/src/core/state/cells.ts
- frontend/src/editor/chrome/panels/error-panel.tsx
- frontend/src/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/editor/chrome/wrapper/footer.tsx
- frontend/src/editor/links/cell-link.tsx
- frontend/src/editor/output/MarimoErrorOutput.tsx
> feature: Errors sidebar

- marimo/_server/api/set_cell_config.py
- marimo/_server/api/test_model.py
- marimo/_smoke_tests/altair_charts.py
> fix: typing issue in python 3.8

- frontend/src/plugins/impl/vega/VegaPlugin.tsx
- frontend/src/plugins/impl/vega/fix-relative-url.ts
- marimo/_dependencies/dependencies.py
- marimo/_output/data/data.py
- marimo/_output/formatters/altair_formatters.py
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- marimo/_plugins/ui/_impl/test_altair_chart.py
- marimo/_runtime/virtual_file.py
- marimo/_server/api/virtual_file.py
- marimo/_smoke_tests/altair_charts.py
- marimo/_smoke_tests/charts/1mil_flights.py
* add custom altair data_transformer for csv and json (default to csv)
* add smoke_test for 1 million flights
* fix shared memory buffer to use the write buffer offset
> improvement: Custom altair data_transformer, load 1 million points

- frontend/src/plugins/layout/ProgressPlugin.tsx
- align progress bar text to start instead of center
- make title font size smaller
> minor change to progress bar style

- marimo/_runtime/cell_runner.py
- marimo/_runtime/control_flow.py
- marimo/_runtime/test_runtime.py
- fixes a bug where `except Exception` would catch marimo's `MarimoInterrupt` exception
- makes `MarimoInterrupt`, `MarimoStopError` inherit from `BaseException` just like the builtin `KeyboardInterrupt`, so `except Exception` doesn't swallow them
- fixes a bug where `KeyboardInterrupt` crashed the kernel
> fix exception handling with user interrupts

- frontend/src/core/codemirror/completion/hints.ts
- frontend/src/css/codemirror.css
- marimo/_runtime/complete.py
- fixes a bug which prevented user from being able to select (eg copy) text in a completion window
- blur logic for closing completion window already handled by cell component
- fix a bug in which kernel stopped sending "no completions" op
- make tooltips appear above code completion
> fix: autocomplete regressions

- frontend/src/components/forms/switchable-multi-select.tsx
- frontend/src/components/ui/combobox.tsx
- frontend/src/components/ui/form.tsx
- frontend/src/components/ui/native-select.tsx
- frontend/src/components/ui/select.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- frontend/src/plugins/impl/data-frames/forms/context.ts
- frontend/src/plugins/impl/data-frames/forms/form.tsx
- frontend/src/plugins/impl/data-frames/forms/options.ts
- frontend/src/plugins/impl/data-frames/panel.tsx
- frontend/src/plugins/impl/data-frames/python/code-panel.tsx
- frontend/src/plugins/impl/data-frames/schema.ts
- frontend/src/plugins/impl/data-frames/utils/operators.ts
- frontend/src/stories/dataframe.stories.tsx
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
* add RPC to `mo.ui.dataframe` to load column values. this loads all values instead of at that particular transform or filter. this adds complexity and could be confusing to users.
* refactor the inputs in form.tsx to be more re-usable and use better inputs (selects, multi-select, etc)
* make panels the same height to avoid content shift
* improving some border styling
> dataframe: load values from backend and distaply in better dropdowns

- frontend/src/core/dom/__tests__/outline.test.ts
- frontend/src/core/dom/outline.ts
- frontend/src/core/model/cells.ts
- frontend/src/core/model/outline.ts
- frontend/src/core/state/__tests__/__snapshots__/cells.test.ts.snap
- frontend/src/core/state/cell.ts
- frontend/src/core/state/cells.ts
- frontend/src/editor/chrome/panels/outline-panel.css
- frontend/src/editor/chrome/panels/outline-panel.tsx
- frontend/src/editor/chrome/types.ts
- frontend/src/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/editor/chrome/wrapper/footer.tsx
- marimo/_output/md.py
* this is just in editor mode, until we get more feedback in app-mode / how this could be handled (app-config, always, `mo.toc()`, etc)
* we don't handle duplicate headers between different cells, we just go to the first header. i think this is ok as we likely want the user to define unique headers. i'd propose we can handle this based on feedback
> feat: add outline as a panel while in edit-mode

- marimo/_smoke_tests/charts/1mil_flights.py
-100k is slow with select
@mscolnick included a scatter plot in the charts smoke test. it's not really usable at 100k points right now -- haven't looked into where the slowness is coming from
> Add scatter to smoke test

- marimo/_config/config.py
- marimo/_server/server.py
Let user specify which web browser to use.
Implements the feature requested in #265
> feat: add BrowserConfig to UserConfig

- frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/completion/hints.ts
- frontend/src/css/Cell.css
- frontend/src/css/codemirror.css
* clear tooltip on Esc and don't lose focus
* improve dark mode contrast
* make tooltip height responsive, With This One Neat Trick™️
> Update code editor to clear tooltips on 'Escape' key press, adjust code cell active line contrast in dark mode and optimize tooltip height

- frontend/src/css/codemirror.css
- marimo/_runtime/complete.py
* change font of tooltip
| With monospace | Without monospace |
|--------|--------|
| ![Screenshot 2023-10-28 at 12 01 27 PM](https://github.com/marimo-team/marimo/assets/2753772/c4ee9dd0-52de-4b24-8d93-747e7a8434c1) | ![Screenshot 2023-10-28 at 12 01 18 PM](https://github.com/marimo-team/marimo/assets/2753772/94cb8426-1654-4896-ad6e-1a7545e9dad6) |
> Update tooltip styles in codemirror.css and handle docstrings differently based on module in complete.py

- marimo/_runtime/runtime.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/charts/1mil_flights.py
- marimo/_smoke_tests/forms.py
This change fixes a bug in which refreshing in edit mode would kill the server. Previously, a CTRL_BREAK event was sent to the kernel process, but this killed the server, since the kernel process is in the same process group as the parent. Instead, this change uses the `Process.terminate()` method to force the process to exit, which uses `TerminateProcess` on Windows.
A better fix would figure out how to put the kernel process in its own process group on Windows; that would let us send the ctrl-break and still do cleanup in the kernel process. This is possible through the subprocess module (creation_flags), but not through the multiprocessing module as far as I can tell. To start a process with subprocess, though, requires starting it as an external program, which is extra (coding) work. …
> fix: [windows] refresh shouldn't kill server

- marimo/_runtime/virtual_file.py
- marimo/_server/api/virtual_file.py
- marimo/_smoke_tests/third_party/plotly.py
- marimo/_smoke_tests/ws.py
Can't close `shared_memory` objects on Windows due to a bug in the Windows implementation of `shared_memory` (or an incorrect description in the Python docs).
Makes altair plots, plotly plots work on Windows (for #273)
> Fix virtual files on Windows

- marimo/_plugins/ui/_core/ui_element.py
- marimo/_plugins/ui/_impl/array.py
- marimo/_plugins/ui/_impl/test_array.py
Fixes array updates to check value frontend sent against last value received from frontend (instead of against Python value). Fixes a bug in which `mo.ui.array()` couldn't hold `mo.ui.dataframe` and other complex types.
> fix ui.array updating logic: check against frontend value

- marimo/_plugins/ui/_core/ui_element.py
- marimo/_runtime/runtime.py
This change fixes a race in the UI element lifecycle. Previously we relied on `__del__` to cleanup global state associated with a cell, but we can't rely on when Python will call `__del__`. This change moves the cleanup code to a `CellLifecycleItem`.
> fix: Eliminate race in UI element lifecycle

- marimo/_plugins/stateless/mpl/_mpl.py
- marimo/_smoke_tests/third_party/plotly.py
- marimo/_smoke_tests/ws.py
Stops the HTTP server for mpl.interactive when it's cleaned up.
@mscolnick mpl interactive works fine for me on linux and macOS. This change is just a precaution but it doesn't seem to affect behavior for me. Can you share a repro for the issue you found?
> Stop HTTP Server for MPL Interactive on cleanup

- docs/faq.md
FAQ: Use `plt.tight_layout()` to prevent axes labels from being cut off
> faq: plt.tight_layout

- pyproject.toml
Raise pygments min version. There was a bug in 2.11.2 that broke syntax highlighting. Increase to 2.13, which I've been using locally, to be safe.
> fix: increase pygments min version

- frontend/src/editor/renderers/vertical-layout/vertical-layout-wrapper.tsx
> fix: remove aggressive padding on mobile

- marimo/_plugins/ui/_core/registry.py
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_runtime/test_ui_element_registration.py
UI elements may be cached across runs, so can't be tied to cell lifecycle. Use __del__ to manage, but add safety check to account for fact that we don't know when del will be called
Fixes #307. An analogous bug exists for virtual files, but the fix is not as apparent.
> fix cleanup of UI elements

- marimo/_output/hypertext.py
- marimo/_plugins/stateless/mpl/_mpl.py
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_runtime/cell_lifecycle_item.py
- marimo/_runtime/cell_lifecycle_registry.py
- marimo/_runtime/runtime.py
- marimo/_runtime/test_virtual_file.py
- marimo/_runtime/virtual_file.py
This PR includes an important fix to the management of virtual file lifecycles.
Previously, all of a cell's virtual files were deleted at the end of its lifecycle. This broke cached HTML that referenced those virtual files (e.g., with a `@functools.cache` decorator).
This change adds reference counting to virtual files, to prevent them from being deleted when objects exist referencing them. We assume that only HTML objects will reference virtual files, and we implement the ref-counting by string matching on HTML text: on object creation, we search the text to find its virtual files and increment their refcounts, on deletion we decrement these refcounts. String matching was the simplest solution we could find that is compatible with using f-string interpolation of HTML text into other HTML …
> Fix: Don't Delete Cached Virtual Files

- frontend/e2e-tests/layout-grid.spec.ts
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/dependency-graph/constants.ts
- frontend/src/components/dependency-graph/custom-node.tsx
- frontend/src/components/dependency-graph/dependency-graph.css
- frontend/src/components/dependency-graph/dependency-graph.tsx
- frontend/src/core/state/__tests__/cells.test.ts
- frontend/src/core/state/cells.ts
- frontend/src/editor/cell/TinyCode.css
- frontend/src/editor/cell/TinyCode.tsx
- frontend/src/editor/chrome/panels/dependency-graph-panel.tsx
- frontend/src/editor/chrome/panels/variable-panel.tsx
- frontend/src/editor/chrome/types.ts
- frontend/src/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/editor/chrome/wrapper/footer.tsx
- frontend/src/hooks/useDebounce.ts
Adds a panel for a vertical dependency tree. the edges are along the side only when a node it clicked. 
This is using the library https://reactflow.dev
Some alternatives:
* add a button for more of a tree view (TB or LR). Could additional focus on an element so there is an inverted-tree above and a tree below
* add more controls for zoom/pan
> feat: dependency graph

- pyproject.toml
Polars `0.19.13` requires maturin to be built from source, which breaks our CI (https://github.com/pola-rs/polars/pull/12370)
> Fix broken docs CI

- marimo/_output/formatters/pandas_formatters.py
Previously the formatter showed the entire dataframe, which can make the frontend slow and unresponsive. This change sets pandas options for `display.max_rows` and `display.max_columns` to 10 and 20.
Users can override these options using `pd.set_option` or the pandas option context manager. Or they can output the HTML themselves: `mo.Html(df.to_html())`.
Fixes #339
> Fix: truncate dataframes rows, columns in output

- frontend/src/components/editor/cell/TinyCode.tsx
- frontend/src/components/editor/renderers/grid-layout/grid-layout.tsx
- frontend/src/components/editor/renderers/grid-layout/plugin.tsx
- frontend/src/components/editor/renderers/grid-layout/types.ts
- frontend/src/components/editor/renderers/plugins.ts
few changes to make grids more usable, will list them out once done:
* move drag handle outside of the content to avoid clicks and drags
* add scroll config to each panel
* add `side`: "left", "right" to each output. can later add top/bottom and start/end
* add max-width
* make it easier to drag items down
> fix: grid improvements

- frontend/src/core/codemirror/cm.ts
currently there is a tradeoff, and I spent some time trying for no tradeoff, but was unable to find a solution.
when `position: absolute` is enabled, we can select text within the tooltip without losing focus of the editor.
when `position: fixed` is enabled, the autocomplete and hover tooltip take up a bit more space up to the edges thus utilizing more space.
> Update tooltip position to absolute

- examples/third_party/mapbox.py
The Mapbox example used `mo.state` even though it didn't need to. Simpler to just use the value of the UI Element.
> eliminate unnecessary use of state

- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- frontend/src/plugins/impl/plotly/__tests__/parse-from-template.test.ts
- frontend/src/plugins/impl/plotly/parse-from-template.ts
- marimo/_plugins/ui/_impl/plotly.py
- marimo/_smoke_tests/third_party/plotly.py
Fixes https://github.com/marimo-team/marimo/issues/353
* Add indexes property to mo.ui.plotly - this is a great escape hatch to filter an original dataset in case not all the data is passed to plotly)
* update points to use original column names, instead of `x`, `y`
> Add indexes property to mo.ui.plotly, and update points to use original column names

- marimo/_runtime/output/_output.py
- marimo/_runtime/output/test_output.py
This change fixes a bug that prevented `mo.spinner()` from being cleared on context manager exit (previously it was only cleared at the end of cell execution, by the cell's last expression -- but when running in a callback there is no "last expression").
> fix: flush empty outputs

- marimo/_server/server.py
mime types are pulled from the registry on Windows, which can sometimes be corrupted. This change explicitly registers mime types with the `mimetypes` module.
Context here: https://github.com/encode/starlette/issues/829
> Initialize mimetypes

- marimo/_ast/test_visitor.py
- marimo/_ast/visitor.py
`from foo import *` should not register `*` as a definition
> fix: star is not a name

- frontend/src/core/codemirror/completion/hints.ts
- frontend/src/css/codemirror.css
- white-space: pre-wrap on pre elements was obscuring code at the end (right) of a cell; change to white-space: pre instead.
- pre over pre-wrap means that user may sometimes need to scroll horizontally to see complete docstring text; this is an acceptable tradeoff compared to obscuring the code the user was trying to type
also tweaks some settings to make more of docstrings visible, without compromising legibility too much
> fix: tooltip should not obscure code

- frontend/src/components/editor/Cell.tsx
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/completion/hints.ts
- frontend/src/css/codemirror.css
Prior to this fix, cursor tooltips would bounce distractingly when typing near the end of a cell, as codemirror would think the tooltip exceeded its space and therefore repositioned it.
This change eliminates that bounce by switching back to fixed positioning for tooltips.
This change does NOT regress selectable completion text.
- Previously, we had switched from fixed to absolute to allow text to be selected, but this came with downsides (including tooltip bounce).
- To ensure text is selectable, we make the Cell responsible for closing completions/tooltips on blur. (The cell was already responsible for closing completions, for this very reason.)
- As a bonus, cursor tooltips are now selectable, whereas they previously weren't.
> fix: elminate bouncing of tooltip

- examples/embeddings/rotational_invariance.py
> example: rotational invariance of embeddings

- marimo/_cli/cli.py
- marimo/_cli/file_path.py
- marimo/_cli/ipynb_to_marimo.py
- marimo/_cli/test_file_path.py
This change updates `marimo convert` to handle github URLs.
Example:
`marimo convert https://github.com/cvxgrp/pymde/blob/main/examples/drawing_graphs.ipynb`
> marimo convert: from github url

- marimo/_ast/test_visitor.py
- marimo/_ast/visitor.py
Python disallows `import *` everywhere except at the module-level. We store marimo code in functions, so we can't support `import *`. Star imports are also not great because they introduce globals that marimo can't easily track
This fixes a bug in which a user could create a notebook with a `star` import but then couldn't re-open it due to the syntax error.
> fix: disallow `import *` in marimo notebooks

- .github/workflows/test.yaml
- marimo/_ast/codegen.py
- marimo/_ast/test_visitor.py
- marimo/_ast/visitor.py
- marimo/_output/formatters/altair_formatters.py
- marimo/_output/formatters/plotly_formatters.py
- marimo/_output/formatters/seaborn_formatters.py
- marimo/_plugins/stateless/mpl/_mpl.py
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- pyproject.toml
Python 3.12 introduced a new type parameter syntax, with scoping rules. This change implements those rules.
Before this change, in the statement
```python
type Alias[T] = list[T]
```
`T` was incorrectly parsed as a ref. This change ensures that `T` doesn't leak from its annotation scope.
More information here:
https://docs.python.org/3/whatsnew/3.12.html#pep-695-type-parameter-syntax
> fix: Python 3.12 type parameter syntax

- marimo/_output/formatters/altair_formatters.py
- marimo/_output/formatters/plotly_formatters.py
- marimo/_output/formatters/seaborn_formatters.py
- marimo/_plugins/stateless/mpl/_mpl.py
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_plugins/ui/_impl/array.py
- marimo/_plugins/ui/_impl/batch.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- marimo/_plugins/ui/_impl/test_batch.py
- marimo/_plugins/ui/_impl/test_dictionary.py
`ui.batch` and `ui.dictionary` should only update their children when the new value is different from the old value, like `ui.array`.
> fix: batch/dict should only update when necessary

- marimo/_cli/file_path.py
Prints a helpful error message on using marimo convert if user tries to edit a Jupyter notebook.
Closes #392
> Helpful error for marimo edit foo.ipynb

- docs/faq.md
- docs/recipes.md
Improve the docs recipes and FAQs for creating outputs with a dynamic number of UI elements. Also add a FAQ for "Why aren't my `on_change` handlers being called?`.
In the future, we can experiment with error messages that point people to the FAQ/recipes if they have unbound UI elements with handlers, and/or experiment with `mo.ui.vstack` and `mo.ui.hstack`.
> docs: improve batch recipe + faq

- frontend/src/core/codemirror/completion/hints.ts
- marimo/_runtime/complete.py
Cursor tooltips get in the way of code too often, especially when editing markdown, or editing the middle of a long expression inside a function call. 
This PR just disables cursor tooltips. Fine-tuning them (eg better positioning, preventing them from re-opening after user hitting escape, and surely other tweaks) would take more effort than it's worth right now. Now that we have hover tooltips, the need for cursor tooltips is much less.
@mscolnick open to discuss if you disagree
> Remove cursor tooltip

- marimo/_config/config.py
- marimo/_messaging/console_output_worker.py
- marimo/_output/rich_help.py
- marimo/_plugins/core/web_component.py
- marimo/_plugins/ui/_impl/utils/dataframe.py
- marimo/_server/server.py
- marimo/_server/sessions.py
- pyproject.toml
Since the following libraries are present only when installed with python <3.9, you can adopt the following requirements spec:
```toml
[project]
dependencies = [
...
"importlib_resources>=5.10.2; python_version < \"3.9\"",
"typing_extensions>=4.4.0; python_version < \"3.9\"",
...
]
```
In this way, they will only be installed for Python <3.9.
> Leaner requirements for Py>3.8

- marimo/_cli/ipynb_to_marimo.py
- marimo/_cli/test_ipynb_to_marimo.py
- marimo/_plugins/ui/_impl/utils/dataframe.py
- marimo/_test_utils/ipynb_data/markdown.ipynb.txt
In marimo convert, emit raw string literals to properly handle backslashes. An alternative would be to escape backslashes, but this feels cleaner, especially in the presence of LaTeX.
Closes #423
> fix: handle backslashes in md (marimo convert)

- frontend/pnpm-lock.yaml
- frontend/src/plugins/core/registerReactComponent.tsx
- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- frontend/src/plugins/impl/vega/VegaPlugin.tsx
- frontend/src/plugins/layout/TexPlugin.tsx
This reduces the initial js loaded from **3.8mb gzip to 1.3mb gzip** (~30%)
* lazy load plotly
* lazy load vega
* lazy load katex
* `pnpm dedupe`
Those 3 libraries moved the needle the most.
> improvement: lazy load plotly, katax, and vega for smaller initial load js

- frontend/src/components/editor/renderers/vertical-layout/vertical-layout-wrapper.tsx
- frontend/src/components/static-html/static-banner.tsx
- frontend/src/core/static/download-html.ts
- marimo/_cli/file_path.py
- add dialog for instructions to download
- cleanup filenames and extensions in static export
- support html files in `marimo edit <html_url>`
> improvement: include instructions for how to run static notebooks

- frontend/src/components/editor/cell/useRunCells.ts
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/App.tsx
- frontend/src/core/functions/FunctionRegistry.ts
- frontend/src/core/kernel/RuntimeState.ts
- frontend/src/core/kernel/__tests__/RuntimeState.test.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
Previously if `sendComponentUpdates` failed with a 403 or any other network request, the app would not be able to send any more updates. This makes sure we can recover from those
> fix: fix RuntimeState to be able to recover from failed ui element updates

- frontend/tailwind.config.js
Previously you could not scroll in the console area of a cell due to overlapping elements. This fixes that.
> fix: scroll in cell's console output

- frontend/e2e-tests/helper.ts
- frontend/postcss.config.js
- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/code/readonly-python-code.tsx
- frontend/src/components/editor/inputs/Inputs.styles.ts
- frontend/src/components/editor/renderers/plugins.ts
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- frontend/src/css/Cell.css
- frontend/src/plugins/impl/data-frames/python/code-panel.tsx
* always show a button in the static export to view the code
* code is shown **above** 
* defaults to hidden, but can expose this by a query-param in future if requested
* option to copy each code on hover
> improvement: option to show code in static html

- marimo/_ast/test_visitor.py
- marimo/_ast/visitor.py
This change fixes an issue in Python 3.12, in which functions with generic type parameters were incorrectly introducing refs. Without this change,
```python
def test[U](u: U) -> U: ...
```
generated a ref of `U`. This change makes sure that `U` is not added as a ref (or def).
Closes #388
> fix: handle type params in function defs

- marimo/_server/api/code_complete.py
- marimo/_server/api/delete.py
- marimo/_server/api/directory_autocomplete.py
- marimo/_server/api/format.py
- marimo/_server/api/function_call.py
- marimo/_server/api/instantiate.py
- marimo/_server/api/interrupt.py
- marimo/_server/api/read_code.py
- marimo/_server/api/rename.py
- marimo/_server/api/run.py
- marimo/_server/api/save.py
- marimo/_server/api/save_app_config.py
- marimo/_server/api/save_user_config.py
- marimo/_server/api/set_cell_config.py
- marimo/_server/api/set_ui_element_value.py
- marimo/_server/api/validated_handler.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/status.py
This change makes the server token in run mode a hash of the code, to prevent frontends made for one app from trying to instantiate on a server serving a different app. This still allows frontends to connect to a server that died and came back as long as the server is serving the same app.
> fix: check frontend's app matches server's app in run mode

- marimo/_cli/envinfo.py
So we can tell if users are using x86 or arm.
Example:
```
{
"marimo": "0.1.64",
"OS": "Linux",
"OS Version": "6.2.0-36-generic",
"Processor": "x86_64",
"Python Version": "3.10.12",
"Binaries": {
"Chrome": "119.0.6045.159",
"Node": "v18.13.0"
},
"Requirements": {
"black": "23.3.0",
"click": "8.1.3",
"jedi": "0.18.2",
"pymdown-extensions": "10.0.1",
"tomlkit": "0.12.1",
"tornado": "6.2",
"typing_extensions": "4.4.0"
}
}
```
> Add processor to marimo env

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/code/readonly-python-code.tsx
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- frontend/src/core/cells/__tests__/cell.test.ts
- frontend/src/core/cells/cell.ts
- frontend/src/core/codemirror/language/python.ts
Fixes https://github.com/marimo-team/marimo/issues/448
* Refactor output staleness check in Cell component to use shared function
* Test said function
This issue existed since we render cells slightly differently in run mode vs edit mode. We do this to avoid extra logic like drag handlers and edit UI, so ideally we DRY up logic between the two
> fix: fix incorrect staleness indicator of outputs in run mode

- marimo/_cli/envinfo.py
- marimo/_output/formatters/pandas_formatters.py
When a Pandas dataframe is truncated, show the dimensions.
Closes #389
> feat: show rows, columns of truncated dataframes

- frontend/src/core/cells/cell.ts
This change fixes an issue in which the elapsed time wasn't shown for errored cells.
Closes #458.
> fix: show elapsed time for errored cells

- frontend/src/core/kernel/RuntimeState.ts
- frontend/src/plugins/impl/MultiselectPlugin.tsx
- frontend/src/plugins/impl/__tests__/MultiSelectPlugin.test.ts
- frontend/src/utils/repl.ts
Previous the `filterFn` used in multi-select could return more results than desired. This is because the `filterFn` focused on sorting by relevance if it was a fuzzy-match instead of fully filtering out items that only matched a little. 
This PR instead overrides the `filterFn` to still be a little fuzzy but only by word boundaries and lowercase - see the test cases for examples.
Closes https://github.com/marimo-team/marimo/issues/457
> improve: multi-select filter function

- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- marimo/_cli/cli.py
- marimo/_cli/test_cli.py
- marimo/_server/server.py
- marimo/_server/sessions.py
Add a command-line flag to include the code when running a marimo notebook as an app. This enables a button in the app that allows the user to toggle between notebook view and app view:
`marimo run notebook.py --include-code`
> improvement: add --include-code to marimo run

- frontend/src/components/editor/CommandPallette.tsx
This removes `Ctrl+k` from opening the Command Palette as it is a used hot-key, and instead just opens on `Meta+k` (for Mac, it would be `Cmd+k`)
Fixes https://github.com/marimo-team/marimo/issues/466
> fix: remove Ctrl+k keyboard shortcut in CommandPalette component

- frontend/src/core/websocket/useMarimoWebSocket.tsx
- marimo/_runtime/conftest.py
- marimo/_runtime/runtime.py
- marimo/_server/sessions.py
This PR fixes a race condition in which the frontend sent configs to the kernel without awaiting and instantiated it with code at the same time.
The fix is to just create the kernel with the configs in the backend, and remove the initial saveCellConfig request from the frontend.
> Create kernel with configs on the backend

- pyproject.toml
Update pyproject.toml to explicitly include only the `marimo` package. This fixes an issue surfaced by https://github.com/conda-forge/staged-recipes/pull/24865, in which `examples`, `frontend`, and `docs` where also getting installed as top-level packages.
> Only distribute the marimo package

- marimo/_server/sessions.py
The kernel process should not be daemonic, since daemon processes can't create children (notebooks may use multiprocessing).
The process was previously made daemonic as a precaution to make sure it terminated when the parent did. We have since hardened the code to make sure that the kernel process is terminated, and shouldn't need the daemon flag anymore.
> Fix: kernel process should not be daemonic

- frontend/src/components/editor/SortableCell.tsx
- frontend/src/components/editor/cell/cell-context-menu.tsx
- frontend/src/css/Cell.css
The tray that extended to the edged would mess up the transforms with the drag-and-drop library. So we hide the trays (just used for hover actions) when we are dragging any cells
> fix: dragging cells when in wide mode

- docs/faq.md
Add an FAQ about using `headless` when starting marimo on a remote server
> FAQ: running marimo on a remote server

- codecov.yml
Set a large threshold so CI doesn't fail. We will decrease threshold as our testing becomes more mature.
> Add codecov.yml config

- scripts/print_banned_cell_names.py
This change adds a utility for printing a list of banned names for cells. Run it with
`python scripts/print_banned_cell_names.py`
(The utility is a marimo notebook!)
> Add utility for printing banned cell names

- marimo/_messaging/ops.py
Tell users how to increase the max output size via an environment variable.
> Document env var workaround for output size

- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/core/mode.ts
Fix async/await  to properly wait for the 2 frames before screenshotting. Also added 100ms which is arbitrary, but gives enough time for the browser to load (cached) files.
In future, we can design something more robust with timers and mutation observers.
> fix: wait for content to render before screenshot

- frontend/src/plugins/impl/vega/__tests__/vega.test.ts
- frontend/src/plugins/impl/vega/loader.ts
Fixes https://github.com/marimo-team/marimo/issues/507
Make each csv column name unique before converting to JS objects, by appending zero-width-spaces
Other options:
* larger refactor of passing around objects in a columnar format
* change each column name to index, and create a mapping table to its key
* append `_1`, `_2` to each
> fix: handle duplicate column names in CSV data

- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/variables/variables-table.tsx
This refactors the variable table to use the tanstack headless-UI table library (we use it for our `mo.ui.table` already). This makes it easy to add sorting and flexible columns. 
This also unlocks virtualization or column resizing if we ever want that.
> improvement: sortable variable table

- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/chrome/footer/feedback-button.tsx
- frontend/src/components/static-html/share-modal.tsx
- frontend/src/components/ui/use-toast.ts
- frontend/src/core/constants.ts
- frontend/src/core/static/__tests__/download-html.test.ts
- frontend/src/core/static/download-html.ts
- frontend/src/utils/events.ts
This adds a notebook dropdown to quickly share the static notebook. This create an anonymous like for users to easily share non-sensitive notebook
To test this locally, run:
```
NODE_ENV=test make fe
marimo tutorial intro
```
> misc: allow uploading notebook as shared page

- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/static-html/share-modal.tsx
Put share static notebook first, and rename it to
"Publish as HTML" for consistency ("Export as HTML", "Export as PNG")
> Reorder notebook actions

- frontend/src/components/editor/Cell.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/__tests__/__snapshots__/setup.test.ts.snap
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/hooks/useHotkey.ts
Adds arrow hotkeys to move between cells. VIM users can still use the arrow keys, but I did not hook up j/k
> improvement: Add ArrowUp/ArrowDown hotkey support for moving between cells

- frontend/src/core/codemirror/format.ts
Order matters here (unfortunately fragile). Basically we were updating the cell editor first which made the cell stale
> fix: don't make cells stale after formatting code

- frontend/src/components/app-config/app-config-button.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/core/MarimoApp.tsx
- frontend/src/core/config/config-schema.ts
- frontend/src/css/Cell.css
- frontend/src/stories/cell.stories.tsx
- frontend/src/theme/ThemeProvider.tsx
- marimo/_config/config.py
Fixes https://github.com/marimo-team/marimo/issues/534
Configurable editor font-size. 
Alternative names:
- `code-font-size`
- `editor-font-size`
> improvement: configurable editor font-size

- marimo/_tutorials/layout.py
The documentation doesn't mention `"alert"` but instead uses `"danger"`.
> Update callout kinds

- docs/apps/output.py
- examples/sine_wave.py
- marimo/_tutorials/dataflow.py
- marimo/_tutorials/markdown.py
I'm getting a lot of syntax warnings when running `marimo tutorial ...`
```
❯ marimo tutorial markdown
<unknown>:18: SyntaxWarning: invalid escape sequence '\p'
<unknown>:18: SyntaxWarning: invalid escape sequence '\p'
<unknown>:18: SyntaxWarning: invalid escape sequence '\p'
<unknown>:18: SyntaxWarning: invalid escape sequence '\p'
<unknown>:16: SyntaxWarning: invalid escape sequence '\p'
<unknown>:16: SyntaxWarning: invalid escape sequence '\p'
<unknown>:16: SyntaxWarning: invalid escape sequence '\p'
<unknown>:16: SyntaxWarning: invalid escape sequence '\p'
<unknown>:14: SyntaxWarning: invalid escape sequence '\['
<unknown>:14: SyntaxWarning: invalid escape sequence '\s'
<unknown>:14: SyntaxWarning: invalid escape sequence '\]'
<unknown>:12: SyntaxWarning: invalid escape sequence '\[' …
```
> Use r-string to ignore escaping

- frontend/src/components/editor/chrome/wrapper/footer.tsx
This change makes the footer bar and the footer buttons more noticeable by:
- adding a slight shadow,
- increasing the size of the icons,
- moving the help icon next to the panel icons (it's not a panel, but it's more visible there and the discongruity is ok)
I also tried experimenting with turning the icons black or blue, and floating them in the left as a sidebar instead of a footer. The sidebar could be a better long-term solution -- right now we don't really have any design elements to bring the user's eyes to the bottom of the screen -- but would require some finessing to get right. Hopefully this PR combined with better docs is sufficient  ... we can wait and see how users respond.
> improvement: make footer more visible

- marimo/_ast/codegen.py
- marimo/_cli/ipynb_to_marimo.py
- marimo/_smoke_tests/code_editor.py
Read JSON with encoding="utf-8" to handle platforms where utf-8 is not the default encoding.
Fixes #540.
> Fix JSON encodings - use utf-8

- frontend/src/components/data-table/pagination.tsx
- frontend/src/plugins/impl/common/error-banner.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
1. clip mo.ui.dataframe preview to 100 row
2. add dropdown for pagination to find specific page
> improvement: clip mo.ui.dataframe preview to 100 rows, add dropdown for pagination to find specific page

- docs/guides/plotting.md
The code for the Altair [plotting example](https://docs.marimo.io/guides/plotting.html) makes a call to `altair.load_datset` to load the `cars` dataset. However, this was [deprecated a few years back](https://github.com/altair-viz/altair/issues/644) and has now been removed in favour of using the [vega-datasets](https://pypi.org/project/vega-datasets/) module.
This PR updates the code example accordingly.
It also reformats the `.mark_point().encode()` calls onto a single line, so that the code can be copied and run into marimo without syntax errors.
Thanks for all of your work on marimo — it's a beautiful project, and I really appreciate all of the care that you have put into the design and developer experience!
> Update plotting example to use vega_datasets module, replacing obsole altair.load_dataset()

- frontend/src/core/hotkeys/__tests__/shortcuts.test.ts
- frontend/src/core/hotkeys/shortcuts.ts
- frontend/src/hooks/useHotkey.ts
When i tried `Alt-Up` and `Alt-Down` - i would end up moving between cells, when i didnt want to
> fix: Add support for recognizing Alt key in shortcuts

- frontend/src/components/ui/input.tsx
- frontend/src/components/ui/textarea.tsx
Change background from transparent to bg-background. Transparent made these inputs difficult to see in some contexts, such as forms and the console area; background helps them stand out.
> improve: mo.ui.text/text_area background

- marimo/_ast/app.py
- tests/_ast/test_app.py
This change fixes a bug with app.run() and cells that conditionally define variables. app.run() shouldn't return defs that don't exist after running.
Fixes #599
> fix: missing defs at runtime in app.run()

- frontend/src/core/codemirror/language/markdown.ts
- frontend/src/css/codemirror.css
Just for fun - emoji auto-complete when in markdown mode via `:`.
I pull emojis from a CDN to avoid the cost when bundling (although could lazy load), which should be a fine tradeoffs since when offline, it is ok to miss this feature. (although happy to bundle/lazy-load)
> feat: emojis autcomplete in markdown

- docs/api/markdown.md
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/core/MarimoApp.tsx
- marimo/__init__.py
- marimo/_output/builder.py
- marimo/_output/utils.py
- marimo/_plugins/stateless/flex.py
- marimo/_plugins/stateless/icon.py
- marimo/_plugins/stateless/test_icon.py
- marimo/_smoke_tests/icons.py
- tests/_output/test_builder.py
This adds `mo.icon` using [iconify](https://iconify.design/). It's an open-source project that contains many different icon sets (each with 100s to 1000s of icons). The icons are lazily loaded and can be styled with size/color/etc. 
These work well inside buttons or markdown
```bash
make fe
marimo edit marimo/_smoke_tests/icons.py
```
> feat: mo.icon

- frontend/src/css/App.css
- frontend/src/css/md.css
- frontend/src/plugins/impl/plotly/plotly.css
This makes it easy to override if you do choose so
> fix: reference fonts by css vars

- marimo/_messaging/streams.py
- marimo/_runtime/redirect_streams.py
- tests/_messaging/test_streams.py
- tests/conftest.py
- These are attributes that exist on sys.stdout and sys.stderr
- This change also refactors stream redirection in order to expose the duped fd to the stream objects (and reduce code duplication)
Fixes #634
> Fix: add encoding, fileno to Stdout/Stderr

- marimo/_ast/compiler.py
- marimo/_ast/visitor.py
- marimo/_runtime/runtime.py
- tests/_runtime/test_runtime.py
Setting the value of a local UI element shouldn't crash the runtime
Fixes #641
> fix: set-ui-element-value on local variable

- docs/guides/editor_features.md
I've seen a couple people ask about Vim settings, and then later realize we already have it. Adding it to the docs so it can be searched at least (currently "vim" in the docs returns nothing)
> docs: type out some settings for searchability

- marimo/_ast/compiler.py
- marimo/_runtime/cell_runner.py
- tests/_ast/test_compiler.py
- tests/_runtime/test_cell_runner.py
This fixes a bug in which tracebacks were missing for exceptions raised in cells.
Fixes #649
> fix: traceback should contain line number, stack trace

- marimo/_messaging/console_output_worker.py
This change fixes a race condition in the console output worker that sometimes caused outputs to not be sent to the frontend.
Fixes #628
> fix: truncation of standard streams

- marimo/_runtime/redirect_streams.py
`stream.cell_id` has to be set as long as streams are redirected
> Fix: stream restoration order

- frontend/e2e-tests/cells.spec.ts
- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/scrollCellIntoView.ts
- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/core/codemirror/extensions.ts
- frontend/src/core/codemirror/keymaps/keymaps.ts
- frontend/src/core/codemirror/keymaps/vim.ts
- frontend/src/core/codemirror/utils.ts
- frontend/src/utils/scroll.ts
This:
* Allows `j`/`k` to focus below/above when at the last line (and also works when the code is hidden)
* This improves `j`/`k` and `Up/Down` to focus on the first or last line, when come from above or below (instead of the previous line)
* add padding to the bottom of the cells when editing to you can scroll the bottom cell to the middle (request in Discord)
* fix the `scrollActiveLineIntoView`. this was probably regressed a while ago when we added the app footer
Fixes https://github.com/marimo-team/marimo/issues/658
> improvement: focus-up/focus-down cells with vim

- marimo/_server/start.py
This change fixes edit mode on Linux/POSIX systems by keeping the TCP socket open indefinitely. Tornado's keep-alive was apparently much higher than uvicorn's 5 seconds. For some reason, closing and re-opening these sockets interacts badly with multiprocessing on linux, causing the server to stop accepting requests.
We can look into sending an connection: close header on unload to make these connections close, but not sure if that would resurface the issue that this change is trying to patch over.
> fix: edit mode on linux

- frontend/src/core/codemirror/cells/extensions.ts
Previously you can accidentally go to the next cell when using arrow-keys inside the auto-complete
> fix: dont move between cells if auto-complete is open

- frontend/src/components/editor/Cell.tsx
- frontend/src/core/codemirror/keymaps/keymaps.ts
This fixes a bug in which j/k movement was always registered on the cell (in addition to codemirror), even when the cell wasn't hidden. This made it impossible to type 'j' and 'k' in the last line of an editor in vim mode.
>  fix: vim jk movement should only be registered on cell when code is hidden

- marimo/_messaging/streams.py
Catch and silence exceptions when watching file descriptors; exceptions raised at this point can cause bad things to happen
> fix: silence exception when watching fd

- marimo/_config/config.py
TypedDict is in typing for all python versions we support.
> import typed dict from typing

- .github/workflows/test.yaml
- pyproject.toml
- tests/_plugins/ui/_impl/dataframes/test_handlers.py
- tests/_plugins/ui/_impl/test_altair_chart.py
- To facilitate CI testing with minimal possible set of dependencies.
- Refactor pandas/altair tests to only run when deps installed
- Updates CI to run tests with and without the optional dependencies, to make sure we don't accidentally require an optional dep.
> Add testcore, testoptional deps to pyproject.toml

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/Output.tsx
- frontend/src/core/config/config-schema.ts
- frontend/src/css/Cell.css
- frontend/src/stories/cell.stories.tsx
- frontend/tailwind.config.js
- marimo/_config/config.py
This lets the user configure where the output of the cell should be. Defaults to `above`
> improvement: add configuration to specifcy where the cell's output should be (above/below)

- marimo/_ast/compiler.py
- tests/_ast/test_compiler.py
- tests/_runtime/test_virtual_file.py
- tests/conftest.py
This change fixes tracebacks, which regressed and stopped showing line numbers when we changed the cell ID format.
This change also modifies the tests to catch bugs like this in the future, by making `ExecutionRequestProvider` use the `CellManager` for creating cell IDs.
> fix: traceback line number

- marimo/_runtime/output/_output.py
- marimo/_runtime/runtime.py
- marimo/_tutorials/intro.py
- tests/_runtime/output/test_output.py
This fixes a bug in which appended outputs were re-formatted each time an output message was set. This was incorrect because the appended objects may be mutated.
> fix: output append should not render lazily

- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- frontend/src/plugins/impl/plotly/mapbox.css
Fixes: https://github.com/marimo-team/marimo/issues/693
I spend a fair amount of time finding a more maintainable way, but plotly generates their styles quite oddly and not in a compossible way. They:
1) generate the styles at runtime, and
2) it to the document.head which doesnt play nicely with shadow DOMs.
The best I could do is copying the styles it generates via in the browser console.
```js
copy(Array.from(document.getElementById("plotly.js-style-global").sheet.cssRules)
.map((rule) => rule.cssText)
.filter((rule) => rule.includes("mapboxgl"))
.join("\n"))
```
> fix: plotly mapbox styles

- marimo/_server/api/endpoints/execution.py
- marimo/_server/api/lifespans.py
- marimo/_server/uvicorn_utils.py
This change fixes shutdown via Ctrl+C and the shutdown route on Windows. The event loop previously endlessly awaited `wait_closed()` in `close_uvicorn`, preventing the server from shutting down.
The server appears to shut down fine without us waiting for its own servers to shut down.
> fix: cross-platform server shutdown

- marimo/_plugins/ui/_core/registry.py
- marimo/_smoke_tests/ansi.py
- marimo/_smoke_tests/third_party/rich.py
- tests/_plugins/ui/_core/test_registry.py
- tests/_runtime/test_runtime.py
When a parent UI element has a child bound to a global, interacting with the parent should trigger reactive execution of cells referring to the child.
> fix: fix how names bound to lensed elements are resolved

- marimo/_messaging/streams.py
- marimo/_runtime/redirect_streams.py
- marimo/_runtime/runtime.py
- tests/_messaging/test_streams.py
This change fixes a bad interaction between standard stream redirection
and multiprocessing, in which the forwarding thread would fail to join.
Instead of creating a new forwarding thread for each cell execution,
this change creates the forwarding threads at runtime start, and keeps
them alive for the duration of the kernel process. Similarly, instead
of creating a pipe for the redirection on each cell execution, this
change just creates the pipes once.
Addresses #684
> fix: fix standard stream direction + multiprocessing 

- marimo/_ast/codegen.py
- marimo/_server/api/endpoints/files.py
- tests/_ast/codegen_data/test_get_header_comments.py
- tests/_ast/codegen_data/test_get_header_comments_invalid.py
- tests/_ast/test_codegen.py
- tests/_server/api/endpoints/test_files.py
This PR allows `marimo` to not overwrite the headers in a notebook while saving. It does so by extracting the header while writing the file, and prepending the header (the portion of the source file until the `import marimo` line) to the new content. 
We often automatically add license headers to all the source files that we develop commercially. Moreover, `mypy` and `ruff` seem to complain over `marimo` notebook. Thus, a common header to solve these issues would be
```
import marimo
...
```
Before this PR, every time I save the notebook it removes these headers and causes unnecessary file changes and a lot of red in the `precommit` checks. 
I took the liberty of giving it a shot and adapting `marimo` to support persisting these headers. Given I am not familiar with the codebase, so …
> Persist comment headers while resaving notebooks

- docs/guides/plotting.md
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/altair_charts.py
Fixes https://github.com/marimo-team/marimo/issues/727
This fixes `mo.ui.altair_chart` plot showing incorrect data with when using `transform_filter` and other `transform_*`. This is because the python side does not apply the `transform_filter` by default and lets the FE (vega) do that. 
But we can force the python side to support this by installing `vegafusion`. This PR adds docs and a clearer warning to install. 
When not installed, we fallback to the dataframe without the filter (but error to the user). We could hard-throw instead of falling back for correctness.
> fix: mo.ui.altair_chart with transform_filter

- marimo/_output/md.py
- marimo/_output/md_extensions/__init__.py
- marimo/_output/md_extensions/external_links.py
- marimo/_smoke_tests/latex.py
- marimo/_smoke_tests/md.py
- tests/_output/test_md.py
Open markdown links in a new tab - you rarely (if ever) want to open in your current tab.
> fix: open markdown links in a new tab

- frontend/index.html
- frontend/playwright.config.ts
- frontend/src/core/network/api.ts
- frontend/src/core/static/__tests__/__snapshots__/download-html.test.ts.snap
- frontend/src/core/static/__tests__/download-html.test.ts
- frontend/src/core/static/download-html.ts
- frontend/vite.config.mts
- marimo/_cli/cli.py
- marimo/_cli/cli_validators.py
- marimo/_runtime/virtual_file.py
- marimo/_server/api/deps.py
- marimo/_server/api/endpoints/assets.py
- marimo/_server/api/endpoints/files.py
- marimo/_server/api/lifespans.py
- marimo/_server/api/middleware.py
- marimo/_server/main.py
- marimo/_server/router.py
- marimo/_server/start.py
- tests/_server/api/test_middleware.py
- tests/_server/conftest.py
This adds support for `--base-url=/foo` when running `marimo run`.
Closes https://github.com/marimo-team/marimo/issues/721
> feat: add support for --base-url from marimo run

- frontend/src/core/static/files.ts
- frontend/src/plugins/impl/vega/VegaPlugin.tsx
- frontend/src/plugins/impl/vega/__tests__/__snapshots__/make-selectable.test.ts.snap
- frontend/src/plugins/impl/vega/__tests__/make-selectable.test.ts
- frontend/src/plugins/impl/vega/fix-relative-url.ts
- frontend/src/plugins/impl/vega/make-selectable.ts
- frontend/src/plugins/impl/vega/params.ts
- frontend/src/utils/__tests__/url.test.ts
- frontend/src/utils/url.ts
- marimo/_smoke_tests/altair_charts.py
We didnt handle `layer` (we did with hstack and vstack). Added this code path and tests.
Also fixed a small bug with url parsing that regressed when adding base-url
> fix: support selection when using 'layer' in altair/vega spec

- frontend/src/components/editor/links/cell-link.tsx
- frontend/src/components/variables/variables-table.tsx
- frontend/src/core/codemirror/find-replace/search-highlight.ts
- frontend/src/css/Cell.css
This improves the go-to variable. There is an edge case where it finds the first occurrence (as in could be in a comment) instead of the first variable occurrence.
> improvement: move cursor to variable when clicked in variable explorer

- marimo/_output/formatters/formatters.py
- tests/_output/formatters/test_formatters.py
This PR fixes a bug in which patched `find_spec` methods for finders in the importlib process were not bound to the instance.
Fixes #763
> fix: patched `find_spec` should be a bound method

- docs/api/inputs/index.md
- docs/api/inputs/tabs.md
- docs/api/layouts/index.md
- docs/apps/output.py
- docs/guides/overview.md
- examples/dashboards/movies.py
- examples/embeddings/drawing_graphs.py
- examples/pokemon_stats/pokemon.py
- examples/table.py
- examples/tabs.py
- frontend/e2e-tests/py/kitchen_sink.py
- frontend/src/components/ui/tabs.tsx
- frontend/src/plugins/impl/TabsPlugin.tsx
- frontend/src/plugins/plugins.ts
- marimo/_plugins/stateless/tabs.py
- marimo/_plugins/ui/__init__.py
- marimo/_plugins/ui/_impl/tabs.py
- marimo/_tutorials/layout.py
- marimo/_tutorials/ui.py
- marimo/_utils/deprecated.py
Add `mo.ui.tabs` so users can track tab state or manually set it (i.e. a "controlled component). This makes tabs a little more ergonomic/powerful.
> feat: mo.ui.tabs, deprecate mo.tabs

- marimo/_output/builder.py
- marimo/_plugins/stateless/mpl/_mpl.py
`__resizeIframe` doesnt work when using `src` due to cors. this switches to using `srcdoc`
> fix: mpl interactive with large plot sizes

- frontend/src/components/editor/code/readonly-python-code.tsx
- frontend/src/components/editor/output/JsonOutput.tsx
- frontend/src/plugins/core/registerReactComponent.tsx
- frontend/src/plugins/impl/CodeEditorPlugin.tsx
- frontend/src/plugins/impl/TabsPlugin.tsx
- frontend/src/plugins/impl/vega/VegaPlugin.tsx
- frontend/src/plugins/layout/mermaid/mermaid.tsx
- frontend/src/theme/useTheme.ts
- marimo/_plugins/ui/_impl/tabs.py
Fixes #779 
The plugin backend will send `""` when not selected, and the frontend will default to the `(last selected || first item)`
Also removes the need for `useThemeForPlugin`
> fix: tab re-render

- marimo/_plugins/ui/_impl/dataframes/handlers.py
Pandas `agg` function missing a typing for arg, leading it to incorrectly think we are returning a `Series`
> fix pandas typecheck

- docs/guides/state.md
- marimo/_runtime/cell_runner.py
- marimo/_runtime/state.py
- tests/_runtime/test_state.py
This PR adds a keyword argument `allow_self_loops` to `mo.state`, which creates state objects that are allowed to re-run the cell that called their setter.
Closes #803
> Add an option to allow self-loops on `mo.state`

- marimo/_runtime/runtime.py
- tests/_runtime/test_runtime.py
Invalidate cell state early on to relieve memory pressure.
Fixes #806 
Verified that CUDA memory is freed on re-run with a test script:
```python
import marimo
__generated_with = "0.2.5"
app = marimo.App()
@app.cell
def __():
import torch
return torch,
@app.cell
def __():
import time
return time,
@app.cell
def __(time, torch):
control = None
torch.cuda.empty_cache()
time.sleep(20)
return control,
@app.cell
def __(control, torch):
control
t = torch.randn((3000000, 500), device='cuda')
t
return t,
if __name__ == "__main__":
app.run()
```
> Invalidate cell state before running queued cells

- marimo/_ast/app.py
- marimo/_runtime/patches.py
- marimo/_runtime/runtime.py
- tests/_ast/test_app.py
- tests/_runtime/test_runtime.py
- tests/_server/conftest.py
- tests/_server/test_sessions.py
- tests/conftest.py
Replace the `__main__` module with a dummy module, and use this dummy module's `__dict__` as our globals, to fix an issue with pickling (only functions defined at module scope can be pickled).
I ran into this issue when testing top-level await. Another one of our users also found this issue and mentioned it in a blog post.
> fix: pickle-ability of functions/classes

- frontend/public/files/wasm-intro.py
- frontend/src/core/pyodide/worker/bootstrap.ts
- marimo/_ast/app.py
- marimo/_ast/cell.py
- marimo/_ast/codegen.py
- marimo/_ast/compiler.py
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/cell_runner.py
- marimo/_runtime/runtime.py
- pyproject.toml
- tests/_ast/codegen_data/test_generate_filecontents_async.py
- tests/_ast/test_app.py
- tests/_ast/test_app_cell.py
- tests/_ast/test_codegen.py
- tests/_messaging/test_streams.py
- tests/_plugins/stateless/test_image.py
- tests/_plugins/ui/_core/test_registry.py
- tests/_plugins/ui/_impl/test_altair_chart.py
- tests/_runtime/output/test_output.py
- tests/_runtime/test_capture.py
- tests/_runtime/test_cell_runner.py
- tests/_runtime/test_control_flow.py
- tests/_runtime/test_marimo_pdb.py
- tests/_runtime/test_runtime.py
- tests/_runtime/test_state.py
- tests/_runtime/test_virtual_file.py
This change makes it possible to use top-level `await` in marimo cells.
**Motivation.**
The main motivation for this change is to enable users to reliably install packages when running WebAssembly notebooks: the `micropip.install()` function is asynchronous, and must be awaited. Unfortunately, when running under `pyodide`, one cannot simply use `asyncio.run()` or any other similar method to block on completions of coroutines ([see Pyodide docs](https://pyodide.org/en/stable/usage/api/python-api/webloop.html#pyodide.webloop.WebLoop)). In contrast, `await`-ing the coroutine does the right thing.
With this change, users can write code like:
```python
import micropip
await micropip.install("plotly")
import plotly
```
As an alternative, I explored enabling WebAssembly stack-switching and using …
> feat: top-level await

- .github/renovate.json
- frontend/e2e-tests/cells.spec.ts
- frontend/e2e-tests/helper.ts
- frontend/e2e-tests/kitchen-sink.spec.ts
- frontend/src/components/editor/CommandPalette.tsx
- frontend/src/components/editor/actions/types.ts
- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/chrome/types.ts
- frontend/src/components/editor/chrome/wrapper/footer.tsx
- frontend/src/components/editor/notebook-menu-dropdown.tsx
- frontend/src/components/ui/context-menu.tsx
- frontend/src/components/ui/dropdown-menu.tsx
- frontend/src/components/ui/menu-items.tsx
- frontend/src/core/pyodide/bridge.ts
- frontend/src/core/static/download-html.ts
- frontend/src/utils/download.ts
This improves the "framework" side of the notebook actions as well as adds new ones or cleans up existing ones. 
* Adds nesting to actions
* Adds Helper panel actions
* Consolidate "Download" and "Share"
> improvement: improve download menu nesting and add more actions

- frontend/src/components/editor/renderers/layout-select.tsx
- frontend/src/core/config/config-schema.ts
- frontend/src/core/config/feature-flag.ts
This GAs the Grid Layout which was behind an experimental flag
> feat: bring Grid Layout out of experimental

- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- frontend/src/core/pyodide/utils.ts
This is a case where you may want to share a static notebook or wasm-notebook without including the code. You can pass `include-code=false`
> improvement: Add include-code=false query param for static notebooks to hide the code

- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/cell/cell-actions.tsx
- frontend/src/components/editor/controls/Controls.tsx
- frontend/src/components/editor/controls/command-palette-button.tsx
- frontend/src/components/editor/controls/command-palette.tsx
- frontend/src/components/editor/controls/keyboard-shortcuts.tsx
- frontend/src/components/editor/controls/notebook-menu-dropdown.tsx
- frontend/src/components/editor/controls/shutdown-button.tsx
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout-wrapper.tsx
- frontend/src/components/indicator.tsx
- frontend/src/core/App.tsx
- frontend/src/core/MarimoApp.tsx
- frontend/src/core/codemirror/cm.ts
- frontend/src/css/Header.css
- frontend/src/css/common.css
- frontend/tailwind.config.js
- Change the bottom action from KeyboardShortcut to CommandPalette
- Add responsive indicator when in dev-mode
- Fix a bug in renaming cells (the input was disabled)
- Disable "show actions on hover" for touch devices
- Fix z-index issue with hover/completion tooltips
- make keyboard shortcuts mobile friendly
Misc:
- Move some files to a new folder, rename for consistency
> fix: change KeyboardShortcut control to CommandPalette, amd some mobile fixes

- README.md
- docs/guides/deploying/deploying_marimo_cloud.md
- docs/guides/deploying/deploying_public_gallery.md
- docs/guides/deploying/index.md
- docs/guides/index.md
- docs/guides/wasm.md
- frontend/public/files/wasm-intro.py
Add a guide on using "WASM notebooks".
The guide explains what WASM notebooks are, how to create and share them, how to embed them on web pages, when they are useful, and what their limitations are today.
We can separately work through terminology. Many (most?) of our users won't know what WASM is. But I wanted to get this guide up in the meantime.
> Add a guide on how to run marimo in the browser using Pyodide and WebAssembly

- frontend/src/components/ui/slider.tsx
- frontend/src/plugins/impl/SliderPlugin.tsx
- frontend/src/plugins/plugins.ts
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/inputs.py
Adds 2 new args to slider for orientation and showing the value (at rest)
Closes #836 
```diff
mo.ui.slider(
+       orientation: Literal["horizontal", "vertical"] = "horizontal",
+       show_value: bool = False,
)
```
> feat: vertical slider

- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/controls/command-palette.tsx
- frontend/src/components/editor/controls/keyboard-shortcuts.tsx
- frontend/src/components/shortcuts/renderShortcut.tsx
- frontend/src/components/ui/kbd.tsx
- frontend/src/components/ui/tooltip.tsx
- frontend/src/core/codemirror/copilot/client.ts
- frontend/src/core/codemirror/copilot/language-server.ts
- frontend/src/core/codemirror/copilot/types.ts
- frontend/src/hooks/useElapsedTime.ts
- frontend/tailwind.config.js
Use more symbols where possible. And add tooltip over the symbols
> improvement: improved shortcut symbols

- frontend/src/components/editor/code/readonly-python-code.tsx
- frontend/src/components/editor/output/ConsoleOutput.tsx
- frontend/src/core/cells/__tests__/collapseConsoleOutputs.test.ts
- frontend/src/core/cells/collapseConsoleOutputs.tsx
- frontend/src/css/Cell.css
Closes https://github.com/marimo-team/marimo/issues/826
```
// Keep scroll at the bottom if it is within 120px of the bottom,
// so when we add new content, it will lock to the bottom
// This won't handle large jumps in the scroll position
// if there is a lot of content added at once.
```
> improvement: Add scroll lock to bottom of console output

- docs/api/cell.md
- docs/api/index.md
- marimo/__init__.py
- marimo/_ast/app.py
- marimo/_ast/cell.py
- marimo/_ast/codegen.py
- marimo/_ast/compiler.py
- marimo/_output/formatters/cell.py
- marimo/_output/formatters/formatters.py
- marimo/_output/md_extensions/external_links.py
- marimo/_plugins/ui/_core/registry.py
- marimo/_plugins/ui/_impl/dataframes/handlers.py
- marimo/_runtime/dataflow.py
- marimo/_server/models/base.py
- marimo/_smoke_tests/import_named_cells.py
- marimo/_smoke_tests/named_cells.py
- pyproject.toml
- tests/_ast/cell_data/named_cells.py
- tests/_ast/test_app_cell.py
- tests/_ast/test_cell.py
- tests/_ast/test_compiler.py
- tests/_plugins/ui/_impl/test_altair_chart.py
- tests/_runtime/runtime_data/cell_ui_element.py
- tests/_runtime/test_runtime.py
This PR makes it possible to import named cells from one notebook into another, and to run the imported cells programmatically to obtain their output and definitions.
For example:
```python
from my_notebook import my_cell
refs: dict[str, Any] | None = { ... }
output, defs = my_cell.run(**refs)
```
This helps make notebooks more testable: you can import named cells in a `pytest` module, run it, and check their outputs or defs. It also also helps with code re-use, making it possible to re-use cells across notebooks, especially if the cells are written in a functional way.
The main changes are in `cell.py`: we've introduced a new public `Cell` class. Calling its `run()` method executes the cell's ancestors, and then the cell itself, returning a tuple of its output and a `Mapping` of def …
> feat: import and run named cells

- frontend/src/components/editor/renderers/grid-layout/grid-layout.tsx
- frontend/src/components/editor/renderers/layout-select.tsx
- frontend/src/core/App.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/layout/layout.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
Fix: 
1) Fix scrolling in grid when bordered=true
2) Fix auto-save indicator when layout has changed
3) Hide layouts in pyodide (we don't support it when shared)
> fix: show stale save after layout edit, add scroll to bordered grid

- frontend/src/components/editor/chrome/panels/file-explorer-panel.tsx
- frontend/src/components/editor/file-tree/__tests__/requesting-tree.test.ts
- frontend/src/components/editor/file-tree/file-explorer.tsx
- frontend/src/components/editor/file-tree/file-viewer.tsx
- frontend/src/components/editor/file-tree/requesting-tree.tsx
- frontend/src/core/network/requests.ts
- frontend/src/core/network/static-requests.ts
- frontend/src/core/network/types.ts
- frontend/src/core/pyodide/bridge.ts
- frontend/src/core/pyodide/worker/types.ts
- frontend/src/core/pyodide/worker/worker.ts
- frontend/src/css/Cell.css
- frontend/src/plugins/impl/CodeEditorPlugin.tsx
- frontend/src/plugins/impl/code/LazyAnyLanguageCodeMirror.tsx
- frontend/src/utils/__tests__/path.test.ts
- frontend/src/utils/functions.ts
- frontend/src/utils/paths.ts
- marimo/_pyodide/pyodide_session.py
- marimo/_server/api/endpoints/file_explorer.py
- marimo/_server/files/file_system.py
- marimo/_server/files/os_file_system.py
- marimo/_server/models/files.py
- tests/_plugins/ui/_impl/test_altair_chart.py
- tests/_server/files/test_os_file_system.py
This adds a few new features to the file explorer:
1) You can now view the contents of a file by clicking it. Currently doesn't handle edge cases like large files or octet files. I can handle this in a follow-up as well as pretty render `csv`.
2) You can rename a file
3) You can drag-n-drop to move to a folder
4) This all works in WASM too
> improvement: rename files, file viewer, move files

- frontend/src/core/pyodide/worker/bootstrap.ts
- marimo/_runtime/virtual_file.py
This change removes the multiprocessing mock in order to extend compatibility to packages that import multiprocessing but don't use offending features. In particular, with this fix it is now possible to import `sklearn` in WASM notebooks.
Of the modules that were previously mocked, the only one that actually fails to be imported under pyodide is `shared_memory`. Instead of mocking this module, this PR updates our runtime code to just not import this module when running under Pyodide.
> fix: remove multiprocessing mock for WASM

- frontend/src/components/editor/actions/useNotebookActions.tsx
We now wait 2 seconds before downloading. In future we can make this more robust and checking for loading indicators, but this is a sufficient quick fix now.
Closes https://github.com/marimo-team/marimo/issues/861
> fix: wait to render before downloading png

- frontend/src/components/editor/file-tree/file-explorer.tsx
- marimo/_server/file_manager.py
- marimo/_server/sessions.py
We had multiple sources of truth for `filename` and `path`, and renaming the filename got `SessionManager` out of state. this makes `path` a computer property based on `filename`
> fix: opening notebooks from the UI

- frontend/src/core/pyodide/worker/bootstrap.ts
- frontend/src/core/pyodide/worker/message-buffer.ts
- frontend/src/core/pyodide/worker/types.ts
- frontend/src/core/pyodide/worker/worker.ts
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_pyodide/pyodide_session.py
- marimo/_pyodide/streams.py
Pass down a message callback to flush sync instead of using async-iterators + queue to handle a message. This is actually a simpler implementation, but provides the benefit that std out and stream outputs appear right away instead of at the end of the cell's code.
> improvement: flush sync in wasm instead of async

- frontend/src/plugins/impl/SliderPlugin.tsx
Fix styling to make vertical slider inline with content (like with horizontal)
Closes https://github.com/marimo-team/marimo/issues/871
> fix: inline slider

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/stories/cell.stories.tsx
If you delete a cell and bring it back, we hydrate it with its old `serializedEditorState`. But if the cell unmount/remounts, we re-do that even if the cell's code changed. This clears the `serializedEditorState` after consuming it.
> fix: clear serializedEditorState after used

- marimo/_output/formatters/altair_formatters.py
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/bugs/877.py
Fixes #877
This allows you to still use the transformers even without `mo.ui.altair_chart`
> fix: register_transformers when altair is imported

- frontend/src/plugins/impl/vega/loader.ts
- marimo/_smoke_tests/bugs/881.py
Fixes an edge case in which numbers like `2.0` were being parsed as BigInts in `ui.table`, and then failing
Fixes #881
> fix: don't parse floats as BigInts

- frontend/src/plugins/impl/vega/VegaPlugin.tsx
- frontend/src/plugins/impl/vega/__tests__/resolve-data.test.ts
- frontend/src/plugins/impl/vega/loader.ts
- frontend/src/plugins/impl/vega/resolve-data.ts
- frontend/src/plugins/impl/vega/types.ts
- marimo/_output/formatters/altair_formatters.py
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
We have some logic to load/resolve URL-based data ahead of time so when passed to altair, it can render without unmounting (to avoid a flicker). This PR adds support to do this for layered charts and `hconcat` and `vconcat`.
This also updates a bit of logic when we use our custom `"marimo"` `data_transformer` (I didn't realize it support `with `)
> fix: altair blinking on layered charts

- frontend/src/core/pyodide/worker/bootstrap.ts
- frontend/src/core/pyodide/worker/worker.ts
This makes code formatting work in WASM notebooks
> pyodide: lazily install black on first format

- frontend/src/components/app-config/app-config-form.tsx
- frontend/src/components/app-config/user-config-form.tsx
This makes the config forms more legible
> remove margin left from controls in user/app config forms

- marimo/_runtime/patches.py
- marimo/_runtime/runtime.py
- marimo/_runtime/virtual_file.py
- marimo/_smoke_tests/bugs/852.py
- marimo/_smoke_tests/bugs/877.py
- marimo/_smoke_tests/bugs/881.py
- marimo/_utils/debounce.py
- marimo/_utils/platform.py
- tests/_messaging/test_streams.py
- tests/_runtime/test_patches.py
This change makes a mocked micropip available when not running under Pyodide. The mocked micropip's functions are noops (they just print warnings to the user that micropip is unavailable when not running under WASM). Still, this is better than outright failing, and is a step toward compatibility with Pyodide and CPython notebooks.
> improvement: mock micropip when not running under pyodide

- .github/workflows/test.yaml
- frontend/src/plugins/layout/CarouselPlugin.tsx
When touch-to-swipe was active, trying to scrub a slider ended up changing the slide instead
> Disable touch in carousel for UI element compatibility

- frontend/src/components/editor/cell/code/ai-completion-editor.tsx
Webkit has a weird bug that some hidden text is being shown again on hover. this just adds another layer of overflow prevention
> fix: safari overflow on hover

- marimo/_dependencies/dependencies.py
- marimo/_output/builder.py
- marimo/_output/formatters/formatter_factory.py
- marimo/_output/formatters/formatters.py
- marimo/_output/formatters/ipython_formatters.py
- marimo/_plugins/ui/_impl/dataframes/handlers.py
- marimo/_smoke_tests/third_party/ipython_display.py
- pyproject.toml
- tests/_output/formatters/test_formatters.py
- tests/conftest.py
This improves compatibility with code written for IPython.
Additionally, this adds a formatter for `IPython.display.HTML` -- we already some `display.HTML` objects by special casing `_repr_html_`, but this adds support for URLs. However, iframe'd URLs are not resizing; left a TODO.
Smoke test:
> improvement: patch `IPython.display.display` to call `mo.output.append`

- frontend/src/plugins/layout/CarouselPlugin.tsx
- only use keyboard nav in fullscreen 
- prevent keypresses while inside components (e.g. `mo.ui.code_editor`) from moving the carousel
Fixes #923
> fix: fix keyboard controls with carousel

- frontend/e2e-tests/components.spec.ts
- frontend/src/components/ui/slider.tsx
- frontend/src/core/dom/UIElement.ts
- frontend/src/core/dom/ui-element.css
Add UI element CSS to marimo web components. these are used for logic and not styling. but in their current form, they are all display:block which can prevent the underlying component from rendering the way it wants
> fix: content layouting of elements in <marimo-ui/>

- frontend/src/plugins/impl/vega/__tests__/__snapshots__/make-selectable.test.ts.snap
- frontend/src/plugins/impl/vega/__tests__/make-selectable.test.ts
- frontend/src/plugins/impl/vega/make-selectable.ts
- frontend/src/plugins/impl/vega/params.ts
- marimo/_smoke_tests/bugs/altair-bug.py
This fixes a bug, but also uncovers another bug that is not fixed.
This fixes rendering layered charts with multiple selection. If there are multiple layers with multiple point selections, we would give the params the same name which would cause errors. We now dedupe them
This also uncovers that we don't support selection in `timeUnit` aggregations. so doing `month(date)` makes it hard for us to back into filter the date by a month. This is because `month(date)` is an binning function that altair performs on the frontend. but the backend does the filtering and does not have this transformation.
> fix: render altair layered charts (dedupe selection params)

- CONTRIBUTING.md
- docs/getting_started/index.md
- frontend/public/files/wasm-intro.py
- frontend/src/components/editor/boundary/ErrorBoundary.tsx
- frontend/src/core/MarimoApp.tsx
- frontend/src/core/pyodide/bridge.ts
- frontend/src/core/pyodide/worker/types.ts
- frontend/src/core/pyodide/worker/worker.ts
- frontend/src/plugins/impl/common/error-banner.tsx
- marimo/_messaging/ops.py
- marimo/_server/sessions.py
- marimo/_tutorials/intro.py
- Fix function calls in wasm (like from `mo.ui.dataframe`)
- add error state to pyodide bootstrap when bootstrap fails
> fix: function calls in wasm, add error state to pyodide bootstrap

- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/cell_runner.py
- marimo/_runtime/marimo_pdb.py
- marimo/_runtime/runtime.py
- tests/conftest.py
Only patch Pdb in edit mode; in run mode, in addition to pdb not being useful, patching it is problematic since multiple threads share the same Python process.
This might fix #930 ...
> fix: disable pdb patch in marimo run

- .github/workflows/dev-release.yml
This adds a workflow that creates a dev release on every push to main. The release is uploaded to test.pypi.org.
The uploaded version has the form `X.Y.dev<n-commits-since-last-tag>+g<short-sha>`.
I believe the latest dev release should then be available via `pip` with
`pip install --index-url https://test.pypi.org/simple/ --pre marimo`
This release doesn't publish new frontend packages; I'm not sure how we want to handle that.
> dev release workflow for marimo python

- .github/workflows/dev-release.yml
Upload npm assets as well on the dev release workflow. Also change the schema to be `X.Y.<Z+1>-dev{n-commits-since-last-tag}` since this valid semver.
Also `0.3.3-dev5 < 0.3.2` so "latest" will resolve properly
> chore: add frontend dev release

- frontend/src/components/editor/file-tree/upload.tsx
- frontend/src/core/network/types.ts
- marimo/_pyodide/pyodide_session.py
- marimo/_server/api/endpoints/file_explorer.py
- marimo/_server/files/file_system.py
- marimo/_server/files/os_file_system.py
- marimo/_server/models/files.py
- marimo/_smoke_tests/bugs/924.py
- marimo/_smoke_tests/bugs/altair-bug.py
- tests/_server/files/test_os_file_system.py
This PR fixes the editor's file upload to send raw bytes to the kernel. Previously, we assumed that files were encoded as `UTF-8`, which is not always the case.
File contents are now base64-encoded in the frontend and decoded in the backend. This adds some overhead that we can optimize away in the future should we need to.
This bug was surfaced by #938, but it isn't specific to WASM.
Fixes #938
> fix: file upload should serialize raw bytes

- marimo/_dependencies/dependencies.py
- marimo/_plugins/stateless/image.py
- pyproject.toml
- scripts/pycheck.sh
- scripts/pycopyright.sh
- tests/_plugins/stateless/test_image.py
Closes out https://github.com/marimo-team/marimo/issues/629
Note that this plots the exact size, but it might be OK to sanity-check datasets or something.
I think this is a fair tradeoff though since you really should be using matplotlib if you want more control
> mo.image(): visualize NumPy array, torch.tensor, scipy.sparse matrix

- frontend/src/components/app-config/common.tsx
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/package-alert.tsx
- frontend/src/core/config/__tests__/config-schema.test.ts
- frontend/src/core/config/config-schema.ts
- frontend/src/core/network/types.ts
- frontend/src/stories/cell.stories.tsx
- lsp/pnpm-lock.yaml
- marimo/_config/config.py
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/packages/package_manager.py
- marimo/_runtime/packages/package_managers.py
- marimo/_runtime/packages/pypi_package_manager.py
- marimo/_runtime/runtime.py
- marimo/_server/sessions.py
- marimo/_server/start.py
- tests/_config/test_config.py
- tests/_runtime/packages/test_package_managers.py
- tests/_server/mocks.py
- tests/_server/test_session_manager.py
- tests/_server/test_sessions.py
This PR adds a key `package_management` to our marimo.toml-based user config, and an option to select the package manager.
It also adds support for `rye` and `uv`.
> feat: configurable package manager + uv, rye support

- marimo/_ast/app.py
- marimo/_output/hypertext.py
- marimo/_utils/exiting.py
- don't import methods in destructors -- can lead to confusing errors when python is shutting down (fixes the issue one of our users was seeing at SLAC)
- register formatters in `app.run()` (helpful for generating HTML programmatically)
> improvements for running as a script

- marimo/_plugins/stateless/mpl/_mpl.py
We were previously waiting with `asyncio.sleep`, but marimo runs in an event loop now so we can't do that.
Closes #978
> Fix mpl interactive: remove asyncio.run()

- frontend/src/components/editor/actions/name-cell-input.tsx
- frontend/src/components/editor/actions/types.ts
- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/components/editor/cell/cell-actions.tsx
- frontend/src/components/editor/cell/cell-context-menu.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/cell/useRunCells.ts
- frontend/src/components/editor/controls/command-palette.tsx
- frontend/src/components/ui/use-restore-focus.ts
- frontend/src/core/cells/focus.ts
- frontend/src/core/vscode/vscode-bindings.ts
This adds cell actions in the command palette by keeping track of the last focused cell. \
Fixes #976
> feat: cell actions in the command-pallete

- frontend/src/components/app-config/user-config-form.tsx
I just noticed this when reexamining the screenshot associated with another issue I filed.
> Deduplicate code completion form description field

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/plugins/impl/MultiselectPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
- tests/_plugins/ui/_impl/test_input.py
This PR adds an optional parameter to `mo.ui.multiselect` to limit the maximum number of selections that can be made (see Issue #920).
- Add `max_selections` parameter to `mo.ui.multiselect`
- Validate user input before passing to component
- Ignore `setValue` for `MultiselectPlugin` if `len(newValues) > maxSelections`
- Write unit tests
> feat: Limit maximum selections in mo.ui.multiselect

- marimo/_utils/health.py
- tests/_cli/test_envinfo.py
This PR uses `importlib.metadata` to get package versions for marimo env. This fixes a bug in which packages that were not imported before running marimo env had missing package versions.
importlib.metadata looks at Python's site-packages, so does not require any specific package manager to be installed.
> fix: package versions in envinfo

- frontend/src/components/editor/file-tree/file-viewer.tsx
- frontend/src/core/network/requests-network.ts
- frontend/src/core/network/requests-static.ts
- frontend/src/core/network/requests-toasting.ts
- frontend/src/core/network/requests.ts
- frontend/src/core/network/types.ts
- frontend/src/core/pyodide/bridge.ts
- frontend/src/core/pyodide/worker/types.ts
- frontend/src/core/pyodide/worker/worker.ts
- frontend/src/css/Cell.css
- frontend/src/css/codemirror.css
- frontend/src/hooks/useAsyncData.ts
- frontend/src/utils/json/base64.ts
- marimo/_pyodide/pyodide_session.py
- marimo/_server/api/endpoints/file_explorer.py
- marimo/_server/files/file_system.py
- marimo/_server/files/os_file_system.py
- marimo/_server/models/files.py
- tests/_server/api/endpoints/test_file_explorer.py
- tests/_server/files/test_os_file_system.py
This PR:
* adds a new endpoint to update file contents 
* renames an existing `update` endpoint, to `move`
* supports saving, downloading, copying from the file-viewer
* adds a basic media view for image, audio, video, 
* fixes a dark-mode bug with the editor
> feat: support media in file viewer, allow editing files

- frontend/src/components/editor/file-tree/file-explorer.tsx
- frontend/src/components/editor/file-tree/requesting-tree.tsx
- frontend/src/css/globals.css
Allow deleting files/folders from the explorer. We confirm this before actually doing it
> feat: allow deleting file from the file explorer

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/components/editor/cell/cell-context-menu.tsx
- frontend/src/core/cells/focus.ts
Cell actions only had a snapshot of the ref's current value, which is `null` when the component  is first created.
@riyavsinha this should fix the last issue you noted in #1021
> fix: stale editor view in cell action buttons

- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/core/codemirror/extensions.ts
- frontend/src/core/codemirror/format.ts
- frontend/src/core/hotkeys/hotkeys.ts
Features demonstrated in video:
- markdown toggle in cell menu
- markdown toggle doesnt show in cell menu when non-markdown-convertible code
- markdown shortcut works (mod-shift-m)
However, it seems that when a cell is created, the `editorView` is null until _something_ is typed. For this reason, I only know how to get this working after typing some whitespace character first, not sure how to actually initialize the EditorView.
Fixes #1003 
https://github.com/marimo-team/marimo/assets/33243383/4dca535f-7611-4594-9613-136213a2bfd7
> feat: enable toggling to md mode automatically via mod-shift-m

- frontend/src/hooks/useHotkey.ts
- Still register the shortcut, just not the action
- Fixes a bug in which NOOP-d cell.format, cell.hideCode was showing up in the command palette, but clicking it did nothing. (Cell > Format, Cell > Hide Code still shows up and works)
> fix: command palette shouldn't show NOOP-ed hotkeys

- docs/api/index.md
- docs/api/query_params.md
- docs/guides/apps.md
- frontend/src/core/kernel/messages.ts
- frontend/src/core/pyodide/bridge.ts
- frontend/src/core/pyodide/worker/bootstrap.ts
- frontend/src/core/pyodide/worker/types.ts
- frontend/src/core/pyodide/worker/worker.ts
- frontend/src/core/websocket/createWsUrl.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
- marimo/__init__.py
- marimo/_messaging/ops.py
- marimo/_messaging/types.py
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/packages/module_registry.py
- marimo/_runtime/query_params.py
- marimo/_runtime/requests.py
- marimo/_runtime/runtime.py
- marimo/_server/api/endpoints/ws.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/query_params.py
- tests/_runtime/test_query_params.py
- tests/_server/api/endpoints/test_ws.py
- tests/_server/test_session_manager.py
- tests/_server/test_sessions.py
- tests/conftest.py
This adds the ability pass query_params to python and keep it in sync with the URL state.
```python
@app.cell
def __(mo):
query_params = mo.query_params()
return query_params,
@app.cell
def __(mo, query_params, random):
print(random.randint(1, 50))
search = mo.ui.text(
value=query_params["search"] or "",
on_change=lambda v: query_params.set("search", v),
)
search
return search,
@app.cell
def __(mo):
toggle = mo.ui.switch(label="Toggle me")
toggle
return toggle,
@app.cell
def __(query_params, toggle):
query_params["has_run"] = toggle.value
return
@app.cell
def __(mo):
new_value = mo.ui.text(label="Text to add")
return new_value,
@app.cell
def __(mo, new_value, query_params):
append_button = mo.ui.button(
label="Add to query param",
on_click=lambda _: query_params.append("list", …
```
> feat: mo.query_params

- marimo/_server/files/os_file_system.py
When there is a bad symbolic link in a directory, [this line](https://github.com/marimo-team/marimo/blob/413bc9dbb20aa7be86b6cf661606134583ae5e6b/marimo/_server/files/os_file_system.py#L46) will lead to an "Internal Server Error". ("Bad" can either be a recursive link (ln -s broken) or a link pointing to a non-existing file (ln -s broken notthere).)
> avoid server error when encountering broken symlinks

- frontend/src/core/websocket/useWebSocket.tsx
- frontend/src/hooks/useAsyncData.ts
The `useAsyncData` would not start in the load state, which would cause an additional re-render while in pyodide mounting/unmounting the application and missing some initialization code.
This also fixes the autosave since that was not initialized with the correct data.
> fix: pyodide additional remounting

- marimo/_server/files/os_file_system.py
- tests/_server/files/test_os_file_system.py
* dont allow renaming to `.` or `..`,
* show dotfiles, like `.env`, but hide `.DS_STORE`
Fixes one of the issues from #1031
> fix: dont allow renaming to '.' or '..', show dotfiles

- frontend/src/core/App.tsx
- frontend/src/core/cells/cells.ts
> improvement: click hourglass to move view to current cell

- docs/guides/ai_completion.md
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/core/config/__tests__/config-schema.test.ts
- frontend/src/core/config/config-schema.ts
- frontend/src/core/config/feature-flag.ts
- frontend/src/stories/cell.stories.tsx
- marimo/_config/config.py
- marimo/_config/manager.py
- marimo/_config/utils.py
- marimo/_server/api/endpoints/ai.py
- pyproject.toml
- tests/_config/test_config.py
- tests/_config/test_manager.py
- tests/_server/api/endpoints/test_ai.py
- tests/_server/conftest.py
This adds an optional config setting for `ai -> open_ai -> model/base_url/api_key`. The api key is not configured in the UI. There is also some additional logic for masking the config and then being able to update the config that has been masked.
> feat: model/base-url settings for AI completion, bring out of experimental

- marimo/_runtime/packages/module_registry.py
- marimo/_runtime/runtime.py
- marimo/_smoke_tests/bugs/1055.py
Some modules, like `manim_slides`, mess with Python's import system and don't have a `__spec__` attr after being imported. This was causing marimo to crash.
Fixes #1055
> fix: guard against modules that don't have a `__spec__` attr

- frontend/src/core/websocket/useMarimoWebSocket.tsx
When resuming a session and auto-instantiate is false, restore history of which cells have been executed and which are stale.
Fixes #1050
> fix: resuming when auto-instantiate is false

- marimo/_server/asgi.py
- marimo/_smoke_tests/bugs/1064.py
- tests/_server/test_asgi.py
Before if you had a root app and nested app, order mattered. This fixes it an lazily mounts the applications after ordering them.
> fix: sort routes in create_asgi_app

- frontend/src/plugins/impl/FileUploadPlugin.tsx
With this change, looks like
Previously
> Better styling of file upload area

- marimo/_runtime/packages/conda_package_manager.py
- marimo/_runtime/packages/module_name_to_conda_name.py
- marimo/_runtime/packages/module_name_to_pypi_name.py
- marimo/_runtime/packages/package_manager.py
- marimo/_runtime/packages/package_managers.py
- marimo/_runtime/packages/pypi_package_manager.py
- map it to opencv-python for pip and opencv for conda
- split package manager base class for pypi/conda
Fixes #1071
> fix: add mapping for cv2 module

- frontend/src/components/editor/output/ConsoleOutput.tsx
Issue was an indexing error (due to reversing outputs). Also fixes an issue with `input()`
Closes #1051
> Fix: close pdb inputs after resolved

- frontend/src/core/pyodide/bridge.ts
- marimo/_pyodide/pyodide_session.py
- discard stale code completion requests
- don't send code completion requests while the pyodide kernel is running
> performance: pyodide code completion

- marimo/_output/data/data.py
- marimo/_plugins/stateless/audio.py
Use virtual files in `mo.audio()` to make it possible to include large audio files. Gets around marimo's limitation on the amount of data the kernel can pass to the server.
Additionally, make it possible to use a path to local file in `mo.audio()`.
> improvement: large audio files

- docs/faq.md
- frontend/e2e-tests/disabled.spec.ts
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/core/config/__tests__/config-schema.test.ts
- frontend/src/core/config/config-schema.ts
- frontend/src/core/pyodide/bridge.ts
- frontend/src/core/pyodide/worker/bootstrap.ts
- frontend/src/core/pyodide/worker/types.ts
- frontend/src/core/pyodide/worker/worker.ts
- frontend/src/stories/cell.stories.tsx
- marimo/_config/config.py
- marimo/_output/formatters/ipython_formatters.py
- marimo/_plugins/ui/_impl/from_anywidget.py
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/autoreload.py
- marimo/_runtime/requests.py
- marimo/_runtime/runtime.py
- marimo/_server/api/endpoints/config.py
- marimo/_server/asgi.py
- marimo/_server/sessions.py
- marimo/_server/start.py
- tests/_runtime/test_autoreload.py
- tests/_server/mocks.py
- tests/_server/test_session_manager.py
- tests/_server/test_sessions.py
- tests/conftest.py
This PR implements autoreloading of Python modules (including hot-reloading of objects). The implementation is based on IPython's autoreload extension, and in particular follows the popular `%autoreload 2` settings.
Autoreloading is not reactive, i.e., marimo does NOT watch files and automatically re-execute affected cells. Instead, when autoreloading is enabled, marimo hot-reloads modules before executing the cell.
In the future, if there's interest, we can support reactive autoreloading.
Closes #998 , #292
> feat: autoreload

- marimo/_server/api/endpoints/documentation.py
- marimo/_snippets/snippets.py
- tests/_server/api/endpoints/test_documentation.py
`@lru_cache` doesn't play well with async functions (the first call to the doc endpoint would succeed, all future ones would fail)
> fix: snippet endpoint

- marimo/_runtime/query_params.py
- tests/_runtime/test_query_params.py
We should remove queryparams when we set to `None` or `[]`
> fix: Fix handling of None and empty values in QueryParams class

- marimo/_pyodide/pyodide_session.py
- marimo/_server/api/endpoints/editing.py
- marimo/_utils/formatter.py
We still prefer `black` formatting, but if they have `ruff` we fallback to that before showing the warning. 
Perf for each subprocess seems ok, but because we launch a new subprocess for each, I'd still prefer to use `black`
Fixes https://github.com/marimo-team/marimo/issues/546 , as long as the user removes `black`
> feat: format with ruff if provided, black is not

- tests/_utils/test_parse_dataclass.py
Fixes the error mentioned in the title, cf. [the comment under this answer](https://stackoverflow.com/a/57560632/143931).
(Note: seems to be correct in all other tests.)
> fixed "AssertionError: .value can only be used after the context manager exits

- marimo/_dependencies/dependencies.py
- marimo/_output/formatters/structures.py
- tests/_output/formatters/test_structures.py
This PR improves formatting of the output of `matplotlib.pyplot`'s `plot` function.
Previously, when `plt.plot()` was the last expression of a cell, multiple copies of the same plot would be displayed, one for each line in the plot. This is because `plt.plot()` returns a list of `Lines2D` objects, one for each line in the figure, but each object is attached to the same figure.
This PR special-cases the structures formatter for lists that contain only matplotlib objects on the same figure to show the figure just once.
> improvement: special case list formatter for matplotlib.

- marimo/_runtime/runtime.py
- tests/_runtime/test_runtime.py
Fixes module resolution for notebooks opened in a directory different from where marimo was called.
> fix: add notebook's current directory to path

- frontend/src/core/config/config.ts
- frontend/src/core/kernel/messages.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
- marimo/_ast/app.py
- marimo/_messaging/ops.py
- marimo/_pyodide/pyodide_session.py
- marimo/_server/api/endpoints/ws.py
- tests/_ast/test_app.py
- tests/_server/api/endpoints/test_files.py
- tests/_server/api/endpoints/test_resume_session.py
- tests/_server/api/endpoints/test_ws.py
- tests/_server/mocks.py
There are some cases (wasm) where the server does not have the code, so it cannot send the correct app-config in the index.html (this keeps the old way, but then continues to send it from in the kernel-ready response)
> fix: send app-config in kernel ready response

- marimo/_output/data/data.py
- marimo/_runtime/functions.py
- marimo/_runtime/virtual_file.py
- marimo/_server/export/exporter.py
previously running a script that created a mo.ui.table() would throw a ContextNotInitializedException
> fix: use data urls for vfiles when running as a script

- marimo/_cli/export/commands.py
- marimo/_server/export/utils.py
Example:
`marimo export html notebook.py -o notebook.html -- -arg1 foo -arg2 bar`
> feat: add cli args to html export

- frontend/src/components/editor/renderers/grid-layout/grid-layout.tsx
Previously the grid editor did not expand to it's full height
> fix: grid editor when bordered

- marimo/_server/recents.py
Ignore more tmp files in the `marimo edit` homepage. Also, don't show recents that are in a directory other than `cwd`.
> chore: ignore /var tmp directory in homepage

- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- frontend/src/utils/objects.ts
- marimo/_smoke_tests/bugs/1161.py
- marimo/_smoke_tests/bugs/1165.py
Fix: 
* keeps dragmode and selection across re-renders (new value updates) and re-mounts (switching to present mode)
* keeps zoom across re-renders and re-mounts. this can be misleading if its a new plot, but we this seems like the better default behavior
* adds a button (to the default topbar) to reset the state completely 
Fixes #1160 #1161
> fix: fix plotly re-rendering and re-mounting state

- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- marimo/_output/formatters/plotly_formatters.py
- marimo/_plugins/ui/_impl/plotly.py
- marimo/_smoke_tests/bugs/1161.py
- marimo/_smoke_tests/bugs/1165.py
- marimo/_smoke_tests/bugs/846.py
Fixes #846 
Adds support for plotly config and using their `pio.renderers` feature.
```python
@app.cell
def __(fig, mo):
fig  # Uses the default renderer
return
@app.cell
def __(fig, mo):
mo.ui.plotly(fig)  # Uses the default renderer
return
@app.cell
def __(fig, mo):
mo.ui.plotly(fig, config={})  # Uses the empty config
return
@app.cell
def __(fig, mo):
mo.ui.plotly(fig, config={"staticPlot": True})  # Uses the passed config
return
@app.cell
def __(fig, mo):
mo.ui.plotly(fig, renderer_name="browser")  # Uses a pre-defined rendererer
return
```
> improvement: support plotly config and renderers

- marimo/_runtime/cell_runner.py
- tests/_runtime/reload/test_module_watcher.py
- tests/_runtime/test_cell_runner.py
To prevent bugs in imported libraries from crashing the kernel
Closes #1176 
Context: We started catching `BaseExceptions` in https://github.com/marimo-team/marimo/pull/253. But since we now use `os._exit(0)` instead of `sys.exit()` (latter throws a `SystemExit` exception), it's fine to catch `BaseException`s, the process should still terminate ...
> fix: catch base exceptions

- marimo/_runtime/reload/module_watcher.py
- tests/_runtime/reload/test_module_watcher.py
ModuleFinder often fails on large modules, such as numpy, scipy, torch, pandas ...
Ignore third-party packages (installed in site-packages) so that scripts or user namespace packages importing these modules can still be used with autorun reloading.
Fixes #1174
> fix: ignore third-party packages in module watcher

- marimo/_server/file_router.py
Prune dirs `> MAX_DEPTH` from homepage search. Reduces time to load the homepage.
> fix: prune directories from os.walk search

- marimo/_runtime/runtime.py
- only store mtime timestamps of newly loaded modules after execution
- fixes an edge case bug in which a cell modifies the source of a module imported in another cell
fixes #1188
> fix: only check newly loaded modules after execution

- docs/guides/editor_features.md
- docs/guides/exporting.md
- docs/guides/index.md
- marimo/_cli/export/commands.py
- marimo/_server/api/endpoints/export.py
- marimo/_server/export/exporter.py
- marimo/_server/export/utils.py
- marimo/_server/models/export.py
- marimo/_server/router.py
- tests/_cli/snapshots/script.txt
- tests/_cli/test_cli_export.py
- tests/_server/api/endpoints/test_export.py
- tests/conftest.py
Part of #717 
Adds the ability to generate a flat python script from the command line as well as `watch`:
```bash
marimo export script notebook.py > notebook.script.py
marimo export script notebook.py --output notebook.script.py
marimo export script notebook.py --watch --output notebook.script.py
```
> feat: `marimo export script`, to export notebook as a flat script

- marimo/_runtime/reload/module_watcher.py
- tests/_runtime/reload/reload_test_utils.py
This PR fixes a race condition in which the module watcher was iterating over `sys.modules` while the kernel may have been modifying it.
Fixes the race mentioned in #https://github.com/marimo-team/marimo/pull/1179#issuecomment-2073974729
> fix: race condition in module watcher

- marimo/_ast/app.py
- tests/_ast/test_app.py
Each cell gets a fresh figure, just like in edit mode. Without this using the imperative api makes all plots share the same object.
Fixes one of the issues in #1142
> fix: close matplotlib figures in app.run()

- marimo/__init__.py
- marimo/_ast/app.py
- marimo/_messaging/tracebacks.py
- marimo/_output/formatters/matplotlib_formatters.py
- marimo/_runtime/context/utils.py
- marimo/_runtime/runtime.py
- tests/_ast/test_app.py
- tests/_runtime/test_runtime.py
This was fixed earlier but regressed when we added `running_in_notebook`.
Fixes an issue mentioned in #1142 
Adds a simple unit test instead of the entire smoke test mentioned in that issue, since `plt.show()` blocks.
> fix: don't load marimo mpl backend in script context

- marimo/_output/hypertext.py
- marimo/_plugins/stateless/status/_progress.py
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_utils/exiting.py
- tests/_cli/test_cli_export.py
`__del__` methods were previously throwing on script exit. Bind globals needed to detect whether Python is exiting as locals on `__del__` methods.
> fix: graceful exit when running as a script

- marimo/_runtime/reload/autoreload.py
- marimo/_runtime/reload/module_watcher.py
- tests/_ast/test_app.py
- tests/_smoke_tests/test_run_as_script.py
- syntax error doesn't mean automatically stale
- report syntax errors to the user
> fix: syntax error handling in module reloading

- marimo/_server/export/exporter.py
Alternatively, add click to micropip install, but this is better
> Add guard around click import for WASM

- marimo/_messaging/tracebacks.py
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/context/script_context.py
- marimo/_runtime/context/types.py
- marimo/_runtime/runtime.py
- marimo/_server/export/utils.py
- tests/_cli/test_cli_export.py
- tests/conftest.py
Previously HTML formatted tracebacks were being printed to the terminal.
> fix: don't format tracebacks with codehilite when stderr not overridden

- marimo/_server/export/utils.py
This fixes the HTML exporter to include console outputs.
However, even though the HTML now contains non-empty `cellConsoleOutputs` (verified manually on a simple example), the console outputs are still not shown in the browser.
~@mscolnick, would appreciate your help with getting the frontend to render the outputs.~
This is only a partial (backend) fix, the frontend still doesn't render the captured console outputs, since it renders in run mode.
Here's my simple test case:
```python
import marimo
app = marimo.App()
@app.cell
def printer():
print("hello, world!")
return
```
> fix: include console outputs in exported html

- marimo/_server/api/endpoints/assets.py
- tests/_server/api/endpoints/test_assets.py
404s are less noisy to the console and if its not in the right format, it wont be found
> fix: Invalid virtual file returns 404

- marimo/_server/files/os_file_system.py
- tests/_server/files/test_os_file_system.py
Fixes the error
```
...
File "[home]/ProjekteAktuell/marimo/marimo/_server/files/os_file_system.py", line 96, in _is_marimo_file
return "app = marimo.App(" in file.read()
File "/usr/lib/python3.8/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 1535: invalid continuation byte
```
that will occur when trying to open the file browser in a directory that contains a file that is not utf8-encoded.
To reproduce the error, run the following cell in a marimo notebook and reload the file browser:
`open("babylon.py", "wb").write(b"\xe4")`
> fix UnicodeDecodeError

- marimo/_runtime/reload/autoreload.py
- tests/_runtime/reload/test_autoreload.py
This escalates all errors encountered when reloading a module.
Previously, one could introduce errors like faulty imports and have them silently failed. I ran into this and was confused why I wasn't seeing the latest changes in my notebook.
> fix: no silent errors in module autoreloading

- docs/guides/coming_from_jupyter.md
- docs/guides/wasm.md
- marimo/_output/builder.py
- marimo/_output/formatters/altair_formatters.py
- marimo/_output/formatters/bokeh_formatters.py
- marimo/_output/formatters/ipython_formatters.py
- marimo/_output/formatters/leafmap_formatters.py
- marimo/_output/formatters/utils.py
- marimo/_runtime/virtual_file.py
- tests/_output/formatters/test_altair.py
- tests/_output/formatters/test_formatter_utils.py
- tests/_output/test_builder.py
- tests/_output/test_data.py
Fixes #1255
1. We properly add `filename` to the virtual file so it can guess the mime type which is needed when creating an data-uri
2. We use `srcdoc` over `src` for better cors support (so resizing the iframe on load works)
> fix: properly handle iframes in marimo export

- frontend/src/components/app-config/app-config-form.tsx
- frontend/src/core/config/config-schema.ts
- marimo/_ast/app.py
- marimo/_server/templates/templates.py
- tests/_ast/codegen_data/test_generate_filecontents_empty.py
- tests/_ast/codegen_data/test_generate_filecontents_empty_with_config.py
- tests/_ast/test_app.py
- tests/_ast/test_codegen.py
- tests/_server/templates/snapshots/export1.txt
- tests/_server/templates/snapshots/export2.txt
- tests/_server/templates/snapshots/export3.txt
This PR adds a field in the configuration that allows the user to change the title (HTML <title>) displayed in the browser.
> Make app title configurable

- frontend/src/plugins/core/RenderHTML.tsx
- frontend/src/plugins/core/__test__/RenderHTML.test.ts
fixes #1270 
Output may contain something that looks like a tag but is not, e.g. `<abc:123>`
> fix: render-html with invalid tags

- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- frontend/src/utils/objects.ts
- marimo/_smoke_tests/bugs/1273.py
Fixes #1273
Previously we stored the state in the component value without letting the external change update the component. This fixes that
> fix: allow resetting plotly zoom/pan externally

- marimo/_plugins/stateless/status/_progress.py
- marimo/_smoke_tests/bugs/1271.py
- tests/_ast/test_codegen.py
Fixes #1271
Add a `_mime_()` to the spinner class to display without a context manager
> improvement: mo.ui.spinner can display without a context manager

- marimo/_output/formatters/altair_formatters.py
- marimo/_smoke_tests/bugs/1279.py
- tests/_output/formatters/test_altair.py
Fixes #1279 
Using src makes the filepath for virual files a bit funky and fails when loading data via a virtual file
> fix: altair when using marimo_csv data_transformer

- frontend/src/core/cells/__tests__/collapseConsoleOutputs.test.ts
- frontend/src/core/cells/collapseConsoleOutputs.tsx
Fixes #1274
outputs where not updated due to mutating the object (no new references)
> fix: Refactor console outputs to use a copy of the input array

- marimo/_server/api/endpoints/ws.py
- marimo/_server/sessions.py
Sometimes a proxy can hang onto to a connection, but the client is already disconnected (and trying to reconnect). This disconnects if there is still a connection
> fix: disconnect from consumer if there is a stale connection

- frontend/src/components/editor/output/MarimoErrorOutput.tsx
- frontend/src/core/kernel/messages.ts
- marimo/_messaging/errors.py
- marimo/_runtime/dataflow.py
- marimo/_runtime/validate_graph.py
- tests/_runtime/test_runtime.py
- tests/_runtime/test_validate_graph.py
> Improvement: annotate cycles with variable names

- marimo/_plugins/stateless/status/_progress.py
- marimo/_smoke_tests/status.py
Hi! Thanks for all the good work with marimo. I found myself wanting to update the subtitle while the progress bar was running, which is a pattern I've used before with `tqdm`.
I modified progress_bar to also be usable as a context manager, which exposes the underlying `ProgressBar` and allows for manual calls to `update`. This achieves the functionality I'm looking for, and still allows for using the normal iterable method.
Happy to make any changes if needed 😄
> feat: allow status.progress_bar to be used as a context manager

- marimo/_cli/convert/markdown.py
- marimo/_server/export/exporter.py
- marimo/_server/export/utils.py
- tests/_cli/snapshots/marimo_for_jupyter_users.md.txt
- tests/_cli/snapshots/unsafe-app.md.txt
- tests/_cli/snapshots/unsafe-app.py.txt
- tests/_cli/snapshots/unsafe-doc.md.txt
- tests/_cli/snapshots/unsafe-doc.py.txt
- tests/_cli/test_markdown_conversion.py
Was looking over the merge this morning and realized it would be possible to "inject" code blocks.
I don't think this could be used that maliciously since running a notebook is already pretty risky. Maybe injecting a <script> tag that would only appear during conversion.
Either way, it's a bug. If you can think of more unsafe behavior let me know. Might be a cool chance to use one of those LLM fuzzers.
> fix: add markdown sanitization for malicious notebooks

- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_smoke_tests/bugs/1312.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
Fixes #1312
Our frontend can handle duplicate datatypes but since add `.get_field_types` to the TableManager, it can fail on duplicate headers (which returns a nested `dataframe` instead of a series)
> fix: handle duplicate columns in pandas when inferring datatype

- Makefile
- marimo/_smoke_tests/bugs/1312.py
- scripts/pyfix.sh
> Run typos checks in makefile

- .github/workflows/playwright.yml
- frontend/e2e-tests/helper.ts
- frontend/e2e-tests/kitchen-sink-wasm.spec.ts
- frontend/playwright.config.ts
- frontend/src/core/pyodide/worker/getMarimoWheel.ts
- frontend/vite.config.mts
- marimo/_config/manager.py
- marimo/_config/utils.py
- marimo/_islands/island_generator.py
- marimo/_server/export/__init__.py
- marimo/_server/export/exporter.py
- pyodide/DOCS.md
> chore: improve wasm development, e2e test

- frontend/src/core/islands/worker/controller.ts
- frontend/src/core/islands/worker/worker.tsx
- frontend/src/core/pyodide/worker/bootstrap.ts
- frontend/src/core/pyodide/worker/getPyodideVersion.ts
- frontend/src/core/pyodide/worker/types.ts
- frontend/src/core/pyodide/worker/worker.ts
This is so we can test with new pyodide versions before they are released
> improvement: load pyodide dev version on marimo dev releases

- marimo/_cli/convert/markdown.py
- marimo/_server/export/exporter.py
- tests/_cli/snapshots/broken.txt
- tests/_cli/snapshots/dataflow.md.txt
- tests/_cli/snapshots/marimo_for_jupyter_users.md.txt
- tests/_cli/snapshots/unsafe-doc.md.txt
- tests/_cli/snapshots/unsafe-doc.py.txt
- tests/_cli/test_markdown_conversion.py
I got `marimo edit document.md` working locally and realized a few things were missing:
The actual code to get `marimo edit document.md` working is a bit of a hack. Once this is in, I'll open the PR for reference, but I think that it will require a deeper rework from someone more versed in the internals
> Persist App state + Cell state in md conversions

- marimo/_runtime/reload/module_watcher.py
> fix: ignore warnings when analyzing modules in watcher

- marimo/_ast/cell.py
- marimo/_runtime/reload/autoreload.py
- marimo/_runtime/reload/module_watcher.py
- marimo/_runtime/runtime.py
- tests/_runtime/reload/test_module_watcher.py
Fixes a bug in which registering a new cell or editing an existing cell wouldn't mark the cell as stale even if it used a stale module. This led to an unfortunate bug where the frontend thought a cell was stale but the backend didn't, since we try to minimize the number of stale status changes sent to the FE to prevent re-renders.
The set of stale modules is stored on a `ModuleReloader` object, which is shared between the `module_watcher` thread and the main thread. To avoid races I made the `ModuleReloader` thread-safe with a coarse lock. Tested manually and the performance impact is not noticeable.
> fix: check for module staleness when registering a cell

- frontend/src/components/editor/header/filename-input.tsx
- frontend/src/utils/__tests__/path.test.ts
- frontend/src/utils/paths.ts
- marimo/_cli/cli.py
- marimo/_cli/export/commands.py
- marimo/_cli/file_path.py
- marimo/_server/asgi.py
- marimo/_server/export/__init__.py
- marimo/_server/file_manager.py
- marimo/_server/file_router.py
- marimo/_server/utils.py
- marimo/_utils/marimo_path.py
- tests/_cli/test_markdown_conversion.py
- tests/_runtime/reload/test_module_watcher.py
- tests/_server/mocks.py
- tests/_server/test_file_router.py
- tests/_utils/test_marimo_path.py
- Adds a `MarimoPath` class with useful validation tools. This might be overkill now, but can help consolidate our renaming/validation logic over time
- Allow renaming `.md` files in the frontend
> improvement: allow renaming markdown files when enabled

- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
If console outputs are present and code is not shown, show them in run mode.
> fix: include console outputs in HTML exports when code is shown

- marimo/_server/export/exporter.py
- marimo/_utils/marimo_path.py
- tests/_cli/snapshots/script.txt
Make exported scripts compatible with VSCode notebook format
For #717
> fix: # %% in export script

- frontend/src/plugins/layout/LazyPlugin.tsx
- marimo/_plugins/stateless/lazy.py
- marimo/_smoke_tests/lazy.py
Previously we would not re-render contents inside lazy if they were updated from reactivity.
> fix: mo.lazy rendering

- marimo/_plugins/ui/_impl/array.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/sidebar.py
- tests/_plugins/ui/_impl/test_input.py
Fix clone method of form -- don't need to special case it. Previously we were dropping form info on clone.
Fixes #1131
> fix: cloning of forms in arrays/dicts

- frontend/src/components/dependency-graph/dependency-graph-minimap.tsx
- frontend/src/components/dependency-graph/dependency-graph-tree.tsx
- frontend/src/components/dependency-graph/panels.tsx
- frontend/src/components/editor/links/cell-link-list.tsx
- frontend/src/components/editor/links/cell-link.tsx
- frontend/src/components/variables/common.tsx
- frontend/src/components/variables/variables-table.tsx
- frontend/src/core/codemirror/find-replace/search-highlight.ts
- marimo/_smoke_tests/bugs/1362.py
Fixes #1362 
This improves the scroll to variable logic by using the syntax tree as well as using CodeMirrors scroll to focus
> fix: scroll to variable

- frontend/src/core/islands/worker/controller.ts
- frontend/src/core/islands/worker/worker.tsx
- frontend/src/core/pyodide/bridge.ts
- frontend/src/core/pyodide/worker/bootstrap.ts
- frontend/src/core/pyodide/worker/fs.ts
- frontend/src/core/pyodide/worker/getController.ts
- frontend/src/core/pyodide/worker/save-worker.ts
- frontend/src/core/pyodide/worker/types.ts
- frontend/src/core/pyodide/worker/worker.ts
- marimo/_pyodide/bootstrap.py
This adds a second web-worker for saving. This does add to the overhead since now we need to install pyodide on 2 workers since the python interpreter is not shared between them
> improvement: seperate worker for saving

- frontend/src/components/editor/chrome/wrapper/machine-stats.tsx
- frontend/src/core/websocket/types.ts
- frontend/src/core/websocket/useWebSocket.tsx
* Adds the onOpen/onClose handlers to the websocket creation, rather than on mount
* adds a small icon in the footer to signify connection - easier for debugging if this problem arrises 
_Screenshot of all the icons (although not all appear at the same time)_
> fix: race-condition when connecting to websocket sometimes

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/core/codemirror/language/utils.ts
- frontend/src/core/hotkeys/hotkeys.ts
Fixes: https://github.com/marimo-team/marimo/issues/1372
The issue mentioned using Ctrl+Shift+- as the hotkey, but that seemed to have some interaction with zooming in the browser.
I have the hotkey set to Mod+Shift+' for now; if you'd like to change that, I'm happy to do so!
Also, tested in the browser but could not make unit tests for the reducer due to the dependency on the editor view. I have added a TODO to find a solution to this.
Solved with the help of Glide. Check out the full solution here!
https://glide.agenticlabs.com/sharing?userId=65bae76b7fbfb1c20ac1f3b8&taskId=miIvJdg
> Hotkey for splitting cells

- marimo/_ast/cell.py
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_runtime/runtime.py
- pyproject.toml
- tests/_cli/snapshots/ipynb.txt
- tests/_runtime/test_runtime.py
- tests/conftest.py
- if the output of a cell contains a UIElement, store a reference to it
- the stored reference is released when a cell's state is invalidated
(on rerun, deletion, etc)
We check for UI elements by using flatten -- covers bare UI elements
and lists, tuples, dicts. Custom datastructures not supported but
should cover almost all real cases, including the very common
practice of ending a cell with `mo.ui.table()`.
> fix: enable rpcs unnamed UI elems

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/cell/code/language-toggle.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/extension.ts
- frontend/src/core/codemirror/language/markdown.ts
- frontend/src/core/codemirror/language/utils.ts
Open to discussing if we want this. but this will make every cell that is markdown compatible, start with the markdown editor
> improvement: start cell editor in markdown if is markdown-compatible

- marimo/_plugins/ui/_core/registry.py
- marimo/_runtime/runtime.py
This is needed to give make mo.ui.dataframe() work when unnamed (RPC alone wasn't enough).
This also enables on_change to work on unnamed elements, as long as someone is holding a reference to the element.
> enable SetUIElementValue on unnamed elements

- marimo/_output/formatting.py
- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/context/script_context.py
- marimo/_runtime/context/types.py
- just print plaintext of str(obj): this is better for some objects, plus pprint can fail when str() doesn't
- without this, attempting to outupt duckdb.read_csv() failed
> fix: formatting when no formatter is found

- marimo/_cli/convert/markdown.py
- pyproject.toml
Cool template!
Add yaml dep, since it is _not_ default. Tests passed because pyyaml is a dep of pytest.
Added pyyaml as a dep to nixpkgs. Will submit for review whenever the next version bump is later this week or whatever
https://github.com/NixOS/nixpkgs/pull/313178
Fixes #1418 
@mscolnick
> explicitly add yaml as a dep

- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/cell/code/language-toggle.tsx
- frontend/src/core/cells/__tests__/add-missing-import.test.ts
- frontend/src/core/cells/add-missing-import.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/core/codemirror/extensions.ts
- frontend/src/core/codemirror/format.ts
- frontend/src/core/codemirror/language/utils.ts
- frontend/src/core/config/config.ts
- frontend/src/core/variables/state.ts
This will auto-import `import marimo as mo` after toggling markdown
> feat: auto-import marimo for markdown

- marimo/_output/formatters/formatters.py
Running some old converted jupyter notebooks gave me a kernel failure:
```txt
Process Process-1:                                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                               
File "/nix/store/ddhcwc8k9ma093n5vlpa9l617p4q2cax-python3-3.10.5/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap                                                                                           
self.run() …
```
> fix: don't break on vendored dependencies

- marimo/_server/file_manager.py
- tests/_server/test_file_manager.py
Sorry for the spam, I just patch these things as I find them.
I was converting some notebooks today, and used the rename functionality to go from py -> md. I noticed that if I didn't save after the rename, I'd end up with a markdown file with Python content.
Fix just runs save if the suffix is different
> fix: renaming a file extension should save in file format

- .github/PULL_REQUEST_TEMPLATE.md
A shorter PR template.
This change makes the PR template shorter.
N/A
N/A
@mscolnick
> Shorter PR template

- frontend/src/core/cells/__tests__/collapseConsoleOutputs.test.ts
- frontend/src/core/cells/collapseConsoleOutputs.tsx
Limit console outputs to last 5000 lines per cell. Fixes #1380 
This PR limits the number of lines shown in the console output per cell to avoid overloading the frontend. The tail of the console output is shown, limited to 5000 lines.
The number 5000 was chosen by comparison to Google Colab.
Fixes #1380 
> fix: limit console outputs to last 5000 lines per cell

- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/runtime.py
RPC triggered creation of a UI element (`altair_chart`), which then incorrectly evicted an existing UI element from the registry.
PR is exactly the same as #1397 -- pulling it out into its own PR so it's not blocked on routes. We can close #1397 after merging this.
> fix: random ids for ui elements made in functions

- marimo/_plugins/ui/_core/registry.py
- tests/_plugins/ui/_core/test_registry.py
Fix a regression in which we were accidentally removing a UI element from the registry.
Fixes #1438 
Need to test the Python id in addition to the object id.
@mscolnick
> fix: check python id before deleting UI element

- marimo/_output/utils.py
- marimo/_server/export/exporter.py
Fixes a bug in which notebooks containing images and other media couldn't be exported as HTML (reported on Discord).
@mscolnick
> fix: base64 encode vfile buffers in html export

- frontend/src/css/md.css
> fix: button styling with nested markdown

- marimo/_messaging/console_output_worker.py
- marimo/_smoke_tests/admonitions.py
The backend merges console outputs when it can before sending them to the frontend, but we weren't checking the mimetype (since they all used to be `text/plain`). This was causing tracebacks (text/html) to be incorrectly merged with `text/plain` stderr messages.
> fix: check mimetype when merging console outputs in BE

- frontend/src/css/admonition.css
- frontend/src/plugins/impl/vega/loader.ts
Implement a custom boolean parser on the frontend that accounts for the fact that pandas serialized bools start with uppercase letters.
Fixes #1459
> fix: boolean parsing for pandas and ui.table

- frontend/src/components/find-replace/find-replace.tsx
- frontend/src/core/codemirror/find-replace/state.ts
* add helper message to open the native browser search
* fix when a dialog is open
> fix: helper message to open the native browser search, fix when a dialog is open

- tests/_cli/snapshots/unsafe-doc.md.txt
- tests/_cli/snapshots/unsafe-doc.py.txt
- tests/_cli/test_markdown_conversion.py
Not sure what happened, but I noticed that markdown strings do not preserve `r` or `f.` Which causes breakage
Currently effecting the markdown_format tutorial (open it directly and then close).
Opening as a min repro, but I can make an issue too
Added snapshot tests from scratch
> Add markdown edgecase test

- docs/api/layouts/lazy.md
This PR addresses the issue with the `LazyComponent` example in the `docs/api/layouts` section, where the example code was not functioning correctly due to a missing library dependency. Fixes #1490.
The issue was caused by the absence of the random library, which is required for the `LazyComponent` preview code in docs to work correctly. To resolve this, the following changes have been made:
1. The `random` library has been imported.
2. The updated example code now runs as expected, demonstrating the correct usage of the `mo.lazy`.
@mscolnick (saw that this feature was introduced by him in the PR [here](https://github.com/marimo-team/marimo/pull/1052).
> Fix #1490 `docs: Fix LazyComponent example by installing missing dependency` 

- frontend/src/core/codemirror/cm.ts
The go-to-definition codemirror extension has introduced an urgent usability bug that often makes it impossible to continue coding in a marimo notebook (#1462).
This PR disables the extension. We can re-enable it once we fix this issue.
> Temporarily disable go-to-definition codemirror extension

- frontend/src/components/editor/RecoveryButton.tsx
- frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/components/editor/chrome/wrapper/sidebar.tsx
- frontend/src/components/editor/controls/Controls.tsx
- frontend/src/components/editor/controls/command-palette-button.tsx
- frontend/src/components/editor/header/status.tsx
- frontend/src/components/editor/inputs/Inputs.styles.ts
This change fixes positioning bugs with sidebars and the notebook "bottom-left" controls (save, preview, command palette).
Previously, the panel sidebar and `mo.ui.sidebar()` overlapped, and both of these sidebars overlapped the save/preview/command palette buttons.
- This change updates the panel sidebar to not have absolute positioning, fixing the sidebar overlap problem.
- Save/preview/command palette buttons are moved to the bottom right (by the run button), fixing positioning conflicts with both sidebars. This also makes the notebook controls more intuitive by putting them all in one place.
- Undo button stacks on top of run bottom (column flex) to avoid button shift.
- In narrow screens, controls stack with column flex.
Also fixes some styles on the save/preview/command-palette …
> fix: notebook control positioning

- frontend/src/core/pyodide/worker/getPyodideVersion.ts
This reverts commit e01f1829fb267baaf9344693b67b494fc75aa3cf.
FE appears to be incompatible with 0.26.0, needs debugging.
> Revert "bump pyodide to 0.26.0 (#1499)"

- frontend/src/core/edit-app.tsx
This pull request addresses the issue where the browser tab title does not update when a notebook is renamed. Fixes #1428 .
- Updated the `handleFilenameChange` function in the EditApp component to set `document.title` with the new filename.
- Added a `useEffect` hook to update `document.title` whenever the filename changes, ensuring the browser tab title stays in sync with the notebook name.
- Added a default value ("Untitled Notebook") for the document title in case the filename is null.
https://github.com/marimo-team/marimo/assets/123119434/37c1bbd6-ec64-4bf1-afee-c91b30de8ca6
- [✓ ] I have read the [contributor guidelines](../CONTRIBUTING.md).
- [✓ ] I have run the code and verified that it works as expected.
@akshayka #1428
> Fix #1428 - Update Browser Tab Title When Notebook is Renamed

- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/go-to-definition/underline.ts
* fixes the cmd+click crashing the codemirror editor (the reason it broke #1462 was because our plugin cashed the editor. this error was apparent in the console). So we removed the logic in `update()`)
* few performance improvements on mousemove
> fix: re-enable cmd click go-to-definition

- .github/workflows/test_cli.yaml
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- marimo/_cli/cli.py
- marimo/_cli/config/commands.py
- marimo/_cli/config/utils.py
- marimo/_config/manager.py
- scripts/buildfrontend.sh
- tests/_cli/test_cli_config.py
This adds a new CLI command `marimo config show`.  It's kinda hidden that we store user config in a config file on the user's computer and a few users have missed this - hopefully this helps with some education.
`show` is the only command under `marimo config` but its future looking for other commands.
> feat: add 'marimo config show' CLI command

- docs/api/inputs/button.md
- docs/api/inputs/run_button.md
- docs/recipes.md
- marimo/_plugins/ui/__init__.py
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_plugins/ui/_impl/run_button.py
- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/runtime.py
- marimo/_smoke_tests/run_button.py
Adds `mo.ui.run_button()`, which can be used to trigger computations when a button is pressed and ONLY when a button is pressed.
When the button is pressed, its value is set to `True` and its descendants are run. After its descendants have run, marimo automatically sets the button's value back to False. In this way, cells can gate computations on `run_button.value` -- updates to other variables won't spuriously cause the cell to run.
Caveat: The button's value is only reset to `False` when the runtime is configured to autorun cells, since the lazy runtime doesn't know when the button's descendants will/have been run. This should be fine in practice, since `ui.run_button` has no real use in lazy kernels anyway.
The implementation reuses the frontend plugin for `mo.ui.button()`.
@mscolnick
> feat: run_button

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/codemirror/go-to-definition/underline.ts
We previously did not call `.destroy` on the codemirror editor, leading to a memory leak
> fix: more defensive clearing of codemirror event listeners

- frontend/src/core/codemirror/go-to-definition/underline.ts
Noticed that GTD underline sometimes was not cleared on mouse leave, allowing multiple symbols to become underlined.
> fix: clear underline on mouseleave

- frontend/src/core/datasets/state.ts
- marimo/_data/get_datasets.py
- marimo/_dependencies/dependencies.py
- marimo/_plugins/ui/_impl/data_explorer.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_plugins/ui/_impl/tables/types.py
- marimo/_plugins/ui/_impl/tables/utils.py
- marimo/_smoke_tests/dataframe.py
This adds support for Ibis and the [dataframe protocol](https://data-apis.org/dataframe-protocol/latest/) in `mo.ui.table` and `mo.ui.data_explorer` as well as the new datasources panel.
This is using the pyarrow interchange to convert to a pyarrow table, so we can use leverage our existing infrastructure downstream.
It isn't quite necessary to try to convert to pandas or polars from the dataframe protocol since most of the libraries that implement the dataframe protocol (i.e. ibis) already require pyarrow. If we wanted to add this later, we ccan
> feat: support ibis and the dataframe protocol

- frontend/src/core/codemirror/copilot/client.ts
Closes #1484 !
Copilot previously tried to connect on `:0`
> Change WS port for copilot behind proxy

- frontend/src/components/debug/indicator.tsx
- frontend/src/components/editor/chrome/state.ts
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout-wrapper.tsx
- frontend/src/css/app/Cell.css
- frontend/src/utils/createReducer.ts
- persist sidebar across refreshes in local storage (it's jarring when a session is resumed, by the sidebar is not)
- reduce some padding on the side (with the sidebar open more, its quite useful padding
> improvement: persist sidebar across refreshes

- marimo/_server/api/auth.py
Fixes a regression in which we accidentally became incompatible with older versions of starlette. This was causing marimo to break on upgrade.
Fixes #1523
> fix: Starlette compatability

- frontend/src/components/editor/chrome/wrapper/footer.tsx
- frontend/src/core/codemirror/copilot/client.ts
- frontend/src/core/codemirror/language/__tests__/utils.test.ts
- frontend/src/core/codemirror/language/markdown.ts
Expose some runtime configuration in the footer:
- autorun on startup
- on cell change
and make it toggle-able on click. This change increases the information density of our UI, making these settings more discoverable.
> improvement: runtime configuration in footer

- frontend/src/components/debug/indicator.tsx
- frontend/src/components/editor/chrome/wrapper/footer.tsx
- frontend/src/core/pyodide/worker/worker.ts
Fixes #1547
Download `pyyaml` beforehand if it doesn't exist
> fix: download as yaml in WASM

- marimo/_islands/island_generator.py
- tests/_islands/test_island_generator.py
This PR adds a `include_initialization_indicator` flag to the `MarimoIslandsGenerator.render_body()` function to indicate to the user when the Pyodide initialization is done.
Fixes #1468.
Specifically, it prepends the following div in the rendered stubs:
```html
<div class="marimo" style="--tw-bg-opacity: 0;">
<div class="flex flex-col items-center justify-center">
<svg
xmlns="http://www.w3.org/2000/svg"
width="24"
height="24"
viewBox="0 0 24 24"
fill="none"
stroke="currentColor"
stroke-width="1"
stroke-linecap="round"
stroke-linejoin="round"
class="size-20 animate-spin text-primary"
>
<path d="M21 12a9 9 0 1 1-6.219-8.56"></path>
</svg>
<div>Initializing...</div>
</div>
</div>
```
which uses the `animate-spin` class loaded with the marimo css to display something like the following:
Note …
> feat: adding initialization indicator to marimo islands

- marimo/_ast/compiler.py
- tests/_cli/snapshots/marimo_for_jupyter_users.md.txt
- tests/_runtime/test_runtime.py
Some browsers might send the nbsp character (U00A0) instead of spaces, causing syntax errors when trying to run Python.
This change uniformly replaces nbsp characters with spaces when compiling code.
This seems okay to me, but not sure if this has second-order effects that I'm unaware of ...
Fixes #1546
> fix: replace nbsp with space

- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/bugs/1545.py
Adds `.apply_selection` to a altair_chart widget:
Apply the selection to a DataFrame.
This method is useful when you have a layered chart and you want to
apply the selection to a DataFrame.
**Example.**
```python
import altair as alt
from vega_datasets import data
cars = data.cars()
_chart = (
alt.Chart(cars)
.mark_point()
.encode(
x="Horsepower",
y="Miles_per_Gallon",
color="Origin",
)
)
chart = mo.ui.altair_chart(_chart)
chart
selected_df = chart.apply_selection(cars)
```
**Args.**
- `df`: a Pandas DataFrame to apply the selection to
**Returns.**
- a Pandas DataFrame of the plot data filtered by the selections
> improvement: add .apply_selection() to mo.ui.altair_chart for layered/stacked charts

- marimo/_ast/compiler.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/bugs/1545.py
- marimo/_smoke_tests/bugs/643.py
- tests/_plugins/ui/_impl/test_input.py
- tests/_runtime/test_runtime.py
Raise an error if a dropdown/multiselect has too many options.
Without this limit, dropdowns/multiselect can crash the frontend.
> fix: refuse to create dropdown, multiselect with >1k options

- marimo/_ast/compiler.py
- marimo/_runtime/complete.py
- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/context/utils.py
- marimo/_runtime/runtime.py
- marimo/_smoke_tests/bugs/1545.py
- marimo/_smoke_tests/bugs/643.py
- tests/_runtime/test_runtime.py
This change improves the responsiveness and coverage of code completion.
- Fallback to the Jedi `Interpreter` class when static analysis-based completion turns up empty. (Jedi's static completer fails on some libraries, like ibis.) The `Interpreter` completer evaluates code, so care is taken to avoid race conditions with the kernel by introducing a lock on the globals dictionary. Acquiring/releasing the lock works in Pyodide, even though Pyodide doesn't support creating threads, so no separate codepath was needed for WASM.  
- Decrease the docstring limit when running locally from 1000 to 80.
- Add a cumulative timeout across completions, after which we stop computing completion info. 
As a result:
- We now get completions for Ibis, and probably other libraries that we were failing to …
> improvement: fallback to jedi interpeter in completion

- frontend/src/plugins/impl/FileBrowserPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
Enhances the File Browser component (fulfilling #1478) with a few bug fixes.
- Adds `selection_mode` parameter to allow the user to select files, directories, or both.
- To select a directory, user must check the checkbox next to the directory name. Clicking the table row still "opens" the directory.
- Adds "Select all" / "Deselect all" button to allow user to select or deselect all files in the current directory.
- If `multiple == False`, then these buttons are not rendered.
- Fixes error when clicking ".." at the topmost directory.
- TODO: Prints a more readable representation of a FileInfo list.
- @mscolnick
> improve: Select folders and select all in File Browser

- marimo/_ast/visitor.py
- tests/_ast/test_visitor.py
- tests/_runtime/test_runtime.py
previously
```python
try:
1 / 0
except Exception as e:
f = e
e = 2
refs(), defs()
```
Would give `ref=e`, `def=e,f`. At first glance, this seems fine- but "e" is scoped to the try block and is deleted afterwards, so the correct solution is `ref=[]`, `def=[f]`
Note in the case
```python
e = 7
try:
1 / 0
except Exception as e:
f = e
e = 2
print("woops")
```
e is no longer set if the except block triggers, but because it was set outside of the block, `ref=`, `def=e,f` is correct
Added an `ObscuredScope` context to remove Name references if they are obscured by the try block + added some unit tests
Your PR will be reviewed more quickly if you can figure out the right person to tag with @ -->
> fix: `try` blocks delete context variable afterwards, but marimo still considers them refs or defs if used

- frontend/src/components/app-config/app-config-form.tsx
- frontend/src/components/app-config/user-config-form.tsx
This change improves the legibility of the user config form.
Styling for the user/app config was inconsistent across items, making the config menu difficult to read.
> chore: tidy config form style

- frontend/src/components/editor/chrome/panels/outline-panel.tsx
- frontend/src/core/cells/outline.ts
- frontend/src/core/dom/__tests__/outline.test.ts
- frontend/src/core/dom/outline.ts
Fixes #1582 
While it's better to use `.id`, we can fallback to an xpath to find the correct heading to navigate to
> improvement: use xpath when heading does not contain an ID

- frontend/src/components/editor/chrome/panels/datasources-panel.tsx
- marimo/_data/get_datasets.py
- marimo/_data/preview_column.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/dataframe_protocol.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/df_protocol_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_plugins/ui/_impl/tables/pyarrow_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_plugins/ui/_impl/tables/types.py
- marimo/_plugins/ui/_impl/tables/utils.py
- marimo/_smoke_tests/bugs/1586.py
- tests/_plugins/ui/_impl/tables/test_df_protocol.py
Fixes #1586
- make ibis and dataframe-like tables lazy evaluate (specifically for num rows)
- add `DataFrameProtocolTableManager` which can be lazier and more performant when displaying in the datasources panel
> improvement: make ibis and dataframe-like tables lazy evaluate

- frontend/src/components/editor/RecoveryButton.tsx
- frontend/src/components/editor/renderers/vertical-layout/useDelayVisibility.ts
- frontend/src/components/ui/dialog.tsx
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/cm.ts
- frontend/src/core/codemirror/config/extension.ts
- frontend/src/core/codemirror/copilot/extension.ts
- frontend/src/core/codemirror/language/__tests__/utils.test.ts
- frontend/src/core/codemirror/language/extension.ts
- frontend/src/core/codemirror/language/markdown.ts
- frontend/src/core/codemirror/language/python.ts
- frontend/src/core/codemirror/language/types.ts
- frontend/src/stories/editor.stories.tsx
* don't show placeholders in markdown
* allow toggling markdown when no text is written
* Some styling cleanup to the recover dialog
> fix: allow converting to markdown when empty

- marimo/_output/hypertext.py
- marimo/_plugins/stateless/status/_progress.py
To avoid spurious error logs on Python exit.
`weakref.finalize` is called when an object is destructed (like `__del__`), but it can be configured to not be called when Python is exiting.
> Use weakref.finalize instead of __del__ in Html destruction

- .github/workflows/test.yaml
- slows down CI
- we're not referring to it right now
can add back in later if there is a need, or run codecov somewhere else
Fixes #1598
> disable codecov

- marimo/_messaging/ops.py
- marimo/_plugins/core/json_encoder.py
- use our WebEncoder which handles more edge-cases for serialization
- gracefully handle serialization errors and still return a response
> fix: rpc serialization and gracefully handle errors

- frontend/src/components/data-table/column-header.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- frontend/src/plugins/impl/vega/loader.ts
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/df_protocol_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_plugins/ui/_impl/tables/pyarrow_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
- remove useEffect usage and consolidate loading logic in dataframe plugin
- better generic types in dataframe plugin
- handle sorting when types are not comparable in the `DefaultTableManager`
> fix: dataframe be sorting follow-ups

- marimo/_ast/app.py
- marimo/_ast/transformers.py
- marimo/_cli/convert/ipynb.py
- marimo/_runtime/dataflow.py
- marimo/_smoke_tests/bugs/1602.py
- marimo/_smoke_tests/no_mutating.py
- tests/_cli/ipynb_data/multiple_defs.ipynb.txt
- tests/_cli/test_ipynb_to_marimo.py
Automatically transform variables that are defined multiple times but referenced nowhere into local variables when using marimo convert.
This increases the chances of a smooth conversion from Jupyter to marimo.
Partially addresses #1477
> improvement: autofix some multiple definition errors in marimo convert

- marimo/_server/start.py
- marimo/_server/utils.py
With this change, one should be able to open > 100 notebooks in a single marimo server on macOS, which should be more than enough.
Previously the limit was ~8.
Fixes #1610
> fix: increase fd limit on the marimo server

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/cell/CellStatus.tsx
- frontend/src/core/cells/cell.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/types.ts
Fixes #1444, an edge case bug that caused cells to lose "stale" status on session resume.
Important to note that this bug was only for uninstantiated cells, or effectively, the first session resume. Cells that had been run and later became stale were already persisted on subsequent resumes.
- In `createCellRuntimeState()`, pass `staleInputs: true` if `lastExecutionTime == null`, which will only be null for an uninstantiated cell.
- Update cell status tooltip with more relevant "This cell has not yet been run" hint for uninstantiated cells.'
Uninstantiated cells after session resume:
Stale cells after session resume:
@mscolnick
> fix: Persist stale cells on session resume

- frontend/src/core/dom/uiregistry.ts
- frontend/src/core/functions/FunctionRegistry.ts
- frontend/src/core/islands/bridge.ts
- frontend/src/core/islands/main.ts
- frontend/src/core/kernel/RuntimeState.ts
- frontend/src/core/kernel/__tests__/RuntimeState.test.ts
- frontend/src/core/pyodide/bridge.ts
- frontend/src/core/static/virtual-file-tracker.ts
This will help for the vscode plugin - since each renderer may need to import their own js script
> chore: cleanup singleton logic to cache on the window

- frontend/src/components/editor/Cell.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/types.ts
This change fixes a bug in which cells were incorrectly marked as stale on session startup/resume.
Previously, the frontend set a cell's `staleInputs` to `true` if autorun-on-startup was disabled or if a cell didn't have an execution time. But errored cells don't have execution times. And in general, setting `staleInputs` is error-prone and only something the BE can determine.
This change instead initializes with `staleInputs=False`, letting session replay override it as usual, and makes the check for whether a cell is `uninstantiated` more robust.
Tested by manually playing around with a lot of edge cases.
> fix: uninstantiated logic

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/cells/scrollCellIntoView.ts
This change modifies scrolling to cells to use block nearest instead of center, keeping the page as is if the element is already in view.
As a result, running shift enter, adding or deleting a cell no longer scrolls the page (unless eg the created cell is not in the viewport).
3 users have complained about our scroll being too jumpy, especially on cell run -- this addresses that feedback.
> improvement: less scroll shift

- frontend/src/components/data-table/data-table.tsx
- frontend/src/components/data-table/pagination.tsx
- frontend/src/components/ui/button.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- frontend/src/plugins/impl/data-frames/forms/__tests__/__snapshots__/form.test.tsx.snap
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/df_protocol_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_plugins/ui/_impl/tables/pyarrow_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_smoke_tests/datasources.py
- tests/_plugins/ui/_impl/tables/test_default_table.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_plugins/ui/_impl/tables/test_pyarrow.py
- tests/_plugins/ui/_impl/test_table.py
Add global search to tables. Supports:
* polars
* pandas
* pyarrow
* lists/dicts
Bugfix:
* clear selection when filter or sort changes
Other:
* i removed the mb-1 on buttons. This caused lots of issues with composition, but if this was useful somewhere, we can add this back per-case.
> feat: global table search

- frontend/src/plugins/impl/DataTablePlugin.tsx
Followup from #1641 
Need to clear the filters
> fix: clear global search in the backend for dataframes

- frontend/src/core/edit-app.tsx
- frontend/src/core/saving/filename.ts
This PR fixes #1630 by displaying the basename only instead of the entire path in the tab.
I introduced a new atom `useFiletitle()` which simply extracts the string after the last `/` character in the path (path.basename not available in the client). It depends on the full filename so reacts to changes in the filename accordingly.
> fix: use basename for document title (#1630)

- frontend/src/components/editor/chrome/wrapper/machine-stats.tsx
- marimo/_server/api/endpoints/health.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_server/api/endpoints/test_health.py
Add server memory (the whole `marimo edit`) and kernel memory (just the current session), to the footer
> improvement: more memory stats

- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/types.ts
Fixes a bug in which the run all stale button would always indicate staleness when autorun on startup was disabled.
Fixes #1656
> fix: run all stale button

- frontend/src/core/websocket/useWebSocket.tsx
- marimo/_server/api/auth.py
- marimo/_server/api/endpoints/health.py
- marimo/_server/api/endpoints/ws.py
- marimo/_server/sessions.py
1. When multiple notebooks are open in marimo edit, we sometimes get unexpected `WebSocketDisconnect`s. This change makes the server more robust to those errors — one can at least continue working with notebooks that failed to connect by refreshing —  without solving the root problem.
2. Make usage endpoint's CPU measurement nonblocking. This was slowing down the server.
Fixes #1653 
Fixes #1622
> fix: robust websocket disconnect, nonblocking usage stats

- marimo/_server/export/exporter.py
Saving a new markdown file with a user specified default width, causes breakage since `tomlkit` loads wrapped types as opposed to raw python types. The result of saving or creating a new md notebook gives something like:
```md
---
title: Example
marimo-version: 0.6.22
width: !!python/object/apply:tomlkit.items.String
- !!python/object/apply:tomlkit.items.StringType
- '"'
- medium
- medium
- !!python/object:tomlkit.items.Trivia
indent: ''
comment_ws: ''
comment: ''
trail: '
'
---
```
Ideally, you might consider casting config loads to be the raw python values.
To replicate, set your default to something that is not "compact".
Then do `marimo edit example.md` (assuming example.md doesn't exist). Make a change, and try to save. View the raw file.
Just run str on frontmatter inputs, this is …
> Add str in conversion to stop toml.type from being encoded and breaking markdown mode

- marimo/_ast/cell.py
- marimo/_messaging/ops.py
- marimo/_runtime/runner/execution_hooks.py
- marimo/_runtime/runner/hooks_on_finish.py
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_runtime/runtime.py
- tests/_plugins/ui/_impl/test_run_button.py
- tests/_runtime/test_runtime.py
Cleans up hooks so that state transitions aren't repeated. The
semantics in cell-op are that a field is non-None if and only if the
field's value has changed.
Also sneaks in a unit test that I forgot to include in a previous PR.
> fix: status transitions should not be repeated

- frontend/src/core/edit-app.tsx
- frontend/src/core/saving/useAutoSave.ts
We don't want the user to save in kiosk mode - otherwise you could save stale state.
> fix: don't allow saving in kiosk

- marimo/_ast/app.py
- marimo/_plugins/ui/_core/registry.py
- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/context/script_context.py
- marimo/_runtime/context/types.py
- marimo/_runtime/runtime.py
- marimo/_smoke_tests/appcomp/inner.py
- marimo/_smoke_tests/appcomp/make_table.py
- marimo/_smoke_tests/appcomp/outer.py
- pyproject.toml
- tests/_ast/app_data/calculator.py
- tests/_ast/app_data/ui_element_dropdown.py
- tests/_ast/test_app.py
Embed notebooks in other notebooks.
This change makes it possible to embed a notebook as an output in another notebook. The embedded notebook is rendered as a `vstack` of its non-None outputs, and is reactive with respect to UI element value updates.
This lets you make a more complex notebook out of smaller building-block notebooks.
Enhancements left for the future:
1. Multiple levels of composition. Right now, reactivity wrt to UI elements only allows for 1 level of nesting.
2. API for passing references to the app, or for otherwise injecting/overriding args into the embedded app.
> feat: app comp

- frontend/src/components/dependency-graph/panels.tsx
- frontend/src/components/editor/chrome/panels/datasources-panel.tsx
- frontend/src/core/pyodide/bridge.ts
This gets emitted in WASM, but rather than throwing an error, we should just ignore it
> fix: ignore not implmented sync-cell-ids

- frontend/src/components/editor/output/MarimoErrorOutput.tsx
- marimo/_messaging/errors.py
- marimo/_runtime/dataflow.py
- marimo/_runtime/runner/cell_runner.py
- marimo/_runtime/runtime.py
- tests/_runtime/test_runtime.py
fix: If a cell references a variable that no other cell potentially produces, strict mode is supposed to create an error.
A small bug in `transitive_references` (dataflow.py) stopped the expected behavior from happening, but then I realized the error UI was slightly wrong (MarimoErrorOutput.tsx, cell_runner.py, errors.py).
So, I added a unit test (test_runtime.py), and realized that Strict Errors should probably be promoted to kernel level errors (runtime.py).
Your PR will be reviewed more quickly if you can figure out the right person to tag with @ -->
> fix: strict execution single cell reference error

- marimo/_data/series.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/from_series.py
- tests/_data/test_series.py
- tests/_plugins/ui/_impl/test_input.py
Add `.from_series` to many mo.ui inputs.
```python
number = mo.ui.number.from_series(df["column_name"])
slider = mo.ui.slider.from_series(df["column_name"])
range_slider = mo.ui.range_slider.from_series(df["column_name"])
radiogroup = mo.ui.radio.from_series(df["column_name"])
dropdown = mo.ui.dropdown.from_series(df["column_name"])
multiselect = mo.ui.multiselect.from_series(df["column_name"])
date = mo.ui.date.from_series(df["column_name"])
```
> improvement: add .from_series to many mo.ui inputs

- pyproject.toml
It was incompatible with awscli. Fixes #1693
> fix: loosen docutils lower bound

- docs/api/inputs/anywidget.md
- marimo/_plugins/ui/_impl/from_anywidget.py
- tests/_plugins/ui/_impl/test_anywidget.py
This allows you to access attributes directly on the original widget
```python
from drawdata import ScatterWidget
scatter = ScatterWidget()
scatter = mo.ui.anywidget(scatter)
scatter.value
scatter.data_as_pandas
scatter.data_as_polars
```
> improvement: proxy attributes for `mo.ui.anywidget`

- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/filters.ts
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/tables/default_table.py
- marimo/_plugins/ui/_impl/tables/df_protocol_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_plugins/ui/_impl/tables/pyarrow_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_smoke_tests/bugs/1689.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/utils/test_dataframe_utils.py
Fixes #1689 
This cleans up some weird logic I had earlier with passing down row headers. Now instead I just pass down which column names are the row headers and just include the index columns in the csv when using pandas.
> fix: cleanup row headers logic, so its included in sorts

- frontend/src/components/data-table/chart-spec-model.tsx
- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/filters.ts
- frontend/src/components/data-table/types.ts
- frontend/src/components/editor/chrome/panels/datasources-panel.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- frontend/src/plugins/impl/data-frames/types.ts
- marimo/_data/get_datasets.py
- marimo/_data/models.py
- marimo/_data/preview_column.py
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/tables/df_protocol_table.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_plugins/ui/_impl/tables/pyarrow_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_plugins/ui/_impl/dataframes/test_dataframe.py
- tests/_plugins/ui/_impl/tables/test_df_protocol.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_plugins/ui/_impl/tables/test_pyarrow.py
- tests/_server/session/test_session_view.py
Add the external datatypes that come from pandas/arrow/polars. These don't conform to the same types or names, so they are just strings used as display. 
* adds it to the table dropdown
* adds it to the dataset sidebar
> improvement: add dtype to mo.ui.table and dataset sidebar

- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/column-wrapping/feature.ts
- frontend/src/components/data-table/column-wrapping/types.ts
- frontend/src/components/data-table/data-table.tsx
Adds column wrapping to the header. This is only frontend state rather than putting it in the python plugin.
> feat: add column wrapping

- marimo/_output/formatters/df_formatters.py
- marimo/_smoke_tests/bugs/1706.py
> fix: don't render dataframes in mo.ui.table if they contain nested datastructures

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/__tests__/utils.test.ts
- frontend/src/core/codemirror/language/markdown.ts
There are too many edge cases to handle with f-strings in markdown (latex, escaping rules, syntax highlighting). This change changes the markdown viewer to no longer parse f strings.
Closes #1727  #1684
> no f-strings in md viewer

- frontend/src/core/codemirror/cm.ts
The lint diagnostic keymap (ctrl-shift-m) interferes with the view as markdown keymap.
I don't think we use the functionality provided by the lint keymap anyway: https://codemirror.net/docs/ref/#lint.lintKeymap
Addresses an issue mentioned in #1737 (markdown keymap not working)
> disable lint keymap

- lsp/index.ts
On enabling Github copilot in a Marimo notebook, the LSP server tries to initialize the Copilot language server. The script to run has since changed, from "agent.js" to "language-server.js". 
Discord discussion - https://discord.com/channels/1059888774789730424/1258708018397184031
Changed name of the script. Similar change in Rstudio repo - https://github.com/rstudio/rstudio/pull/14808
> Change the copilot server script name

- marimo/_output/mpl.py
Update outdated import of `Gcf` in `mpl.py`
Fixes #1741 
This pull request addresses an outdated import statement in the `mpl.py` file located in `marimo\_output\mpl.py`. The current import of `Gcf` is from an obsolete location in the Matplotlib library.
Changes made:
- Updated the import statement for `Gcf` to reflect the current Matplotlib structure.
Before:
```python
from matplotlib.backend_bases import Gcf
```
After:
```python
from matplotlib._pylab_helpers import Gcf
```
This change aligns our code with the current Matplotlib implementation, as seen in their [backend_template.py](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/backend_template.py).
The update resolves potential compatibility issues or errors that could occur when using newer versions of …
> Update outdated import of Gcf in mpl.py

- docs/guides/apps.md
- frontend/src/components/editor/renderers/layout-select.tsx
- frontend/src/components/editor/renderers/plugins.ts
- frontend/src/components/editor/renderers/slides-layout/plugin.tsx
- frontend/src/components/editor/renderers/slides-layout/slides-layout.tsx
- frontend/src/components/editor/renderers/slides-layout/types.ts
- frontend/src/components/editor/renderers/types.ts
- frontend/src/components/slides/slides-component.tsx
- frontend/src/components/slides/slides.css
- frontend/src/plugins/layout/carousel/CarouselPlugin.tsx
- marimo/_smoke_tests/layouts/slides.slides.json
- marimo/_smoke_tests/slides.py
This PR adds Slides as a layout plugin. Code was fairly small given the abstractions of the `LayoutRenderer` and the already existing `mo.carousel` ui element. 
```
marimo run marimo/_smoke_tests/slides.py
marimo edit marimo/_smoke_tests/slides.py
```
> feat: slides

- README.md
- frontend/public/files/wasm-intro.py
- marimo/_tutorials/fileformat.py
- marimo/_tutorials/intro.py
- marimo/_utils/formatter.py
- marimo/_utils/health.py
- pyproject.toml
prioritize ruff over black in formatter, requirements, and documentation
as discussed in this [discord thread](https://discord.com/channels/1059888774789730424/1260236862862266564), changes were made to prioritize ruff over black.
- ecd1279fb85eee7c4bbfd9b4dbce79dbd4a17d12 `formatter.py` prefers ruff over black. warnings updated to reflect this.
- 7d01256a79af5c42016482973e4e504251ca101e ruff required instead of black
- a3747e22e58a9d17ee18a3cf8dd61a91633a9e20 readme and tutorials mention ruff instead of black
tested changes with environments ± ruff and ± black, and an editable install and custom ruff configuration.
`marimo/_utils/format_signature.py` and `frontend/src/core/pyodide/worker/worker.ts` not updated
@mscolnick
> feat: prioritize ruff over black in formatter, requirements, and documentation

- frontend/src/core/static/__tests__/files.test.ts
- frontend/src/core/static/files.ts
- frontend/src/plugins/impl/vega/vega-loader.ts
Fixes #1768
fix: patching vegaloader when rendering static content.
Was missing a `.bind` which fails for http calls and handle when it fails with for data-uris
> fix: patching vegaloader when rendering static content

- marimo/_plugins/ui/_impl/input.py
Small changes to update documentation of `marimo.ui.file_browser()`.
Fixes #1752 
In addition to the wrong name of the argument (that was `path` instead of `initial_path`), I noticed that the other examples were not accurate: `file_browser.value[index]` does not return the path of the selected file, but a `FileInfo` object. Given that its attributes are not so useful, I have proposed to give instead a second example using another dedicated method of the `file_browser` class.
> docs: fix example for marimo.ui.file_browser

- frontend/src/core/dom/events.ts
- frontend/src/core/dom/ui-element.ts
- frontend/src/core/dom/uiregistry.ts
- frontend/src/core/islands/main.ts
- frontend/src/core/kernel/RuntimeState.ts
- frontend/src/core/kernel/__tests__/RuntimeState.test.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
- frontend/src/plugins/core/registerReactComponent.tsx
- frontend/src/plugins/impl/DictPlugin.tsx
- frontend/src/plugins/impl/FormPlugin.tsx
- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- frontend/src/plugins/impl/anywidget/types.ts
- frontend/src/plugins/plugins.ts
- marimo/_cli/development/commands.py
- marimo/_messaging/ops.py
- marimo/_plugins/ui/_core/ui_element.py
- marimo/_plugins/ui/_impl/from_anywidget.py
- marimo/_smoke_tests/anywidget/maplibre.py
- marimo/_smoke_tests/anywidget/mosaic.py
- marimo/_smoke_tests/anywidget/weather.yaml
- marimo/_smoke_tests/bugs/1710.py
- marimo/_smoke_tests/bugs/1711.py
- marimo/_sql/sql.py
- marimo/_tutorials/sql.py
- openapi/api.yaml
- openapi/src/api.ts
This adds a new `MarimoIncomingMessageEvent` frontend UI element event and a backend `SendUIElementMessage` to allow the backend plugins/ui-elements to push messages to UI elements
Fixes #1690
> improvement: support AnyWidget.send, mosaic_widget example

- marimo/_cli/cli.py
- marimo/_server/asgi.py
- marimo/_server/main.py
- marimo/_server/start.py
Restrict CORS allowed origins to localhost. Can be overriden by a CLI flag.
> Restrict CORS allow origins to localhost; add CLI flag to specify allowed origins

- marimo/_runtime/executor.py
Came across these during my research, quick fix for common unclonable types
Strict mode should not clone _io objects or wrapped numpy objects by default
> Add Additional 'unclonables'

- frontend/src/core/codemirror/keymaps/keymaps.ts
- frontend/src/core/codemirror/keymaps/vim.ts
- frontend/src/css/common.css
This PR adds some hooks into the codemirror vim plugin to keep the vim-mode (normal, insert, visual) in sync with other editors. This includes a bit of hacks in order to get into the internal of the vim plugin. 
Fixes #915
> improvement: sync vim mode

- frontend/src/core/cells/__tests__/__snapshots__/cells.test.ts.snap
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cell.ts
When preparing to run a cell, register a cell as queued. This is only on the FE, and doesn't solve the deeper problem of deduping execution requests on the BE, but it does as a stopgap fix the problem in #1788 from the user's perspective.
We already clear its interrupted status, etc on run in the FE, so thought it could be okay to set the status too.
> fix: register cell as queued on run

- marimo/_runtime/requests.py
- marimo/_runtime/runtime.py
- marimo/_smoke_tests/bugs/1684.py
- tests/_runtime/test_runtime.py
This change updates the kernel to cancel queued execution requests on interrupt. This saves the user
from having to spam the interrupt button if they executed multiple cells manually.
> Cancel queued execution requests on interruption

- marimo/_plugins/ui/_core/ui_element.py
- marimo/_smoke_tests/bugs/1816.py
- tests/_plugins/ui/_impl/test_input.py
This PR fixes the logic for cloning composite UI elements to exclude the runtime context, which is not deep-clonable.
Fixes #1816
> fix: cloning UI elements

- frontend/src/components/ui/alert-dialog.tsx
- frontend/src/components/ui/context-menu.tsx
- frontend/src/components/ui/dialog.tsx
- frontend/src/components/ui/dropdown-menu.tsx
- frontend/src/components/ui/fullscreen.tsx
- frontend/src/components/ui/popover.tsx
- frontend/src/components/ui/select.tsx
- frontend/src/components/ui/sheet.tsx
This makes the fullscreen component the root of the portal when in fullscreenmode
> fix: portal menus when in fullscreen

- marimo/_runtime/packages/conda_package_manager.py
- marimo/_runtime/packages/package_manager.py
- marimo/_runtime/packages/pypi_package_manager.py
- marimo/_runtime/runtime.py
Fixes an issue that is related to #1736 (infinite loop when installing a package that doesn't have an importable module — found this when importing an empty package).  I am unsure if this fixes the problem in #1736, since that involved packages that should be importable.
> fix: dont autoinstall pkgs we already tried installing

- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/core/codemirror/extensions.ts
- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/commands.ts
- frontend/src/core/codemirror/language/markdown.ts
This allow converting any python to markdown, even if its not in the valid markdown syntax `mo.md(...)`
> improvement: always allow converting cell to markdown from python

- frontend/src/core/vscode/vscode-bindings.ts
Fixes copy/paste when marimo is embedded elsewhere
> fix: only initialize vscode bindings when url param is passed

- marimo/_output/formatting.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_server/api/endpoints/terminal.py
- marimo/_smoke_tests/polars/polars_to_csv.py
- tests/_plugins/ui/_impl/test_table.py
Refuse to show tables with > 100 columns as a heuristic to prevent the frontend from crashing.
Can handle this more gracefully in the future if needed.
Fixes #1846
> fix: dont show tables with many columns

- frontend/src/core/codemirror/language/__tests__/markdown.test.ts
- frontend/src/core/codemirror/language/__tests__/utils.test.ts
- frontend/src/core/codemirror/language/markdown.ts
- marimo/_smoke_tests/markdown_quotes.py
Fixes #1832
We now always force triple quote (in some cases we keep a single line; others we make it multi-line). This is so that single quotes (which can be more common) don't need to be escaped.
If the user wants triple-quotes not escaped, they will need to remove the `r-string` (which is the default to latex works properly) for a normal string or f-string.
> fix: always use triple quotes to prevent escaping single quotes

- frontend/src/plugins/impl/CodeEditorPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/bugs/1851.py
- marimo/_smoke_tests/markdown_quotes.py
Optional argument to impose a max height in pixels for ui.code_editor. The editor scrolls if height > max_height. This is useful for embedding code editors with a lot of code in slides.
> feat: max_height argument for ui.code_editor

- frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/components/terminal/terminal.tsx
- marimo/_server/api/endpoints/terminal.py
Handles writing `exit` in the terminal 
Fixes #1872
> fix: handle exit code in terminal, auto-close terminal

- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_smoke_tests/bugs/1851.py
- marimo/_smoke_tests/markdown_quotes.py
- tests/_runtime/test_runtime.py
This PR modifies the cell state machine to count the cell as "running" when output formatters are running.
Sometimes formatters can take a very long time — today, this happens when outputting a very large list or dict. Before this change, formatters that took a long time would lock the kernel without any UI indication in the frontend, making the notebook appear to be broken. 
This has the side-effect of making a formatter interruptible, which is helpful if the formatter is taking a very long time to run.
Re: lists/dicts formatting, we should probably lists/dicts/tuples when outputting very large ones, to avoid locking the kernel, but can handle that in another PR.
Draft because haven't tested thoroughly.
> Set status to idle after formatters run, not before

- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- frontend/src/plugins/impl/data-frames/types.ts
- frontend/src/plugins/impl/data-frames/utils/__tests__/operators.test.ts
- frontend/src/plugins/impl/data-frames/utils/operators.ts
- marimo/_smoke_tests/dataframe.py
When we added polars support, we moved away from numpy types and instead created our own types. So i accidentally regressed the filtering chooser. 
Fixes #1880
> fix: mo.ui.dataframe filtering

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/editor/output/JsonOutput.tsx
- frontend/src/components/editor/output/Outputs.css
- frontend/src/core/MarimoApp.tsx
- frontend/src/css/app/reset.css
- frontend/src/css/md.css
- frontend/src/css/table.css
- frontend/src/plugins/layout/AccordionPlugin.tsx
- frontend/tailwind.config.js
- marimo/_output/md.py
- marimo/_smoke_tests/markdown_size.py
- tests/_islands/snapshots/island-no-code.txt
- tests/_islands/snapshots/island.txt
- tests/_output/test_md.py
Cleanup markdown to allow for dynamic/responsive sizing across marging/padding/font-size/line-height by using `tailwind typography`.
Now we can easily add `size` to `mo.md()`.
In future we can size the whole document (by app config or user config)
> improvement: cleanup markdown, use prose

- frontend/src/components/data-table/data-table.tsx
- marimo/_smoke_tests/markdown_size.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
So NLP-ers and data scientists can see true underlying data.
Before this change, the two rows looked identical -- saw an NLP-er bang their head against this for a while (they incorrectly thought their data had dupes based on what they saw).
> fix: preserve whitespace in data table

- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
The vertical layout was missing spacing when code was shown.
> fix: cell spacing in run, html export

- frontend/src/components/pages/home-page.tsx
- frontend/src/utils/__tests__/path.test.ts
- frontend/src/utils/paths.ts
- marimo/_server/file_router.py
- tests/_server/test_file_router.py
Fixes a bug in which marimo edit /abs/path/ would fail to open notebooks due to incorrect slicing.
Fixes a bug in which marimo edit /abs/path/ or /abs/path would fail when run in a directory other than /abs/path
Fixes #1895.
> fix: marimo edit with absolute path to directory

- frontend/package.json
- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- frontend/src/plugins/impl/anywidget/types.ts
- marimo/_plugins/ui/_impl/from_anywidget.py
- marimo/_smoke_tests/quak-demo.py
Related to https://github.com/manzt/quak/issues/25
Sorry I probably won't have the time to test further but hopefully this is useful! Widgets can export and object or a function that returns a (promise) for an object with `initialize` and `render` [lifecycle hooks](https://anywidget.dev/blog/a-year-with-anywidget/#introducing-widget-lifecycle-hooks).
quak exports a default function (to intialize some initial state).
> feat: Support anywidget lifecycle hooks

- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/islands/worker/worker.tsx
- frontend/src/core/kernel/handlers.ts
- frontend/src/core/wasm/worker/bootstrap.ts
- frontend/src/core/wasm/worker/worker.ts
Add sql support to wasm. `pandas` and `duckdb` aren't loaded until the first `mo.sql` call
> feat: sql support in wasm

- marimo/_ast/visitor.py
- tests/_ast/test_visitor.py
broad exception catching, more granular exception checking.
Previously uncaught errors would lead to uncaught exceptions in codegen/saving.
> fix: unparsable sql cells shouldnt fail

- marimo/_plugins/stateless/tabs.py
This PR fixes incorrect notation in the UI component documentation (in docstrings - came across this when referring to the live docs in the siderbar panel in marimo itself). It removes misleading string keys and colons from the examples, ensuring that the documentation accurately reflects the proper usage of the framework's UI components.
Fixes #1915 
This pull request addresses a documentation error in our UI component usage examples. The current documentation incorrectly shows UI components being used with string keys and colons, which could lead to implementation errors and developer confusion.
```python
"slider": mo.ui.slider(1, 10),
"text": mo.ui.text(),
"date": mo.ui.date()
```
```python
mo.ui.slider(1, 10),
mo.ui.text(),
mo.ui.date()
```
> Fix `mo.ui.tabs` UI Component Documentation Example

- marimo/_output/formatters/plotly_formatters.py
Users are accustomed to plotly's default action being zoom.
mo.ui.plotly() still defaults to select.
> improvement: default stateless plotly plugin to zoom

- marimo/_output/formatters/formatters.py
- marimo/_output/formatters/tqdm_formatters.py
- marimo/_smoke_tests/tqdm_notebook.py
monkey patch tqdm.notebook, translating it to mo.status.progress_bar.
Will likely work for >90% of tqdm.notebook use cases, but won't work for power users since we don't support all of tqdm's options (we just drop unsupported options).
> support tqdm.notebook

- marimo/_plugins/ui/_impl/input.py
There is a stale override that sets `filetypes` always to None. This causes extension filtering not to work.
Removing the `self.filetypes = None` allows the set filetypes to propagate. Before this change, the if statement either throws an exception or it sets `filetypes` to None. Both outcomes are undesirable. Therefore, removing the override is the best way forward.
To reproduce:
The code below also shows files that don't have the extension "pdf". With this PR, it will hide other files.
```py
mo.ui.file_browser(
multiple=True,
selection_mode="file",
filetypes=[".pdf"],
)
```
> Fixed setting filetypes to None, causing the parameter not to work

- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_smoke_tests/bugs/1927.py
- marimo/_utils/flatten.py
- tests/_runtime/output/test_output.py
- tests/_utils/test_flatten.py
Fixes #1927 
Fixes recursive outputs.
Replaces `flatten` with `contains_instance` which is slightly cheaper and easier to test/follow
> fix: recursive outputs

- frontend/src/components/editor/Output.tsx
- frontend/src/core/MarimoApp.tsx
- frontend/tailwind.config.js
_doesnt need to be merged / open to discurss_
this adds a Fullscreen button to expand any output to fullscreen.
> improvement: fullscreen outputs

- marimo/_server/api/endpoints/execution.py
Fixes a bug in which shutting down a notebook opened from the file explorer would incorrectly shut down the whole server.
> fix: shutdown should only shutdown current notebook

- .github/workflows/test_cli.yaml
- tests/_cli/test_cli_export.py
- tests/conftest.py
The unit test `TestExportMarkdown::test_export_watch_script` should expect a .py file and convert it into a .md file, so the following line is incorrect:
https://github.com/marimo-team/marimo/blob/fd0f67b10963403a213eaeec4f605a943a7b0c47/tests/_cli/test_cli_export.py#L368-L369
The above unit test fails when runing `pytest tests/_cli/test_cli_export.py`. However, the test failure is not catched by CI because the test requires `pytest-asyncio` which is not installed: https://github.com/marimo-team/marimo/actions/runs/10220369751/job/28280651187#step:8:71
- Corrected the file extension in test `TestExportMarkdown::test_export_watch_script`
- Renamed the unit test functions in `TestExportMarkdown` from `script` to `markdown` (Looks like that most functions in `TestExportMarkdown` are copied …
> fix: unit test for markdown export

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/editor/output/JsonOutput.tsx
- frontend/src/components/editor/output/Outputs.css
- frontend/src/core/MarimoApp.tsx
- frontend/src/css/app/reset.css
- frontend/src/css/md.css
- frontend/src/css/table.css
- frontend/src/plugins/layout/AccordionPlugin.tsx
- frontend/tailwind.config.js
- marimo/_output/md.py
- marimo/_plugins/core/web_component.py
- tests/_islands/snapshots/island-no-code.txt
- tests/_islands/snapshots/island.txt
- tests/_output/test_md.py
This reverts commit 15fa75a7a4deaf98c905179f46ae454c7ab044d9.
Tailwind prose broke dark mode colors. This PR reverts the associated change so that dark mode users can enjoy the other new features and bug fixes in 0.7.14-0.7.16. We can bring it back when the styling bug is fixed (the revert was easy).
Fixes #1949
> Revert "improvement: cleanup markdown, use prose (#1892)"

- marimo/_cli/cli.py
- marimo/_cli/upgrade.py
- marimo/_utils/config/config.py
- tests/_cli/test_cli.py
Let `marimo edit` work under Internet-restricted environments by adding a `--skip-update-check` command-line argument, and a default update check timeout.
Fixes #1936.
PS: In issue #1936 I proposed adding a new configuration item, but I found it quite cumbersome. Doing it will require changing the backend, the frontend and even the public API. I think this feature doesn't worth such a big code change. The code is kept for reference in https://github.com/mutongx/marimo/commit/9a583e7ab71fa0fab3accd09f96a6afa2643a81d for anyone interested.
- Add `--skip-update-check` command-line argument to `marimo edit`
- Add a default timeout (which is 5 seconds) to update check's `urlopen()` call
- Support setting the `.marimo` configuration directory in unit test, so we can test on the update check …
> feat: support skipping update check in `marimo edit`

- marimo/_plugins/stateless/image.py
support paths starting with ~ or ~user
> fix: expand user for mo.image()

- docs/guides/outputs.md
document the md editor, and tell users how to switch back to `mo.md` to use f-strings.
> docs md editor

- docs/guides/sql.md
- frontend/src/components/editor/renderers/CellArray.tsx
- marimo/_messaging/ops.py
- marimo/_tutorials/sql.py
- pyproject.toml
Add an optional [sql] section to the pyproject.toml which enumerates our SQL dependencies with lower bounds, currently only `duckdb >= 1.0`.
Tell users to obtain SQL dependencies with pip install marimo[sql] instead of pip install duckdb, to ensure they get the correct versions.
Update the kernel capabilities check for SQL to check duckdb verison.
Fixes a bug in which we'd enable SQL support even though users were using incompatible versions of duckdb, causing the kernel to crash.
> fix: duckdb lowerbound

- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/controls/notebook-menu-dropdown.tsx
- frontend/src/components/editor/renderers/cells-renderer.tsx
- frontend/src/components/editor/renderers/layout-select.tsx
- frontend/src/components/editor/renderers/types.ts
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- frontend/src/components/shortcuts/renderShortcut.tsx
- frontend/src/core/constants.ts
- frontend/src/core/edit-app.tsx
- frontend/src/core/kernel/session.ts
- frontend/src/core/layout/useTogglePresenting.ts
- frontend/src/core/network/auth.ts
- frontend/src/core/vscode/vscode-bindings.ts
- frontend/src/core/websocket/__tests__/createWsUrl.test.ts
- frontend/src/core/websocket/createWsUrl.ts
* add Presentation toggling to menu dropdown
* if we are currently in 'edit' mode, it will toggle to 'present' mode before changing the layout type
* by adding it to the notebook dropdown, it also gets added to the Command Palette
* allow forcing slides by URL query param. e.g. https://marimo.app/?slug=14ovyr8&mode=run&view-as=slides (only works once this lands)
* DRY up some query param strings through the codebase, with docs
> improvement: add Presentation toggling to menu dropdown, allow forcing slides by URL query param

- frontend/src/components/editor/cell/useSplitCell.tsx
- frontend/src/core/cells/cells.ts
Follow up to #2018 that addresses an edge case. 
Originally, split cell undo was done by triggering an undo in the original cell. However, if the user were to split a cell, edit the original cell, and then undo the split cell, this would not undo the cell action correctly.
In `useSplitCellCallback`, save the original cell's code in a variable before cell split, and then pass it to `undoSplitCell()` if the user undoes the split.
@mscolnick
> fix: Undo split cell with code snapshot

- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- tests/_plugins/ui/_impl/test_table.py
1. Add a hard-coded row count upper limit on table's column summaries feature.
2. Update column summaries after changing search/filter criteria
3. Fix the inconsistency of table filtering and row count limiting
4. Some code reorganization
Fixes #1979.
Fixes #2016.
- Add a `is_disabled` field to `ColumnSummaries` so it can indicate itself being disabled
- I tried to use exceptions, but I found Function objects only propagates human-readable error messages. So it's unfeasible.
- Add a hard-coded 1,000,000 row count limit to the column summaries feature
- marimo already imposes a column count limit, so I think limiting only rows here should be OK for most situations
- Make column summaries react to filter/search criteria changes, so the summaries gets updated after such operations
- Separate …
> fix(mo.ui.table): implement row count limit on column summaries; various bug fixes

- marimo/_cli/development/commands.py
- marimo/_dependencies/dependencies.py
- marimo/_smoke_tests/quak-demo.py
Just an experimental util behind the `marimo development` CLI. 
This automatically adds the inline package metadata per PEP 723 using `uv`.
> development: marimo development inline-packages

- marimo/_cli/cli.py
- marimo/_cli/upgrade.py
- marimo/_config/settings.py
- marimo/_server/api/endpoints/ws.py
- marimo/_tutorials/plots.py
- tests/_cli/test_upgrade.py
For users who don't look at their terminal (or use vscode), this will toast the status update once per-marimo startup.
Later we can add a small indicator to the UI for future sessions.
> improvement: toast user for new marimo versions

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/codemirror/__tests__/setup.test.ts
- frontend/src/core/codemirror/language/__tests__/extension.test.ts
- frontend/src/core/codemirror/language/__tests__/utils.test.ts
- frontend/src/core/config/__tests__/config-schema.test.ts
- frontend/src/core/config/config-schema.ts
- frontend/src/core/network/api.ts
- frontend/src/css/md.css
- frontend/src/stories/editor.stories.tsx
- marimo/_ast/app.py
- marimo/_config/config.py
- marimo/_config/settings.py
- marimo/_output/formatters/df_formatters.py
- marimo/_output/formatters/pandas_formatters.py
- marimo/_plugins/ui/_impl/anywidget/comm.py
- marimo/_plugins/ui/_impl/anywidget/init.py
- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/context/script_context.py
- marimo/_runtime/context/types.py
- marimo/_runtime/runtime.py
- marimo/_smoke_tests/bugs/2070-latex-slides.py
- marimo/_smoke_tests/quak-demo.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_server/templates/snapshots/export1.txt
- tests/_server/templates/snapshots/export2.txt
- tests/_server/templates/snapshots/export3.txt
Fixes #2065, letting users default to the plain dataframe viewer (ie an HTML table).
> feat: user config for dataframe viewer

- docs/api/inputs/dropdown.md
I had to read the docs like 8 times to figure out what `selected_key` does, at first I thought it was a vestigal name for `value`. So here is an update to the interactive example (so cool) that shows off more features.
Also the name `value` for the argument to pick the default choice of the dropdown takes the key from the options dict, so the name is misleading.
> Update dropdown.md to show of dict options and selected_key

- .github/workflows/test.yaml
- development_docs/traces.md
- marimo/_cli/upgrade.py
- marimo/_config/settings.py
- marimo/_dependencies/dependencies.py
- marimo/_plugins/ui/_impl/anywidget/comm.py
- marimo/_plugins/ui/_impl/anywidget/init.py
- marimo/_runtime/runner/hooks_on_finish.py
- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_runtime/runner/hooks_pre_execution.py
- marimo/_runtime/runner/hooks_preparation.py
- marimo/_runtime/runtime.py
- marimo/_server/api/middleware.py
- marimo/_server/main.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/bugs/2070-latex-slides.py
- marimo/_smoke_tests/quak-demo.py
- marimo/_tracer.py
- pyproject.toml
- scripts/analyze_traces.py
- tests/_runtime/test_runtime.py
- tests/_runtime/test_virtual_file.py
- tests/_server/api/test_auth.py
This adds local-only open telemetry that gets output `~/.marimo/traces/traces.jsonl` that can be later analyzed. This should help debug slow parts of marimo when working with users.
> chore: add internal tracing for debugging

- marimo/_output/formatters/formatters.py
- marimo/_output/formatters/lets_plot_formatters.py
Register formatters for 'plot' objects produced by the Lets-Plot plotting library: https://lets-plot.org
Added `LetsPlotFormatter` class (marimo/_output/formatters/lets_plot_formatters.py) implementing formatters associated with the 'lets_plot' package.
Demo code:
```
import numpy as np
from lets_plot import ggplot, geom_point, aes, gggrid, ggsize, geom_livemap
x = np.random.rand(100)
y = 2 * x + 1 + np.random.normal(0, 0.1, 100)
data = dict(x = x, y = y)
p = ggplot(data) + geom_point(aes('x', 'y'))
p
---------
gggrid([p, p]) + ggsize(1000, 300)
---------
ggplot() + geom_livemap()
```
- [ x] I have run the code and verified that it works as expected.
> Add formatter for lets-plot figures.

- marimo/_messaging/completion_option.py
Small fix for something that a few users have mentioned.
> fix: don't include trailing quotes in completions

- marimo/_cli/cli.py
- marimo/_config/settings.py
- marimo/_loggers.py
- marimo/_runtime/runtime.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/tooltips.py
can't rely on fork() process start, reinitialize log level
> fix: macOS logging

- marimo/_cli/config/commands.py
- marimo/_utils/config/config.py
- pyproject.toml
- tests/_cli/test_cli.py
We don't install tomlkit when running under wasm (and don't need to). This was breaking marimo wasm.
> fix: don't import tomlkit top-level

- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/altair/altair_charts.py
- marimo/_smoke_tests/altair/altair_polars.py
- pyproject.toml
- tests/_plugins/ui/_impl/test_altair_chart.py
Fixes #2107 
Allow using just polars in `mo.ui.altair_chart`. 
Altair does support many other dataframes (via [narwhals](https://github.com/narwhals-dev/narwhals)), so we could theoretically add more, but we would need to support filter. We can fix this overtime per requests/feedback.
> improvement: support polars filtering in altair

- .github/workflows/release.yml
Add mac support.
Linux works: `docker run -p 8080:8080 -it ghcr.io/marimo-team/marimo:latest-sql`
> fix: publish docker containers for arm64 (mac compat)

- frontend/src/components/editor/header/filename-input.css
- frontend/src/components/pages/home-page.tsx
- frontend/src/components/ui/toast.tsx
- frontend/src/css/app/Cell.css
- frontend/src/css/app/codemirror.css
- frontend/src/css/globals.css
- frontend/src/plugins/impl/common/error-banner.tsx
- frontend/src/stories/colors.stories.tsx
- frontend/tailwind.config.js
Reduces some of the extra variables for shadows. They can be more easily created by overriding the colors. 
Can view "Shadows" and "Cell" states here: https://marimo-storybook-git-ms-consolidate-shadows-marimo.vercel.app/
> fix: consolidate shadows to be easily overriden

- marimo/_cli/cli.py
- marimo/_cli/sandbox.py
- tests/_cli/test_cli.py
- tests/_cli/test_sandbox.py
🎉  This _might_ be the first Python notebook with package reproducibility, down to the packages (versions to come soon)
This adds:
```
marimo edit --sandbox nb.py
marimo run --sandbox nb.py
```
Both commands grab the dependencies from the script, if it exists following PEP 723.
This builds on the shoulders of giants (`uv`) for their new `--isolated` feature. It roughly gets translated to:
```
uv run --isolated --with-requirements /var/folders/tmp/tmpvn.txt marimo edit nb.py
```
> feat: marimo edit --sandbox nb.py

- docs/guides/editor_features/ai_completion.md
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/config/config-schema.ts
- frontend/src/core/config/config.ts
- marimo/_config/config.py
- marimo/_server/api/endpoints/ai.py
- openapi/api.yaml
- openapi/src/api.ts
- pyproject.toml
- tests/_server/api/endpoints/test_ai.py
Fixes #2141 
This adds Claude (anthropic) support:
-----------
To use Anthropic with marimo:
1. Sign up for an account at [Anthropic](https://console.anthropic.com/) and grab your [Anthropic Key](https://console.anthropic.com/settings/keys).
2. Add the following to your `~/.marimo.toml`:
```toml
[ai.open_ai]
model = "claude-3-5-sonnet-20240620"
[ai.anthropic]
api_key = "sk-..."
```
> feat: add anthropic support

- marimo/_islands/island_generator.py
- tests/_islands/snapshots/header.txt
HTML generated with `MarimoIslandGenerator.from_file().render_html()` was failing to render because the frontend expects marimo-filename and marimo-mode tags to be present.
> fix: islands render_html() head needs marimo tags

- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/components/data-table/pagination.tsx
- frontend/src/components/scratchpad/scratchpad.tsx
In the DataTablePagination component, the rendering of page options was improved to prevent browser hanging when there are a large number of pages. Now, only the first 10 pages, the middle 10 pages, and the last 10 pages are shown, with ellipsis indicating the skipped pages.
> fix: fix browser freezing when rendering large dataframes

- marimo/_ast/sql_visitor.py
- marimo/_runtime/runtime.py
- tests/_ast/test_sql_visitor.py
The code changes in `sql_visitor.py` handle the case where SQL statements have escaped table names. This is done by checking if the statement starts with `e'` and adjusting the start and end indices accordingly. This ensures that the correct table name is extracted.
> fix: handle escaped table names in SQL statements

- marimo/_tutorials/markdown_format.md
> improve: md format tutorial

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/editor/ai/add-cell-with-ai.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/core/codemirror/language/sql.ts
- frontend/src/css/app/codemirror.css
- marimo/_server/ai/prompts.py
- marimo/_server/api/endpoints/ai.py
- marimo/_server/models/completion.py
- marimo/_smoke_tests/dataframe.py
- tests/_server/ai/snapshots/system_prompts.txt
- tests/_server/ai/snapshots/user_prompts.txt
- tests/_server/ai/test_prompts.py
Uses our existing datasources/tables infrastructure to allow for @ mentions for any dataframe or sql table when using AI assist. 
Also allows prompting for SQL.
Also cleans up some logic for prompting with snapshots 
https://github.com/user-attachments/assets/fca7c7ee-9653-4426-b3fd-c73d06c05f4c
> feat: Add support for @ mentions of dataframes and sql tables in AI assistant

- frontend/index.html
- marimo/_server/api/endpoints/assets.py
- marimo/_server/templates/templates.py
- marimo/_smoke_tests/theming/custom_css.py
- tests/_server/api/endpoints/test_assets.py
- tests/_server/templates/test_templates.py
Fixes #2172 
Custom css works on `marimo edit nb.py` but not `marimo edit`. This fixes this by not requesting custom css and instead inlining it.
> fix: embed custom.css directly in index.html

- README.md
- docs/index.md
Add some links, sync with docs
> readme touchup

- marimo/_dependencies/dependencies.py
- marimo/_output/formatters/holoviews_formatters.py
Verifies that plotly or bokeh is installed when using holoviews
Fixes #2198 
Importing `holoviews` was failing of plotly or bokeh was not installed. 
In holoviews formatter, only apply theme for plotly or bokeh when they are installed.
It also adds bokeh in `DependencyManager`
@mscolnick
> fix: do not require plotly or bokeh when holoviews is used

- marimo/_server/file_manager.py
- marimo/_server/files/os_file_system.py
- tests/_server/test_file_manager.py
Allows users to create files in subdirectories that don't yet exist by creating them; previously, this failed in an unintuitive way.
> fix: file handling when directory does not exist

- marimo/_ast/codegen.py
- tests/_ast/codegen_data/test_generate_filecontents_empty_with_config.py
- tests/_ast/test_codegen.py
Escape backslashes in app config strings.
Fixes #2202
> fix: allow backslashes in app config (file format)

- marimo/_cli/cli.py
- marimo/_cli/sandbox.py
Forward Ctrl-C to marimo subprocess instead of aborting, so user can confirm if they really want to quit.
Also adds --sandbox to marimo new.
> fix: sandbox graceful termination

- frontend/src/components/editor/chrome/wrapper/sidebar.tsx
- frontend/src/css/md.css
- marimo/_smoke_tests/bugs/2216-accordions.py
- marimo/_smoke_tests/datasources.py
Fixes #2217
Fixes #2216
Unset the max-width for buttons that is added by `.prose`
Small drive-by to add a tooltip to the running cell's indicator
> fix: accordion max-width styling

- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_smoke_tests/tables/pandas_nan.py
Pandas doesn't like it when you take the median of an empty column
> chore: workaround runtime warning in pandas table column summary

- .github/workflows/playwright.yml
- .github/workflows/test_be.yaml
- .github/workflows/test_cli.yaml
- .github/workflows/test_fe.yaml
- .github/workflows/test_typos.yaml
split up test workflow so they only run when changed
> chore: split up test workflow so they only run when changed

- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
Total rows is 0 for empty tables, not too_many. Previously empty tables showed a results clipped warning on the frontend.
> fix: empty tables total rows

- frontend/src/components/slides/slides-component.tsx
- frontend/tailwind.config.js
- marimo/_plugins/core/web_component.py
- marimo/_smoke_tests/slides.py
Add `prose-slides` to make all typography elements larger. 
This should help with #2125 
Some ui elements are harder to override and may need another pass:
- accordion 
- tabs
> improvement: add typoegraphy setting for slides

- frontend/src/core/codemirror/copilot/extension.ts
- frontend/src/core/codemirror/copilot/language-server.ts
- frontend/src/core/codemirror/copilot/types.ts
This actually fixes the stale requests. When comparing the version, it was always `0` since we werent using `this.documentVersion`
> fix: actually fix copilot stale requests

- marimo/_runtime/runtime.py
Lazy execution is an edit mode concept
> fix: kernel should never be lazy in run mode

- frontend/src/core/codemirror/cells/extensions.ts
- frontend/src/core/codemirror/copilot/extension.ts
- frontend/src/core/codemirror/extensions.ts
I think this fixes #2246 
* dont auto-run markdown on mount
* dont auto-scroll unfocused cells
`EditorView.updateListener` is gets called more than you'd link. this has better logic for ignoring
> fix: dont auto-run markdown on mount, dont auto-scroll unfocused cells

- frontend/src/components/data-table/data-table.tsx
- frontend/src/components/editor/file-tree/renderers.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- fix pagination and sort in csv viewer in the file-explorer panel
- reset pagination state whenever the total rows changes or pageSize changes (go back to the first page)
> fix: pagination and sort in csv viewer in the file-explorer panel

- marimo/_dependencies/dependencies.py
- marimo/_output/formatters/formatters.py
- marimo/_output/formatters/sympy_formatters.py
- pyproject.toml
- tests/_output/formatters/test_sympy.py
Adds SymPy expression rendering support, with output similar to Jupyter's notebooks. Fixes #1412 
An analog to Jupyter lab pretty-printing of sympy expressions is missing from marimo. This code aims to solve that problem.
The codes adds an output formatter that applies a patch to Sympy `Printable` base class. This class is used in all the sympy printable expressions. The code  adds a `__mime__` attribute to the `Printable` with a function pointing to the sympy -> html marimo md formatter.
@mscolnick
> Adds SymPy expression rendering support (#1412)

- marimo/_dependencies/dependencies.py
- marimo/_plugins/ui/_impl/tables/utils.py
- tests/_dependencies/test_dependencies.py
This change adds an `imported()` method to the DependencyManager that checks whether a module has been imported, and updates the broadcast-datasets codepath to use this check instead of DependencyManager.has().
Previously, running an arbitrary line of code (eg import marimo as mo) could take 10+ seconds, as our table libraries (such as pandas) were all being eagerly imported in order to check if a variable was of a table type. Instead, this change only does the import and instance check if the module has already been imported, which should be the case if an instance of it is in memory.
With this change, import marimo as mo takes just ms.
The bottleneck was discovered with cProfile using the --profile-dir development CLI arg:
```
marimo edit --profile-dir profiles/ notebook.py
```
> perf: lazy imports when checking for datasets

- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/data-table.tsx
- frontend/src/components/data-table/pagination.tsx
- frontend/src/core/codemirror/go-to-definition/underline.ts
- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_smoke_tests/_polars/polars_to_csv.py
- marimo/_smoke_tests/datasources.py
- tests/_runtime/test_runtime.py
Fixes #2221
* This shows the dtype in the table without having to click the dropdown. 
* Updates some styles and padding of the header to be aligned with its contents
* Fixes a small bug where if you do a screenshot, the Go-to-definition underline is still active
* Shows num columns in the footer
> improvement: show dtype and column count in table

- marimo/_sql/sql.py
- pyproject.toml
`duckdb`s scanning must have changed in 1.1.0 such that we need to augment the default `globals()` with the notebook `globals()`. this feels more correct, but I am unsure why this worked previously. 
Fixes #2277 #2272
> fix: support duckdb 1.1.0, update globals() for scanning

- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
This removes any markdown code editors from the UI if its just pure markdown. This should clean up HTML exports without any loss of information. 
This does not apply to interpolated markdown (`f-strings`)
> improvement: hide pure markdown code in html export

- frontend/src/components/editor/actions/types.ts
- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/controls/notebook-menu-dropdown.tsx
- frontend/src/components/ui/menu-items.tsx
- frontend/src/core/edit-app.tsx
- frontend/src/core/export/hooks.ts
- frontend/src/core/export/state.ts
- frontend/src/core/islands/bridge.ts
- frontend/src/core/network/requests-network.ts
- frontend/src/core/network/requests-static.ts
- frontend/src/core/network/requests-toasting.ts
- frontend/src/core/network/requests.ts
- frontend/src/core/network/types.ts
- frontend/src/core/wasm/bridge.ts
- frontend/src/hooks/useInterval.ts
- marimo/_server/api/endpoints/export.py
- marimo/_server/api/status.py
- marimo/_server/export/exporter.py
- marimo/_server/session/session_view.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_server/api/endpoints/test_export.py
- tests/_server/mocks.py
- tests/_server/session/test_session_view.py
This adds a new notebook action to turn on "Auto-export to markdown/html" which does so every 5 seconds **only if there are changes**.
cc @patrick-kidger - I figure you might be the first to want to try this. Once this releases, and if you do try it, could you give us some feedback on the ergonomics. I'd like to figure out if it should be per session (as it is today), CLI arg, User Config, App Config, etc.
> feat: add Auto-export to markdown or html from the marimo editor

- frontend/src/components/data-table/chart-spec-model.tsx
- marimo/_smoke_tests/tables/booleans.py
Pandas serializes to `True` (unlike polars)
> fix: boolean charts in table headers for pandas 

- marimo/_plugins/ui/_impl/dataframes/transforms/handlers.py
- tests/_plugins/ui/_impl/dataframes/test_handlers.py
- tests/_plugins/ui/_impl/test_table.py
Fixes #2299 
Pandas decides to not filter null items, so this fixes the defaults
> fix: pandas filtering for string n/a

- marimo/_output/formatting.py
- tests/_output/formatters/test_formatters.py
`_repr_*_` is allowed to return null, so we should fallback to another `_repr_*_`
> improvement: handle fallback _repr_mime_ in formatters

- .github/workflows/test_be.yaml
- marimo/_output/formatters/altair_formatters.py
- marimo/_smoke_tests/altair/embed_options.py
- tests/_output/formatters/test_altair.py
Fixes #2302 
User's can set `embed_options` globally with altair. However these embedoptions were missing from the final chart spec.
I am surprised this is not handled by altair internally, but we can handle this ourselves.
> fix: handle altair usermeta embed_options manually

- docs/guides/editor_features/package_management.md
- frontend/src/components/app-config/user-config-form.tsx
- frontend/src/core/config/__tests__/config-schema.test.ts
- frontend/src/core/config/config-schema.ts
- marimo/_cli/sandbox.py
- marimo/_config/config.py
- marimo/_config/settings.py
- marimo/_pyodide/bootstrap.py
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/runtime.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_config/test_config.py
- tests/_runtime/test_manage_script_metadata.py
- tests/_server/templates/snapshots/export1.txt
- tests/_server/templates/snapshots/export2.txt
- tests/_server/templates/snapshots/export3.txt
- tests/_server/templates/snapshots/export4.txt
This removes the config `add_script_metadata` and just auto-adds it whenever we do `--sandbox`
> improvement: simplify inline metadata config, turn on only in --sandbox

- frontend/src/components/editor/actions/useCopyNotebook.tsx
Use the destination path to open the new notebook copy, not its filename. Small fix for #2307. 🙂
In `useNotebookCopy.tsx`, the `destination` variable was set to the new copy's filename, not the full file path.
@akshayka
> fix: Open destination path on notebook copy

- frontend/src/plugins/impl/FileBrowserPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
fixes various bugs in ui.file_browser that all arose from the assumption that the initial path was an absolute path.
> fix: ui.file_browser() abs paths

- openapi/api.yaml
- openapi/src/api.ts
- tests/_cli/test_cli_development.py
Tests to check that marimo's backend is up-to-date with the open-api schema (minus the version)
> tests: check schema drift from openapi schema

- frontend/src/core/codemirror/language/__tests__/sql.test.ts
- frontend/src/core/codemirror/language/panel.tsx
- frontend/src/core/codemirror/language/sql.ts
- marimo/_sql/sql.py
- tests/_sql/test_sql.py
Fixes #2266
Adds "Hide output" to the sql. This serializes to `mo.sql("...", output=False)`
Note: Since this changes the code, it does mark the cell as stale, instead of actually hiding the output at the time. 
We could auto-run this cell afterwards, but that could create undesirable.
> improvement: Add "Hide outputs" to sql cells

- frontend/src/components/data-table/__test__/chart-spec-model.test.ts
- frontend/src/components/data-table/chart-spec-model.tsx
- marimo/_smoke_tests/bugs/2315.py
Fixes #2315
per https://github.com/vega/altair/blob/32990a597af7c09586904f40b3f5e6787f752fa5/doc/user_guide/encodings/index.rst#escaping-special-characters-in-column-names
> fix: vega charts with special characters

- frontend/src/plugins/core/registerReactComponent.tsx
- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- frontend/src/utils/__tests__/shallow-compare.test.ts
- frontend/src/utils/shallow-compare.ts
This commit optimizes setting state by plugins by using a newly added shallowCompare utility function. This helps improve performance by avoiding unnecessary rerenders when the value hasn't really changed.
> improvement: prevent uncessary rerenders in plugins

- frontend/src/components/icons/large-spinner.tsx
- frontend/src/core/wasm/PyodideLoader.tsx
- frontend/src/core/wasm/bridge.ts
- frontend/src/core/wasm/state.ts
- frontend/src/core/wasm/worker/bootstrap.ts
- frontend/src/core/wasm/worker/worker.ts
- frontend/src/utils/urls.ts
- show ongoing messages as pyodide loads
- if we are not showing the code cells, keep showing the loading indicator until _some_ output is shown
- don't initialize the save-rpc webworker when running in read mode
> improvement: better loading indicator while pyodide is bootstrapping

- frontend/src/components/ui/input.tsx
- frontend/src/components/ui/textarea.tsx
- frontend/src/plugins/impl/TextAreaPlugin.tsx
- frontend/src/plugins/impl/TextInputPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
- marimo/_smoke_tests/debounce_input.py
Debounce `mo.ui.text` and `mo.ui.text_area` either until Enter is pressed (or Ctrl+Enter for text area), or by a given number of milliseconds. Completes #2218.
- If `debounce === true`, then only emit values on Enter key down (Ctrl + Enter for text area)
- If `typeof debounce === "number"`, then delay emit by that value in milliseconds
- Both `mo.ui.text` and `mo.ui.text_area` have `debounce` set to `True` by default now
Feel free to check out the example notebook in the `_smoke_tests` directory. When `debounce === False`, noticed some flickering when the value from an input/textarea is printed in a different cell; may need to address in a separate issue.
> improvement: Debounce mo.ui.text and text_area

- marimo/_cli/sandbox.py
Without this change, running `marimo edit --sandbox notebook.py` in a directory with a pyproject.toml (such as the marimo repo itself) very often fails because the notebook's requirements conflict with the project's requirements, which defeats the purpose of "sandboxing" the notebook. This change makes the notebook actually self-contained.
> ignore project when running in a sandbox

- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- marimo/_messaging/ops.py
- marimo/_plugins/core/json_encoder.py
- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/ibis_table.py
- marimo/_plugins/ui/_impl/tables/polars_table.py
- marimo/_plugins/ui/_impl/tables/table_manager.py
- marimo/_plugins/ui/_impl/tables/utils.py
- marimo/_smoke_tests/tables/ibis_example.py
- marimo/_smoke_tests/tables/ibis_interactive.py
- marimo/_smoke_tests/tables/lazy.py
- marimo/_utils/memoize.py
- pyproject.toml
- tests/_plugins/ui/_impl/dataframes/test_dataframe.py
- tests/_plugins/ui/_impl/tables/snapshots/ibis.csv
- tests/_plugins/ui/_impl/tables/snapshots/ibis.field_types.json
- tests/_plugins/ui/_impl/tables/snapshots/ibis.json
- tests/_plugins/ui/_impl/tables/test_ibis_table.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_utils/test_memoize.py
This adds an `IbisTableManager` instead of using converting it to a a `PyArrowTableManager`, otherwise the ibis table is no longer lazy.
This also has a few fixes for `str(ibis)` which when interactive mode was enabled, would be very expensive
Also adds a `limit=` field to `mo.ui.dataframe`, which fixes #2269
> feat: support ibis native in mo.ui.table()

- marimo/_output/show_code.py
- tests/_output/test_show_code.py
- fix the regex for show code
- remove the position keyword argument; we weren't handling it correctly.
- more tests
This is a breaking change, but 0.8.16 has only been out for a few minutes, so it shouldn't affect anyone if we release soon.
> fix: show code should be greedy, remove position

- marimo/_runtime/output/_output.py
- tests/_plugins/stateless/status/test_progress.py
- tests/_runtime/output/test_output.py
This lets `mo.status.spinner` and `mo.state.progress` be used outside marimo, for example if you export to a pure script if you want to run something on it. This just noops the output updates
For example:
`marimo export script notebook.py -o notebook_test.py; python -m doctest notebook_test.py `
Unblocks https://github.com/marimo-team/marimo/issues/2191
> fix: allow mo.status.spinner and mo.state.progress to noop outside marimo

- marimo/_runtime/marimo_pdb.py
- marimo/_smoke_tests/doctests.py
Fixes #2191
Fixes the signature of `pdb` which unlocks
```python
import doctest; doctest.testmod()
```
Which will run doctests from marimo (and reactively if you reference the function), great for education!
```python
def euclid_mcd(a: int, b: int) -> int:
"""Return the MCD between positive a, b.
>>> euclid_mcd(42, 24)
6
>>> euclid_mcd(24, 42)
6
>>> euclid_mcd(42, 42)
42
"""
assert a > 0
assert b > 0
if a < b:
a, b = b, a
if (a != b):
r = a - b
return euclid_mcd(b, r)
return a
euclid_mcd
import doctest
failures, success = doctest.testmod(verbose=True)
mo.md(f"Success: {success}, Failures: {failures}")
```
> fix: support import doctest; doctest.testmod()

- marimo/_ast/codegen.py
- tests/_ast/codegen_data/test_generate_filecontents.py
- tests/_ast/codegen_data/test_generate_filecontents_async_long_signature.py
- tests/_ast/codegen_data/test_generate_filecontents_shadowed_builtin.py
- tests/_ast/codegen_data/test_generate_filecontents_single_cell.py
- tests/_ast/codegen_data/test_generate_filecontents_with_syntax_error.py
- tests/_ast/codegen_data/test_get_codes_messy.py
- tests/_ast/codegen_data/test_get_codes_multiline_fndef.py
- tests/_ast/codegen_data/test_get_codes_multiline_string.py
- tests/_ast/codegen_data/test_get_codes_single_line_fn.py
- tests/_ast/codegen_data/test_get_codes_with_incorrect_args_rets.py
- tests/_ast/codegen_data/test_long_line_in_main.py
- tests/_ast/codegen_data/test_main.py
- tests/_ast/test_codegen.py
- tests/_cli/snapshots/unsafe-app.py.txt
- tests/_server/test_file_manager.py
formats single-element tuples in return statements to match ruff/black to prevent unnecessary git diffs for ruff/black users
> chore: format tuple in return to match ruff/black

- marimo/_messaging/ops.py
- marimo/_plugins/core/json_encoder.py
- marimo/_plugins/ui/_impl/from_anywidget.py
- marimo/_pyodide/bootstrap.py
- marimo/_smoke_tests/bugs/2357-table-ui-elements.py
- tests/_plugins/core/test_json_encoder.py
`asdict` does not encode our UI elements properly and should be used sparingly
> fix: encoding table elements when passed through RPC calls

- marimo/_server/export/exporter.py
- marimo/_server/templates/templates.py
- tests/_server/templates/snapshots/export1.txt
- tests/_server/templates/snapshots/export2.txt
- tests/_server/templates/snapshots/export3.txt
- tests/_server/templates/snapshots/export4.txt
- tests/_server/templates/test_templates.py
Fixes #2346
Includes a 256 bit has regardless if the code is included, as a cache bust / integrity for the html export
> improvement: add hash to html export

- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- frontend/src/utils/__tests__/date-views.test.ts
- frontend/src/utils/date-views.ts
- marimo/_plugins/ui/_impl/from_anywidget.py
- marimo/_smoke_tests/bugs/2366-anywidget-binary.py
- tests/_plugins/ui/_impl/test_anywidget.py
> fix: handling of buffer paths in Anywidget

- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
A much simpler approach, and the previous way was not working with maps.
> fix: better plotly deselect

- frontend/src/components/editor/chrome/panels/outline/floating-outline.tsx
Hide floating outline if less than 2 items.
This is what Notion does too.
> fix: hide floating outline if less than 2 items

- marimo/_output/formatting.py
- marimo/_output/hypertext.py
- marimo/_plugins/stateless/style.py
- tests/_output/formatters/test_formatters.py
- tests/_output/test_hypertext.py
- tests/_plugins/stateless/test_style.py
Adds an additional UI to `mo.style()`:
```python
mo.style(item, styles={"max-height": "300px", "overflow": "auto"})
mo.style(item, max_height="300px", overflow="auto")
mo.md("...").style({"max-height": "300px", "overflow": "auto"})
mo.md("...").style(max_height="300px", overflow="auto")
```
> improvement: allow .style() to take kwargs, add tests

- frontend/src/components/editor/actions/types.ts
- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/controls/command-palette.tsx
- frontend/src/components/editor/controls/notebook-menu-dropdown.tsx
- frontend/src/components/shortcuts/renderShortcut.tsx
- marimo/_smoke_tests/third_party/plotly_example.py
Fixes #2376
Rather than trying to switch to app-view and waiting some time, we just disable the action and let the user do it. 
1. this is more correct / less error-prone
2. the user may want to set up the view a bit more before exporting (expanding accordions, setting a correct tab, etc)
> fix: disable pdf export while editing

- marimo/_runtime/runtime.py
- tests/_runtime/test_manage_script_metadata.py
There are cases where you want the requirement to be in the metadata even if the import is not in the notebook
> Don't remove packages when imports removed from notebook in sandbox

- frontend/src/components/data-table/columns.tsx
- frontend/src/components/editor/file-tree/renderers.tsx
- frontend/src/hooks/debug.ts
- frontend/src/plugins/impl/DataTablePlugin.tsx
- marimo/_smoke_tests/bugs/2327_table_staleness.py
- marimo/_smoke_tests/bugs/2403_table_ui_staleness.py
Fixes #2403
Fixes #2327
There is a subtle bug that when the table is not properly memoized, it can mount stale data when re-mounting. 
There is likely a better long-term fix as this can pop-up again unknowingly by not preventing re-renders, which I plan to look into in a followup.
> fix: staleness in mo.ui.table() when using UI elements

- marimo/_ast/visitor.py
- tests/_ast/test_compiler.py
- tests/_ast/test_visitor.py
- tests/_runtime/test_dataflow.py
- tests/_runtime/test_runtime.py
Came across a few notebooks that use plain `duckdb.sql` instead of `mo.sql`. We should still track the dependencies.
> improvement: track duckdb.sql and duckdb.execute SQL statements in dep graph

- marimo/_runtime/packages/conda_package_manager.py
- marimo/_runtime/packages/package_manager.py
- marimo/_runtime/packages/pypi_package_manager.py
- marimo/_runtime/runtime.py
- marimo/_server/api/endpoints/packages.py
Fixes #2425
Improve the warnings and better error handling when a user does not have the package manager installed.
> fix: don't allow install/uninstall if package manager doesn't exist, better warnings

- marimo/_server/start.py
- tests/_convert/test_convert_utils.py
Under uvloop, reading the socket we monitor under `add_reader()` occasionally throws BlockingIOError (errno 11), even though our socket is blocking and doesn't have a receive timeout
RUN mode no longer uses a socket (it has no IPC) but EDIT does, so this PR forces `asyncio` in `uvicorn`.
Not 100% sure the issue was due to `uvloop`, but did notice it in the stack trace in #1568, and also found a few similar issues (https://github.com/ipython/ipython/issues/12563).
Hopefully fixes the edit mode counterpart of #1568
> Force asyncio in edit mode

- marimo/_cli/cli.py
- marimo/_cli/sandbox.py
This PR adds a new option, `--skip-sandbox-prompt`, to prevent running a sandboxed notebook to forever prompt the user to run with sandbox.
> fix: in sandbox, skip sandbox prompt if possible

- marimo/_cli/sandbox.py
We need to pin since we pass args from one marimo CLI to another, and marimo CLI args may not be backwards/forwards compatible.
> fix: pin version to current marimo version in sandbox

- marimo/_runtime/packages/utils.py
- tests/_runtime/packages/test_package_utils.py
Allow fancier package installation rules like editable (`-e`) or `@`
> improvement: allow more package installation rules in the pkg management UI

- marimo/_ast/visitor.py
- tests/_runtime/test_runtime.py
Fixes a bug in which `as` imports weren't mangled, making it impossible to use modules imported as local variables.
> fix: mangle node.asname for imports

- frontend/package.json
- frontend/patches/react-plotly.js.patch
- frontend/pnpm-lock.yaml
- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
- marimo/_smoke_tests/bugs/2457-plotly-section.py
Fixes #2457
Support sunburst and treemap selection. react-plotly does not have a callback for treemap, so I had to add a patch. I will try to commit this upstream, so later remove the patch.
> improvement: support sunburst and treemap plotly selection

- docs/api/miscellaneous.md
- marimo/__init__.py
- marimo/_ast/app.py
- marimo/_runtime/app/script_runner.py
- marimo/_runtime/context/kernel_context.py
- marimo/_runtime/context/script_context.py
- marimo/_runtime/context/types.py
- marimo/_runtime/runtime.py
- marimo/_smoke_tests/nb_dir.py
- tests/_ast/test_app.py
- tests/_cli/test_cli_export.py
- tests/_runtime/test_runtime.py
This adds `mo.notebook_dir()` to get the directory the notebook is in. This is useful when you want to grab some file without a relative path. 
This is so running `marimo edit foo.py`, `marimo edit some/nested/dir/foo.py`, `python foo.py`, and `python some/nested/dir/foo.py` are all the same. 
This is not true for Jupyter as Jupyter will change the directory to the notebook directory which can cause problems when you want to use your notebook as a script
```python
data_file = mo.notebook_dir() / "data" / "example.csv"
if data_file.exists():
print(f"Found data file: {data_file}")
else:
print("No data file found")
```
> feat: add `mo.notebook_dir()`. avoid relative paths for better reproducibility

- .github/workflows/test_be.yaml
- marimo/_convert/ipynb.py
- marimo/_plugins/ui/_impl/batch.py
- marimo/_runtime/copy.py
- marimo/_runtime/primitives.py
- marimo/_runtime/runtime.py
- marimo/_server/api/lifespans.py
- marimo/_utils/paths.py
- pyproject.toml
- tests/_cli/test_file_path.py
- tests/_runtime/test_trace.py
This PR drops support for Python 3.8, which has reached its end-of-life.
> Remove 3.8 support

- docs/guides/exporting.md
- frontend/src/components/app-config/app-config-form.tsx
- marimo/_server/export/exporter.py
- tests/_server/api/endpoints/test_export.py
To be the same as where the cache is saved (caches are saved under `__marimo__/cache` and can be selectively git-ignored).
> Update AutoExporter directory to __marimo__

- docs/api/caching.md
- marimo/_save/save.py
Make mo.persistent_cache()'s save_path default to
`{notebook_dir} / __marimo__ / cache`
so that the cache works no matter from where `marimo edit` is invoked.
> Use notebook directory in persistent_cache

- docs/guides/integrating_with_marimo/displaying_objects.md
Let users know that we support IPython's `_repr_*_()_` protocol, to make it easier to integrate with marimo.
> Document support for IPython `_repr_*_()_` protocol

- marimo/_runtime/packages/pypi_package_manager.py
- tests/_runtime/packages/test_pypi_package_manager.py
fixes #2465
Pointers to runtime python executable were added:
1) pip:
- `pip --python {PY_EXE} install ...`
- `pip --python {PY_EXE} uninstall ...`
- `pip --python {PY_EXE} list`
For pip, the --python option must be placed before the pip subcommand name
2) uv:
- `uv pip install ... -p {PY_EXE} `
- `uv pip uninstall ... -p {PY_EXE} `
- `uv pip list -p {PY_EXE} `
UV allows -p/--python at the end.
> added python executable to pip and uv

- marimo/_runtime/runner/hooks_post_execution.py
- marimo/_runtime/state.py
- marimo/_save/cache.py
- marimo/_save/hash.py
- marimo/_save/save.py
- marimo/_tutorials/dataflow.py
- marimo/_tutorials/markdown.py
- marimo/_tutorials/plots.py
- tests/_cli/snapshots/dataflow.md.txt
- tests/_save/test_cache.py
- tests/_save/test_hash.py
This PR updates tutorials to use `mo.cache`, and fixes `mo.cache` to handle shadowed variables.
> fix: handle shadowed variables in mo.cache, update tutorials

- docs/api/inputs/chat.md
- examples/ai/chat/anthropic_example.py
- examples/ai/chat/openai_example.py
- frontend/src/plugins/impl/chat/ChatPlugin.tsx
- frontend/src/plugins/impl/chat/chat-ui.tsx
- frontend/src/plugins/impl/chat/types.ts
- marimo/_cli/file_path.py
- marimo/_plugins/ui/_impl/chat/chat.py
- marimo/_plugins/ui/_impl/chat/convert.py
- marimo/_plugins/ui/_impl/chat/types.py
- marimo/_plugins/ui/_impl/chat/utils.py
- tests/_plugins/ui/_impl/chat/test_chat_convert.py
Add opt-in support for file attachments.
You can opt in all attachment types or specific content-types.
> feat: attachment support in mo.ui.chat

- frontend/src/components/editor/cell/code/cell-editor.tsx
This PR improves the UX of working with hidden cells. When code is hidden, clicking on the eye icon will now temporarily show the code as long as the editor is focused, and hide it again once the editor is blurred.
In this way users can, for example, hide markdown code and later edit it without permanently unhiding it.
To permanently unhide code, users can use the cell action menu or the keyboard shortcut, as before.
This change is based on user feedback, and it also happens to match the behavior in Observable notebooks.
Interactions with changing the cell config to `show code` while temporarily focused still works, since the user must first click the cell action menu which blurs the editor.
> improve: temporarily show code

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/codemirror/language/__tests__/utils.test.ts
- frontend/src/core/codemirror/language/utils.ts
Implements #2474.
When a new cell is created, any highlighted code is cut from the original cell and pasted into the new cell.
> improve: Move highlighted code to newly created cells

- frontend/src/components/editor/cell/code/cell-editor.tsx
When re-hiding a cell, process blur on the parent of the editor view, not the editorview itself, so things like the delete button, language toggle, and codemirror folds are still clickable.
cc @wasimsandhu
> fix: hidden cell blur on parent, not editorview

- marimo/_plugins/core/json_encoder.py
- marimo/_smoke_tests/bugs/2506_anywidget_buffer_paths.py
- tests/_plugins/core/test_json_encoder.py
Fixes #2506
We failed to decode when bytes are not utf-8 decodable, so instead we should fallback to latin1 (for cases such as png).
> fix: json encoding of png binary

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/config/config.ts
- frontend/src/core/config/feature-flag.tsx
- marimo/_config/config.py
- marimo/_config/manager.py
- marimo/_config/utils.py
- marimo/_utils/dataclass_to_openapi.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_config/test_config.py
- tests/_config/test_manager.py
- tests/_utils/test_dataclass_to_openapi.py
Improve typings for `PartialMarimoConfig` and handle NotRequired from TypedDict
> fix: typings of marimo config, fix typedict to openapi cases

- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_plugins/ui/_impl/dates.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_plugins/ui/_impl/microphone.py
- marimo/_plugins/ui/_impl/plotly.py
- marimo/_plugins/ui/_impl/refresh.py
- marimo/_plugins/ui/_impl/run_button.py
- marimo/_plugins/ui/_impl/switch.py
- marimo/_plugins/ui/_impl/table.py
marimo expects labels to be markdown; update docstrings to make this explicit.
cc @fuenfundachtzig , thanks for the suggestion.
> improve: text label -> markdown label

- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
Fixes #2509.
Added `language: LanguageAdapterType` to `state.history`, and use this in `deleteCell` and `undoDeleteCell` handlers to bring back SQL/Markdown cells appropriately.
> fix: Preserve language in cell actions undo/redo stack

- frontend/src/components/editor/cell/toolbar.tsx
To avoid overlap with code editor text. Buttons now match the size of the `CreateCell` buttons.
> fix: slightly decrease cell toolbar size

- frontend/src/components/dependency-graph/dependency-graph-tree.tsx
- frontend/src/components/dependency-graph/panels.tsx
- frontend/src/core/cells/focus.ts
Fixes https://github.com/marimo-team/marimo/issues/2576
Add a control button to jump to the focused cell.
> improvement: add 'jump to focused cell' in the dependency viewer

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/plugins/impl/DataEditorPlugin.tsx
- frontend/src/plugins/impl/data-editor/data-editor.tsx
- frontend/src/plugins/impl/data-editor/grid.css
- frontend/src/plugins/plugins.ts
- marimo/_plugins/core/web_component.py
- marimo/_plugins/ui/__init__.py
- marimo/_plugins/ui/_impl/charts/altair_transformer.py
- marimo/_plugins/ui/_impl/data_editor.py
- marimo/_plugins/ui/_impl/table.py
- marimo/_plugins/ui/_impl/tables/utils.py
- marimo/_plugins/ui/_impl/utils/dataframe.py
- marimo/_smoke_tests/editable_df.py
- openapi/api.yaml
- openapi/src/api.ts
- pyproject.toml
- tests/_plugins/ui/_impl/test_altair_chart.py
- tests/_plugins/ui/_impl/test_data_editor.py
- tests/_plugins/ui/_impl/utils/test_dataframe_utils.py
This adds an experimental ui element for editing a dataframe, using `mo.ui.data_editor`.
* Add `mo.ui.data_editor` (BE plugin and FE plugin)
* This adds a dependency on `narwhals`. It's a lightweight library (no deps itself) and does a lot of what we try to roll ourselves, by creating a single dataframe interface. There is a lot of other code to clean up by depending on this. This library will also be better tested again more versions of polars/pandas/other-df-library
* We use `ag-grid` for the editing. It is missing key features that only exist in the enterprise that we will likely want and force us to move to something else. This includes: cell range selection, copy/paste ranges. I don't expect this future migration to change the API, only implementation details. I also don't expect the …
> experimental: mo.ui.data_editor

- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/utils.ts
This reverts commit 9a674dcb5900a4f4204cba548697b85c395b0c00.
The logic for temporarily showing code for markdown cells is incorrect and causing all hidden cells to not render as hidden.
We can fix and restore in a follow up
> Revert "improve: Hide code by default for Markdown cells (#2507)"

- examples/third_party/plotly/mapbox.py
- frontend/src/core/wasm/worker/bootstrap.ts
Add narwhals as a dependency to Pyodide, since we recently added it as a dependency to marimo.
> fix: install narwhals in pyodide bootstrap

- frontend/src/components/dependency-graph/dependency-graph-tree.tsx
- frontend/src/components/editor/Output.tsx
- frontend/src/components/editor/SortableCell.tsx
- frontend/src/components/editor/cell/CreateCellButton.tsx
- frontend/src/components/editor/cell/DeleteButton.tsx
- frontend/src/components/editor/cell/toolbar.tsx
- frontend/src/utils/events.ts
Fixes #2589
Prevent buttons from stealing focus;
This is used when we are focused in a code-editor, but don't want pressing a button to move focus to that button and instead stay in the code editor.
> fix: prevent more buttons from stealing focus

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/logs.ts
- frontend/src/core/mime.ts
* Don't show errors in run mode when re-running. This can happen when a cell errors (not shown yet) and then is re-running (is in a queued/running state) so we end up showing the error briefly.
* Since we do send these errors to the frontend anyways, I now log it to the console for developers.
> fix: don't show errors in run mode when re-running

- .github/workflows/dev-release-marimo-base.yml
This change adds a workflow that releases a marimo-base package to TestPyPI.
marimo-base is marimo without static artifacts, which are not needed when running on WASM.
Because Python build tools only allow one project per pyproject.toml, it is not possible to do this by adding a build rule to hatch. Instead, marimo-base is built by adapting the pyproject.toml in CI (this is what CVXPY does).
With this change, the wheel size is reduced from `15M` to `614k`.
> release marimo-base to test pypi

- frontend/src/components/editor/Cell.tsx
Because of auto-run in markdown, markdown completions got removed.
> fix: emoji popover in markdown

- docs/api/markdown.md
- frontend/src/core/codemirror/language/markdown.ts
- marimo/_output/md.py
- marimo/_output/md_extensions/iconify.py
- marimo/_smoke_tests/icons.py
- tests/_output/test_md.py
> feat: support iconfify icons in markdown with ::lucide:rocket:: syntax

- docs/guides/editor_features/hotkeys.md
- frontend/src/components/editor/chrome/wrapper/footer.tsx
- frontend/src/core/hotkeys/hotkeys.ts
Toggle terminal with Ctrl + ` just as in vscode. Completes #2608.
> improve: Keyboard shortcut to toggle terminal

- marimo/_plugins/core/json_encoder.py
- marimo/_plugins/ui/_impl/data_editor.py
- marimo/_smoke_tests/editable_df.py
- tests/_plugins/core/test_json_encoder.py
- tests/_plugins/ui/_impl/test_data_editor.py
Fixes #2617
Support date/datetime/duration conversion in the data-editor plugin. The frontend is still a string instead of a date-input, but this fixes backend support.
> fix: support dates in data-editor

- frontend/src/core/wasm/worker/bootstrap.ts
import pygments not Pygments
fixes broken handling of tracebacks on WASM
> fix: pyodide dependency

- marimo/_plugins/ui/_impl/chat/chat.py
- marimo/_plugins/ui/_impl/chat/convert.py
- marimo/_plugins/ui/_impl/chat/llm.py
- marimo/_plugins/ui/_impl/chat/types.py
- tests/_plugins/ui/_impl/chat/test_chat.py
- keep rich objects in mo.ui.chat contents, so they can be used later if desired
- convert strings to markdown by default (most LLMs return markdown)
> improvement: keep rich objects in mo.ui.chat contents, convert strings to markdown

- frontend/src/core/cells/__tests__/__snapshots__/cells.test.ts.snap
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/__tests__/utils.test.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/types.ts
- frontend/src/core/cells/utils.ts
Previously, the value for column in a single-column notebook was sometimes null, sometimes undefined. This led to false positives on notebookNeedsSave. This PR changes it so that when a column is not set, the corresponding config value is `null` (which corresponds to `None` in Python).
Without this fix, if you opened a notebook and saved it with or without making any changes (experimental multi-column was disabled), the notebook was marked as needing to be save for the remainder of the session, no matter how many times you clicked "save".
I found that I also had to change arrayShallowEquals to lodash isEquals for the equality check on config objects to work.
> fix: consistent value for no column in config

- frontend/src/core/wasm/worker/bootstrap.ts
- marimo/_pyodide/pyodide_session.py
- marimo/_runtime/packages/module_name_to_conda_name.py
We would install the import/module name, not the package name. This fixes that.
> fix: install packages not modules with micropip eager install

- marimo/_cli/cli.py
- marimo/_cli/print.py
- marimo/_cli/run_docker.py
- marimo/_cli/sandbox.py
- marimo/_config/settings.py
- tests/_cli/test_cli.py
This prompts the user to run the marimo file in a dockerized container when running remote marimo notebooks.
```
marimo edit https://raw.githubusercontent.com/marimo-team/marimo/main/examples/third_party/polars/polars_example.py
```
Couple details on implementation:
* I haven't exposed this as feature-flag yet, since I don't know if we want people to do this for local notebooks. Also most of the other CLI flags won't work, so this can create more issues/bugs than help.
* We prompt on all URL based notebooks (unless `--yes`) is passed.
* We run notebooks using `uvx marimo` and using the uv docker image. (we could use our own later which doesn't buy much at the moment)
* I didn't use the `docker` python library which would be cleaner, so we can avoid the additional dependency
Error state:
> feat: add run in docker for remote urls

- pyproject.toml
We still format and force the best we can. But we don't need to fight the formatter in getting the perfect length
> fix: don't fail line length in CI

- pyproject.toml
- tests/_plugins/ui/_impl/tables/snapshots/narwhals.field_types.json
- tests/mocks.py
can run with:
```bash
hatch run +py=3.12 test-optional:test-narwhals
```
cc @MarcoGorelli this should be the only command you need to run (i dont think there is benefit with `test:test-narwhals`)
> chore: add narwhals test command

- frontend/src/components/editor/ai/__tests__/completion-utils.test.ts
- frontend/src/components/editor/ai/completion-utils.ts
- frontend/src/components/editor/chrome/panels/datasources-panel.tsx
- frontend/src/core/edit-app.tsx
- marimo/_data/preview_column.py
- marimo/_plugins/ui/_impl/table.py
Couple fixes
* catch errors from polars panics
* fix sql table context not being added if they have a `.`
> fix: ai prompt context from sql tables with periods

- docs/api/miscellaneous.md
- marimo/__init__.py
- marimo/_cli/run_docker.py
- marimo/_data/sql_summaries.py
- marimo/_runtime/threads.py
- marimo/_smoke_tests/threads.py
- marimo/_utils/narwhals_utils.py
- tests/_runtime/test_threads.py
This change adds a new public API, `mo.Thread`, which is exactly the same as `threading.Thread` except it inherits the "parent" thread's runtime context. This allows it to communicate to the parent's session.
Users can optionally choose to monkey patch `threading.Thread` with `mo.Thread` to redirect third-party library logs to the appropriate session, ie
```python
import threading
threading.Thread = mo.Thread
```
Fixes #2642 as best we can.
> feat: mo.Thread

- examples/ui/arrays_and_dicts.py
- marimo/_plugins/ui/_impl/dictionary.py
Improve documentation for dictionary UI element
- Fix f-string syntax in example: `d['slider']` to `{d['slider']}`
- Fix range syntax in example: `for i in range random.randint(4, 8)` to `for i in range(random.randint(4, 8))`
- [Add interpretation for difference between marimo.ui.dictionary and python dictionary](https://discord.com/channels/1059888774789730424/1298939811268264016)
- Add example in doc for quick layouts using `.vstack()`
- Update example for marimo dictionary
> docs: marimo.ui.dictionary

- pyproject.toml
Set a timeout on tests since I thikn one is hanging and then time's out our CI which then doesnt show the hanging test
> chore: add pytest-timeout

- marimo/_output/mpl.py
- marimo/_plugins/stateless/mpl/_mpl.py
- pyproject.toml
- tests/_plugins/stateless/test_mpl.py
Fixes #2713
We don't actually use tornado (we moved it to Starlette at some point), but an import still uses tornado
> fix: remove any need for tornado in matplotlib.interactive

- marimo/_plugins/ui/_impl/plotly.py
Adds a period to the `plotly` docstring. [In the docs](https://docs.marimo.io/guides/working_with_data/plotting.html#plotly) it ends up looking like a typo:
Looks like convention is to end each param definition without a period, though, so I haven't added periods where the description is only one sentence.
> doc: add period to Plotly docstring

- frontend/src/plugins/layout/mermaid/mermaid.tsx
Fixes #2746
The title of #2746 is actually a feature, but it made it look like a bug since we were no re-rendering mermaid on theme changes.
> fix: mermaid responding to dark mode

- frontend/src/components/data-table/column-header.tsx
- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/components/editor/code/readonly-python-code.tsx
- frontend/src/components/editor/file-tree/file-explorer.tsx
- frontend/src/components/editor/file-tree/file-viewer.tsx
- frontend/src/components/icons/copy-icon.tsx
- frontend/src/components/static-html/share-modal.tsx
- frontend/src/components/static-html/static-banner.tsx
- frontend/src/components/variables/common.tsx
- frontend/src/core/codemirror/copilot/copilot-config.tsx
- frontend/src/core/islands/components/output-wrapper.tsx
- frontend/src/plugins/impl/chat/chat-ui.tsx
- frontend/src/utils/copy.ts
Fixes #2729
As of 2024-10-29, Safari does not support navigator.clipboard.writeText when running localhost HTTP.
So this shows a prompt when copying fails so that the user can copy themselves
> fix: add clipboard copy fallback for Safari

- marimo/_cli/run_docker.py
This prevents re-prompting the user to run in a docker container when running in a package sandbox.
> fix: don't reprompt docker when running in sandbox

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/cell/code/cell-editor.tsx
- frontend/src/components/editor/renderers/CellArray.tsx
- frontend/src/components/scratchpad/scratchpad.tsx
- frontend/src/stories/cell.stories.tsx
Fixes 2 subtle bugs: 
- allow deleting a cell when hidden, but temporarily shown
- allow un-hiding a cell when hidden, but temporarily shown
> fix: allow un-hiding code when temporarily shown, show delete button

- frontend/src/plugins/impl/DataTablePlugin.tsx
Fixes #2756
There is a subtle bug when clearing table sort/filter, we reverted back to the initial page but we did not tell the backend, so the was an inconsistency in state. This fixes it while still showing the initial state when possible.
> fix: table selection when being cleared

- docs/guides/configuration/theming.md
docs: add community themes section to theming guide
- Add new section highlighting the marimo-themes repository
- Inform users about available themes and contribution opportunities
- Include direct link to the community theme library
- List example themes like coldme, nord, mininini, and wigwam
> docs: add community themes section to theming guide

- docs/api/inputs/chat.md
- examples/ai/chat/anthropic_example.py
- examples/ai/chat/gemini.py
- examples/ai/chat/groq-example.py
- examples/ai/chat/openai_example.py
- marimo/_dependencies/dependencies.py
- marimo/_plugins/ui/_impl/chat/convert.py
- marimo/_plugins/ui/_impl/chat/llm.py
- marimo/_server/api/endpoints/ai.py
- marimo/_smoke_tests/chat/chatbot.py
- tests/_plugins/ui/_impl/chat/test_chat_convert.py
Adding `GROQ` in `mo.ai.llm` inside [`mo.ui.chat`](https://docs.marimo.io/api/inputs/chat.html#chat) integration to extend Marimo's AI capabilities alongside existing support for OpenAI, Gemini, and Anthropic. This addition introduces GROQ support for AI completions and chat interactions. Also fixes a documentation display issue for the `iframe` function.
1. **Implementation**: Added `groq` as a model option in `marimo/_plugins/ui/_impl/chat/llm.py`.
2. **Documentation**: Minor docs touchups.
3. **Examples**: Created a GROQ chatbot example in `examples/ai/chat`.
Reference PR includes [#2398](https://github.com/marimo-team/marimo/pull/2479) and issue includes https://github.com/marimo-team/marimo/issues/2505.
Encountering `AttributeError` when testing GROQ in …
> Add `Groq` for `mo.ui.chat`

- marimo/_output/data/data.py
- marimo/_plugins/ui/_impl/tables/narwhals_table.py
- tests/_plugins/ui/_impl/tables/test_ibis_table.py
- tests/_plugins/ui/_impl/tables/test_narwhals.py
- tests/_plugins/ui/_impl/tables/test_pandas_table.py
- tests/_plugins/ui/_impl/tables/test_polars_table.py
- tests/_plugins/ui/_impl/test_table.py
Regression when moving to narwhals, pagination offset logic was incorrect. This fixes it and adds a test
> fix: table pagination for next page

- frontend/src/components/data-table/__test__/__snapshots__/chart-spec-model.test.ts.snap
- frontend/src/components/data-table/__test__/chart-spec-model.test.ts
- frontend/src/components/data-table/chart-spec-model.tsx
Column summaries in wasm come in as data-uris. This handles that case and adds some snapshot tests to make sure we don't change it
> fix: column summaries in wasm

- docs/guides/working_with_data/sql.md
- frontend/src/components/editor/renderers/CellArray.tsx
- marimo/_tutorials/sql.py
Add a quotation mark for the pip install command for `marimo[sql]`. I was confused why it didn't work when I ran this command. You would get a `zsh: no matches found` error by default.
This is just a small QoL improvement.
> docs: add quotation marks for marimo[sql] commands

- frontend/src/components/editor/chrome/wrapper/app-chrome.tsx
- frontend/src/components/editor/chrome/wrapper/footer.tsx
- frontend/src/components/editor/chrome/wrapper/sidebar.tsx
- frontend/src/css/common.css
This hides some elements that were causing click conflicts with the table when in fullscreen 
Fixes #1971
> fix: allow table selection in full screen

- frontend/src/components/app-config/user-config-form.tsx
- marimo/_plugins/ui/_impl/data_explorer.py
- tests/_plugins/ui/_impl/test_data_explorer.py
If the index is there, pandas will add an empty column name in the csv, which breaks the data-explorer.
> fix: drop index for data-explorer

- examples/README.md
- examples/sql/README.md
- examples/sql/connect_to_persistent_db.py
A very small example on how to connect to a local `duckdb` file.
Additionally, update readme to let users know about run via URL.
> example: attach to persistent duckdb db

- frontend/src/components/editor/Cell.tsx
Fixes #2822
A flipped boolean made j/k not work in any cells
> fix: vim j/k keys

- frontend/e2e-tests/py/components.py
- frontend/src/components/ui/button.tsx
- frontend/src/core/hotkeys/__tests__/shortcuts.test.ts
- frontend/src/core/hotkeys/shortcuts.ts
- frontend/src/plugins/impl/ButtonPlugin.tsx
- marimo/_plugins/ui/_impl/input.py
- marimo/_plugins/ui/_impl/run_button.py
Fixes #633 . Buttons can now have shortcuts by declaring them
`mo.ui.button(label='Add', value=0, on_click=lambda x: x + 1, keyboard_shortcut="Cmd-L")`
- Adds a global listener for keyboard shortcuts when declared on a button, prevents default action
- Uses the default hotkeys parsing
- Adds a default tooltip for the keyboard shortcut
> feat: add keyboard shortcut to buttons

- frontend/src/components/editor/Disconnected.tsx
- frontend/src/components/editor/actions/useRestartKernel.tsx
- frontend/src/components/editor/header/app-header.tsx
- frontend/src/core/network/requests-network.ts
- frontend/src/core/wasm/bridge.ts
- frontend/src/core/websocket/types.ts
- frontend/src/core/websocket/useMarimoWebSocket.tsx
- frontend/src/utils/reload-safe.ts
- marimo/_server/api/endpoints/execution.py
- tests/_server/api/endpoints/test_execution.py
This will disconnect the other session and refresh your page (and resume where the other session left off). This should also help with vscode connections that sometimes seem to hold onto websocket connections even though the vscode browser was closed.
> improvement: allow taking control of an existing session if in edit mode

- marimo/_server/api/endpoints/ai.py
Some OpenAI-compatible endpoints appear to need the API key sent in the header,
this change makes it work.
Without it, I'm getting an error 401.
(I don't actually know which specific endpoint provider/product I am using.)
Set `default_headers` in the OpenAI instance.
> AI Completion: Send api-key header for OpenAI endpoints

- docs/conf.py
Use primary background color for sidebar, based on looking at docs for other popular and modern projects.
> docs: light-theme sidebar color

- frontend/src/plugins/impl/panel/PanelPlugin.tsx
- frontend/src/plugins/impl/panel/utils.ts
- marimo/_plugins/ui/_impl/from_panel.py
Ensures binary messages sent from the frontend to Python are serialized from binary ArrayBuffers to base64 strings.
Adds code on the frontend to convert Bokeh `Buffer` objects to base64 and convert the base64 buffers arriving in Python into `memoryview` objects expected by the Bokeh protocol  
@mscolnick please review.
I wasn't aware that binary transport was not supported at all. Is there any chance this could be enabled? Panel applications often push a lot of data across the websocket and base64 encoding/decoding adds major overhead.
> Ensure binary messages are serialized to base64 in Panel Comm layer

- marimo/_output/formatters/repr_formatters.py
- marimo/_output/formatters/structures.py
- marimo/_output/formatting.py
- marimo/_smoke_tests/third_party/seaborn_example.py
- marimo/_utils/methods.py
- tests/_output/formatters/test_formatters.py
This prefers the _repr_ methods when printing out top level list/dicts if they exist.
> improvement: prefer _repr_ methods on list/dicts/tuple

- marimo/_ast/app.py
Document that app.embed() shouldn't be called in the cell that imports the app.
Add a TODO to raise a RuntimeError if the user does this.
This issue was hit in #2833
> docs: app.embed() usage

- marimo/_convert/ipynb.py
- marimo/_convert/utils.py
Adds support for extracting inline script metadata from notebook cells, and lifting the comment block to the top of the converted marimo Python script.
This allows for nice interchange between a tool like juv and marimo:
```sh
juv init
juv add Untitled.ipynb anywidget polars
marimo convert Untitled.ipynb > Untitled.py
marimo edit Untitled.py
```
Adds regex to extract metadata from inline script comments, and lifts the comment block to the top of the converted marimo Python script.
> improvement: Extract and lift inline script metadata in `marimo convert`

- docs/api/plotting.md
- marimo/_output/formatters/leafmap_formatters.py
- marimo/_output/formatters/plotly_formatters.py
- marimo/_smoke_tests/third_party/leafmap/backends.py
- pyproject.toml
* Adds formatters for plotly and kepler.
* Warns about using the default leafmap formatter
* Smoke test for different backends. 
https://github.com/opengeos/leafmap/pull/973 will help when doing `import leafmap`
> improvement: better leafmap formatters

- docs/guides/deploying/deploying_docker.md
- docs/guides/working_with_data/plotting.md
- marimo/_plugins/stateless/mpl/_mpl.py
1. Gets the host from an environment variable, if specified, for the mpl plugin.
2. Adds checks to make sure the host name is valid. Throws an error on `marimo run` if failure.
3. Exposes host and port variables through the main create application function for simpler configuration in the future, hopefully when spawning the process instead of being specified by the user.
Unfortunately this spawns a new error that I really don't understand. I'm submitting this to see if it's an easy fix or if the approach should be thrown away altogether and the process should be proxied through the main server.
See: https://github.com/marimo-team/marimo/issues/2848
I only saw integration tests for marimo.mpl And those all pass. I did not add additional testing for this.
I did run manual tests:
- …
> Fix: expose port via os to allow mpl to work in docker

- frontend/islands/vite.config.mts
- frontend/src/core/islands/worker/worker.tsx
- frontend/src/core/wasm/bridge.ts
- frontend/src/core/wasm/store.ts
- frontend/src/core/wasm/worker/bootstrap.ts
- frontend/src/core/wasm/worker/getPyodideVersion.ts
- frontend/src/core/wasm/worker/save-worker.ts
- frontend/src/core/wasm/worker/worker.ts
- frontend/vite.config.mts
- marimo/_cli/upgrade.py
- marimo/_dependencies/dependencies.py
- marimo/_server/api/auth.py
- marimo/_server/uvicorn_utils.py
We now host lockfiles for pyodide at https://wasm.marimo.app/pyodide-lock.json. This allows us resolve marimo packages and deps much faster than before (no waterfalls, and no looking at pypi for the file urls or deps)
Other improvements: 
* don't load the initial `pyodide.js`, we bundle this in
* don't initialize the save worker until the main worker is done -> we can benefit from a cache hit 
* lazily import `packages`
> perf: use pyodide lockfiles

- frontend/src/hooks/useScript.ts
- frontend/src/plugins/impl/plotly/PlotlyPlugin.tsx
Fixes #2060 . Adding MathJax library in PlotlyPlugin to render LaTeX for Plotly.
- Using MathJax 2 library from https://www.mathjax.org/#gettingstarted . Should use v3 in the future once all v2 features are ported over.
- created a custom hook as the uidotdev useScript hook isn't suitable when there are multiple components calling `useScript` at the same time
WIP
> feat: add mathjax lib using useScript

- docs/api/inputs/chat.md
Update the `chat.md` file to include examples for GROQ and Cerebras model providers (while also linking the [LiteLLM page](https://litellm.vercel.app/docs/providers) to showcase various other model providers).
Address comment - https://github.com/marimo-team/marimo/issues/2773#issuecomment-2455326251
- Added examples for GROQ and Cerebras model providers.
- Included a note about the availability of free API keys for GROQ and Cerebras.
- Provided guidance on finding the correct endpoint URLs for model providers (refer to docs; usually found in the curl commands).
> docs: add support for model providers with usage examples

- docs/getting_started/index.md
- docs/guides/working_with_data/sql.md
- docs/integrations/motherduck.md
- pyproject.toml
1. Add `pip install "marimo[recommended]"` which unlocks all the features. I did not want to go with `all` as there are more deps that we could add in future that we may not need in recommended (`vegafusion`, `duckdb` extensions, `anthropic`0
2. This also add polars to the sql deps, since we require one of pandas and polars, and this helps them get started without an initial error when starting from a clean venv
> chore: add recommended deps

- marimo/_ast/visitor.py
- tests/_ast/test_sql_visitor.py
- tests/_ast/test_visitor.py
`duckdb.get_table_names` fails for unknown (or unloaded) functions. so we don't want to fail everything if that fails
> fix: sql case with function

- examples/README.md
Add frameworks subfolder in README listing; fix small typo
Add [`frameworks`](https://github.com/marimo-team/marimo/tree/main/examples/frameworks) to [`README`](https://github.com/marimo-team/marimo/blob/main/examples/README.md); fix typo [here](https://github.com/marimo-team/marimo/blame/076514328aa92fb7d0a75f023253d44bee1e3f64/examples/README.md#L11)
> Add `frameworks` in README list; fix typo

- pyproject.toml
`websockets` is required by uvicorn, which does not set an upperbound: https://github.com/encode/uvicorn/blob/master/pyproject.toml#L47
Fixes #2890
> fix: remove upper bound on websockets

- docs/guides/deploying/deploying_docker.md
- docs/guides/working_with_data/plotting.md
- marimo/_plugins/stateless/mpl/_mpl.py
- marimo/_server/api/middleware.py
- marimo/_server/main.py
- pyproject.toml
- tests/_server/api/test_middleware.py
This represents the matplotlib fix to create a proxy middleware which connects the main starlette process to the mpl starlette process.
Using this mapplotlib can be used in production on Docker for any kind of interactive stuff.
See my demo app here, which is finally working: https://causal-quartets.fly.dev/
I left the environmental variables in the codebase so that you could customize the port or hosts for some reason in the future, but I removed references to them from the documentation since I think that would be more of a developer-facing thing anyway.
1. Creates AsyncHTTPClient class to manage HTTP responses between the two starlette processes without any dependencies (i.e., no httpx)
2. Fixes The WebSocket handling from the original implementation of the proxy class. There were two …
> mpl proxy for matplotlib process

- marimo/_server/api/middleware.py
fixes this bug that happens on closed when the web socket is connected that wasn't caught in the previous PR:
```
File "/Users/max/Documents/causal_quartets/.venv/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 358, in asgi_send
raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close' or response already completed.
```
It simply checks the state of the WebSocket before trying to close it.
@mscolnick
> Proxy fixes mpl

- docs/guides/integrating_with_marimo/displaying_objects.md
- marimo/_output/formatting.py
- marimo/_utils/methods.py
- tests/_output/formatters/test_formatters.py
If an object implements `_display_() -> Any`, we render it using marimo's built-in renderer applied to `obj._display_()`.
Example:
> feat: _display_ protocol

- docs/guides/deploying/deploying_docker.md
- docs/guides/working_with_data/plotting.md
- marimo/_plugins/stateless/mpl/_mpl.py
- marimo/_server/api/middleware.py
- marimo/_server/main.py
- pyproject.toml
- tests/_server/api/test_middleware.py
Heavy lifting done by @maxtheman! 
This puts the mpl communication behind the main server URL and port, and proxies request internally.
via @maxtheman:
This represents the matplotlib fix to create a proxy middleware which
connects the main starlette process to the mpl starlette process.
Using this mapplotlib can be used in production on Docker for any kind
of interactive stuff.
See my demo app here, which is finally working:
https://causal-quartets.fly.dev/
I left the environmental variables in the codebase so that you could
customize the port or hosts for some reason in the future, but I removed
references to them from the documentation since I think that would be
more of a developer-facing thing anyway.
1. Creates AsyncHTTPClient class to manage HTTP responses between the
two starlette …
> improvement: mpl proxy middleware

- frontend/src/components/data-table/columns.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
Hide data-types when we pass a list/dictionary to `mo.ui.table`, but show them when we pass a dataframe.
> fix: only show data-types if coming from a dataframe

- marimo/_plugins/ui/_impl/comm.py
This is probably a good change to make, but I only have seen one `anywidget` need this change.
> fix: correct flush of anywidget messages

- Makefile
Totally a minor update this one. This PR changes a `pip install -e .[dev]` into `pip install -e ".[dev]"` command in the `Makefile`. 
The reason I did this is because some shells (Zshell mainly, but maybe others too) seem to have trouble parsing the command in the Makefile. Gives me this error:
```
zsh: no matches found: .[dev]
```
> Update Makefile for ".[dev]"

- frontend/src/plugins/impl/vega/__tests__/__snapshots__/make-selectable.test.ts.snap
- frontend/src/plugins/impl/vega/__tests__/make-selectable.test.ts
- frontend/src/plugins/impl/vega/make-selectable.ts
- marimo/_plugins/ui/_impl/altair_chart.py
- marimo/_smoke_tests/altair/layered_charts.py
- tests/_plugins/ui/_impl/test_altair_chart.py
Fixes #2901
If selection params are already added by the users, we should not automatically the default chart/legend selection and just use the users.
> fix: mo.ui.altair_chart when give by the user

- docs/guides/configuration/html_head.md
- docs/guides/configuration/index.md
- docs/guides/configuration/theming.md
- frontend/src/components/app-config/app-config-form.tsx
- frontend/src/core/config/config-schema.ts
- marimo/_ast/app.py
- marimo/_server/file_manager.py
- marimo/_server/templates/templates.py
- marimo/_smoke_tests/theming/custom_head.py
- marimo/_smoke_tests/theming/head.html
- openapi/api.yaml
- openapi/src/api.ts
- tests/_ast/test_app.py
- tests/_ast/test_app_config.py
- tests/_server/templates/snapshots/export5.txt
- tests/_server/templates/test_templates.py
You can include a custom HTML head file to add additional functionality to your notebook, such as analytics, custom fonts, meta tags, or external scripts. The contents of this file will be injected into the `<head>` section of your notebook.
To include a custom HTML head file, specify the relative file path in your app configuration. This can be done through the marimo editor UI in the notebook settings (top-right corner).
Some examples:
1. **Google Analytics**
2. **Custom Fonts**
3. **Meta Tags**
4. **External Scripts and Libraries**
> feat: add html_head_file to inject custom head scripts into the app

- frontend/src/plugins/core/RenderHTML.tsx
- marimo/_smoke_tests/third_party/mohtml_example.py
This allows `<script src/>` tags to be properly created. This doesn't open up a new attack vector since this is already possible today with anywidget (running javascript)
cc @koaning
> improvement: allow <script src/> in html

- frontend/src/components/debugger/debugger-code.tsx
- frontend/src/components/editor/Cell.tsx
- frontend/src/hooks/__tests__/useEventListener.test.tsx
- frontend/src/hooks/useEventListener.ts
- frontend/src/hooks/useHotkey.ts
useEventListener wasn't working properly when you passed in ref.current. For example, the `ArrowUp` & `ArrowDown` keys to move between cells. This is because changes to ref.current will not trigger a re-render.
useEventListener lets you pass in a ref object instead of ref.current and ensure it re-renders correctly when ref.current is no longer null.
Stumbled upon this as I was trying to add new eventListeners. Shoutout to Claude for helping me understand & write 😅.
> fix: add ref handling for useEventListener

- frontend/src/hooks/__tests__/useEventListener.test.tsx
- frontend/src/hooks/useEventListener.ts
- frontend/src/hooks/useHotkey.ts
- frontend/src/plugins/core/registerReactComponent.tsx
- frontend/src/plugins/impl/anywidget/AnyWidgetPlugin.tsx
- frontend/src/plugins/impl/panel/PanelPlugin.tsx
This does't change any runtime code but adds stricter types so that we can enforce the correct practice that @Light2Dark pointed out (pass the Ref, not the HTMLElement)
cc @Light2Dark
> chore: add stricter types for useEventListener

- marimo/_plugins/ui/_impl/tables/narwhals_table.py
Currently, `tests/_plugins/ui/_impl/test_altair_chart.py` is failing for DuckDB input, because:
- previously `_data` has already been converted to PyArrow Table
- now, `_data` is still a DuckDB PyRelation, which for now only has "interchange" level support in Narwhals. So, in that case, we convert to PyArrow. We plan to greatly improve DuckDB support next year: https://github.com/narwhals-dev/narwhals/discussions/1370
> fix: Altair 5.5 compat

- frontend/src/components/editor/actions/useCellActionButton.tsx
- frontend/src/components/editor/actions/useNotebookActions.tsx
- frontend/src/core/cells/__tests__/cells.test.ts
- frontend/src/core/cells/cells.ts
Add an option to clear cell outputs. This can be useful if you are rendering a lot of graphs and they start to bog down the browser ([feedback from here](https://github.com/marimo-team/marimo/discussions/2899#discussioncomment-11371867)).
> improvement: add action to Clear Cell Outputs / Clear All Outputs

- marimo/_plugins/ui/_impl/input.py
- tests/_plugins/ui/_impl/test_input.py
Following up from #2958, this adds support to `range_slider` and a couple tests/examples
> improvement: add numpy support to range_slider, update examples

- marimo/_output/utils.py
- marimo/_plugins/stateless/image.py
- marimo/_plugins/stateless/video.py
- tests/_output/test_output_utils.py
Fixes #2952
Allows for relative units to width/height of mo.image()
> improvement: allow non-pixels for mo.image, mo.video

- frontend/index.html
- tests/_cli/test_cli_export.py
- tests/_server/templates/data/index.html
- tests/_server/templates/snapshots/export1.txt
- tests/_server/templates/snapshots/export2.txt
- tests/_server/templates/snapshots/export3.txt
- tests/_server/templates/snapshots/export4.txt
- tests/_server/templates/snapshots/export5.txt
- tests/_server/templates/test_templates.py
The base URL known by the marimo server and marimo frontend are the same when set by directly in marimo's server. But users could set up their own proxy that changes the base URL (e.g. jupyter-server-proxy), in which they could be out of sync. This lets the frontend infer the base URL, so the proxy can strip it out as needed.
> improvement: remove base-url from index.html, instead infer it

- frontend/src/plugins/impl/DataTablePlugin.tsx
Fix #2967 
We were checking the original totalRows, not the filtered totalRows.
> fix: resetting pagination after filtering

- docs/recipes.md
https://github.com/marimo-team/marimo/pull/2979#issuecomment-2501998832 After checking the updated website, noticed that the query parameter in the link to notebook got reformatted to `https://marimo.app/l/w21a3x?t1=query&amp;t2=params` - which breaks the notebook.
try HTML instead of Markdown link
@mscolnick
> docs: Populating form - HTML escape

- marimo/_utils/formatter.py
Ruff doesn't always go on PATH; if marimo is launched directly via `.venv/bin/marimo`, ruff that sits at `.venv/bin/ruff` will not be found.
Call ruff using `f"{sys.prefix}/ruff"`
> Find ruff when it's not on PATH

- frontend/src/components/data-table/TableActions.tsx
- frontend/src/components/data-table/column-summary.tsx
- frontend/src/components/data-table/data-table.tsx
- frontend/src/components/data-table/pagination.tsx
- frontend/src/components/editor/file-tree/renderers.tsx
- frontend/src/components/utils/delay-mount.tsx
- frontend/src/plugins/impl/DataEditorPlugin.tsx
- frontend/src/plugins/impl/DataTablePlugin.tsx
- frontend/src/plugins/impl/data-frames/DataFramePlugin.tsx
- frontend/src/stories/data-table.stories.tsx
- marimo/_plugins/ui/_impl/table.py
- marimo/_smoke_tests/issues/2991-df-columns.py
- tests/_plugins/ui/_impl/test_table.py
Fixes #2996
Fixes #2991
- clamp tables at 50 columnns by default
- delay render of charts until they are visible, this also delays parsing/aggregating the data for the chart
> improvement: clamp tables at 50 columnns by default

- frontend/src/components/data-table/column-summary.tsx
- frontend/src/core/static/files.ts
- frontend/src/plugins/impl/vega/__tests__/resolve-data.test.ts
- frontend/src/plugins/impl/vega/batched.ts
- frontend/src/plugins/impl/vega/vega-loader.ts
- frontend/src/utils/__tests__/batch-requests.test.ts
- frontend/src/utils/batch-requests.ts
Helps https://github.com/marimo-team/marimo/issues/2996, https://github.com/marimo-team/marimo/issues/2991, but not fixed until https://github.com/marimo-team/marimo/pull/3000
This shared promises with inflight requests (e.g. when they are shot off at the same time), and then clears the share cache, because (in this case) can fall back to browser cache.
> improvement: batch the same url requests to avoid additional download / parsing

- frontend/src/components/data-table/columns.tsx
- frontend/src/components/data-table/date-popover.tsx
- frontend/src/utils/dates.ts
- marimo/_smoke_tests/tables/subseconds.py
Fixes #3007 
This adds microsecond support to the table. 
It does not handle nanoseconds since browser `Dates` do not handle nanoseconds. So the workaround is to cast the column as a string.
```python
_start = datetime.datetime(2024, 11, 27, 16, 17, 7, 742951)
_slice = datetime.timedelta(microseconds=123456)
test_df = pd.DataFrame(
data={
"timestamp": [_start + n * _slice for n in range(5)],
}
)
nano_df = test_df.copy()
nano_df["timestamp"] = nano_df["timestamp"].astype(str)
nano_df
```
> fix: support microseconds in mo.ui.table, (but not nanoseconds)

- marimo/_plugins/ui/_impl/dataframes/dataframe.py
- marimo/_plugins/ui/_impl/table.py
- tests/_plugins/ui/_impl/test_table.py
Fixes #3017 . Checks if sorted column exists before sorting.
- Added some tests, let me know if I should add more sort tests to the dataframe component.
> fix: sort only when column exists

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/Output.tsx
Fixes #2804
When markdown is hidden, we should force expand the output so its not in a scroll bar
> improvement: force expand markdown content

- frontend/src/components/editor/output/JsonOutput.tsx
- marimo/_output/formatters/structures.py
- marimo/_smoke_tests/structures.py
- tests/_islands/snapshots/island-mimetypes.txt
- tests/_output/formatters/test_formatters.py
- tests/_output/formatters/test_structures.py
For top-level classes that extend list/dict/tuple, it seems preferable to use the custom repr over converting it to json
> improvement: don't convert classes that extend tuple/dict/list to structure when formatting

- frontend/src/components/editor/Cell.tsx
Don't unhide the markdown if empty since it may start empty (before any rendering)
> fix: don't unhide when markdown is empty

- frontend/src/components/data-table/url-detector.tsx
- frontend/src/components/editor/output/JsonOutput.tsx
- frontend/src/components/editor/output/Outputs.css
- frontend/src/components/editor/output/__tests__/json-output.test.ts
- frontend/src/utils/urls.ts
- marimo/_output/formatters/structures.py
- marimo/_smoke_tests/structures.py
- tests/_output/formatters/test_structures.py
This adds copy/paste support for floats/sets/lists/dictionaries. This also adds a URL renderer.
**It does not yet support tuples** since those get converted to lists on `json.dump` and not sure I want to make that change yet.
> improvement: add copy/paste to json viewer, support urls

- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
Tiny change to drop borders for markdown in HTML export.
> improve: borderless markdown in html exports

- docs/guides/deploying/programmatically.md
- marimo/_server/asgi.py
- marimo/_smoke_tests/custom_server/my_server.py
- tests/_server/test_asgi.py
This adds `with_dynamic_directory`:
------
If you'd like to create a server to dynamically load marimo notebooks from a directory, you can use the `with_dynamic_directory` method. This is useful if the contents of the directory change often, such as a directory of notebooks for a dashboard, without restarting the server.
```python
server = (
marimo.create_asgi_app()
.with_dynamic_directory(path="/dashboard", directory="./notebooks")
)
```
If the notebooks in the directory are expected to be static, it is better to use the `with_app` method and loop through the directory contents.
```python
from pathlib import Path
server = marimo.create_asgi_app()
app_names: list[str] = []
notebooks_dir = Path(__file__).parent / "notebooks"
for filename in sorted(notebooks_dir.iterdir()):
if …
```
> improvement: add marimo.create_asgi_app().with_dynamic_directory

- marimo/_runtime/dataflow.py
- tests/_runtime/test_dataflow.py
This is useful to keep markdown elements (which may not have a dependency) in the same order that they are created, when exporting to a script or ipynb.
This also renders markdown from top to bottom which is less jerky on startup.
> improvement: tie-break topological sort by top-down order

- marimo/_plugins/ui/_core/ui_element.py
- marimo/_runtime/app/kernel_runner.py
- marimo/_runtime/context/kernel_context.py
- marimo/_server/sessions.py
- tests/_plugins/ui/_core/test_ui_element.py
- tests/_runtime/test_runtime.py
- tests/conftest.py
This helps when committing generated marimo files (html/ipynb) that they don't cause unnecessary diffs.
html files still have some changes from the timestamps in the outputs
> improvement: make ui-element ids deterministic across runs

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/renderers/vertical-layout/vertical-layout.tsx
There is a bad bug when you're in app view, since the borders are removed, so hovering over the cell will cause borders to be re-added. Borderless view is not needed in 'present' or 'view' mode.
> fix: only add borderless css when not published

- examples/frameworks/fastapi-github/main.py
Detects `GITHUB_REPO` and `REPO_ROOT` environment variables if set,
falling back to default in marimo.
(I believe this is the desired behavior of the script)
Just detects `GITHUB_REPO` and `REPO_ROOT` environment variables if set.
@mscolnick
> Parameterize fastapi-github example with environment vars

- frontend/src/components/scratchpad/scratchpad.tsx
Fixes #3073 . Each individual part can be scrolled (code editor, output area, console output) and the whole scratchpad can be scrolled too. I think it maintains the feel of scratchpad while handling long inputs / outputs.
I'm not sure if it breaks anything else, so plan to test it locally a while.
> fix: make scratchpad scrollable

- marimo/_server/asgi.py
- tests/_server/test_asgi.py
Adds a validate callback that can be used in the programmatic ASGI app to check for authN or authZ.
```
validate_callback (Optional[ValidateCallback]): A callback function to validate the application path.
This is useful to plug in authentication or authorization checks.
The validate_callback receives the application path and the scope,
and returns a boolean indicating whether the application is valid.
You may also raise an exception for a custom error message.
```
> improvement: add validate callback to asgi with_dynamic_directory

- frontend/src/components/editor/renderers/grid-layout/grid-layout.tsx
Fixes #3074. Adjusts z-index of grid-controls to be the same as app header like below:
```.tsx
<AppHeader
connection={connection}
className={cn(
"pt-4 sm:pt-12 pb-2 mb-4 print:hidden z-50",
// Keep the header sticky when scrolling horizontally, for column mode
"sticky left-0",
)}
>
```
> fix: allow grid controls to be edited

- docs/guides/exporting.md
- marimo/_cli/cli_validators.py
- marimo/_cli/export/commands.py
- marimo/_cli/print.py
- marimo/_islands/island_generator.py
- marimo/_messaging/errors.py
- marimo/_plugins/ui/_impl/input.py
- marimo/_plugins/ui/_impl/tables/pandas_table.py
- marimo/_server/export/__init__.py
- tests/_cli/snapshots/export_markdown_with_errors.txt
- tests/_cli/snapshots/ipynb_with_errors.txt
- tests/_cli/snapshots/script_with_errors.txt
- tests/_cli/test_cli_config.py
- tests/_cli/test_cli_export.py
- tests/_cli/test_markdown_conversion.py
- tests/_server/export/snapshots/notebook_with_outputs.ipynb.txt
- tests/_server/export/test_exporter.py
- tests/conftest.py
Fixes #3089
1. return proper errors codes if any cells fail
2. validate file exist in `marimo export`
3. print out errors when they are run to stderr
> fix: marimo export returns propper error code

- marimo/_ast/app.py
- marimo/_ast/cell.py
- marimo/_server/export/exporter.py
- tests/_ast/test_cell.py
- tests/_server/export/snapshots/notebook_top_down.ipynb.txt
- tests/_server/export/snapshots/notebook_topological.ipynb.txt
- tests/_server/export/snapshots/notebook_with_cells.ipynb.txt
- tests/_server/export/snapshots/notebook_with_outputs.ipynb.txt
- tests/_server/export/test_exporter.py
Fixes #2960 
Last bit for #2960. This scopes everything under a `"marimo"` config to it won't conflict with any other future or existing configs
> improvement: include cell config and name in ipynb metadata

- marimo/_ast/app.py
- marimo/_ast/codegen.py
- marimo/_server/file_manager.py
- tests/_ast/codegen_data/test_app_with_no_cells.py
- tests/_ast/codegen_data/test_app_with_only_comments.py
- tests/_ast/test_codegen.py
This change makes blogs or tutorials easier since you can give the user a starting file that installs the deps, for sandboxed environments.
> improvement: allow python files with just deps or no cells

- marimo/_server/export/__init__.py
- tests/_server/export/snapshots/run_until_completion_with_stop.txt
- tests/_server/export/test_exporter.py
We recently propagated errors from `marimo export`, but we should ignore `mo.stop()` as errors since they are intentional and should fail the export
> fix: ignore mo.stop() 'errors' in marimo export

- frontend/src/components/editor/chrome/components/feedback-button.tsx
- frontend/src/core/constants.ts
This PR updates the feedback panel to highlight three channels:
1. Our [survey](https://marimo.io/feedback)
2. GitHub issues
3. Discord
It removes the free-form feedback text input.
> Update feedback dialog

- docs/guides/exporting.md
If you export to a Jupyter notebook, you can leverage various Jupyter ecosystem tools. For PDFs, you will
need to have [Pandoc](https://nbconvert.readthedocs.io/en/latest/install.html#installing-pandoc) and [Tex](https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex) installed.
```bash
NOTEBOOK=notebook.ipynb
uvx --with nbconvert --from jupyter-core jupyter nbconvert --to pdf $NOTEBOOK
uvx --with "nbconvert[webpdf]" --from jupyter-core jupyter nbconvert --to webpdf $NOTEBOOK --allow-chromium-download
uvx --with nbconvert --from jupyter-core jupyter nbconvert --to slides $NOTEBOOK
uvx --with nbconvert --from jupyter-core jupyter nbconvert --to rst $NOTEBOOK
uvx --with nbconvert --with jupyter --from jupyter-core jupyter nbconvert --to pdf --execute --stdout $NOTEBOOK \ …
```
> docs: add docs for exporting to PDF, slides, or rst

- frontend/src/components/editor/Cell.tsx
- frontend/src/components/editor/cell/useRunCells.ts
- frontend/src/core/cells/__tests__/utils.test.ts
- frontend/src/core/cells/cells.ts
- frontend/src/core/cells/utils.ts
- frontend/src/core/kernel/handlers.ts
- frontend/src/core/wasm/worker/bootstrap.ts
- marimo/_pyodide/bootstrap.py
- marimo/_runtime/requests.py
- marimo/_runtime/runtime.py
- marimo/_server/models/models.py
- marimo/_server/sessions.py
- marimo/_smoke_tests/auto_instantiate_off.py
- openapi/api.yaml
- openapi/src/api.ts
- tests/_runtime/test_runtime.py
- tests/_server/api/endpoints/test_execution.py
- tests/_server/session/test_session_view.py
- tests/_server/test_sessions.py
Fixes #2983
This registers all cells with the graph (but does not run them) when auto-run-on-startup is `off`. This allows you to run parts of the notebook (a sub-graph), without having to run all of it and without having to know which ones to run.
> improvement: allow running any cell when auto-run-on-startup is off
